### ISSUE TITLE
Slow WMS are depending on how you change the scale not displayed in the main map window

### ISSUE THREAD

**Issue by sylviaobk** [mapbender/mapbender#1009]
Some „slow“ WMS like „Stadtkarte grau“, „Stadtkarte light“, „Stadtkarte farbe“ and „Luftbilder“ are not always rendered in the main map window

Let me illustrate this by an example:

Open https://rio.obk.de/mapbender3073/app.php/application/RIO_Aktuelles_Service
and watch the behaviour of the layer „Stadtkarte light“

The following steps are ok:	
With the preselected scale 1:200000 the layer „Stadtkarte light“ is not visible in the main map window:

 ![sichtbarkeit1](https://user-images.githubusercontent.com/20552367/44526585-fd226480-a6d3-11e8-8109-0ce5ccedefa3.PNG)

Choose **10000** from the **Scale Selector** (Toolbar)

Now „Stadtkarte light“ is visible in the main map window:

![sichtbarkeit2](https://user-images.githubusercontent.com/20552367/44526630-28a54f00-a6d4-11e8-83b1-512d77fbc53e.PNG)
 
Roll the **mouse wheel** upwards to scale **1:7500**

 „Stadtkarte light“ is visible in the main map window:
 
![sichtbarkeit3](https://user-images.githubusercontent.com/20552367/44526671-47a3e100-a6d4-11e8-9b0c-7ae1d936f787.PNG)

The next step is probably a bug:

Choose 10000 from the **Scale Selector** (Toolbar)
 „Stadtkarte light“ is not visible in the main map window:
 
![sichtbarkeit4](https://user-images.githubusercontent.com/20552367/44526686-4f638580-a6d4-11e8-9546-e563f48645c8.PNG)

„Fast“ layers like „Haltestellen VRS“ are not affected

https://rio.obk.de/cgi-bin/mapserv?map=/home1/data/umn/obk/obk_amt62_stadtplanwerk_light.map&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.1.1

**Comment by astroidex** [comment]
Hello @sylviaobk . Thanks for the bug report. I can reporducte the error in your installation with 3.0.7.3 version. Same error occurs in version 3.0.7.5

* https://rio.obk.de/mapbender3075/app.php/application/RIO_Aktuelles_Service

We will try to reproduce the error in a local installation and fix it

* I created an application at https://demo.mapbender.org/application/mapbender_user_1009 to reproduce the error

**Comment by astroidex** [comment]
@sylviaobk does this problem still occur in 3.0.8.5? 

The application https://rio.obk.de/mapbender3073/app.php/application/RIO_Aktuelles_Service is not available anymore for testing.

If the error is still there, could you please provide a demo application.

**Comment by sylviaobk** [comment]
The application https://rio.obk.de/mapbender3085/app_dev.php/application/RIO_Aktuelles_Service is now available for testing.

The error is fixed in 3.0.8.5 :-)

**Comment by astroidex** [comment]
Great thanks you for the feedback.
