### ISSUE TITLE
WMS with only one root layer fails to initialize the map

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#1011]
A WMS with only one Layer (the root layer containing data) cannot be loaded into Mapbender. In 3.0.6 and before, the WMS was ignored. In 3.0.7 the Layertree fails to initialize.

Although the specification can be interpreted in different ways, 'from my point of view' this WMS is not configured properly. A WMS has a root layer without data and one or many other layers containing data or not.

Steps to reproduce:

- Add new Source: https://geodienste.sachsen.de/wms_geosn_dtk-pg-color/guest?VERSION=1.3.0&REQUEST=GetCapabilities&SERVICE=WMS

- Add to a layerset of your app.

- Start app.

Behaviour:

- The layertree isn't initialized.
- Error message: "Your element with id 12345 (widget mapbender.mbMap) failed to initialize properly.

Expected behaviour:

- The layertree should be displayed and fully functional.

Bonus:
- The WMS should be displayed.

Workaround:

Create a XML-file from the Capabilities above and insert a root layer above the one existing.

**Comment by werrolf** [comment]
Fixed in 0192e0c, included in v3.0.7.5 and later
