### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by Vaddo** [mapbender/mapbender#102]
What about a fancy datepicker for inputs????

**Comment by eSlider** [comment]
Datepicker is integrated and styled as component based on [vis-ui.js](https://github.com/eSlider/vis-ui.js) and [jQuery UI libraries](https://github.com/jquery/jquery-ui). 

Here is a demo:
http://release.mapbender3.org/application/mapbender_digitize_demo
* Select one feature in the right sidebar
* Start to edit it (click on edit button)
* Select "personal information" in the poped dialog
* Select  "favorit date"
