### ISSUE TITLE
create your own Element not work

### ISSUE THREAD

**Issue by SplashZK** [mapbender/mapbender#1023]
I done all steps in https://doc.mapbender.org/en/development/element_generate.html, the element appear in the list of elements but when i try to add i have the next error:
![image](https://user-images.githubusercontent.com/28606261/45313682-2d03a180-b4f5-11e8-98ce-53289a05e963.png)

**Versions**
 - Mapbender: 3.0.7.3 
 - Database: --
 - Browser:  chrome
 - PHP: 7.1

**Comment by astroidex** [comment]
Hello @SplashZK, thanks for the feedback. I tested the workflow as described.

For newer Mapbender versions Mapbender expects an AdminType to be provided for an element. This is not generated throught the command. We have to discuss and fix it.

I added a MapKlick element and added it to the workshop repository. 

You can find all the files that are necessary there.

https://github.com/mapbender/mapbender-workshop

I also created a ticket to discuss the bug in the generate:elemnt command: 
https://github.com/mapbender/mapbender/issues/1033

**Comment by rschwammborn** [comment]
Hi @SplashZK ,

thank you for your bug report. In the meantime, your version (3.0.7.3) is not supported anymore. We recommend to update Mapbender to a newer version - 3.0.8 as a LTS version should do the trick - and try to generate an element once more.

If the bug persists, feel free to reopen the issue at any time!
