### ISSUE TITLE
Web Mercator doesn't use geodesic measurements

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#1026]
**Describe the bug**
Line and area ruler don't use `geodesic: true`-Parameter if **Web Mercator** is used as projection. http://dev.openlayers.org/docs/files/OpenLayers/Control/Measure-js.html#OpenLayers.Control.Measure.geodesic

**To Reproduce**
1. Go to https://demo.mapbender.org/application/mapbender_user
2. Measure the length of Kennedybrücke with *UTM 32 selected* (~320m) and with *WGS 84 / Web Mercator* selected (~620m)

**Expected behavior**
Bridge length should be 320m.

**Versions (please complete the following information if it helps to narrow down the bug):**
Mapbender v. 3.0.7.3 (13.07.2018)

**Additional context**
Relevant line of code:
https://github.com/mapbender/mapbender/blob/release/3.0.7/src/Mapbender/CoreBundle/Resources/public/mapbender.element.ruler.js#L154

**Comment by DeEgge** [comment]
Possbile (if not complete) solution to fix this would be the following:

```javascript
return mapProj.proj.units === 'degrees' || mapProj.proj.units === 'dd' || mapProj.projCode === "EPSG:3857";
```

But surely there are other mercator based projections out there with metric units.

**Comment by DeEgge** [comment]
BTW: This also impacts the scale bar in print, but i might open another issue for this!

**Comment by DeEgge** [comment]
This should also be fixed
here (https://github.com/mapbender/mapbender/blob/release/3.0.7/src/Mapbender/CoreBundle/Resources/public/mapbender.model.js#L273),
here (https://github.com/mapbender/mapbender/blob/release/3.0.7/src/Mapbender/CoreBundle/Resources/public/mapbender.element.scalebar.js#L30),
here (https://github.com/mapbender/mapbender/blob/release/3.0.7/src/Mapbender/CoreBundle/Resources/public/mapbender.element.printClient.js#L218)

**Comment by werrolf** [comment]
Please try again.

**Comment by DeEgge** [comment]
Looks good! Still wondering why you would have the property `geodesic ` if it could be true by default!
