### ISSUE TITLE
Multi tab region support 

### ISSUE THREAD

**Issue by stekule** [mapbender/mapbender#1039]
Due to element id creation it is impossible to use multiple tab or accordion regions.
At the moment some element ids in 'MapbenderCoreBundle:Template:region.html.twig' are composed of a prefix 'tab', 'accordion' or 'container' and the loop index.
I propose to insert the name of the region between prefix and the loop index.
For example the id of a tab element could be created by `tab_{{ region }}{{loop.index}}`.

**Comment by astroidex** [comment]
Hello @stekule . Thanks for your suggestion. Can you define a usecase where this modification would help.

**Comment by stekule** [comment]
Hello @astroidex. Thanks for your reply. In ower usecase we have two different tabregions which group diffent information and actions. These regions are displayed at the same time. For examle the first region is used for diffent search tools and the second one holds some diffent widgets for the selected result.

**Comment by rschwammborn** [comment]
Hi @stekule ,
thank you for your feature suggestion. if you'd still love to see this feature being implemented in Mapbender, do not hesistate to contact our team at: https://mapbender.org/en/about-contact
Right now, I will close your request. If you are still interested, feel free to reopen it anytime!
