### ISSUE TITLE
[translations] add missing Italian translations

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1044]
* some Italian translations are missing
* https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/translations/messages.it.yml

**Comment by astroidex** [comment]
see Pull Request https://github.com/mapbender/mapbender/pull/1062

**Comment by werrolf** [comment]
Changes merged.

**Comment by pfavero-wheregroup** [comment]
Pull request: 
https://github.com/mapbender/fom/pull/47
https://github.com/mapbender/mapbender/pull/1078

**Comment by astroidex** [comment]
I tested with v3.0.8-beta4
Works fine. Italien translation is there.
Thanks to @pfavero-wheregroup!
