### ISSUE TITLE
WMS Update does not Update the WMS title

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1051]
When you update a WMS and the layertitle changes it is not updated in the Instanzes. YOu have to delete the Instanz from the application and loada it again to get the Title-definition from the Service.

**Describe the solution you'd like**
* would be great still to be able to change the title for a service instanz
* if the title of the service changes and no explicit change of the former title exists the new title from the services should be used 

# see internal #771

**Comment by werrolf** [comment]
https://github.com/mapbender/mapbender/pull/1115 (merged)

**Comment by astroidex** [comment]
Nice implementation.
I tested with v3.0.8-beta4
Works fine
-> it does not effect the title of the instanz at the top after update -> it stays the same

![title](https://user-images.githubusercontent.com/996298/55560410-7107ff00-56f0-11e9-9dbb-ee89b33f85a2.png)


**Just minor change -> set the grey color a bit darker.** 

- The grey color of the names are very light with firefox see screenshot. With chrome they are ok.

![firefox_layerinstanzdefinition](https://user-images.githubusercontent.com/996298/55560314-3e5e0680-56f0-11e9-9165-c602045e22d1.png)

**Comment by astroidex** [comment]
I talked to @werrolf 
css is from fom. Improvements of the colors are done in future releases.
