### ISSUE TITLE
Support/ Motivaiton - Become a Contributor

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#1056]
To support new contributors and motivate new persons to use mapbender or improve documentation/code i would suggest something like this: 
* https://github.com/OpenDroneMap/WebODM#become-a-contributor
* `When your first pull request is accepted, don't forget to fill this form to get your free WebODM T-Shirt metal`

**Comment by CharlyUnicorn** [comment]
nice idea from @pwheregroup : 
we could use a lvl system: 
* 1 pull request accepted and you get a small price (sticker ...) 
* 30 pull requests accepted and you get a big price (t-shirt...)
* 50 ...

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
