### ISSUE TITLE
ZoomToMaxExtent of ZoomBar behaves wrong

### ISSUE THREAD

**Issue by GeOSMRob** [mapbender/mapbender#1071]
**Describe the bug**

By clicking on the button "zoom to full extent" (globe in the zoombar element) an unexpected behavior is triggered.

Normally, the button should zoom to the max-extent configured in the application, considering the scale-controlled layers. Normally, zooming should only display specific layers that are in the affected scales. This behavior works properly when you click in the zoom bar or through interactive zooming.

**Example:**

If you move to the zoom scale 1: 250.000, then the layer "DTK250" will be automatically loaded and everything will be displayed correctly, see screenshot. But if you click on the button "zoom on total extent", then a wrong GetMap request will be made where the DTK250 layer is still active and is not automatically switched to the configured layer "TK1000".

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: [3.06.3, 3.0.7.7]
 - Browser [chrome, firefox]

**Comment by rschwammborn** [comment]
Hi,
does the bug still occur in Mapbender 3.0.8?
Could you attach the mentioned screenshot to the issue?

**Comment by GeOSMRob** [comment]
Hello,
I did not find the BUG in Mapbender 3.0.8. ZoomtoExtent works.
