### ISSUE TITLE
too many highlighted objects after search (router) when zooming

### ISSUE THREAD

**Issue by kartoffelfee** [mapbender/mapbender#1072]
**Describe the bug**

When I select two or more entries of the search router result list and zoom out not only the last obejct is highlighted in the map but  every object that has been selected before.

**To Reproduce**
1. https://demo.mapbender.org/application/suche_test
2. search for city 'berlin'
3. select 'berlin schöneberg' in the result list -> point of schöneberg is highlighted
4.  select 'berlin treptow' in the result list -> only point of treptow is highlighted
5. zoom out or in -> both points are highlighted

**Expected behavior**
Only the las selected object should be highlighted in the map

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: [e.g. 3.0.7.7]
 - Browser [e.g. chrome]

**Comment by astroidex** [comment]
Hi @kartoffelfee I can reproduce the behaviour. It does not make sense like this.

**Comment by werrolf** [comment]
Please test with [PR#1103](https://github.com/mapbender/mapbender/pull/1103).
