### ISSUE TITLE
[Redining] Zoom to feature zooms to the smallest level in your application for points and text without a buffer

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1081]
**Describe the bug**
When you zoom to a point or a text. The application will zoom to the smallest level (f.e. 1:500 see demo.mapbender.org)

**To Reproduce**
1. Redlining: Draw a big rectangle, draw a point , draw a text
2. Click zoom to geometry for the rectangle
3. Click zoom to geometry for the point/text
4. see: for text/point the smallest Zoomlevel will be choosed (ths can look very odd, when you provide an application with 1:100)

* see line in code: https://github.com/mapbender/mapbender/blob/release/3.0.7/src/Mapbender/CoreBundle/Resources/public/mapbender.element.redlining.js#L276

**Expected behavior**
* suggestion: either define a buffer around the element, define a Scale in the backend or zoom to the smallest level+1

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.7.7

**Screenshots / Logmessage**

![redlining1](https://user-images.githubusercontent.com/996298/52336078-39d4e480-2a04-11e9-8f5c-5f60edf5862e.png)
![redlining2](https://user-images.githubusercontent.com/996298/52336086-3e999880-2a04-11e9-8514-dd797e996ee4.png)
![redlinig3](https://user-images.githubusercontent.com/996298/52336097-42c5b600-2a04-11e9-9d7d-9bc86ebda6fe.png)

**Comment by eschuettler** [comment]
Thank you!
I can reproduce the behaviour with mb version 3.0.8. And I removed the label "bug", because I think it is a feature request.

**Comment by eschuettler** [comment]
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html
