### ISSUE TITLE
[map][visibleLayers] root layer can't get activated by visiblelayer parameter on start & toggle is gone

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1082]
**Describe the bug**
Documentation see: https://doc.mapbender.org/en/functions/basic/map.html#make-layer-visible

When you have a service deactivated on start (but the layer active) you can not use visiblelayers to activate the root layer. 

https://demo.mapbender.org/application/mapbender_digitize_demo?visiblelayers=50/150,50/151,50/152

**To Reproduce**
1. https://demo.mapbender.org/application/mapbender_digitize_demo -> Mapbender user root layer is disabled, the other layer are active, toggle is on
2. https://demo.mapbender.org/application/mapbender_digitize_demo?visiblelayers=50/150 -> 50/150 is the rot layer. Request should activate the root layer and like this activate all the layers oft the Service (as there are on by configuration) It is still not activated and the toggle is gone (service is closed)
3. https://demo.mapbender.org/application/mapbender_digitize_demo?visiblelayers=50/150,50/151,50/152 -> root layer activated butt toggle is gone

**Expected behavior**
* see above

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.7.7.

**Screenshots / Logmessage**

**Additional context**
With the following SQL you can create the requests for all WMSInstances:

`
Select slug, title,
'https://demo.mapbender.org/application/'
|| foo2.slug ||  '?visiblelayers=' || string_agg(combi, ',') as
mb_visibleLayerId
from
(SELECT li.id, li.title as title_Layerinstance, wmsinstance || '/' || li.id as combi, parent, wmsinstance, wmslayersource, foo.application_id, foo.slug, foo.wms_instance_id, foo.layerset, foo.title , foo.layerset_title
, 'https://demo.mapbender.org/application/' || foo.slug || '?visiblelayers=' || wmsinstance || '/' || li.id as mb_visibleLayerId
--parent, li.title, active, allowselected, selected, info, allowinfo, toggle, allowtoggle, allowreorder, minscale, maxscale, style, priority
          FROM public.mb_wms_wmsinstancelayer li,
                                ( SELECT l.id as layerset_id, l.application_id, l.title as layerset_title,
  s.id as wms_instance_id, layerset, s.title, weight, enabled, discr, basesource, a.slug
   FROM public.mb_core_layerset l,
  public.mb_core_sourceinstance s,
  public.mb_core_application a
  where s.layerset = l.id
  and s.enabled = true
  and a.id = l.application_id
) as foo
   where foo.wms_instance_id = wmsinstance and li.active = true
) as foo2
group by slug, title;
`

**Comment by werrolf** [comment]
Issue no longer occurs after merge of #1083.

**Comment by astroidex** [comment]
Thanks @werrolf I will test it an report

**Comment by astroidex** [comment]
Visible Layers does still not work, when you try to activate more then one layer. 

Does not work, when you try to activate more than one layer
- https://demo.mapbender.org/nightly/application/mapbender_digitize_demo?visiblelayers=50/150,50/151,50/152
- https://demo.mapbender.org/nightly/application/mapbender_digitize_demo?visiblelayers=50/151,50/152

Works fine when you activate one layer (it activates the root layer too)
- https://demo.mapbender.org/nightly/application/mapbender_digitize_demo?visiblelayers=50/150
- https://demo.mapbender.org/nightly/application/mapbender_digitize_demo?visiblelayers=50/151
- https://demo.mapbender.org/nightly/application/mapbender_digitize_demo?visiblelayers=50/152

**Comment by werrolf** [comment]
Error on passing in multiple layer idents confirmed.  
Seems [we use an OpenLayers.Util method](https://github.com/mapbender/mapbender/blob/v3.0.8-beta3/src/Mapbender/CoreBundle/Resources/public/mapbender.application.js#L457) to extract URL parameters. That method performs special treatment for comma-separated lists and the parameter comes out as an array instead of a scalar, which the receiving code does not handle.

Direct OpenLayers 2 dependencies in such peripheral code need to be cut rather soon anyway.

The only open question to me atm is if any users of that `Mapbender.Util.Url` class actually _expect_ array parameters. If none does, the fix would be much easier to implement than otherwise.

**Comment by astroidex** [comment]
I tested with v3.0.8-beta4
Works fine now.

I close the ticket.
