### ISSUE TITLE
[Backend] [map] layersets-dialog: long layerset names have word wrap and do not use the whole dialog 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1085]
**Describe the bug**
list of layersets is not displayed good. Word wrap is not at the enf of the dialog.

**To Reproduce**
1. Create a layerset wit a long name
2. Go to your map-element
3. Have a look at the layesets section of the map-element

**Expected behavior**
Layerset name should use the whole dialog

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.7.7
 - Browser firefox

**Screenshots / Logmessage**
* Demo application https://release.mapbender.org/manager/application/Geoportal_6402/edit

![backend_map_layerset](https://user-images.githubusercontent.com/996298/52559809-be55a780-2df6-11e9-9574-a61820401eee.png)

**Additional context**

**Comment by astroidex** [comment]
* additional information. Issue was fixed in 3.0.6

https://github.com/mapbender/mapbender/blob/release/3.0.7/src/Mapbender/ManagerBundle/Resources/public/sass/element/map.scss

**Comment by werrolf** [comment]
Word wrap is not an issue, it is exactly desired behaviour and will remain.  
Wasting width is an isse.

We're banging into

**Comment by astroidex** [comment]
Tested. Lookes good.
