### ISSUE TITLE
Feature_Count default to large

### ISSUE THREAD

**Issue by Noobud** [mapbender/mapbender#1099]
Hi,

in #849 there is the Feature_Count Parameter set to 1000.
Now i have a WMS Service, that reports that the Feature_Count must be <= 100.
So it does not work.

Is it possible to make this parameter configurable?

Many thanks,
Daniel

**Comment by werrolf** [comment]
Was raised to 1000 in 778ccc6be3ed737c32c939263907e263509c5937. Unsure why this number, but apparently the default was too low for a certain use case.  
@LazerTiberius might want to comment on this.

**Comment by LazerTiberius** [comment]
I just implemented this in this manner because I didn´t know that such a limitation can exist. The default value of 10 is not really reasonable. 
We should make this configurable if there can be limitations from the WMS side, right? @werrolf

**Comment by astroidex** [comment]
To make it configurable makes sense. maybe as a prameter in parameters.yml

Maybe 1000 is a bit high too. We changed as the default was 10 see #830

**Comment by astroidex** [comment]
let's make a quick solution and change the parameter to 100 (1000 was too high, 1000 sounds ok)
