### ISSUE TITLE
Feature Info dialog does not open after deactivate/activate layer

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1102]
**Describe the bug**
Feature Info dialog does not open after deactivate/activate layer

**To Reproduce**
1. Go to https://demo.mapbender.org/application/mapbender_user
2. Click on FeatureInfo for layer **name** of WMS Mapbender User -> FI result dialog shows up
3. disable visablity of layer **name** of WMS Mapbender User and enable it again
4. Try to get the featureInfo again
5. no Feature Info dialog shows up

**Expected behavior**
As usual the FeatureInfo dialog should show up

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.7.7

**Screenshots / Logmessage**

![fi](https://user-images.githubusercontent.com/996298/53016322-a6f96880-344d-11e9-9cdf-e4f28b742c01.png)

**Comment by rschwammborn** [comment]
That's unfortunate. But: I couldn't recreate the bug while testing the upcoming Mapbender version - so stay tuned!

**Comment by astroidex** [comment]
I tested with 3.0.8 beta 1: error does not occur anymore.
