### ISSUE TITLE
[PrintClient] Replace Pattern does not work

### ISSUE THREAD

**Issue by GeOSMRob** [mapbender/mapbender#1104]
**Describe the bug**
If I set the Replace Pattern in the print element, then only the "default" is evaluated and replacement is not evaluated.

**To Reproduce**
1. Go to PrintClient
2. Click on PrintClient-Configuration
3. Scroll down to Replace pattern
4. Set replace_pattern-Params
4. See error to Printing

**Docs**
- https://doc.mapbender.org/de/functions/export/printclient.html#yaml-definition

**Versions:**
 - Mapbender: [3.0.7.7]
 - Browser [Chrome,Firefox]

**Code:**
- https://github.com/mapbender/mapbender/blob/release/3.0.7/src/Mapbender/PrintBundle/Element/PrintClient.php#L367

**Comment by GeOSMRob** [comment]
Problem was found and a solution is worked out.

**Comment by werrolf** [comment]
See PR#1105

**Comment by werrolf** [comment]
We're good now right?

**Comment by GeOSMRob** [comment]
Alright bug has been fixed and the replace pattern works now.
