### ISSUE TITLE
[frontend][layertree] - context menu opens always at first wms

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1124]
**Describe the bug**
layertree - context menu opens always at first wms and not at the WMS where you opened it. 

**To Reproduce**
1. Open application https://demo.mapbender.org/nightly/application/mapbender_user
2. Go to the layertree and open the context menu for OSM Demo
3. See: context menu was opened for OSM Demo but is displayed at Mapbender users
4. Compare with last release 3.0.7.7: https://demo.mapbender.org/application/mapbender_user

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: [3.0.8 beta 3]
 - Browser chrome firefox

**Screenshots / Logmessage**
![mb_layertree_slider](https://user-images.githubusercontent.com/996298/54768606-cbd52d00-4bff-11e9-9f1c-904ff1a814ad.png)

**Comment by werrolf** [comment]
Can confirm context menu placement issues persist in a non-thematic layertree.
