### ISSUE TITLE
[frontend][printClient] text f.e. street names are printed twice instead of once

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1131]
**Describe the bug**
If you use a WMS that is not cached with dynamic text positioning it can occur that textes are printed out twice when tiles are used to generate the print output.

**To Reproduce**
1. use 288 dpi and A2
2. use a WMS that is not cached
3. print a region with textes and check the print output

**Expected behavior**
please do not print double textes

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8beta3

**Screenshots / Logmessage**
![mb_print_double](https://user-images.githubusercontent.com/996298/54900200-a469b300-4ed2-11e9-8b2c-f0246bd83aa4.png)

**Comment by werrolf** [comment]
As documented in [PR#1073](https://github.com/mapbender/mapbender/pull/1073), you can play with the container parameter `mapbender.imaageexport.renderer.wms.tile_buffer`, which is 512 by default.

If you have control over the WMS in question, you can also disable its obviously "smart" label placement entirely, to keep buffering overheads low.

**Comment by werrolf** [comment]
Alternative: you can bump `mapbender.imaageexport.renderer.wms.max_getmap_size` up from its rather safe default of 4096 to whatever you're sure of _all_ WMS services on the installation can serve. That may well be 8k or even higher. Be advised that you may still need to adjust buffering if you want to do larger than A2 @ 288dpi.
