### ISSUE TITLE
[frontend][Redlining] you can not disable a button

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1133]
**Describe the bug**
When you enable f.e. button 'point' you can not disable it via a second click on the button. It stays active. 

**To Reproduce**
1. Open Redlining https://demo.mapbender.org/nightly/application/mapbender_user
2. Click on button point and create a point
3. Try to disable the button point
4. See error: does not work

**Expected behavior**
If you click a second time on the button it should disable the funtionality

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender:3.0.8beta

**Screenshots / Logmessage**

**Additional context**

**Comment by werrolf** [comment]
You're describing the behaviour of every single tool in Redlining which has been consistent since the very beginning of Redlining in January 2015.  
This is a CR, marking appropriately.

**Comment by werrolf** [comment]
Stop assigning milestones to wishlist items.

**Comment by astroidex** [comment]
I tested with v3.0.8-beta4
Works fine.
I added 3.0.8 Milestone as it is now part of the version
