### ISSUE TITLE
[frontend][Redlining] textfield is empty after every text that is positioned 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1134]
**Describe the bug**
Redlining textfield is empty after every text that is positioned. 

In older versions the text in the textfield remained. Like that the user could define texts with the same content very easy.

See
https://version.mapbender.org/3063/application/mapbender_user

**To Reproduce**
1. Go to https://demo.mapbender.org/nightly/application/mapbender_user
2. Choos redlining in sidepane
3. Chosse button text and define a text
4. See: after you positioned the text the textfield is empty again

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: [e.g. 3.0.6.3]
 - Database: [e.g. PSQL 9.5.12]

**Screenshots / Logmessage**
If applicable, add screenshots or a logmessage from app/logs to help explain your problem.

**Additional context**

**Comment by werrolf** [comment]
You're describing behavior that was introduced in 1fd2c1725e6d000b94bef41cf6821b8f94ec10fc as part of PR #456, to resolve Issue #401, and first officially shipped in v3.0.5.4.

So I suppose you want to CR that the label text stays for the next feature.

**Comment by eschuettler** [comment]
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html
