### ISSUE TITLE
[frontend][Layertree] cursor remains in the tree after using the context menu

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1135]
**Describe the bug**
When you use the context menu of a layer f.e. to change the opacity and you close the window again, a blinking cursor remains close to the context-menu-icon 

https://demo.mapbender.org/nightly/application/mapbender_user

**To Reproduce**
1. Go to https://demo.mapbender.org/nightly/application/mapbender_user
2. Click on the context menu for mapbender_user
3. When you use the context menu of a layer f.e. to change the opacity and you close the window again, a blinking cursor remains close to the context-menu-icon 

**Expected behavior**
no cusor
**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8beta3
 - Browser: firefox (can't reproduce the behaviour in chrome)

**Screenshots / Logmessage**
![cursor](https://user-images.githubusercontent.com/996298/54900851-07f4e000-4ed5-11e9-8ad5-503406ae5cd0.png)

**Comment by werrolf** [comment]
Can't confirm cursor (Firefox Quantum 65.0.1 on auto-update).  
Can confirm context menu placement issues persist in a non-thematic layertree.
