### ISSUE TITLE
Update Element configuration without closing the edit dialog

### ISSUE THREAD

**Issue by frwg** [mapbender/mapbender#1139]
As a developer, I sometimes need to regularily update configurations, which can be exhausting when the dialog is closed on every update.  In developer mode, I would like to have an update-but-not-close button.

**Comment by astroidex** [comment]
Great suggestion. I would absolutely support this feature. Users asked for it quite often.

Would be great for
* service instance configuration
* element configurateion

**Comment by eschuettler** [comment]
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html
