### ISSUE TITLE
[frontend][WMSLoader] possibility to define to load the layers in reverve order

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1141]
**Is your feature request related to a problem? Please describe.**
WMS Loader enables to load a WMS to the application. QGIS Server provides a reverse layer order, so that layer can cover other layers. That is not wanted by the user.

It would be great to decide on load whether to use the **reverse order**  

**Describe the solution you'd like**
* Add a checkbox to the dialog: unchecked -> reverse order
* if reverse order is wanted the user can enable the checkbox
* the the WMS layer order should be loaded reverse

![reverse](https://user-images.githubusercontent.com/996298/55016085-5f3aa380-4fee-11e9-958d-7fb2e0a44531.png)

**Comment by eschuettler** [comment]
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html
