### ISSUE TITLE
[frontend][SearchRouter] zoom works only once, afterwards nothing happens

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1145]
**Describe the bug**
SearchRouter zoom works only once, afterwards nothing happens

**To Reproduce**
1. Go to https://demo.mapbender.org/nightly/application/test_ticket_1145
2. Search for Gemeinde Bonn
3. Many results show up
4. Zoom to Beuel -> works fine
5. Zoom to Geislar  or something else -> nothing happens
-> compare with 3.0.7.7 http://localhost/master/app_dev.php/application/Geoportal_5681

**Expected behavior**
Zoom should always work

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8 beta 3
 - Browser firefox, chrome

**Comment by rschwammborn** [comment]
Can confirm. The query itself works fine, the map just doesn't zoom accordingly. Even on the first query (4.), it centers on the false object.

**Comment by astroidex** [comment]
I tested with v3.0.8-beta4
Works fine now. 

I noticed that the searchrouter only jumps to results inside the max-extent-definition
