### ISSUE TITLE
[digitizer][clustering] label for clustered features is not displayed anymore

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1154]
**Describe the bug**
You can cluster feature in digitizer. Normally a label is shown with the number of clustered features. this label is not displayed anymore. Not sure whether an additional parameter is needed?
See https://doc.mapbender.org/en/functions/editing/digitizer.html#clustering-experimental

**To Reproduce**

- Add clustering to your application digitizer schema:

`                                clustering:
                                    -
                                      scale: 10000
                                      distance: 60
                                    -
                                      scale: 2500
                                      distance: 40
                                    -
                                      scale: 1000
                                      distance: 20
                                    -
                                      scale: 500
                                      distance: 1
                                      disable: true
`

1. Open your application 
2. See the clustered features
3. See that no label is displayed

**Expected behavior**
Clustered objects should be displayed as points with a label

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8beta4 -> digitizer:1.168
- also Digitizer-> 1.2 branch Status: 5.4.2019 (commit 7f096e8f07cbb3da7fc0a47a1caea9bbf75a8a77)

Should look like this 
![digitizer_clustering1](https://user-images.githubusercontent.com/996298/55626129-f6e88080-57aa-11e9-99ec-e6517d5fc31c.png)

**Comment by rschwammborn** [comment]
Thank you!
We are currently looking at this issue. I will create an internal issue to fix the bug.

**Comment by frwg** [comment]
In order to display the number of features, just add the line: `label: ${label}` to the style definition of the scheme, like in the example:

 schemes:
                            poi:
                                label: 'poi cluster'
                                maxResults: 50000
                                styles:
                                    default:
                                        graphic: true
                                        graphicWidth: 20
                                        graphicHeight: 20
                                        graphicOpacity: 0.9
                                        strokeWidth: 10
                                        strokeColor: '#648296'
                                        fillColor: '#7b9fb7'
                                        fillOpacity: 0.7
                                        fillWidth: 2
                                        **label: ${label}**

**Comment by astroidex** [comment]
Tested with 3.0.8.1: 
* Works fine for points
```
                            styles:
                                default:
                                    label: ${label}
```

You can only define label for default and not for select and selected:
-> this does not work. But is ok. Makes sense only to label default.
```
                              styles:
                                    default:
                                        label: ${label} 
                                    select:
                                        label: ${label}  
                                    selected:
                                        label: ${label}
```
