### ISSUE TITLE
Digitizer - default value '2024' as date

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#1155]
**Digitizer - default value '2024' as date**

If you include the element in the form, the day and month from the column in the database is correct BUT as the year you always see "2024", no matter which value is defined in the column of your data.  

**To Reproduce**
1. Go to 'https://demo.mapbender.org/application/mapbender_digi'
2. Click on an existing Point or add a new Point in the Sidepane
3. Open the second tab
4. See error in the field 'favorite Date' 

**Expected behavior**

If you include the element in the form, the date from the column in the database should be displayed at existing geometrys (used format is dd-mm-yyyy). If a "value" is defined, then this date-value should be displayed when you add an new geometry (described here: https://doc.mapbender3.org/de/functions/editing/digitizer.html#datumsauswahl-type-date
). If not then the user should define a date -> This should also show up, when you save the feature and open the dialog. 

**Versions:**
 - Mapbender: 3.0.8
 - Database: PSQL 9.6
 - Browser: tested with Chrome and Firefox

**Screenshots**

![Auswahl_002](https://user-images.githubusercontent.com/13517141/56293053-a701a600-6128-11e9-9b52-35585699ccd9.png)

**Additional context**

Tested with demo.mapbender.org and installations on OSGeoLive with newer PSQL-Database - same behaviour.

**Comment by eschuettler** [comment]
Thank you!
I can reproduce the behavior with mapbender 3.0.8. I will create an internal ticket to fix the bug.

**Comment by eschuettler** [comment]
The bug is fixed in mapbender v. 3.0.8.4. Thank you!
