### ISSUE TITLE
[Frontend][Dimensions Handler][Feature Info] Add support for richer metadata while operating with dimensions handler

### ISSUE THREAD

**Issue by rschwammborn** [mapbender/mapbender#1160]
**Is your feature request related to a problem? Please describe.**
When using the dimensions handler feature, the feature info dialogue always requests the newest metadata for the layer, although I selected an older version of it.

**Describe the solution you'd like**
While using dimensions handler, I'd like to see appear current metadata in the FeatureInfo dialogue for the dimension/year sublayer I'm spectating.

**Additional context**

**Hint**: GetFeatureInfo-request does not correctly fetch the TIME parameter submitted by GetMap-request.

See screenshots for more clarity about frontend behaviour:

![newest-metadata](https://user-images.githubusercontent.com/21199730/57225864-d27ffe00-700d-11e9-93b9-9880c21a01e2.png)
(current layer, current metadata in FeatureInfo)

![older-metadata](https://user-images.githubusercontent.com/21199730/57225852-d01da400-700d-11e9-8bf5-fca199f334e7.png)
(older layer, but current metadata in FeatureInfo)

**Comment by astroidex** [comment]
Testing 3.0.8.1: works fine. getFeatureInfo handles time parameter and give back the right result.
