### ISSUE TITLE
[frontend][overview] WMS in overview ordering is wrong

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1161]
**Describe the bug**
Overview can handle more then 1 WMS. 
Concept is that the WMS at the top in the administration is drawn at the top. In version 3.0.8 it is the other way round. Like this WMS are hidden

**To Reproduce**
1. Open https://demo.mapbender.org/manager/application/mapbender_user_yml/edit
2. Add mapbender-user WMS to your application to overview layerset to the top 
2.  Open the application -> no mapbender user are displayed in overview
3. Change the order in the layerset overview
4. Open application again -> WMS is displayed

**Expected behavior**
WMS at the top should be displayed at the top

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8

Screenshots

**Right order**
![mbo1](https://user-images.githubusercontent.com/996298/57512497-19bb0700-730c-11e9-917c-aeb59aba0084.png)

**WMS is hidden**
![mbo2](https://user-images.githubusercontent.com/996298/57512501-1e7fbb00-730c-11e9-9e1d-bd9af7f64b32.png)

**Order changed**
![mbo3](https://user-images.githubusercontent.com/996298/57512506-20e21500-730c-11e9-8389-35a3f793e919.png)

** WMS is displayed**
![mbo4](https://user-images.githubusercontent.com/996298/57512509-23446f00-730c-11e9-890d-f648fb4ae78e.png)

**Comment by rschwammborn** [comment]
I created an internal issue, the developers are currently looking at it.

**Comment by astroidex** [comment]
Tested with 3.0.8.1: works like expected. Fixed.
