### ISSUE TITLE
[Frontend][Dimensions Handler] when integrated in Layertree and Toolbar are not synchronized

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1162]
**Describe the bug**
When you integrate dimensions handler in Layertree (via WMS-Instance-Activate) and Toolbar via (add element DimensionHandler). The dimension handler does not work at all in 3.0.8.

**To Reproduce**
1. Load WMS http://geo4.service24.rlp.de/wms/hklika.fcgi?service=WMS&request=GetCapabilities&version=1.3.0
2. add wms to your Application
3. activate Dimension for WMS-Instance
4. Add element dimensions handler to the toolbar
5. Try to move the slider -> WMS is not requested and slider are not synchron

![dh1](https://user-images.githubusercontent.com/996298/57514481-e9c23280-7310-11e9-8fe4-9baef6cacbb7.png)

**Expected behavior**
Both dimensions slider should move and map should display the right time selected

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8

**Comment by rschwammborn** [comment]
Hi! We are right now looking at this bug. I created an internal issue.

**Comment by astroidex** [comment]
tested with 3.0.8.1:
* you can use the two slider (in layertree and Toolbar) - they both have an effect on the map. But they are not in sync.

**Comment by rschwammborn** [comment]
This one seems to be revolving about the always-relevant "bug or feature" discussion. It looks like this is regarded more as a feature than a bug, so I'm closing the issue for now. Let's consider this in a future major version of Mapbender.

**Comment by dpakprajul** [comment]
@astroidex  Is this Dimensions Handler depends upon the Mapbender version? Can I integrate this to Mapbender2.8?

**Comment by armin11** [comment]
hi - mapbender 2.8 has it's own dimension handler:
https://documents.geoportal.rlp.de/mediawiki/index.php/TreeGDE2
you can test it live on
https://www.geoportal.rlp.de

if you have further questions - ask them ;-)

best regards from germany,

armin

Am Fr., 20. Okt. 2023 um 13:25 Uhr schrieb Deepak Parajuli <
***@***.***>:
