### ISSUE TITLE
[Backend][Dimensions handler] element configuration change group does not update dimension

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1165]
**Describe the bug**
Element configuration of dimension handler:
* you can change the selected group, but this does not update dimension for the new selected group

**To Reproduce**
1. Go to backend -> administration and add with + a configuration to dimensions handler element
2. Choose a **group** --> see dimension show up
3. Choose another **group** -> dimension should change

**Expected behavior**
Dimension should change, when you choose another group

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.1

![dh_admin](https://user-images.githubusercontent.com/996298/57763281-5e2a1680-7701-11e9-8ba1-08966af5b0ea.png)

**Comment by astroidex** [comment]
@rschwammborn knows about the behaviour

**Comment by rschwammborn** [comment]
This issue is currently on hold. Please stay tuned for more.

**Comment by werrolf** [comment]
This is not a public diary.
