### ISSUE TITLE
[Backend][Dimensionshandler] lists all WMS and not only the active ones

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1166]
**Describe the bug**

You can try with the Two WMS
* http://geo.kreislippe.de/cgi-bin/alz.exe?language=ger&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetCapabilities
* http://geo4.service24.rlp.de/wms/hklika.fcgi?service=WMS&request=GetCapabilities&version=1.3.0

**To Reproduce**
1. Add the two wms to your application
2. **DIscable one WMS** with the eye button
3. Add Element DimensionsHandler and close
4. Open dimenionshandler and click +
5. See that all Services are offered also the not activated ones

**Expected behavior**
Dimensions Handler admin interface: List should only offer activated WMS/Layer for selections

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.1

**Screenshots / Logmessage**
![dh2](https://user-images.githubusercontent.com/996298/57770132-ec0cfe00-770f-11e9-8e93-ffdeda4cb32d.png)

![dh3](https://user-images.githubusercontent.com/996298/57770141-f3340c00-770f-11e9-9827-3c4cb709b8df.png)

**Comment by rschwammborn** [comment]
I created an internal ticket for this issue - stay tuned!
(Please note: DimensionsHandler is still in an experimental stage of development.)

**Comment by rschwammborn** [comment]
Althought DimensionsHandler ist still experimental, this should work now - tested again with 3.0.8.4-rc. Closed.
