### ISSUE TITLE
[backend][WMS Instance] de/activate layer does not work after checking the checkbox at the top

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1169]
**Describe the bug**
You can use the WMS Instance configuration to enable/disable layer on start. There is a line of checkboxes at the top that should help you to quickly disable all layers (usefull if you have many layer). Afterwards you normally can enable some layer agian.
Error: after deactivating the checkbox at the top you can not activate any single checkbox again

**To Reproduce**
0. Go to your WMS Instance
1. Deactivate the **checkbox** at the top
2. try to activate a checkbox from a layer -> does not work -> nothing happens

You can try it here: https://demo.mapbender.org/

**Expected behavior**
2. -> you should be able to activate single layer

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.1

**Screenshots / Logmessage**
![mb_check_wms](https://user-images.githubusercontent.com/996298/57850029-30b29b00-77dd-11e9-9ba4-4c10a9d3e1a6.png)

**Comment by rschwammborn** [comment]
Hi, I created an internal ticket for this issue. The Mapbender Team is fixing this as soon as possible.
