### ISSUE TITLE
[frontend][searchrouter] ILIKE uses LIKE LOWER which is not supported by OGR FDW and BBOX

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1170]
**Describe the bug**
SearchRouter can handle searches with tables that refer to OGR Sources via Foreign Data Wrapper (this worked fine till version 3.0.8.1).
A major change happened with version 3.0.8.1 and search does not work anymore:

1. change ILIKE uses lower instead of ILIKE
error message 
```
(LOWER(t.gebietsnummer) LIKE LOWER('%NSG-7141-004%'))
NOTICE:  unsupported OGR FDW expression type, T_FuncExpr
```

2. Search always adds BBOX of application as filter
* OGR FDW Source runs into timeout with spatial filter 

**To Reproduce**
You can use WFS for testing: Naturschutz WFS von RLP
https://geodaten.naturschutz.rlp.de/kartendienste_naturschutz/mod_ogc/wfs_getmap.php?mapfile=naturschutzgebiet&REQUEST=GetCapabilities&VERSION=1.1.0&SERVICE=WFS

* see internal story 130

```
  An exception occurred while executing '
  SELECT t."padid", t."gebietsname", t."gebietsnummer", t."kreisname", ST_AsGeoJSON(ST_Transform(t."geom", ?::int)) 
  as geom FROM org_fdw_rlp_naturschutzgebiet t WHERE (LOWER(t.gebietsnummer) LIKE LOWER(?)) AND (ST_Transform(ST_SetSRID(ST_MakeBox2D(ST_Point(?, ?), ST_Point(?, ?)), ?), ST_Srid(t."geom")) && t."geom")' 
  with params [25832, "%NSG-7141-004%", -500000, 4350000, 1600000, 6850000, 25832]:
```

**Expected behavior**
Search should work with OGR FDW

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.1

**Comment by werrolf** [comment]
1. LOWER() is standard SQL. FWD has to support this. If it doesn't, open a ticket on the FWD homepage, or try to locate a newer version that supports bare minimum SQL.

2. Add an index on your geometry column

**Comment by astroidex** [comment]
Looks like it was a problem of the special WFS that I tested. The problem does not occur with another WFS that I used.

So I will close this issue.

Just one additional information. If you can not use the bbox restriction you can deactivate it in SQLSearchEngine.php in function search: 

```
        #if ($srs && $extent) {
        #    $cond->add($this->getBoundsExpression($qb, $geomColumn, $extent, $srs));
        #}
```
