### ISSUE TITLE
[frontend][Layertree] i-Button  position for long textes in InternetExplorer

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1172]
**Describe the bug**
i-Button pposition in Layertree is not at the right position for long textes

**To Reproduce**
1. open application in IE
2. load a WMS with long layer names

**Expected behavior**
i-Button should be always at the same position

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.
 - Browser IE 11 wrong position, Firefox position is ok

**Screenshots / Logmessage**
![layertree_i_modified](https://user-images.githubusercontent.com/996298/58326496-43f0e680-7e2d-11e9-8132-1b435dd885e0.png)

**Comment by eschuettler** [comment]
I tried to reproduce the behaviour with 3.0.8.1. It works fine with the new version :)

**Comment by astroidex** [comment]
Hi @eschuettler . As mentioned this is a bug in Internet Explorer. It is still present in 3.0.8.1. See screenshot.

![2019-05-29 08_50_50-Mapbender - mapbender_user YAML - Internet Explorer](https://user-images.githubusercontent.com/996298/58535981-892b6480-81ef-11e9-8812-b568e801bac8.png)

**Comment by eschuettler** [comment]
Thanks :) I open an internal issue.

**Comment by werrolf** [comment]
Please retest with v3.0.8.2.

**Comment by rschwammborn** [comment]
Retested with Mapbender 3.0.8.3 and Internet Explorer 11, could not find the bug. Closed.

<img width="474" alt="long_wmsnames" src="https://user-images.githubusercontent.com/21199730/62859309-051c4f80-bcfd-11e9-9289-2832bac4d510.png">
