### ISSUE TITLE
Forgot password fails

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1173]
**Describe the bug**
Mapbender offers the feature to reset the user password.

**To Reproduce**
0. activate your mailer makes sense as a mail will be send (but error also occurs without activating it)
1. Go to your Mapbender https://demo.mapbender.org/user/password
2. Enter your user or email and click on the button **require password**
3. See error  in app.php mode: The server returned a "500 Internal Server Error
4. See error app_dev.php mode: **Unrecognized field: userName** (see also screenshot)

**Expected behavior**
Forgot password should send a mail to the defined user/email address

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: error occured in 3.0.8.1

**Screenshots / Logmessage**
![mb_pw1](https://user-images.githubusercontent.com/996298/58503078-205cd180-8188-11e9-932d-48e4ecde6771.png)

**Comment by eschuettler** [comment]
I will create an internal issue. Thank you!

**Comment by philvanbwg** [comment]
This is fixed now in FOM v3.1.2 and v3.2.1. I upgraded to v3.1.2 and tested it and it works fine.

**Comment by rschwammborn** [comment]
Can confirm, works fine. I'll close the issue.
