### ISSUE TITLE
selfregister fails - token link is invalid

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1174]
**Describe the bug**
Selfregister fail. The user account is generated in Mapbender but the token-link in the mail send to the new user does not work.

**To Reproduce**
1. Go to your config.yml and activate:
```
fom_user:
    selfregister: true

```
**Clear cache!**
2. Go to your login in Mapbender f.e: http://localhost/mapbender3081/app_dev.php/user/login
3. You find a new link: Register 
4. Klick on the link **Register** and fill the form and register
5. You will receive an email with a link
6. When you klick on the link to activate the user, you get an error message -> see screenshot

**Expected behavior**
The link should activte the new user.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.1

![fehlermeldung_registrierung](https://user-images.githubusercontent.com/996298/58536610-5edaa680-81f1-11e9-83d1-0539a1a4f754.png)

**Comment by werrolf** [comment]
Fixed in FOM [v3.1.2](https://github.com/mapbender/fom/releases/tag/v3.1.2]) and [v3.2.1](https://github.com/mapbender/fom/releases/tag/v3.2.1).

**Comment by astroidex** [comment]
@werrolf thanks for the fix
@rschwammborn please test the bugfix.
