### ISSUE TITLE
YAML-Configuration: published: false application is not accessable at all

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1175]
**Describe the bug**
You can define appllications via yaml. See https://github.com/mapbender/mapbender-starter/blob/master/application/app/config/applications/mapbender_user.yml#L7
And set permissions, access in the yaml-file.

**To Reproduce**
1. Go toyour xaml-application and set published: false
2. login to mapbender with you admin role
3. Your application is not listed in the application list. If you now the name of the slug you can open the link to the aplication and it will show up

**Expected behavior**
Application should be listed in the application list for the admin user

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.1

**Comment by werrolf** [comment]
Fixed in v3.0.8.2.
