### ISSUE TITLE
YAML-Configuration: Application list shows all yaml-applications although access restrictions are defined

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1176]
**Describe the bug**
You can define appllications via yaml and set permissions, access in the yaml-file.
See
https://github.com/mapbender/mapbender-starter/blob/master/application/app/config/applications/mapbender_user.yml#L7

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a user myuser, Create a group mygroup. add user to group
2. Modify your yaml file and add (!!! see how the group is defined uppercase and ROLE_GROUP-prefix)

```
            roles:
               - ROLE_GROUP_MYGROUP
```

3. go to your mapbender application overview page
4. See error: your application is listed although it is not accessible for the IS_AUTHENTICATED_ANONYMOUSLY group

**Expected behavior**
If the application has restrictions it should only be displayed for the user/group with access rights

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.1

**Comment by werrolf** [comment]
Fixed in v3.0.8.2.

**Comment by sylviaobk** [comment]
I can't find the user IS_AUTHENTICATED_ANONYMOUSLY anymore in the userlist. That's why I can't add this user to a new application anymore. 
My only way is to copy an old application with already existing IS_AUTHENTICATED_ANONYMOUSLY.

Cheers Sylvia
