### ISSUE TITLE
 InternetExplorer Application overview screenshots are displayed to big

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1177]
**Describe the bug**
Screenshots are displayed to big with IE 11

**To Reproduce**
1. Open your Mapbender with IE 

**Expected behavior**
All screenshots should be displayed in the predived size of the image section

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.1
- Browser IE

**Screenshots / Logmessage**
![application_overview](https://user-images.githubusercontent.com/996298/58796916-d8620280-85fe-11e9-95b8-8bb19035e3df.png)

**Comment by astroidex** [comment]
Change needed in : 
https://github.com/mapbender/mapbender/blob/release/3.0.7/src/Mapbender/ManagerBundle/Resources/public/sass/manager/manager.scss#L395

A similar definition could fix the behaviour:

```
	.listFilterApplicationBoxes .col1 div.cell img {
	    max-height: 100%;
	    max-width: 100%;
	    display: inline-block;
	    margin: 0 auto;
	}
```

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
