### ISSUE TITLE
parameters.yml add branding example to the file

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1179]
**Describe the feature**
It would be good to add the fom-server* section to parameters.yml to show the users how to switch to a different logo or use an internal version or server name

This could look like:

```
# Define your own branding parameters
#    branding:
#        project_name: Geoportal powered by Mapbender
#        project_version: 
#        logo: bundles/mapbendercore/image/logo_mb3.png
#        favicon: https://github.com/mapbender/mapbender-workshop/blob/master/src/Workshop/DemoBundle/Resources/public/image/favicon.png 
```

It would also be great to move the explanation to the documentation and not to refer to PR and Code Comment: 
https://github.com/mapbender/mapbender-starter/blob/master/application/app/config/parameters.yml.dist#L20

**Comment by werrolf** [comment]
No.
We will not dump values for every possible parameter in paramaeters.yml.dist.

**Comment by astroidex** [comment]
@rschwammborn @eschuettler - if this is the case. Please add the information to the documentation.
