### ISSUE TITLE
favicon is not displayed always 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1180]
**Describe the bug**
in 3.0.8.1 the favicon is not displayed always:
* ok https://demo.mapbender.org
* ok https://demo.mapbender.org/application/mapbender_user_yml
* https://demo.mapbender.org/user/login -> shows Symfony favicon
* https://demo.mapbender.org/user/password -> shows Symfony favicon

**Comment by CharlyUnicorn** [comment]
add the following row 

`<link rel="shortcut icon" href="{% block favicon %}{{ asset('favicon.png') }}{% endblock %}"/> 
`

in the file box.html.twig

**Comment by werrolf** [comment]
Default favicon fixed in v3.0.8.2.
