### ISSUE TITLE
branding.favicon is not displayed or default favicon is displayed

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1181]
**Describe the bug**
You can define your own favicon via branding.favicon. This icon is not used. Sometimes no favicon is displayed, sometimes the default is displayed. But the selfdefined favicon is not displayed at all.

Or is it a configuratioin issue?

-     default is displayed https://localhost/mapbender/
-     default is displayed https://localhost/mapbender/application/mapbender_user_yml
-    no favicon https://localhost/mapbender/user/login 
-    no favicon  https://localhost/mapbender/user/password -> shows Symfony favicon

```
branding parameters
#    branding:
#        favicon: favicon_new.png # download and rename from https://github.com/mapbender/mapbender-workshop/blob/master/src/Workshop/DemoBundle/Resources/public/image/favicon.png 
```

**To Reproduce**
1. Download an alternative favicon f.e https://github.com/mapbender/mapbender-workshop/blob/master/src/Workshop/DemoBundle/Resources/public/image/favicon.png and copy it to your web directory
2. define the branding.favicon in your parameters.yml, set access rights
3. clear cache
4. Open your application and check the favicon
5. View webpage source code and check for 
It reference either to the default favicon or is empty

```
 <link rel="shortcut icon" href="/mapbender/favicon.png" />
 <link rel="shortcut icon" href=""/>
```

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.1

**Comment by werrolf** [comment]
What gave you the impression this would work?

**Comment by eschuettler** [comment]
One can not change/define the favicon in the parameters.yml.
You can change the favicon through replacing the favicon.png-file under application/web.

**Comment by astroidex** [comment]
Hello.
I have the information that it should work from parameters.yml.dist 

```
    ## Legacy branding / versioning params.
    ## This is no longer used for versioning Mapbender and will never be updated
    ## again for a Mapbender release.
    ## For BC / continuity, you may still use these variables to brand / version your project.
    ## For summary information / discussion see https://github.com/mapbender/mapbender/pull/1012
    ## For full project branding / versioning options, see code comment:
    ## https://github.com/mapbender/mapbender/blob/42e0f8b9a8031118719fc4881a92f0adab4ebacf/src/Mapbender/CoreBundle/DependencyInjection/Compiler/ProvideBrandingPass.php#L17
    fom: ~
```

There is a link that refers to parameters that can be set (added in August 2018): 
https://github.com/mapbender/mapbender/blob/42e0f8b9a8031118719fc4881a92f0adab4ebacf/src/Mapbender/CoreBundle/DependencyInjection/Compiler/ProvideBrandingPass.php#L17

Maybe we should delete the information from parameters.yml.dist or modify it and document the possible settings n the documentation.

@eschuettler - could you please check.

**Comment by werrolf** [comment]
Comment will be removed. No such thing was ever implemented.

There are already two ways to customize the favicon.
1) Replace the favicon, like everyone else running a website does it. [First Google hit for "apache favicon"](https://stackoverflow.com/a/2729430).
2) Customize the `favicon` block on the twig level

Two methods is already one too many.

**Comment by astroidex** [comment]
ok. Thanks. Good idea to remove the information from parameters.yml and the script then
