### ISSUE TITLE
[frontend] dialog windows is not resizable for all elements

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1183]
**Is your feature request related to a problem? Please describe.**
For most elements (like measure, legend) the dialog shows a symbol at the right lower corner of the dialog to resize the dialog. This symbol is missing f. e. print and poi. Would be great to have the symbol in all dialogs.

**To reproduce**
* open https://demo.mapbender.org/application/mapbender_user_yml
* klick print
* see there is not symbol at the lower right corner to resize

**Comment by eschuettler** [comment]
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html
