### ISSUE TITLE
SimpleSearch - no results with Solr

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#1184]
**Describe the bug**
The search with the element SimpleSearch will not find any matches if Solr is used. I tested it in a workshop with the default configurations and a running system, but every try ended with error 400 and no results. 

**To Reproduce**
1. Go to 'https://demo.mapbender.org/application/solr_search'
2. Enter in the Searchfield 'Hau'
3. See nothing as Results 'https://demo.mapbender.org/application/solr_search/element/149/search?maxresults=10&term=hau*'

Alternativ: Install solr and test it local with your instance... 

**Expected behavior**
These entrys should appear in the result list: 
http://geodaten.metropoleruhr.de/suche?wt=json&indent=true&rows=10&q=Hau*

**Versions:**
 - Mapbender: 3.0.8.1
 - Solr: 8.1.1 and http://geodaten.metropoleruhr.de/suche
 - Browser Chrome and Firefox

**Screenshots / Logmessage**

![Auswahl_001](https://user-images.githubusercontent.com/13517141/59756196-8c16f380-9289-11e9-8e37-b5c4cc9c0cd9.png)

**Additional context**

Configuration of SimpleSearch Element: 
(https://doc.mapbender.org/de/functions/search/simplesearch.html)

```
query_url: http://geodaten.metropoleruhr.de/suche?wt=json&indent=true&rows=10
query_key: q
query_ws_replace: 
query_format: '%s'
token_regex: [^a-zA-Z0-9äöüÄÖÜß]   
token_regex_in: ([a-zA-ZäöüÄÖÜß]{3,})
token_regex_out: '$1*'   
collection_path: response.docs
label_attribute: text       
geom_attribute: wgs84
geom_format: WKT     
delay: 300
result_buffer: 50 
result_minscale: 1000
result_maxscale: 5000
result_icon_url: http://demo.mapbender.org/bundles/mapbendercore/image/pin_red.png # Marker, der zur Trefferanzeige verwendet werden soll
result_icon_offset: -6,-38    
```

**Comment by werrolf** [comment]
Upstream server problem?

http://geodaten.metropoleruhr.de/suche?wt=json&indent=true&rows=10&q=aac*

```Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.25 (Debian) Server at geodaten.metropoleruhr.de Port 80```

**Comment by werrolf** [comment]
Hint: in debug mode Mapbender SimpleSearch will add a response header `X-Mapbender-SimpleSearch-URL`. You can pick this out of your Chrome / Firefox network console and verify the URL used to query the Solr server.

**Comment by rschwammborn** [comment]
Could've been the upstream server problem - works correctly right now in demo.mapbender.org
I'm closing this issue.
