### ISSUE TITLE
[frontend] add WMS via WMSLoader with InternetExplorer fails

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1187]
**Describe the bug**
With InternetExplorer 11 WMSLoader fails to load the WMS. Only a message shows up. The same problem occurs for WMS that are loaded with **loadDeclarativeWms**.

**To Reproduce**
1. Open InternetExplorer 11
2. Go to https://demo.mapbender.org/application/mapbender_user_yml
2. Click on **WMSLoader**
3. Load the referred mapbender-user WMS
4. See error **WSLoader: wms capabilities can't be loaded**

With app_dev.php tyou can see that the url is not parsed correct:

`Invalid url 'https://wms.wheregroup.com:443cgi-bin/mapbender_user.xml?SERVICE=WMS&VERSION=1.1.1&REQUEST=getCapabilities'`

**Expected behavior**
Load WMS to application

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.1 with IE 11 (with firefox, Edge everything works fine)

**Screenshots / Logmessage**
![mb_wmsLoader](https://user-images.githubusercontent.com/996298/60015208-2e1c4e80-9683-11e9-8e97-3689945c9cb4.png)

**Comment by astroidex** [comment]
@LazerTiberius had a look at the problem and could fix it.

**Comment by astroidex** [comment]
Fix was tested with IE 11 and firefox. Works fine. Can get merged

**Comment by werrolf** [comment]
Fixed in #1191
