### ISSUE TITLE
change Layertitle in demo applications for OSM WMS layer

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1188]
It still says: Germany OSM Demo WhereGroup -> But the layer represents the whole world. 

see https://github.com/mapbender/mapbender-starter/blob/master/application/app/config/applications/mapbender_user.yml#L36

Fix Title for all applications in:
https://github.com/mapbender/mapbender-starter/blob/master/application/app/config/applications/

See WMS for more information: https://osm-demo.wheregroup.com/service?Service=WMS&Request=getCapabilities&Version=1.3.0

Find a good title for the layer f.e OpenStreetMap.

**Comment by eschuettler** [comment]
Thank you!

I changed the title:
https://github.com/mapbender/mapbender-starter/pull/93

**Comment by astroidex** [comment]
@eschuettler - the PR looks good but it is not merged yet. Maybe close the ticket, when the merge was done.

**Comment by werrolf** [comment]
[PR#93](https://github.com/mapbender/mapbender-starter/pull/93) merged.
