### ISSUE TITLE
bugfix geojson and new features of simpleSearch "srs" and "label-string" configurable

### ISSUE THREAD

**Issue by GeOSMRob** [mapbender/mapbender#1189]
**Is your feature request related to a problem? Please describe.**
The SimpleSearch element has only a static label input field for the backend and the result is not transformed on-the-fly in the frontend.

In addition, the Geom format "geojson" is not properly read, interpreted and applied in Openlayers.

**Describe the solution you'd like**

An extension of the simple search:

- Now the objects can be transformed on the client side in projection.

- In the backend, the SRS can now be adjusted for the search

- In addition, it is possible to query Geojson objects via the search

- In addition, the label string in the backend can be adjusted by user-defined settings.

`properties.name + properties.street + properties.housenumber + properties.city + properties.postcode`

**Additional context**

please refer PullRequest: https://github.com/mapbender/mapbender/pull/1182

Example from photon request:

- https://github.com/komoot/photon 

- Search field:

![grafik](https://user-images.githubusercontent.com/9570545/59593337-090f6500-90f2-11e9-909d-f3b32a9dbeb0.png)

- Request:

![grafik](https://user-images.githubusercontent.com/9570545/59592919-3d365600-90f1-11e9-98ac-bf468b333334.png)

![grafik](https://user-images.githubusercontent.com/9570545/59549662-2e209e00-8f61-11e9-8bc8-e96a0503d8e3.png)

**Comment by eschuettler** [comment]
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH
info@wheregroup.com
https://wheregroup.com/kontakt.html
