### ISSUE TITLE
Backend - Add Service - show errors from WMS

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#119]
- when the WMS can't be loaded show the error from the service, like mapServer Message

"Der Mapbender gibt z.B. bei Fehlern in der Mapdatei die Meldung „No supportet capabilities document“ heraus. Damit kann man leider nur wenig anfangen. Lade ich die URL beispielsweise in QGIS, so wird mir die „originale“ Mapserver-Meldung angezeigt. "

**Comment by hwbllmnn** [comment]
Is that still an issue? Nowadays you can have your WMS capabilities document validated.

**Comment by AxxL** [comment]
I close this issue since it is outdated. If this requirement is still relevant, feel free to (re)open again.
