### ISSUE TITLE
[Backend] Click on User Control runs into an ACL error

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1192]
**Describe the bug**

**To Reproduce**
**Use a Mapbender with SQLite**
1. Go to your Mapbender https://demo.mapbender.org/manager/user and login
2. Click User Control
3. See error
```
There is no ACL for the given object identity.
500 Internal Server Error - AclNotFoundException 
```

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender 3.0.8.2
 - use DB SQLITE

**Comment by werrolf** [comment]
Fixed in [FOM v3.2.5](https://github.com/mapbender/fom/releases/tag/v3.2.5).
