### ISSUE TITLE
[Backend] Click on Sources runs into error with postgresql db

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1193]
**Describe the bug**
When you Click on sources in your administration the following error occurs with PostgreSQL (sqlite  is ok)

Mapbender check says everything is o
app/console mapbender:config:check 

**To Reproduce**
1. Go to admin backend / Use Postgresql db as Administration db (I use a PostgreSQL db that was in action since Mapbender 3.0.7.x)
2. Click on 'Source'
3. See error

![Bildschirmfoto von 2019-07-04 16-48-02](https://user-images.githubusercontent.com/996298/60674974-9f29e600-9e7b-11e9-94f6-c0e985841c5c.png)

CRITICAL - Uncaught PHP Exception RuntimeException: "No loader available for source instance type " at /data/mapbender-starter-v3.0.8.2/mapbender/src/Mapbender/CoreBundle/Component/Source/TypeDirectoryService.php line 87 

https://github.com/mapbender/mapbender/blob/release/3.0.7/src/Mapbender/CoreBundle/Component/Source/TypeDirectoryService.php#L87

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3..0.8.2
 - Database: PpostgreSQL 10 runs into error (works fine with shipped SQLite DB)
 - PHP 7.2

**Screenshots / Logmessage**
If applicable, add screenshots or a logmessage from app/logs to help explain your problem.

**Additional context**

**Comment by werrolf** [comment]
You should not empty the "type" field in any row in mb_core_source in pgadmin or whatever you used.

Mapbender does not store sources with empty type column. Nothing works with an empty type column.

Fix your empty type column or delete the affected row(s).

**Comment by astroidex** [comment]
Hello,
thanks for the information. Nice. Now I know how to fix it.

I did not change the content of column "type" of table mb_core_source,

In older Mapbender versions (3.0.4.x) this column was empty. 

My database is in use since some Mapbender versions and I always update to the next version. Like this I have a look on update compatibility.
