### ISSUE TITLE
Cooperate on lib to deserialize Capabilities 

### ISSUE THREAD

**Issue by allartk** [mapbender/mapbender#1194]
Hello,

Last Thursday we spoke about many subjects :) In the mean time we published a library (in early development) to (de)serialize OGC xml documents such as Capabilities;

https://github.com/NieuwlandGeo/OgcSerializer 

We are curious about your thoughts about this.

Regards,

Allart & Eric

**Comment by fhaefker** [comment]
Hello, 

We are sorry that we missed to response earlier. 
There's been a lot going on around Mapbender in the last few months (new MB version, OpenLayers upgrade, MB community meeting...).
We hope you are fine,

Your Mapbender-Team
