### ISSUE TITLE
app/console doctrine:fixtures:load runs into undefined index error with PostgreSQl DB

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1195]
**Describe the bug**
If you want to load the yaml-Application to your PostgreSQl-Database with app/console doctrine:fixtures:load you run run into an error.

* Tested with PostgreSQL 9.5 and 10 with a new created database
* **worked fine with PostgreSQL and 3.0.8.1**

3.0.8.2
app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Application/ --append

  > loading Mapbender\CoreBundle\DataFixtures\ORM\Application\LoadApplicationData                                                     
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined index: mapbender_users_0_0               
``

3.0.8.3
![Konsole-Fehlermeldung-1195](https://user-images.githubusercontent.com/996298/61357139-09795800-a878-11e9-8484-8142b684c2ee.png)

**To Reproduce**
1. Go to 'the terminal' cd mapbender
2. create an administrative DB in PostgreSQL and refer to it in parameters.yml see https://doc.mapbender.org/en/installation/installation_ubuntu.html#id1
3. run: app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Application/ --append
4. See error see above and note that there are no new applications in the database

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.2 and 3.0.8.3
 - Database: PostgreSQL 9.5 and 10

**Comment by rschwammborn** [comment]
I also tested this behaviour (Mapbender 3.0.8.3 / Postgres 10) - the developers are currently working on a fix.

**Comment by rschwammborn** [comment]
The bug has been fixed since Mapbender 3.0.8.4-RC2. I'm closing the issue.
