### ISSUE TITLE
add source v3.0.8.1 - error with secured services

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#1198]
**Describe the bug**

Mapbender in v 3.0.8.1 has problems with the protected services of the LGB. At demo.mapbender.org the same error occurs wit the 3.0.8.x versions. With QGIS 3.4 there were no problems with the service (not tested with v3.6).

**To Reproduce**
1. Go to the administration of sources
2. Click on 'add source'
3. Add a secured WMS from a source of your choice (with the correct user and password), 
e.g.. https://security.geobasis-bb.de/wss/service/WMS_BB_DOP20c_Cache/httpauth?Service=WMS&Request=GetCapabilities&version=1.3.0

**Expected behavior**
The WMS is loaded as a data source and available for your use case. 

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.1
 - Database: PSQL 10
 - Browser: chrome, firefox, chromium

**Screenshots / Logmessage**

 "mb.wms.repository.parser.couldnotparse"

**Comment by rschwammborn** [comment]
You're right. This does not work with the WMS Loader either (tested in 3.0.8.4-rc). QGIS 3.8 also accepted the request. I created an internal ticket on this matter. For developer details, see https://github.com/mapbender/mapbender/issues/1201

**Comment by werrolf** [comment]
Backend-loaded sources are fixed in [Owsproxy v3.1.2](https://github.com/mapbender/owsproxy3/releases/tag/v3.1.2).

For WmsLoader see [#1201](https://github.com/mapbender/mapbender/issues/1201).

**Comment by werrolf** [comment]
WmsLoader fixed in [Mapbender v3.0.8.4-RC2](https://github.com/mapbender/mapbender/releases/tag/v3.0.8.4-RC2), also requires [Owsproxy v3.1.2](https://github.com/mapbender/owsproxy3/releases/tag/v3.1.2).

Changes bundled in [Mapbender Starter v3.0.8.4-RC2](https://github.com/mapbender/mapbender-starter/releases/tag/v3.0.8.4-RC2) (starter branch `rc`).

**Comment by rschwammborn** [comment]
Tested in RC3 - the developers fixed the bug successfully (see comment above).
