### ISSUE TITLE
app/console doctrine:schema:update with SQLite does not show updates

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1199]
**Describe the bug**
app/console doctrine:schema:update with SQLite does not show updates. Instead it shows the whole DB schema.
When you run -force it says it updated the database, but with dump-sql it again shows many sqls.

**To Reproduce**
1. Use mapbender 3.0.8.3 from http://mapbender.org/builds/
2. use the SQLite DB that is provided with Mapbender
3. run app/console doctrine:schema:update --dump-sql -> shows a lot of sqls -> normally it should not show any updated but should say that everything is ok
with a PostgreSQL db the command works fine

app/console mapbender:config:check says that everything is ok

**Expected behavior**
Command should only show the sqls  that are necessary to update the db

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.x
 - Database: SQLite

**Screenshots / Logmessage**
If applicable, add screenshots or a logmessage from app/logs to help explain your problem.

**Additional context**
parameters:
    database_driver:   pdo_sqlite
    database_host:     ~
    database_port:     ~
    database_name:     ~
    database_path:     %kernel.root_dir%/db/demo.sqlite
    database_user:     ~
    database_password: ~

SQL beim AUfruf von: app/console doctrine:schema:update --dump-sql
CREATE TEMPORARY TABLE __temp__fom_profile_basic AS SELECT uid, firstName, lastName, notes, phone, street, zipCode, city, country, organizationName, organizationRole FROM fom_profile_basic;
DROP TABLE fom_profile_basic;
CREATE TABLE fom_profile_basic ("uid" INTEGER NOT NULL, firstName VARCHAR(255) DEFAULT NULL COLLATE BINARY, lastName VARCHAR(255) DEFAULT NULL COLLATE BINARY, notes CLOB DEFAULT NULL COLLATE BINARY, phone VARCHAR(255) DEFAULT NULL COLLATE BINARY, street VARCHAR(255) DEFAULT NULL COLLATE BINARY, zipCode VARCHAR(255) DEFAULT NULL COLLATE BINARY, city VARCHAR(255) DEFAULT NULL COLLATE BINARY, country VARCHAR(255) DEFAULT NULL COLLATE BINARY, organizationName VARCHAR(255) DEFAULT NULL COLLATE BINARY, organizationRole VARCHAR(255) DEFAULT NULL COLLATE BINARY, PRIMARY KEY(uid), CONSTRAINT FK_DE31F81B235C43F FOREIGN KEY ("uid") REFERENCES fom_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO fom_profile_basic ("uid", firstName, lastName, notes, phone, street, zipCode, city, country, organizationName, organizationRole) SELECT uid, firstName, lastName, notes, phone, street, zipCode, city, country, organizationName, organizationRole FROM __temp__fom_profile_basic;
DROP TABLE __temp__fom_profile_basic;
DROP INDEX ipNamedRequestDate;
CREATE TEMPORARY TABLE __temp__fom_user_log AS SELECT id, userId, userName, context, ipAddress, "action", status, creationDate FROM fom_user_log;
DROP TABLE fom_user_log;
CREATE TABLE fom_user_log (id INTEGER NOT NULL, userId INTEGER DEFAULT NULL, userName VARCHAR(255) DEFAULT NULL COLLATE BINARY, ipAddress VARCHAR(255) NOT NULL COLLATE BINARY, "action" VARCHAR(255) NOT NULL COLLATE BINARY, status VARCHAR(255) NOT NULL COLLATE BINARY, creationDate DATETIME DEFAULT NULL, context CLOB DEFAULT NULL, PRIMARY KEY(id));
INSERT INTO fom_user_log (id, userId, userName, context, ipAddress, "action", status, creationDate) SELECT id, userId, userName, context, ipAddress, "action", status, creationDate FROM __temp__fom_user_log;
DROP TABLE __temp__fom_user_log;
CREATE INDEX ipNamedRequestDate ON fom_user_log (ipAddress, userName, creationDate, userId);
DROP INDEX IDX_15F45F1FE54D947;
DROP INDEX IDX_15F45F1A76ED395;
CREATE TEMPORARY TABLE __temp__fom_users_groups AS SELECT user_id, group_id FROM fom_users_groups;
DROP TABLE fom_users_groups;
CREATE TABLE fom_users_groups (user_id INTEGER NOT NULL, group_id INTEGER NOT NULL, PRIMARY KEY(user_id, group_id), CONSTRAINT FK_15F45F1A76ED395 FOREIGN KEY (user_id) REFERENCES fom_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_15F45F1FE54D947 FOREIGN KEY (group_id) REFERENCES fom_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO fom_users_groups (user_id, group_id) SELECT user_id, group_id FROM __temp__fom_users_groups;
DROP TABLE __temp__fom_users_groups;
CREATE INDEX IDX_15F45F1FE54D947 ON fom_users_groups (group_id);
CREATE INDEX IDX_15F45F1A76ED395 ON fom_users_groups (user_id);
DROP INDEX UNIQ_77F4A71D989D9B62;
DROP INDEX UNIQ_77F4A71D2B36786B;
CREATE TEMPORARY TABLE __temp__mb_core_application AS SELECT id, title, slug, description, template, published, screenshot, extra_assets, updated, custom_css FROM mb_core_application;
DROP TABLE mb_core_application;
CREATE TABLE mb_core_application (id INTEGER NOT NULL, title VARCHAR(128) NOT NULL COLLATE BINARY, slug VARCHAR(255) NOT NULL COLLATE BINARY, description CLOB DEFAULT NULL COLLATE BINARY, template VARCHAR(1024) NOT NULL COLLATE BINARY, published BOOLEAN NOT NULL, screenshot VARCHAR(256) DEFAULT NULL COLLATE BINARY, updated DATETIME NOT NULL, custom_css CLOB DEFAULT NULL COLLATE BINARY, extra_assets CLOB DEFAULT NULL, PRIMARY KEY(id));
INSERT INTO mb_core_application (id, title, slug, description, template, published, screenshot, extra_assets, updated, custom_css) SELECT id, title, slug, description, template, published, screenshot, extra_assets, updated, custom_css FROM __temp__mb_core_application;
DROP TABLE __temp__mb_core_application;
CREATE UNIQUE INDEX UNIQ_77F4A71D989D9B62 ON mb_core_application (slug);
CREATE UNIQUE INDEX UNIQ_77F4A71D2B36786B ON mb_core_application (title);
DROP INDEX layerset_idx;
DROP INDEX IDX_9D1A22923E030ACD;
CREATE TEMPORARY TABLE __temp__mb_core_layerset AS SELECT id, application_id, title FROM mb_core_layerset;
DROP TABLE mb_core_layerset;
CREATE TABLE mb_core_layerset (id INTEGER NOT NULL, application_id INTEGER DEFAULT NULL, title VARCHAR(128) NOT NULL COLLATE BINARY, PRIMARY KEY(id), CONSTRAINT FK_9D1A22923E030ACD FOREIGN KEY (application_id) REFERENCES mb_core_application (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO mb_core_layerset (id, application_id, title) SELECT id, application_id, title FROM __temp__mb_core_layerset;
DROP TABLE __temp__mb_core_layerset;
CREATE UNIQUE INDEX layerset_idx ON mb_core_layerset (application_id, title);
CREATE INDEX IDX_9D1A22923E030ACD ON mb_core_layerset (application_id);
DROP INDEX IDX_228B0AD3E030ACD;
CREATE TEMPORARY TABLE __temp__mb_core_element AS SELECT id, application_id, title, class, configuration, region, enabled, weight FROM mb_core_element;
DROP TABLE mb_core_element;
CREATE TABLE mb_core_element (id INTEGER NOT NULL, application_id INTEGER DEFAULT NULL, title VARCHAR(128) NOT NULL COLLATE BINARY, class VARCHAR(1024) NOT NULL COLLATE BINARY, region VARCHAR(255) NOT NULL COLLATE BINARY, enabled BOOLEAN DEFAULT NULL, weight INTEGER NOT NULL, configuration CLOB DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT FK_228B0AD3E030ACD FOREIGN KEY (application_id) REFERENCES mb_core_application (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO mb_core_element (id, application_id, title, class, configuration, region, enabled, weight) SELECT id, application_id, title, class, configuration, region, enabled, weight FROM __temp__mb_core_element;
DROP TABLE __temp__mb_core_element;
CREATE INDEX IDX_228B0AD3E030ACD ON mb_core_element (application_id);
DROP INDEX IDX_A9299ACF3E030ACD;
CREATE TEMPORARY TABLE __temp__mb_core_regionproperties AS SELECT id, application_id, name, properties FROM mb_core_regionproperties;
DROP TABLE mb_core_regionproperties;
CREATE TABLE mb_core_regionproperties (id INTEGER NOT NULL, application_id INTEGER DEFAULT NULL, name VARCHAR(128) NOT NULL COLLATE BINARY, properties CLOB DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT FK_A9299ACF3E030ACD FOREIGN KEY (application_id) REFERENCES mb_core_application (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO mb_core_regionproperties (id, application_id, name, properties) SELECT id, application_id, name, properties FROM __temp__mb_core_regionproperties;
DROP TABLE __temp__mb_core_regionproperties;
CREATE INDEX IDX_A9299ACF3E030ACD ON mb_core_regionproperties (application_id);
DROP INDEX IDX_688D0B496A3B1D21;
CREATE TEMPORARY TABLE __temp__mb_core_sourceinstance AS SELECT id, layerset, title, weight, enabled, basesource, discr FROM mb_core_sourceinstance;
DROP TABLE mb_core_sourceinstance;
CREATE TABLE mb_core_sourceinstance (id INTEGER NOT NULL, layerset INTEGER DEFAULT NULL, title VARCHAR(255) DEFAULT NULL COLLATE BINARY, weight INTEGER NOT NULL, enabled BOOLEAN DEFAULT NULL, basesource BOOLEAN DEFAULT NULL, discr VARCHAR(255) NOT NULL COLLATE BINARY, PRIMARY KEY(id), CONSTRAINT FK_688D0B496A3B1D21 FOREIGN KEY (layerset) REFERENCES mb_core_layerset (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO mb_core_sourceinstance (id, layerset, title, weight, enabled, basesource, discr) SELECT id, layerset, title, weight, enabled, basesource, discr FROM __temp__mb_core_sourceinstance;
DROP TABLE __temp__mb_core_sourceinstance;
CREATE INDEX IDX_688D0B496A3B1D21 ON mb_core_sourceinstance (layerset);
DROP INDEX UNIQ_BC0F146BE7A1254A;
DROP INDEX UNIQ_BC0F146BA393D2FB;
CREATE TEMPORARY TABLE __temp__mb_wmc_wmc AS SELECT id, state, contact_id, version, wmcid, keywords, abstract, logourl, descriptionurl, screenshotPath, public FROM mb_wmc_wmc;
DROP TABLE mb_wmc_wmc;
CREATE TABLE mb_wmc_wmc (id INTEGER NOT NULL, state INTEGER DEFAULT NULL, contact_id INTEGER DEFAULT NULL, version VARCHAR(10) DEFAULT NULL COLLATE BINARY, wmcid VARCHAR(255) DEFAULT NULL COLLATE BINARY, abstract CLOB DEFAULT NULL COLLATE BINARY, screenshotPath VARCHAR(255) DEFAULT NULL COLLATE BINARY, public BOOLEAN DEFAULT NULL, keywords CLOB DEFAULT NULL, logourl CLOB DEFAULT NULL, descriptionurl CLOB DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT FK_BC0F146BA393D2FB FOREIGN KEY (state) REFERENCES mb_core_state (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_BC0F146BE7A1254A FOREIGN KEY (contact_id) REFERENCES mb_core_contact (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO mb_wmc_wmc (id, state, contact_id, version, wmcid, keywords, abstract, logourl, descriptionurl, screenshotPath, public) SELECT id, state, contact_id, version, wmcid, keywords, abstract, logourl, descriptionurl, screenshotPath, public FROM __temp__mb_wmc_wmc;
DROP TABLE __temp__mb_wmc_wmc;
CREATE UNIQUE INDEX UNIQ_BC0F146BE7A1254A ON mb_wmc_wmc (contact_id);
CREATE UNIQUE INDEX UNIQ_BC0F146BA393D2FB ON mb_wmc_wmc (state);
DROP INDEX IDX_384FD2051645DEA9;
CREATE TEMPORARY TABLE __temp__mb_wms_keyword_source AS SELECT id, reference_id FROM mb_wms_keyword_source;
DROP TABLE mb_wms_keyword_source;
CREATE TABLE mb_wms_keyword_source (id INTEGER NOT NULL, reference_id INTEGER DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT FK_384FD2051645DEA9 FOREIGN KEY (reference_id) REFERENCES mb_wms_wmssource (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_384FD205BF396750 FOREIGN KEY (id) REFERENCES mb_core_keyword (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO mb_wms_keyword_source (id, reference_id) SELECT id, reference_id FROM __temp__mb_wms_keyword_source;
DROP TABLE __temp__mb_wms_keyword_source;
CREATE INDEX IDX_384FD2051645DEA9 ON mb_wms_keyword_source (reference_id);
DROP INDEX IDX_2A9363A21645DEA9;
CREATE TEMPORARY TABLE __temp__mb_wms_keyword_layersource AS SELECT id, reference_id FROM mb_wms_keyword_layersource;
DROP TABLE mb_wms_keyword_layersource;
CREATE TABLE mb_wms_keyword_layersource (id INTEGER NOT NULL, reference_id INTEGER DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT FK_2A9363A21645DEA9 FOREIGN KEY (reference_id) REFERENCES mb_wms_wmslayersource (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_2A9363A2BF396750 FOREIGN KEY (id) REFERENCES mb_core_keyword (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO mb_wms_keyword_layersource (id, reference_id) SELECT id, reference_id FROM __temp__mb_wms_keyword_layersource;
DROP TABLE __temp__mb_wms_keyword_layersource;
CREATE INDEX IDX_2A9363A21645DEA9 ON mb_wms_keyword_layersource (reference_id);
DROP INDEX IDX_60860685AED1BBE;
CREATE TEMPORARY TABLE __temp__mb_wms_wmsinstance AS SELECT id, wmssource, configuration, srs, format, infoformat, exceptionformat, transparency, visible, opacity, proxy, tiled, dimensions, vendorspecifics, buffer, ratio FROM mb_wms_wmsinstance;
DROP TABLE mb_wms_wmsinstance;
CREATE TABLE mb_wms_wmsinstance (id INTEGER NOT NULL, wmssource INTEGER DEFAULT NULL, srs VARCHAR(255) DEFAULT NULL COLLATE BINARY, format VARCHAR(255) DEFAULT NULL COLLATE BINARY, infoformat VARCHAR(255) DEFAULT NULL COLLATE BINARY, exceptionformat VARCHAR(255) DEFAULT NULL COLLATE BINARY, transparency BOOLEAN DEFAULT NULL, visible BOOLEAN DEFAULT NULL, opacity INTEGER DEFAULT NULL, proxy BOOLEAN DEFAULT NULL, tiled BOOLEAN DEFAULT NULL, buffer INTEGER DEFAULT 0 NOT NULL, ratio NUMERIC(10, 2) DEFAULT '1.25' NOT NULL, configuration CLOB DEFAULT NULL, dimensions CLOB DEFAULT NULL, vendorspecifics CLOB DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT FK_60860685AED1BBE FOREIGN KEY (wmssource) REFERENCES mb_wms_wmssource (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_60860685BF396750 FOREIGN KEY (id) REFERENCES mb_core_sourceinstance (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO mb_wms_wmsinstance (id, wmssource, configuration, srs, format, infoformat, exceptionformat, transparency, visible, opacity, proxy, tiled, dimensions, vendorspecifics, buffer, ratio) SELECT id, wmssource, configuration, srs, format, infoformat, exceptionformat, transparency, visible, opacity, proxy, tiled, dimensions, vendorspecifics, buffer, ratio FROM __temp__mb_wms_wmsinstance;
DROP TABLE __temp__mb_wms_wmsinstance;
CREATE INDEX IDX_60860685AED1BBE ON mb_wms_wmsinstance (wmssource);
DROP INDEX UNIQ_F5D6FE8FE7A1254A;
CREATE TEMPORARY TABLE __temp__mb_wms_wmssource AS SELECT id, contact_id, originUrl, name, version, onlineResource, fees, accessConstraints, layerLimit, maxWidth, maxHeight, exceptionFormats, supportSld, userLayer, userStyle, remoteWfs, inlineFeature, remoteWcs, getCapabilities, getMap, getFeatureInfo, describeLayer, getLegendGraphic, getStyles, putStyles, username, password FROM mb_wms_wmssource;
DROP TABLE mb_wms_wmssource;
CREATE TABLE mb_wms_wmssource (id INTEGER NOT NULL, contact_id INTEGER DEFAULT NULL, originUrl VARCHAR(255) DEFAULT NULL COLLATE BINARY, name VARCHAR(255) DEFAULT NULL COLLATE BINARY, version VARCHAR(255) DEFAULT NULL COLLATE BINARY, onlineResource VARCHAR(255) DEFAULT NULL COLLATE BINARY, fees CLOB DEFAULT NULL COLLATE BINARY, accessConstraints CLOB DEFAULT NULL COLLATE BINARY, layerLimit INTEGER DEFAULT NULL, maxWidth INTEGER DEFAULT NULL, maxHeight INTEGER DEFAULT NULL, exceptionFormats CLOB DEFAULT NULL, supportSld BOOLEAN DEFAULT NULL, userLayer BOOLEAN DEFAULT NULL, userStyle BOOLEAN DEFAULT NULL, remoteWfs BOOLEAN DEFAULT NULL, inlineFeature BOOLEAN DEFAULT NULL, remoteWcs BOOLEAN DEFAULT NULL, getCapabilities CLOB DEFAULT NULL, getMap CLOB DEFAULT NULL, getFeatureInfo CLOB DEFAULT NULL, describeLayer CLOB DEFAULT NULL, getLegendGraphic CLOB DEFAULT NULL, getStyles CLOB DEFAULT NULL, putStyles CLOB DEFAULT NULL, username VARCHAR(255) DEFAULT NULL COLLATE BINARY, password VARCHAR(255) DEFAULT NULL COLLATE BINARY, PRIMARY KEY(id), CONSTRAINT FK_F5D6FE8FE7A1254A FOREIGN KEY (contact_id) REFERENCES mb_core_contact (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_F5D6FE8FBF396750 FOREIGN KEY (id) REFERENCES mb_core_source (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO mb_wms_wmssource (id, contact_id, originUrl, name, version, onlineResource, fees, accessConstraints, layerLimit, maxWidth, maxHeight, exceptionFormats, supportSld, userLayer, userStyle, remoteWfs, inlineFeature, remoteWcs, getCapabilities, getMap, getFeatureInfo, describeLayer, getLegendGraphic, getStyles, putStyles, username, password) SELECT id, contact_id, originUrl, name, version, onlineResource, fees, accessConstraints, layerLimit, maxWidth, maxHeight, exceptionFormats, supportSld, userLayer, userStyle, remoteWfs, inlineFeature, remoteWcs, getCapabilities, getMap, getFeatureInfo, describeLayer, getLegendGraphic, getStyles, putStyles, username, password FROM __temp__mb_wms_wmssource;
DROP TABLE __temp__mb_wms_wmssource;
CREATE UNIQUE INDEX UNIQ_F5D6FE8FE7A1254A ON mb_wms_wmssource (contact_id);
DROP INDEX IDX_B7B7F16B727ACA70;
DROP INDEX IDX_B7B7F16BAED1BBE;
CREATE TEMPORARY TABLE __temp__mb_wms_wmslayersource AS SELECT id, wmssource, parent_id, name, title, abstract, queryable, cascaded, opaque, noSubset, fixedWidth, fixedHeight, latlonBounds, boundingBoxes, srs, styles, scale, scaleHint, attribution, identifier, authority, metadataUrl, dimension, dataUrl, featureListUrl, priority FROM mb_wms_wmslayersource;
DROP TABLE mb_wms_wmslayersource;
CREATE TABLE mb_wms_wmslayersource (id INTEGER NOT NULL, wmssource INTEGER DEFAULT NULL, parent_id INTEGER DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE BINARY, title VARCHAR(255) DEFAULT NULL COLLATE BINARY, abstract CLOB DEFAULT NULL COLLATE BINARY, queryable BOOLEAN DEFAULT NULL, cascaded INTEGER DEFAULT NULL, opaque BOOLEAN DEFAULT NULL, noSubset BOOLEAN DEFAULT NULL, fixedWidth INTEGER DEFAULT NULL, fixedHeight INTEGER DEFAULT NULL, latlonBounds CLOB DEFAULT NULL, boundingBoxes CLOB DEFAULT NULL, scaleHint CLOB DEFAULT NULL, metadataUrl CLOB DEFAULT NULL, dataUrl CLOB DEFAULT NULL, featureListUrl CLOB DEFAULT NULL, priority INTEGER DEFAULT NULL, srs CLOB DEFAULT NULL, styles CLOB DEFAULT NULL, scale CLOB DEFAULT NULL, attribution CLOB DEFAULT NULL, identifier CLOB DEFAULT NULL, authority CLOB DEFAULT NULL, dimension CLOB DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT FK_B7B7F16BAED1BBE FOREIGN KEY (wmssource) REFERENCES mb_wms_wmssource (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B7B7F16B727ACA70 FOREIGN KEY (parent_id) REFERENCES mb_wms_wmslayersource (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO mb_wms_wmslayersource (id, wmssource, parent_id, name, title, abstract, queryable, cascaded, opaque, noSubset, fixedWidth, fixedHeight, latlonBounds, boundingBoxes, srs, styles, scale, scaleHint, attribution, identifier, authority, metadataUrl, dimension, dataUrl, featureListUrl, priority) SELECT id, wmssource, parent_id, name, title, abstract, queryable, cascaded, opaque, noSubset, fixedWidth, fixedHeight, latlonBounds, boundingBoxes, srs, styles, scale, scaleHint, attribution, identifier, authority, metadataUrl, dimension, dataUrl, featureListUrl, priority FROM __temp__mb_wms_wmslayersource;
DROP TABLE __temp__mb_wms_wmslayersource;
CREATE INDEX IDX_B7B7F16B727ACA70 ON mb_wms_wmslayersource (parent_id);
CREATE INDEX IDX_B7B7F16BAED1BBE ON mb_wms_wmslayersource (wmssource);
DROP INDEX IDX_38F34DB13D8E604F;
DROP INDEX IDX_38F34DB1714D2654;
DROP INDEX IDX_38F34DB176BBE8FB;
CREATE TEMPORARY TABLE __temp__mb_wms_wmsinstancelayer AS SELECT id, wmsinstance, wmslayersource, parent, title, active, allowselected, selected, info, allowinfo, toggle, allowtoggle, allowreorder, minScale, maxScale, style, priority FROM mb_wms_wmsinstancelayer;
DROP TABLE mb_wms_wmsinstancelayer;
CREATE TABLE mb_wms_wmsinstancelayer (id INTEGER NOT NULL, wmsinstance INTEGER DEFAULT NULL, wmslayersource INTEGER DEFAULT NULL, parent INTEGER DEFAULT NULL, title VARCHAR(255) DEFAULT NULL COLLATE BINARY, active BOOLEAN DEFAULT NULL, allowselected BOOLEAN DEFAULT NULL, selected BOOLEAN DEFAULT NULL, info BOOLEAN DEFAULT NULL, allowinfo BOOLEAN DEFAULT NULL, toggle BOOLEAN DEFAULT NULL, allowtoggle BOOLEAN DEFAULT NULL, allowreorder BOOLEAN DEFAULT NULL, minScale DOUBLE PRECISION DEFAULT NULL, maxScale DOUBLE PRECISION DEFAULT NULL, style VARCHAR(255) DEFAULT NULL COLLATE BINARY, priority INTEGER DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT FK_38F34DB176BBE8FB FOREIGN KEY (wmsinstance) REFERENCES mb_wms_wmsinstance (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_38F34DB1714D2654 FOREIGN KEY (wmslayersource) REFERENCES mb_wms_wmslayersource (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_38F34DB13D8E604F FOREIGN KEY (parent) REFERENCES mb_wms_wmsinstancelayer (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO mb_wms_wmsinstancelayer (id, wmsinstance, wmslayersource, parent, title, active, allowselected, selected, info, allowinfo, toggle, allowtoggle, allowreorder, minScale, maxScale, style, priority) SELECT id, wmsinstance, wmslayersource, parent, title, active, allowselected, selected, info, allowinfo, toggle, allowtoggle, allowreorder, minScale, maxScale, style, priority FROM __temp__mb_wms_wmsinstancelayer;
DROP TABLE __temp__mb_wms_wmsinstancelayer;
CREATE INDEX IDX_38F34DB13D8E604F ON mb_wms_wmsinstancelayer (parent);
CREATE INDEX IDX_38F34DB1714D2654 ON mb_wms_wmsinstancelayer (wmslayersource);
CREATE INDEX IDX_38F34DB176BBE8FB ON mb_wms_wmsinstancelayer (wmsinstance);
DROP INDEX IDX_9407E54977FA751A;
DROP INDEX UNIQ_9407E5494B12AD6EA000B10;
CREATE TEMPORARY TABLE __temp__acl_object_identities AS SELECT id, parent_object_identity_id, class_id, object_identifier, entries_inheriting FROM acl_object_identities;
DROP TABLE acl_object_identities;
CREATE TABLE acl_object_identities (id INTEGER NOT NULL, parent_object_identity_id INTEGER UNSIGNED DEFAULT NULL, class_id INTEGER UNSIGNED NOT NULL, object_identifier VARCHAR(100) NOT NULL COLLATE BINARY, entries_inheriting BOOLEAN NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_9407E54977FA751A FOREIGN KEY (parent_object_identity_id) REFERENCES acl_object_identities (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO acl_object_identities (id, parent_object_identity_id, class_id, object_identifier, entries_inheriting) SELECT id, parent_object_identity_id, class_id, object_identifier, entries_inheriting FROM __temp__acl_object_identities;
DROP TABLE __temp__acl_object_identities;
CREATE INDEX IDX_9407E54977FA751A ON acl_object_identities (parent_object_identity_id);
CREATE UNIQUE INDEX UNIQ_9407E5494B12AD6EA000B10 ON acl_object_identities (object_identifier, class_id);
DROP INDEX IDX_825DE299C671CEA1;
DROP INDEX IDX_825DE2993D9AB4A6;
CREATE TEMPORARY TABLE __temp__acl_object_identity_ancestors AS SELECT object_identity_id, ancestor_id FROM acl_object_identity_ancestors;
DROP TABLE acl_object_identity_ancestors;
CREATE TABLE acl_object_identity_ancestors (object_identity_id INTEGER UNSIGNED NOT NULL, ancestor_id INTEGER UNSIGNED NOT NULL, PRIMARY KEY(object_identity_id, ancestor_id), CONSTRAINT FK_825DE2993D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_825DE299C671CEA1 FOREIGN KEY (ancestor_id) REFERENCES acl_object_identities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO acl_object_identity_ancestors (object_identity_id, ancestor_id) SELECT object_identity_id, ancestor_id FROM __temp__acl_object_identity_ancestors;
DROP TABLE __temp__acl_object_identity_ancestors;
CREATE INDEX IDX_825DE299C671CEA1 ON acl_object_identity_ancestors (ancestor_id);
CREATE INDEX IDX_825DE2993D9AB4A6 ON acl_object_identity_ancestors (object_identity_id);
DROP INDEX IDX_46C8B806DF9183C9;
DROP INDEX IDX_46C8B8063D9AB4A6;
DROP INDEX IDX_46C8B806EA000B10;
DROP INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9;
DROP INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4;
CREATE TEMPORARY TABLE __temp__acl_entries AS SELECT id, class_id, object_identity_id, security_identity_id, field_name, ace_order, mask, granting, granting_strategy, audit_success, audit_failure FROM acl_entries;
DROP TABLE acl_entries;
CREATE TABLE acl_entries (id INTEGER NOT NULL, class_id INTEGER UNSIGNED NOT NULL, object_identity_id INTEGER UNSIGNED DEFAULT NULL, security_identity_id INTEGER UNSIGNED NOT NULL, field_name VARCHAR(50) DEFAULT NULL COLLATE BINARY, ace_order SMALLINT UNSIGNED NOT NULL, mask INTEGER NOT NULL, granting BOOLEAN NOT NULL, granting_strategy VARCHAR(30) NOT NULL COLLATE BINARY, audit_success BOOLEAN NOT NULL, audit_failure BOOLEAN NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_46C8B806EA000B10 FOREIGN KEY (class_id) REFERENCES acl_classes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_46C8B8063D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_46C8B806DF9183C9 FOREIGN KEY (security_identity_id) REFERENCES acl_security_identities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO acl_entries (id, class_id, object_identity_id, security_identity_id, field_name, ace_order, mask, granting, granting_strategy, audit_success, audit_failure) SELECT id, class_id, object_identity_id, security_identity_id, field_name, ace_order, mask, granting, granting_strategy, audit_success, audit_failure FROM __temp__acl_entries;
DROP TABLE __temp__acl_entries;
CREATE INDEX IDX_46C8B806DF9183C9 ON acl_entries (security_identity_id);
CREATE INDEX IDX_46C8B8063D9AB4A6 ON acl_entries (object_identity_id);
CREATE INDEX IDX_46C8B806EA000B10 ON acl_entries (class_id);
CREATE INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9 ON acl_entries (class_id, object_identity_id, security_identity_id);
CREATE UNIQUE INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4 ON acl_entries (class_id, object_identity_id, field_name, ace_order);

**Comment by rschwammborn** [comment]
This is a behaviour which seems to also occur in earlier Mapbender versions. I'll close this for now, please feel free to reopen if it creates a real concern.

**Comment by astroidex** [comment]
Thanks @rschwammborn for the information. I was not aware about this. So we should recommend the user to use PostgreSQL for productive environments.
