### ISSUE TITLE
[Frontend] MobileTemplate SearchRouter shows up in every element dialog

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1200]
**Describe the bug**
When you add searchrouter element to your mobiletemplate the element will be displayed in every popup and not only when the searchrouter-button is activated 

**To Reproduce**
* use >= 3.0.8.1
1. Create a mobile application with seachrouter -> you can use the yml-file from the workshop bundle https://github.com/mapbender/mapbender-workshop/blob/master/app/config/applications/mapbender_mobile_searchrouter.yml

2. Click on Button search -> search works fine
3. Click on button 'Themes' or 'Imprint'
4. See error: SearchRouter-Form is diesplayed at the bottom of the dialog

**Expected behavior**
Hide searchrouter form when the functionality is not activated

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.1
 - Browser firefox, chrome

**Screenshots / Logmessage**
![Bildschirmfoto von 2019-08-06 09-45-06](https://user-images.githubusercontent.com/996298/62520952-e87ca500-b82e-11e9-870e-5c590ebe9a30.png)

**Additional context**
Error occurs after changes in mapbender.mobile.js
https://github.com/mapbender/mapbender/commits/release/3.0.7/src/Mapbender/MobileBundle/Resources/public/js/mapbender.mobile.js

**Comment by rschwammborn** [comment]
This is indeed a bug - I created a ticket in our internal system. The developers are currently working on a fix.

**Comment by rschwammborn** [comment]
Tested again in Mapbender 3.0.8.4-rc2. The bug has been solved. I'm closing the issue.
