### ISSUE TITLE
Neither WMS-Loader or importing of data sources works with Basic Auth protected services.

### ISSUE THREAD

**Issue by LazerTiberius** [mapbender/mapbender#1201]
With the introduction of Buzz 0.16.1 it's no longer possible to load protected services into any Mapbender application. The cause of this is that with the new PSR-7 Request Buzz requires a middleware instead of a listener (Listener does not throw an error but just does not work) to inject username/password into the request object. We could simply fix this with replacing the listener with the middleware but would properly lose the support for Buzz 0.15.  

Furthermore, the WMS-Loader generates a URL with a username/password-part instead of just submitting these as form data like the manager component to import a new service does. Because of this difference, the source handler will not recognize the protected services as protected and will omit username and password.

A temporary fix for the manager would be to downgrade  Buzz to 0.15 manually for your project.

A fix for the loader has to be implemented.

Any suggestion, how we could handle these problems without losing support for lower PHP versions and Buzz 0.15?

**Comment by werrolf** [comment]
Fixed in [Owsproxy v3.1.2](https://github.com/mapbender/owsproxy3/releases/tag/v3.1.2).

**Comment by werrolf** [comment]
Or maybe not. WmsLoader required an extra fix.

**Comment by werrolf** [comment]
Fixed in [16b0af4bc](https://github.com/mapbender/mapbender/commit/16b0af4bc8bf0d7aa2faa7579f7701df22c18be7). Release candidate pending.

**Comment by werrolf** [comment]
Fixed in [Mapbender v3.0.8.4-RC2](https://github.com/mapbender/mapbender/releases/tag/v3.0.8.4-RC2), also requires [Owsproxy v3.1.2](https://github.com/mapbender/owsproxy3/releases/tag/v3.1.2).

Changes bundled in [Mapbender Starter v3.0.8.4-RC2](https://github.com/mapbender/mapbender-starter/releases/tag/v3.0.8.4-RC2) (starter branch `rc`).

**Comment by rschwammborn** [comment]
Tested in RC3 - the bug has been fixed successfully (see comment above).
