### ISSUE TITLE
Legend checkbox always active [Print client]

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#1203]
**Describe the bug**
The element print client allows the print of the legend in the pdf-export. If you activate the checkbox "legend checkbox checked " and activate "print legend ", then the checkbox in the print-dialog is checked. If you deactivate this option ("legend checkbox checked "), then the checkbox in the print-dialog appears, but it is not checket.  
Current bug: The checkbox in the print-dialog is always checked, no matter what you define in the option "legend checkbox checked ". 

![Auswahl_039](https://user-images.githubusercontent.com/13517141/62775437-f12be000-baa7-11e9-9b28-589d16b6ea78.png)

**To Reproduce**
1. Go to 'https://sandbox.mapbender.org/application/mapbender_print_legend'
2. Click on 'print client'
3. See error (active checkbox)
4. Login to see the config (checkbox not activated in config....) at 'https://sandbox.mapbender.org/manager/application/mapbender_print_legend/edit'

![Auswahl_038](https://user-images.githubusercontent.com/13517141/62775538-36e8a880-baa8-11e9-95dc-9c697ae6aef2.png)

**Expected behavior**
If you deactivate the checkbox "legend checkbox checked " and activate "print legend ", then the checkbox in the print-dialog is not checked, but you can activate it in the application dialog. 

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.3
 - Database: idn
 - Browser chromium, firefox

**Additional context**
Tested on sandbox and local with current master (09.08.2019)

**Comment by rschwammborn** [comment]
You're right! Tested and requested a fix.

**Comment by werrolf** [comment]
Fixed in [Mapbender v3.0.8.4-RC2](https://github.com/mapbender/mapbender/releases/tag/v3.0.8.4-RC2).

**Comment by rschwammborn** [comment]
Tested again and is indeed fixed. Closing the issue.
