### ISSUE TITLE
[digitizer] features are displayed on start although displayOnInactive: false

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1211]
**Describe the bug**
Digitizer: When you set **displayOnInactive: false** you can define that the digitze features are only displayed when the digitize-element is active (sidepane -> tab is opened).

**displayOnInactive: false**  -> default should be false

This does not work on start of an application (test with digitizer in the second tab). After switch between the tabs it works fine.

**To Reproduce**
1. Create a digitize application with displayOnInactive: false and with digitizer-element i n the second tab (closed on start)
2. Open the application -> digitizer feature will be displayed
3. switch between the tabs digitizer -> layertree -> digitizer: you will see that the **displayOnInactive: false** works fine then 

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.4

**Screenshots / Logmessage**
![Bildschirmfoto von 2019-10-11 08-22-07](https://user-images.githubusercontent.com/996298/66629060-ebb25980-ec00-11e9-8dc9-46073dd6d913.png)

**Comment by rschwammborn** [comment]
Hi, thanks for contributing this bug. Indeed, I can confirm it, so I created an internal ticket for the Mapbender team to fix this.

**Comment by eschuettler** [comment]
Thank you. The bug is fixed in Mapbender 3.0.8.5.
