### ISSUE TITLE
Problems with WMS form ArcGIS-Server in Mapbender 3.0.8.x

### ISSUE THREAD

**Issue by PatrickMeis** [mapbender/mapbender#1212]
I experienced problems with integrating WMS from a ArcGIS-Server into Mapbender 3.0.8.x

Example URL:
http://www.kreis-coesfeld.de/arcgis/services/InspireDenkmale/MapServer/WMSServer?

The WMS simply generates only getLegendGraphic-Requests, but no getMap-Requests.
When i try the WMS in ArcGIS or QGIS, it works fine.

Charlotte Thoma from WhereGroup tested the WMS in Mapbender 3.0.6 and it worked there, so she said it might be a bug in v3.0.8 and recommended me to make an issue in Github.

Also another WMS from ArcGIS-Server is not working, although with a different error:
http://www.kreis-coesfeld.de/arcgisservices/Bauleitplanung/MapServer/WMSServer?

Again this one works ok in ArcGIS and QGIS but when i load it into Mapbender 3.0.8.3 the getMap-Request looks like this:

https://www.kreis-coesfeld.de/arcgis/services/Bauleitplanung/MapServer/WmsServer?_signature=28%253AfFL358V9ZtTnCB6eoQWX92lMSQI&TRANSPARENT=TRUE&FORMAT=image%252Fpng&VERSION=1.3.0&EXCEPTIONS=application%252Fvnd.ogc.se_xml&SERVICE=WMS&REQUEST=GetMap&STYLES=&LAYERS=1&_OLSALT=0.48922565327507583&CRS=EPSG%253A25832&BBOX=273174.2661018,5704711.0561353,539735.63878625,5834631.7251747&WIDTH=2380&HEIGHT=1160

This generates the following error message:

<ServiceExceptionReport version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd"><ServiceException code="InvalidFormat">
Parameter 'exceptions' contains unacceptable value.
  </ServiceException><ServiceException code="InvalidCRS">
Parameter 'srs(crs)' has wrong value.
  </ServiceException></ServiceExceptionReport>

There seems to be a problem with the parameter for the CRS, CRS=EPSG%253A25832, when i change it manually to CRS=EPSG%3A25832 it works.
The getMap-Request from Mapbender seems to first escape the colon in EPSG:25832 to %3A, and then wrongly escaping the ampersand a second time to %253a.

Versions i used:
 -Mapbender 3.0.8.3
 -Database: PostgreSQL 10.10
 Browser: Firefox 60.9.0esr (32-bit), Chrome 77.0.3865.120 (64-bit)

**Comment by armin11** [comment]
hi patrick,

i tested it under mapbender2 and the service works well under wms 1.1.1 and
wms 1.3.0.
the only problem is the encoding of the getlegendgraphic urls for the
legends.
<Style>
          <Name>default</Name>
          <Title>0</Title>
          <LegendURL width="18" height="18">
            <Format>image/png</Format>
            <OnlineResource xlink:href="
http://www.kreis-coesfeld.de/arcgis/services/Bauleitplanung/MapServer/WmsServer?request=GetLegendGraphic%26version=1.1.1%26format=image/png%26layer=0"
xlink:type="simple" xmlns:xlink="http://www.w3.org/1999/xlink" />
          </LegendURL>
</Style>
here is %26 used to mask & - instead this it should be &amp; !!!!!

further info:
https://stackoverflow.com/questions/8215348/including-a-url-with-query-string-in-an-xml-document

best regards
armin


Am Di., 22. Okt. 2019 um 15:52 Uhr schrieb PatrickMeis <
notifications@github.com>:

**Comment by eschuettler** [comment]
Thank you.
If the issue requires further attention, feel free to open a new issue.
