### ISSUE TITLE
[printClient] A0 A1 A2 templates do not show map after change of the template/pdf

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1213]
**Describe the bug**
When you change the template of A1/A0/A2 offical and export a new pdf the map is not dsplayed anymore. It is behind the frame that is around the map.
The reason is because the frame color definition is color instead of none

**To Reproduce**
1. Add print element to your application
2. add template **a1_landscape_offical** or **a1_landscape_offical**
3. Print a1 or A0 A2 -> everything is fine
4. Change the odp f.e. change the size of the map and export the pdf again
5. print again -> error -> map is hidden behind the frame

**Expected behavior**
Map should be on top of the frame

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.4

**Screenshots / Logmessage**
Wrong behavviour after change of template
![Bildschirmfoto von 2019-10-28 10-57-09](https://user-images.githubusercontent.com/996298/67669126-93ee4f00-f971-11e9-9219-3dd43327629e.png)

Worng setting for the frame has to  be none instead of color
![Bildschirmfoto von 2019-10-28 10-58-41](https://user-images.githubusercontent.com/996298/67669244-c9933800-f971-11e9-891b-60d0dbf29cdb.png)

**Comment by astroidex** [comment]
I fixed the setting in the print  templates and changed the folding mark

Created a PR 
https://github.com/mapbender/mapbender-starter/pull/95

**Comment by astroidex** [comment]
Noticed with @eschuettler that the error occurs also for A2 a2_landscape_offical.odg. So I fixed the template too.

**Comment by eschuettler** [comment]
Thank you @astroidex. It works fine with the changes you made.

**Comment by werrolf** [comment]
Try not putting opaque blocks on top of the map view in your custom template.

**Comment by rschwammborn** [comment]
I just tested the behaviour in Mapbender 3.0.8.5. I couldn't reproduce the bug from your description - it seems that everything's fine now :1st_place_medal:
