### ISSUE TITLE
Symfony update

### ISSUE THREAD

**Issue by binarious** [mapbender/mapbender#1217]
**Is your feature request related to a problem? Please describe.**
The support for Symfony 2.8 ends this month. No security updates will be released for Symfony <3.4 then.

**Describe the solution you'd like**
Support for Symfony >= 3.4. I know there is a branch for the upgrade. How is the progress? Is there any released date?

**Additional context**
- https://symfony.com/releases/2.8
- Related: https://github.com/mapbender/mapbender/issues/1064

**Comment by werrolf** [comment]
We were able to resolve the incompatibilities without _requiring_ Symfony 3.4. Mapbender 3.0.8.5 (currently in RC phase, testing is still pending until early next year) will be compatible with Symfony 3.4.

Coordinates Utility and Digitizer have also already been made forward-compatible with Symfony 3.4.

Data Manager is still not compatible, and we are aware of some cases where Element configuration can produce incompatibilities (such as custom form field definitions in SearchRouter).

We will provide updating guidance as soon as we're able.

**Comment by eschuettler** [comment]
Mapbender 3.0.8.5 is now available. 

For further information see: https://github.com/mapbender/mapbender/wiki/Symfony-3.
