### ISSUE TITLE
FeatureInfo - FeatureInfo requests layer that are not visible (active)

### ISSUE THREAD

**Issue by wirkus** [mapbender/mapbender#1218]
**Describe the bug**
FeatureInfo does not behave as expected. The FeatureInfo requests layer that are not visible (active).

**To Reproduce**
1. Go to  https://demo.mapbender.org/application/mapbender_user_yml?poi%5Bpoint%5D=357949.86524%2C5632675.11797&poi%5Bscale%5D=25000&poi%5Bsrs%5D=EPSG%3A25832&poi%5B
2. Click on WMS loader and  load https://wesseling-allgemein.wheregroup.com/cgi-bin/allgemein/freizeit.xml?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0
The service has to layer: Kultur and Sport
3.  Keep in mind where a 'Sport'-symbol is displayed in the map and run FeatureInfo
--> You get Information for the Sport layer. (LAYERS=Sport,Kultur&QUERY_LAYERS=Sport,Kultur)
4. Disabling layer 'Sport' of WMS 'Freizeit'
5. Click on button FeatureInfo
6. Click in the Map where the 'Sport'-symbol was
7. The FeatureInfo requests the layer 'Sport' although it isn't displayed
Wrong behaviour: this is requested: LAYERS=Sport,Kultur&QUERY_LAYERS=Sport,Kultur
 --> **should be LAYERS=Kultur&QUERY_LAYERS=Kultur**

This is the wrong FeatureInfo-request with layer 'Sport' disabled:
https://demo.mapbender.org/owsproxy/?url=https://wesseling-allgemein.wheregroup.com/cgi-bin/allgemein/freizeit.xml?LAYERS=Sport,Kultur&QUERY_LAYERS=Sport,Kultur&STYLES=&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&EXCEPTIONS=XML&BBOX=354426.032531%2C5632516.412011%2C355724.539218%2C5632918.914084&FEATURE_COUNT=100&HEIGHT=575&WIDTH=1855&FORMAT=image%2Fpng&INFO_FORMAT=text%2Fhtml&CRS=EPSG%3A25832&I=790&J=295

**Expected behavior**
Layer that are disabled (not visible) should not be queried
Worked fine with  3.0.5.3 or 3.0.6 or 3.0.7.6. 
Worked not fine with 3.0.7.7 and 3.0.8.4

**Versions **
 - Mapbender: 3.0.7.7  and 3.0.8.4
 - Browser: chrome, Firefox

**Comment by eschuettler** [comment]
Thank you. I reproduced the behaviour and will create an internal ticket.

**Comment by wirkus** [comment]
I tested it. The problem is solved. Thank you
