### ISSUE TITLE
User - change password for existing user does not check password length

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1220]
**Describe the bug**
If you change the pw for an existing user you can choose a password with a length < 8. Normally it should check length >= 8

@swinkelmann made observations about this and can give you more information

**To Reproduce**
1. Go to a user that exists
2. change pw to a string < 8 characters
3. save -> pw is saved

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.4

**Comment by eschuettler** [comment]
Thank you. I reproduced the behaviour and will create an internal ticket.

**Comment by astroidex** [comment]
Checked in version 3.0.8.5. Works fine. PW must have <= 8 charaters.

But user can't change their pw anymore in 3.0.8.5 see #1227

**Comment by eschuettler** [comment]
Thank you. I tested the behaviour and got the same results. I will close this ticket and continue work on #1227.
