### ISSUE TITLE
provide the possibility to copy result textes from searchRouter or digitizer

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1223]
**Is your feature request related to a problem? Please describe.**
It would be great if you could copy the results textes from searchRouter oder Digitizer.

**SearchRouter**
At the moment you can not mark and copy textes from a result.

![Bildschirmfoto von 2019-11-25 14-11-49](https://user-images.githubusercontent.com/996298/69543194-5f2fe080-0f8d-11ea-8578-81829270d399.png)

**Digitizer**
Copy is not possible of textes in the result table

![Bildschirmfoto von 2019-11-25 14-14-51](https://user-images.githubusercontent.com/996298/69543418-dcf3ec00-0f8d-11ea-9daf-abd6a36a6464.png)

**Describe the solution you'd like**
Provide the possibility to mark and copy textes (to be able to use the information somewhere else)

**Comment by eschuettler** [comment]
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html
