### ISSUE TITLE
Git based installation problem

### ISSUE THREAD

**Issue by galzsolt** [mapbender/mapbender#1224]
Install completed with error

> ComposerBootstrap::checkConfiguration

[Create and prepare database]

  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  The service "mapbender.assetic.filter.sass" has a dependency on a non-existent parameter "assetic.filter.sass.timeout".
  Did you mean this: "assetic.filter.scss.class"?

  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  The service "mapbender.assetic.filter.sass" has a dependency on a non-existent parameter "assetic.filter.sass.timeout".
  Did you mean this: "assetic.filter.scss.class"?

[Reset user password]

  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  The service "mapbender.assetic.filter.sass" has a dependency on a non-existent parameter "assetic.filter.sass.timeout".
  Did you mean this: "assetic.filter.scss.class"?

[ATTENTION]
User 'root' account password is: 'root'. Don't forget to change it!

[Import example mapbender applications]

  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  The service "mapbender.assetic.filter.sass" has a dependency on a non-existent parameter "assetic.filter.sass.timeout".
  Did you mean this: "assetic.filter.scss.class"?

[Update EPSG codes]

  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  The service "mapbender.assetic.filter.sass" has a dependency on a non-existent parameter "assetic.filter.sass.timeout".
  Did you mean this: "assetic.filter.scss.class"?

[Clear cache]

  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  The service "mapbender.assetic.filter.sass" has a dependency on a non-existent parameter "assetic.filter.sass.timeout".
  Did you mean this: "assetic.filter.scss.class"?

> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
Bootstrap finished!
If you want to run the builtin development server, run:
 cd application
 php app/console server:run

Full screenlog in attached file
[git_install_error20200118.txt](https://github.com/mapbender/mapbender/files/4081754/git_install_error20200118.txt)

**Comment by rschwammborn** [comment]
Hello @galzsolt ,
that's an odd installation error that has to do with the "non-existent parameter assetic.filter.sass.timeout" (according to your log). I just repeated your bash installation commands with no install error whatsoever. I recommend updating all packages or doing a clean install of LTS version 3.0.8.5, which should repair your faulty installation.Thanks for pointing this out and happy updating!

**Comment by galzsolt** [comment]
Thank you.
