### ISSUE TITLE
WMS with layername 0 are not requested in application 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1225]
**Describe the bug**
It can happen that WMS layer have numers as name (f.e. 0,1,2,...)
Mapbender can load such a service to the repository or via add WMS. But in the application the service is not requested although the layer should be active.
The service could be loaded in Mapbender 3.0.8 version and lower.  
* http://mapservice.region-frankfurt.de/arcgis/services/Regionalverband/regfnp_hauptkarte_wms/MapServer/WmsServer?VERSION=1.3.0&Service=WMS&Request=getCapabilities

**To Reproduce**
1. Go to https://demo.mapbender.org/application/mapbender_user_yml
2. Load service http://mapservice.region-frankfurt.de/arcgis/services/Regionalverband/regfnp_hauptkarte_wms/MapServer/WmsServer?VERSION=1.3.0&Service=WMS&Request=getCapabilities'
3. Zoom to the service via contextmenu (zooms to Frankfurt 1:10000)
4. Klick F12-network, zoom in the map -> see that the service is not requested

**Expected behavior**
A map-resquest should be fired to get a map from the service.

**Versions**
 - Mapbender: 3.0.8.4

**Screenshots / Logmessage**
If applicable, add screenshots or a logmessage from app/logs to help explain your problem.

**Comment by LazerTiberius** [comment]
Already fixed with commit 991fe37ed8a5b11073f2bf4fa551c4092b368531 and will be probably shipped in 3.0.8.5.

**Comment by astroidex** [comment]
Thanks for the information. Testet with 3.0.8.5rc1 and it works. Thanks a lot.
