### ISSUE TITLE
[Backend][access rights] After copy of an application the root user is listed twice in tab security

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1226]
**Describe the bug**
 After copy of an application the root user is listed twice in tab security

**To Reproduce**
1. Create an application
2. Copy the application
3. See in tab security that the admin user is listed twice

refers to change in 3.0.8.5: 
* When cloning DB applications, also clone access control rules
* Automatically assign owner permission for current user on cloned application
* see https://github.com/mapbender/mapbender/releases

![Bildschirmfoto von 2020-02-07 15-18-40](https://user-images.githubusercontent.com/996298/74036844-59a73b80-49bd-11ea-84e4-54fc0025cdbb.png)

**Expected behavior**
root user should only be listed once. the user that copies an applications is automatically the owner of that application.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8-5 new behaviour in this version

**Screenshots / Logmessage**
If applicable, add screenshots or a logmessage from app/logs to help explain your problem.

**Comment by eschuettler** [comment]
Thank you. I tested the behaviour and created an internal ticket for the Mapbender team.

**Comment by astroidex** [comment]
Tested in 3.0.8.6rc1. Error still occurs.

**Comment by thzanger** [comment]
Error occurs as well in 3.2.1
