### ISSUE TITLE
[User - change password] when a user wants to change their own password error occurs

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1227]
**Describe the bug**
A user can't change their password.

**To Reproduce**
1.Login
2.  Select YourAccout settings
3. Change pw and save
4. See error see Screenshot 

**Expected behavior**
User can change pw

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.5

![Bildschirmfoto von 2020-02-07 16-02-09](https://user-images.githubusercontent.com/996298/74040170-78a8cc00-49c3-11ea-95c6-978a84a069c7.png)

![Bildschirmfoto von 2020-02-07 16-02-19](https://user-images.githubusercontent.com/996298/74040161-747cae80-49c3-11ea-9a42-8977a9a88613.png)

**Comment by eschuettler** [comment]
Thank you. I got the same results. I will create an internal ticket to fix the bug.

**Comment by rschwammborn** [comment]
Tested it again, is now fixed in FOM v3.2.13. Please update your version accordingly.

**Comment by astroidex** [comment]
Fixed in 3.0.8.6
