### ISSUE TITLE
Print Frame allways at coordinates where it was shown first

### ISSUE THREAD

**Issue by kartoffelfee** [mapbender/mapbender#1229]
When opening the print-dialog or clicking the show printframe button in the sidepane, the printframes appears in the middle of the map. If the printframe is called a second time within the same session, it appears at the same geo-position as at the first time. So if one prints a part of Bonn, then moves the map to Berlin and opens the print-dialog again, he doesn't see the print-frame, because it is stilled placed in Bonn.

1. Go to https://demo.mapbender.org/application/mapbender_user_yml
2. Click on the print button and admire the print-frame
3. close the print-dialg
4. pan to Berlin or any other place than bonn
5.  Click on the print button
-> nor print-frame

**Expected behavior**
Printframe allways appears in the middle of the map

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.5

**Comment by eschuettler** [comment]
Thank you. I tested the behaviour and created an internal ticket for the Mapbender team.

**Comment by rschwammborn** [comment]
"[PrintClient]: Fully reinitialize selection rectangle scale and center on each activation"

**Comment by thzanger** [comment]
Bug does not occur anymore in latest Mapbender versions.
