### ISSUE TITLE
Digitizer does not accept mandatory definition like 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1230]
**Describe the bug**
Digitizer does not accept mandatory definition like 

```
 -
                                                            type: input
                                                            title: Lastname
                                                            name: lastname
                                                            mandatory: '/^[0-9]+$/'
                                                            mandatoryText: 'Only numbers'
```

**To Reproduce**
1. Go to 3.0.8.5 https://demo.mapbender.org/application/mapbender_user_digitizer
2.  Create a point
3. Add Attributes
4. Try to save. It is not possible as Lastname has to be a number. But whatever a number is also not accepted.

**Expected behavior**
Whe you insert a number the object should be able to be safed.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.5

**Screenshots / Logmessage**
![Bildschirmfoto von 2020-03-30 14-27-00](https://user-images.githubusercontent.com/996298/77912201-6ac04a80-7292-11ea-8c52-325fcb92cb4d.png)

**Comment by frwg** [comment]
Bug is removed in mapbender/vis-ui.js >= 0.2.81

**Comment by astroidex** [comment]
Works fine in 3.0.8.6 with the newer vis-ui.js version
