### ISSUE TITLE
Multiple SimpleSearch-elements always request the same element

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#1240]
**Describe the bug**
If you configure multiple SimpleSearch elements for your application, any of those elements will ask the last configured one.
See example over at https://sandbox.mapbender.org/application/CK_double_simple_search

**To Reproduce**
1. Setup at least 2 SimpleSearch elements for you application with **different** request URLs
2. Load application with developer tools open
3. Search in either of the SimpleSearch elements and watch the network tab. Both elements request the same element id. 

**Expected behavior**
Each configured SimpleSearch element should make requests in their own configured scope.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: [e.g. 3.0.8.5]
 - Browser [chrome]

![image](https://user-images.githubusercontent.com/6780575/80468492-85dcb380-893f-11ea-8b98-604d963ae617.png)

**Comment by werrolf** [comment]
This is fixed in ef7ac67fd18641d28458e579bc5aa7e928a40704.
Can't tell when the next 3.0.8 release will be, but the fix will be included.

**Comment by werrolf** [comment]
Mapbender 3.2.2 release already includes the fix. Still no 3.0.8.
