### ISSUE TITLE
[Digitizer] draw polygon with enclave does not work for multipolygons

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1241]
**Describe the bug**
Digitizer can draw polygons with enclave. This works fine for polygon-type geomety column. But if you geometry column is multipolygon it does not work properly.

Check here
https://demo.mapbender.org/application/mapbender_user_digitizer

**To Reproduce**
1. Go to https://demo.mapbender.org/application/mapbender_user_digitizer
2. Choose 'polygon digitizing' 
3. Draw in an existing polygon a hole (enclave) -> it worls fine you can see the hole while you draw the enclave
4. Now choose 'multipolygon digitizing' 
5. Draw in an existing polygon a hole (enclave) -> it does not work -> you can't see the hole and can't finish and save it 

**Expected behavior**
Should work for both polygon and multipolygon geometry columns

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.5
 - Browser chrome, firefox

**Comment by rschwammborn** [comment]
As of now, multipolygons are not supported - please use polygons instead.
