### ISSUE TITLE
Blue main map after simple search; Mapbender 3084, 3084_73; Microsoft Edge

### ISSUE THREAD

**Issue by sylviaobk** [mapbender/mapbender#1242]
To reproduce the bug follow the instruction and you will get a blue main map and markings on sidempane and toolbar

First part 
Microsoft Edge; Mapbender 3084

1.	https://rio.obk.de/mapbender3084/app.php/application/RIO_Bauen_Wohnen?  ![image](https://user-images.githubusercontent.com/20552367/82646700-5c006f00-9c15-11ea-946d-5f903e593043.png)

2. Type into simple search "Suche" - button in the sidepane "molt 42":
![image](https://user-images.githubusercontent.com/20552367/82646895-a124a100-9c15-11ea-831c-1dd553874151.png)

3. Click on the hit „Gummersbach Gummersbach Moltkestraße 42“ 
![image](https://user-images.githubusercontent.com/20552367/82646984-c6b1aa80-9c15-11ea-97d1-7071e0a5840d.png)

4. Click on the button "Kartenauswahl" and hover with your mouse over the main map window. Now the main map is blue marked

![image](https://user-images.githubusercontent.com/20552367/82647100-fa8cd000-9c15-11ea-906b-b3f1b623833e.png)
Now hover with the mouse to the sidepane and you will see blue markings here, too:

![image](https://user-images.githubusercontent.com/20552367/82648042-67ed3080-9c17-11ea-9ede-61f11956e755.png)

Second part 
Microsoft Edge; Mapbender 3084_73
Do step 1. til 3. same way and then move the main map with your mouse. Now the main map is blue
![image](https://user-images.githubusercontent.com/20552367/82648579-2315c980-9c18-11ea-922f-c026a249192d.png)
Now hover with your mouse to sidepane and toolbar, and they will be blue, too:
![image](https://user-images.githubusercontent.com/20552367/82648654-43de1f00-9c18-11ea-8023-7368636d4b27.png)

-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
Erster Teil 
Microsoft Edge; Mapbender 3084:
1. https://rio.obk.de/mapbender3084/app.php/application/RIO_Bauen_Wohnen?  
![image](https://user-images.githubusercontent.com/20552367/82648797-87d12400-9c18-11ea-8c0f-c4d55eba2ff3.png)

2. Solr – Suche unter dem Button „Suche“ im Seitenfenster aufrufen und „molt 42“ eintippen:
 ![image](https://user-images.githubusercontent.com/20552367/82648805-8e5f9b80-9c18-11ea-91cc-de0e2103ddb4.png)

3. Auf den Treffer „Gummersbach Gummersbach Moltkestraße 42“ klicken:
 ![image](https://user-images.githubusercontent.com/20552367/82648822-9586a980-9c18-11ea-916b-5a96626fa2d0.png)

4. Anschließend auf den Button „Kartenauswahl“ klicken und mit dem Mauszeiger ins Kartenfenster hovern führt dazu, dass das Kartenfenster blau markiert wird:
 ![image](https://user-images.githubusercontent.com/20552367/82648836-9ae3f400-9c18-11ea-85bf-7341acb792d0.png)

Anschießend mit der Maus ins Seitenfenster hovern führt zu Markierungen im Seitenfenster:
 ![image](https://user-images.githubusercontent.com/20552367/82648854-a20b0200-9c18-11ea-9e30-32a3f29c210d.png)

Zweiter Teil
Microsoft Edge; Mapbender 3084_73:
Schritte 1. bis 3. analog Mapbender 3084
Anschließend nicht auf den Button „Kartenauswahl“ klicken sondern direkt mit der Maus das Kartenfenster verschieben und anschließend mit der Maus im Kartenfenster hovern führt zu dem markierten blauen Kartenfenster:
 ![image](https://user-images.githubusercontent.com/20552367/82648878-aafbd380-9c18-11ea-92a0-acf39a51dac8.png)

Auch die Werkzeugleiste und das Seitenfenster werden bei weiteren Bewegungen mit der Maus markiert:
![image](https://user-images.githubusercontent.com/20552367/82648897-b0591e00-9c18-11ea-9b83-1608cf66b4ef.png)

Thank you for your help 
Sylvia

**Comment by astroidex** [comment]
Hello @sylviaobk,

I could reproduce the behaviour with Microsoft Edge and your application. It does not occur with firefox and chrome.
