### ISSUE TITLE
Solr Simple Search - Add functionality to clear search input and results on map

### ISSUE THREAD

**Issue by sylviaobk** [mapbender/mapbender#1246]
Hello,

the Result Icon in the main map window should disappear after reset

Open this application and click on „Suche“ – Button in the sidepane.
https://rio.obk.de/mapbender3084_73/app.php/application/RIO_Bauen_Wohnen

Now type „frit“ and click on „Bergneustadt Wiedenest Fritz-Rau-Straße 1“
![image](https://user-images.githubusercontent.com/20552367/86122229-c12e6680-bad7-11ea-9a6a-8fd8b57a5dc6.png)

Now you see the Result Icon as a red pin.
![image](https://user-images.githubusercontent.com/20552367/86122259-cd1a2880-bad7-11ea-8d32-6d5406343eb0.png)

Click again into the input-field and on the cross the Result Icon is still in the main map window. 
![image](https://user-images.githubusercontent.com/20552367/86122298-e0c58f00-bad7-11ea-86f5-7d2b46f8f6d8.png)

![image](https://user-images.githubusercontent.com/20552367/86122325-f1760500-bad7-11ea-806a-1b6f9486cf9b.png)

Expected behavior:
The red pin should disappear

 - Mapbender: [e.g. 3.0.8.4_73]
 - Browser Edge

Kind regards Sylvia

Hallo,

der Treffer-Pin sollte im Kartenfenster verschwinden, wenn die Suche zurückgesetzt wird.

Schritte, um den Fehler nachzustellen:
Öffne 
https://rio.obk.de/mapbender3084_73/app.php/application/RIO_Bauen_Wohnen
und klicke auf den "Suche" - Button im Seitenfenster

Jetzt gebe "frit" in das Textfeld ein und klicke auf „Bergneustadt Wiedenest Fritz-Rau-Straße 1“
![image](https://user-images.githubusercontent.com/20552367/86123057-25055f00-bad9-11ea-9f4f-c2634830d39e.png)

Jetzt sieht man den roten Treffer-Pin
![image](https://user-images.githubusercontent.com/20552367/86123121-3d757980-bad9-11ea-8a61-6cffbcad4230.png)

Klicke erneut in das Textfeld und auf das Kreuz am rechten Rand
![image](https://user-images.githubusercontent.com/20552367/86123164-53833a00-bad9-11ea-9e3f-d54e113a014e.png)

![image](https://user-images.githubusercontent.com/20552367/86123216-60a02900-bad9-11ea-9523-f638d821af79.png)

Erwartetes Verhalten:
der rote Pin sollte verschwinden

 - Mapbender: [e.g. 3.0.8.4_73]
 - Browser Edge

Viele Grüße Sylvia

**Comment by Phocacius** [comment]
The "X" icon to clear the search input is not part of Mapbender yet. Probably it was a functionality displayed by the browser to clear the input field, that is not handled. In the current Mapbender (v3.3.3) the input field is styled differently and the "X" is not displayed. We consider adding this functionality though.

**Comment by Phocacius** [comment]
The functionality was implemented in PR#1446 and will be available in the next Mapbender release (3.3.4) that is planned to be released within April 2023.
