### ISSUE TITLE
MB does not load properly

### ISSUE THREAD

**Issue by mibalas** [mapbender/mapbender#1247]
Hi, I installed Mapbender from doc tutorial, but when I access the web application, 
the demo map does not load.
it shows only plain texts..
![mberor1](https://user-images.githubusercontent.com/15907968/86134043-81f41b80-babf-11ea-9ed3-a57905cdaa3f.jpg)
![mberor2](https://user-images.githubusercontent.com/15907968/86134052-84567580-babf-11ea-9e62-d51f58bbf06e.jpg)

I'm running on a ubuntu 18 server with php 7.2.24

My mapbender:config:check is:
Check Database connections
 -------------------------------------------- ------------- ---------
  Connection                                   Status        Message
 -------------------------------------------- ------------- ---------
  /var/www/html/mapbender/app/db/demo.sqlite   successfull   ok
 -------------------------------------------- ------------- ---------
Check PHP Version
 ------------------------- ------------------ ---------
  Your Version              Required Version   Message
 ------------------------- ------------------ ---------
  7.2.24-0ubuntu0.18.04.6   5.5.4              ok
 ------------------------- ------------------ ---------
Check System Requirements
 ---------------- ------------ ---------
  Extension name   Is loaded?   Message
 ---------------- ------------ ---------
  sqlite3          yes          ok
  curl             yes          ok
  gd               yes          ok
  intl             yes          ok
  mbstring         yes          ok
  fileinfo         yes          ok
  openssl          yes          ok
  bz2              yes          ok
  zip              yes          ok
  xml              yes          ok
 ---------------- ------------ ---------
Check Asset Folders
 ----------------------------- -------------
  Folder                        is Symlink?
 ----------------------------- -------------
  fomcore                       yes
  fomuser                       yes
  framework                     yes
  mapbendercoordinatesutility   yes
  mapbendercore                 yes
  mapbenderdatasource           yes
  mapbenderdigitizer            yes
  mapbendermanager              yes
  mapbendermobile               yes
  mapbenderprint                yes
  mapbenderwmc                  yes
  mapbenderwms                  yes
 ----------------------------- -------------
Check FastCGI
fcgid (enabled by maintainer script)
Check Apache mod_rewrite
rewrite (enabled by site administrator)

Check PHP ini
 --------------------------------- -------
  Parameter                         Value
 --------------------------------- -------
  date.timezeone
  max_input_vars                    1000
  MaxRequestLen
  max_execution_time                0
  memory_limit                      -1
  upload_max_filesize               2M
  oci8.max_persistent
  oci8.default_prefetch
  session.save_handler              files
  zend_extension
  opcache.enable                    1
  opcache.memory_consumption        128
  opcache.interned_strings_buffer   8
  opcache.max_accelerated_files     10000
  opcache.max_wasted_percentage     5
 --------------------------------- -------
Loaded PHP Extensions
 * Core
 * date
 * libxml
 * openssl
 * pcre
 * zlib
 * filter
 * hash
 * pcntl
 * Reflection
 * SPL
 * sodium
 * session
 * standard
 * mysqlnd
 * PDO
 * xml
 * apcu
 * apc
 * bz2
 * calendar
 * ctype
 * curl
 * dom
 * mbstring
 * fileinfo
 * ftp
 * gd
 * gettext
 * iconv
 * intl
 * json
 * ldap
 * exif
 * mysqli
 * pdo_mysql
 * pdo_pgsql
 * pdo_sqlite
 * pgsql
 * Phar
 * posix
 * readline
 * shmop
 * SimpleXML
 * sockets
 * sqlite3
 * sysvmsg
 * sysvsem
 * sysvshm
 * tokenizer
 * wddx
 * xmlreader
 * xmlrpc
 * xmlwriter
 * xsl
 * zip
 * Zend OPcache

Check Permissions
 ----------------- ---------- ---------- -------------
  Folder            User       Group      Permissions
 ----------------- ---------- ---------- -------------
  app/logs/         www-data   www-data   0775
  app/cache/        www-data   www-data   0775
  web/uploads/      www-data   www-data   0775
  web/xmlschemas/   root       root       0755
  web/              root       root       0755

**Comment by eschuettler** [comment]
Hello mibalas,
recently somebody had a similar problem and shared it on the mapbender-user-mailing-list.
Maybe this will help you: https://lists.osgeo.org/pipermail/mapbender_users/2020-January/005685.html.
Unfortunately the topic was discussed in German. Please tell me, if you need a translation.

**Comment by mibalas** [comment]
Hi eschuettler, 

I did what is said in the topic but it did not solve.

In the browser inspector, shows that it is missing the file "http://localhost/mapbender/application/manager/assets/css" but I can't find this file because the directories are different.

**Comment by astroidex** [comment]
Please check you php.ini file

Check your sys_temp_dir and whether it is writable

sys_temp_dir = "C:/Windows/temp"

**Comment by mibalas** [comment]
Hi, I'm using Ubuntu..

by the way I installed MP on an server with Ubuntu 16 and php 5.6 and it worked normally.

I dont know what the problem with Ubuntu 18 or php 7.2...

**Comment by asereq** [comment]
Same problem here, only with the css asset, because js and trans work fine:
```
190.64.49.27 - - [20/Oct/2022:11:40:20 -0300] "GET /mapbender/ HTTP/1.1" 200 20621
190.64.49.27 - - [20/Oct/2022:11:40:23 -0300] "GET /mapbender/application/manager/assets/css HTTP/1.1" 500 922
190.64.49.27 - - [20/Oct/2022:11:40:23 -0300] "GET /mapbender/application/manager/assets/trans HTTP/1.1" 304 -
190.64.49.27 - - [20/Oct/2022:11:40:23 -0300] "GET /mapbender/application/manager/assets/js HTTP/1.1" 304 -
190.64.49.27 - - [20/Oct/2022:11:40:25 -0300] "GET /mapbender/components/bootstrap/css/bootstrap.min.css.map HTTP/1.1" 304 -
```

did you solve it?
