### ISSUE TITLE
Digitizer form does not respond to „width“ and „height“

### ISSUE THREAD

**Issue by sylviaobk** [mapbender/mapbender#1248]
Digitizer form does not respond to „width“ and „height“
  popup:
    title: 'Bitte Fenster an rechter unterer Ecke mit gedrückter linker Maustaste vergrößern.'
    width: 480px
    height: 580px
    resizable: true
  showExtendSearchSwitch: false
To reproduce the behavior:
1. Open Edge and
https://rio.obk.de/mapbender3084_73/app.php/application/RIO_Test_Sylvia_Digi
2. Click on Digitizer 
 
![image](https://user-images.githubusercontent.com/20552367/88800933-3198d800-d1a9-11ea-9675-a98cf0f4744d.png)

3. Click on „Linie erstellen“ – Button
 
![image](https://user-images.githubusercontent.com/20552367/88800962-3a89a980-d1a9-11ea-9d21-94a4217f4df7.png)

4. Click for the startpoint of the line with the left mouse button into the main map window and doubleclick for the endpoint of the line.
5. Automatically the digitizer form will open
 
![image](https://user-images.githubusercontent.com/20552367/88800901-280f7000-d1a9-11ea-8d9c-20d9717994dc.png)

Expected behaviour:
The form should look like:
 
![image](https://user-images.githubusercontent.com/20552367/88800986-437a7b00-d1a9-11ea-9b32-6cc3f2c7d1e0.png)

You can resize the form by pulling the right buttom corner with pressed left mouse button

PostgreSQL 9.6.15 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
mapbender3084_73
Edge

Sylvia
-------------------------------------------------------------------------------------------------------------------------
Digitizer – Formular reagiert nicht auf konfigurierte Fenstergröße
  popup:
    title: 'Bitte Fenster an rechter unterer Ecke mit gedrückter linker Maustaste vergrößern.'
    width: 480px
    height: 580px
    resizable: true
  showExtendSearchSwitch: false
Um den Fehler nachzustellen:
1. Öffne den Edge und
https://rio.obk.de/mapbender3084_73/app.php/application/RIO_Test_Sylvia_Digi
2. Klicke auf Digitizer 
 
![image](https://user-images.githubusercontent.com/20552367/88800845-129a4600-d1a9-11ea-8856-fab9ec86d7c2.png)

3. Klicke auf „Linie erstellen“
 
![image](https://user-images.githubusercontent.com/20552367/88800862-1928bd80-d1a9-11ea-8ad2-b34aeedea299.png)

4. Klicke für den Linienanfangspunkt mit der linken Maustaste ins Kartenfenster und doppelklicke für den Linienendpunkt.
5. Jetzt öffnet sich automatisch das Digitalisierformular
 
![image](https://user-images.githubusercontent.com/20552367/88800889-23e35280-d1a9-11ea-9187-448ecaedfa9e.png)

Erwartetes Verhalten:
Das Formular sollte größer sein:
 
![image](https://user-images.githubusercontent.com/20552367/88801001-4b3a1f80-d1a9-11ea-9c2b-668fbf51dc3f.png)

An der rechten unteren Ecke kann man mit gedrückter linker Maustaste die Fenstergröße ändern.

PostgreSQL 9.6.15 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
mapbender3084_73
Edge

Sylvia

**Comment by rschwammborn** [comment]
Hello @sylviaobk ,
I've tried to reproduce your issue with the newest LTS-version of Mapbender (which is 3.0.8.6). I made the following adjustments to your configuration to avoid the styling issues you have (Disclaimer: I didn't use Edge). Nethertheless, there should be several solutions to fix this:

```
popup:
title: 'Bitte Fenster an rechter unterer Ecke mit gedrückter linker Maustaste vergrößern.'
width: 480px
height: auto
resizable: true
showExtendSearchSwitch: false
```
Height is automatically adjusted by the browser, probably the preferred fix.

or
```
popup:
title: 'Bitte Fenster an rechter unterer Ecke mit gedrückter linker Maustaste vergrößern.'
height: 580
width: 480
resizable: true
showExtendSearchSwitch: false
```

This is how the parameters should be inserted according to: 
- https://doc.mapbender.org/de/functions/editing/digitizer.html#definition-popup
- https://api.jqueryui.com/dialog/#option-height (more info)

or

```
popup:
title: 'Bitte Fenster an rechter unterer Ecke mit gedrückter linker Maustaste vergrößern.'
width: 480px
resizable: true
showExtendSearchSwitch: false
```

...which would omit the height parameter at all, but the styling should still be fixed.

Please try them all out and see if your problem still occurs afterwards. 
I'm closing this issue. If neither of the proposed solutions should work, please check your configuration and/or comment on the issue again. Thanks!
