### ISSUE TITLE
Digitizer Checkbox does not set value „false“ when unchecked

### ISSUE THREAD

**Issue by sylviaobk** [mapbender/mapbender#1249]
To reproduce the behavior:
1. Open Edge and
https://rio.obk.de/mapbender3084_73/app.php/application/RIO_Test_Sylvia_Digi
2. Click on Digitizer 
![image](https://user-images.githubusercontent.com/20552367/89394767-c4d38f80-d70c-11ea-9c7e-821d23adb7d1.png)

3. Click on „Linie erstellen“ – Button
![image](https://user-images.githubusercontent.com/20552367/89394822-d61c9c00-d70c-11ea-8245-6ce6eace1496.png)

4. Click for the startpoint of the line with the left mouse button into the main map window and doubleclick for the endpoint of the line.
5. Automatically the digitizer form will open
![image](https://user-images.githubusercontent.com/20552367/89394944-fba9a580-d70c-11ea-8cea-787b7b5edab1.png)

6. Resize the form by pulling the right buttom corner with pressed left mouse button
![image](https://user-images.githubusercontent.com/20552367/89394992-0a905800-d70d-11ea-9175-ce5e5fcc90fa.png)

7. Type a text into the textfield, e. g. „myline“. Leave the checkbox empty.
![image](https://user-images.githubusercontent.com/20552367/89395039-19770a80-d70d-11ea-9c49-98b492488f2c.png)

8. Click „Speichern“

![image](https://user-images.githubusercontent.com/20552367/89395084-25fb6300-d70d-11ea-84d1-fb95a0219763.png)

An exception occurred while executing 'INSERT INTO "test"."mylines" ("bez", "wahrheitswert", "the_geom") VALUES ('myline', '', 'SRID=25832;0102000020E864000003000000F98FF942FA7418410C92BE5F498E5541EBBCF8E4D4321841463360758F9055412167AB34D60718410C282F597D925541') RETURNING "gid"':

SQLSTATE[22P02]: Invalid text representation: 7 FEHLER: ungültige Eingabesyntax für Typ boolean: »«
LINE 1: ..., "wahrheitswert", "the_geom") VALUES ('myline', '', 'SRID=...
^
Expected behaviour:
Value for „wahrheitswert“ should be „**false**“ instead of ‘‘

INSERT INTO "test"."mylines" ("bez", "wahrheitswert", "the_geom") VALUES ('myline', **false**, 'SRID=25832;0102000020E864000003000000F98FF942FA7418410C92BE5F498E5541EBBCF8E4D4321841463360758F9055412167AB34D60718410C282F597D925541') RETURNING "gid"

Digitizer-configuration:
        -
          type: checkbox
          title: 'Häkchen gesetzt bedeutet: ja!'
          name: wahrheitswert
          value: false
          checked: true
I tried default: false but it did not help.
PostgreSQL 9.6.15 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
mapbender3084_73
Edge

Cheers Sylvia

------------------------------------------------------------------------------------------------------------------------------------------
Digitizer – Checkbox speichert nur „true“ und nicht „false“
Nachstellen des Verhaltens:
1. Öffne den Edge und
https://rio.obk.de/mapbender3084_73/app.php/application/RIO_Test_Sylvia_Digi
2. Klicke auf Digitizer 
![image](https://user-images.githubusercontent.com/20552367/89395306-6f4bb280-d70d-11ea-9b06-dcc0ff6c69c2.png)

3. Klicke auf „Linie erstellen“
![image](https://user-images.githubusercontent.com/20552367/89395339-7a064780-d70d-11ea-9dfc-0edaab1c89cd.png)

4. Klicke für den Linienanfangspunkt mit der linken Maustaste ins Kartenfenster und doppelklicke für den Linienendpunkt.
5. Jetzt öffnet sich automatisch das Digitalisierformular
![image](https://user-images.githubusercontent.com/20552367/89395372-84284600-d70d-11ea-8027-3d093e1beb6e.png)

6. Vergrößere mit gedrückter linker Maustaste die Fenstergröße.
![image](https://user-images.githubusercontent.com/20552367/89395416-92766200-d70d-11ea-88e0-e95089623dd8.png)

7. Gebe einen Text in das Textfeld ein, z. B. „myline“. Lasse die Checkbox ausgehakt.
![image](https://user-images.githubusercontent.com/20552367/89395447-9efaba80-d70d-11ea-9e75-6ed79810ea8f.png)

8. Klicke auf „Speichern“.
![image](https://user-images.githubusercontent.com/20552367/89395481-aa4de600-d70d-11ea-9f64-b3845b95d402.png)

An exception occurred while executing 'INSERT INTO "test"."mylines" ("bez", "wahrheitswert", "the_geom") VALUES ('myline', '', 'SRID=25832;0102000020E864000003000000F98FF942FA7418410C92BE5F498E5541EBBCF8E4D4321841463360758F9055412167AB34D60718410C282F597D925541') RETURNING "gid"':

SQLSTATE[22P02]: Invalid text representation: 7 FEHLER: ungültige Eingabesyntax für Typ boolean: »«
LINE 1: ..., "wahrheitswert", "the_geom") VALUES ('myline', '', 'SRID=...
^
Erwartetes Verhalten:
Der Wert für „wahrheitswert“ sollte „**false**“ sein und nicht ‘‘

INSERT INTO "test"."mylines" ("bez", "wahrheitswert", "the_geom") VALUES ('myline', **false**, 'SRID=25832;0102000020E864000003000000F98FF942FA7418410C92BE5F498E5541EBBCF8E4D4321841463360758F9055412167AB34D60718410C282F597D925541') RETURNING "gid"

Digitizer-Konfiguration:
        -
          type: checkbox
          title: 'Häkchen gesetzt bedeutet: ja!'
          name: wahrheitswert
          value: false
          checked: true

Ich habe versucht über default: false die leeren Anführungszeichen zu ersetzen, leider erfolglos.

PostgreSQL 9.6.15 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
mapbender3084_73
Edge

Grüße Sylvia

**Comment by thzanger** [comment]
Dear @sylviaobk, we are sorry for the late reply. The issue has been forwarded into our internal ticket system. Regards

**Comment by werrolf** [comment]
This has already been fixed in [mapbender/data-source 0.1.17](https://github.com/mapbender/data-source/releases/tag/0.1.17). The insert will generate a `'t'` or `'f'` string, which works with both native PostgreSQL boolean columns and varchar / text columns.

**Comment by sylviaobk** [comment]
Bug is fixed with Mapbender 3.2.4
