### ISSUE TITLE
searchrouter - not possible to add

### ISSUE THREAD

**Issue by beli2go** [mapbender/mapbender#1250]
update from 3.0.6.3 to 3.2.0

The try to add a searchrouter to a new or a demo application failed.

**To Reproduce**
1. Go to Edit Application, Tab Layout 
2. Click on '+' to add new element to toolbar
3. Scroll down to searchrouter and klick on it
4. See error - nothing happens

**Expected behavior**
The searchrouter added to the toolbar.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: [3.2.0]
 - Database: [e.g. PSQL 12]
 - Browser [chrome, firefox]

**Screenshots / Logmessage**
If applicable, add screenshots or a logmessage from app/logs to help explain your problem.

**Additional context**

**Comment by thzanger** [comment]
Hello, your issue has been noted and will be fixed as soon as possible.

**Comment by thzanger** [comment]
Hello @beli2go, there is no issue regarding the adding of SR in the latest version of MB anymore. This issue will therefore be closed. If further problems should appear, please check your configurations. Regards
