### ISSUE TITLE
[Layertree] Metadata Dialog should show Abract of Layer

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1255]
**Is your feature request related to a problem? Please describe.**
The Metadata Dialog displays of metadata from the WMS. The abstract for the root layer is displayed. But not for other layers.

**Describe the solution you'd like**
Please also show the abstract for the layers

**It would look like this**

![wms_layer_metadata_abstract](https://user-images.githubusercontent.com/996298/91963419-21c36500-ed0e-11ea-82e1-71bc4d9b2822.png)

**Comment by astroidex** [comment]
find the feature in PR https://github.com/mapbender/mapbender/pull/1256

**Comment by rschwammborn** [comment]
Hello @astroidex ,
thanks for your feature & pull request. I forwarded the information into the internal Mapbender ticket system.
Moreover, I'm going to close this GitHub issue to reduce clutter. Stay tuned!

**Comment by astroidex** [comment]
tested in 3.2.3: works fine
