### ISSUE TITLE
Change units on Line/Area Ruler tool

### ISSUE THREAD

**Issue by rickthompson** [mapbender/mapbender#1257]
I am working on a project where the client would like to make measurements in feet/yards. I have successfully added a custom CRS in feet, data renders fine in native CRS from WMS service, but units on the Map element still appear to be in meters? There is a provision to change the units on the scale bar, which I have successfully changed to miles, but no such option for explicitly defining the map element units or units to display when using measure tool. I am suggesting a feature be added to allow units be defined on the line/area ruler element as you can with the scale bar.

**Comment by thzanger** [comment]
Hello @rickthompson ,
thank you for your suggestion. I forwarded the information into the internal Mapbender ticket system.
