### ISSUE TITLE
preview of icons for your buttons

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#1258]
**Describe your feature request**

Many users would like to know what the predefined buttons look like. A preview of these icons would therefore be a cool feature, e.g. next to the name.

In addition, perhaps you could also offer the possibility to use any new icons, e.g. all from the font awsome webside (https://fontawesome.com/icons?d=gallery) or to add a icon of your choice via the unicode (e.g. 'f0a9' for the arrow to the right).

**Additional context**
Currently only the name of the icon is displayed - this hardly helps newcomers to find the right symbol.

**Screenshots**

![Auswahl_002](https://user-images.githubusercontent.com/13517141/69271108-89bc1b00-0bd4-11ea-8610-aeea1e2470cc.png)

**Comment by rschwammborn** [comment]
Transferred the issue into the main repository, as it's probably better to have the icon next to the text instead of looking each icon up in the documentation. Moreover, I'll create an internal ticket regarding the feature request in our system.

**Comment by Phocacius** [comment]
Icon previews will be part of the upcoming release 3.3.4.
Making the available icons configurable is a separate feature request which we'll consider for a future release.
