### ISSUE TITLE
[PrintClient] overview is not printed in PDF althought the the application/template provides an overview area

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1259]
**Describe the bug**
You can define an overview area for the print output see f.e. a4portrait.odg
When you print  a pdf the overview will getprinted in the overview area.
in **Mapbender 3.2.1** this overview frame in the output is missing

**To Reproduce**
1. Go to https://demo.mapbender.org/application/mapbender_user_yml
2. Chood **A4 Portrait** it contains an overview frame
3. Print PDF
4. See error: no overview area is printed

**Expected behavior**
Overview should be printed in the pdf

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.1

**Screenshots / Logmessage**
no message

**Comment by thzanger** [comment]
Hello @astroidex,
thank you for this information. The issue has been forwarded into the internal Mapbender ticket system.

**Comment by astroidex** [comment]
- tested in 3.2.2.: error still occurs

**Comment by astroidex** [comment]
* tested in 3.2.3.: works fine
