### ISSUE TITLE
app/console mapbender:database:upgrade --help shows wrong version in description

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1260]
**Describe the bug**
Run app/console mapbender:database:upgrade --help

ist will show the following message:

Help:
  The mapbender:database:upgrade command updates the Datesbase to the new schema of mapbender version 3.0.6

**Expected behavior**
Should show the right Mapbender Version

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.1

**Comment by thzanger** [comment]
Hello @astroidex, 
thank you for this information. The issue has been forwarded into the internal Mapbender ticket system.

**Comment by astroidex** [comment]
Here is a PR to fix the problem https://github.com/mapbender/mapbender/pull/1265

**Comment by astroidex** [comment]
fixed in 3.2.3
