### ISSUE TITLE
Monitoring Timeout for a single request is fix

### ISSUE THREAD

**Issue by JaegerFrank** [mapbender/mapbender#1261]
The Value of "**CAP_MONITORING_TIMEOUT**" from **mapbender.conf** is not read in /lib/**class_Monitor.php**.
Always the default (20 sec.) is used in /classes/class_connector.php.
Sometimes QGIS-Server with big Projektfiles take more then 20 sec. time.

**Comment by rschwammborn** [comment]
Hello @JaegerFrank,
thank you for this information. Your request has been forwarded into the internal Mapbender ticket system. We will keep you updated!

**Comment by rschwammborn** [comment]
Hello @JaegerFrank,
this GitHub repository is for bug reporting/feature requests regarding newer Mapbender versions (as of now, 3.0.8 and above).
It seems to us that you are currently using an older version (Mapbender2). Please head over to community support and describe your problem to the Mapbender User mailing list:

mapbender_users@lists.osgeo.org

For more information, see: https://mapbender.org/en/mapbender-users/
