### ISSUE TITLE
Mapbender 3.2.2: app/console mapbender:config:check says PHP 5.5.4

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1263]
**Is your feature request related to a problem? Please describe.**
Mapbender 3.2 needs PHP >= 7.1 (see release mail https://lists.osgeo.org/pipermail/mapbender_users/2020-July/005813.html)

But when you check with 3.2 it says Required Version PHP 5.5.4

**Describe the solution you'd like**
Please update the config check to the Required Version PHP

see https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Command/ConfigCheckCommand.php#L100

**Versions **
 - Mapbender: 3.2.2

**Comment by astroidex** [comment]
Created PR https://github.com/mapbender/mapbender/pull/1266

**Comment by werrolf** [comment]
If you want to know the php version, type `php --version`.
