### ISSUE TITLE
WMS is not displayed although the extent fits to the mapextent / zoom to Extent displays wrong region

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1264]
**Describe the bug**
If you load a WMS to your application with WMS version 1.1.1 and version 1.3.0 the layers are not visible for WMS 1.3.0 in regions where they should be displayed. 

- Version 1.1.1: looks fine 
- Version 1.3.0: WMS is not displayed (no requests to WMS due to extent) and zoom to layer zooms to wrong extent 

I tested with 
- https://www.wms.nrw.de/geobasis/wms_nw_bodenbewegungsgebiete_kacheln?Service=WMS&Request=getCapabilities&Version=1.3.0
- https://www.wms.nrw.de/geobasis/wms_nw_bodenbewegungsgebiete_kacheln?Service=WMS&Request=getCapabilities&Version=1.1.1

**To Reproduce**
1. Go to https://demo.mapbender.org/application/mapbender_user_yml (Version 3.2.2 or your local installation) 
2. Load WMS twice to your applicateion
* https://www.wms.nrw.de/geobasis/wms_nw_bodenbewegungsgebiete_kacheln?Service=WMS&Request=getCapabilities&Version=1.3.0
* https://www.wms.nrw.de/geobasis/wms_nw_bodenbewegungsgebiete_kacheln?Service=WMS&Request=getCapabilities&Version=1.1.1
3. WMS 1.1.1 behaves fine: WMS is displayed in NRW / Zoom to layer zooms to NRW

4. See error WMS in 1.3.0 is not requested in the region of NRW / layers are displayed gray / F12 not map-request to WMS 
5. See error: WMS 1.3.0: 
   - Zoom to Layer (on a layer): zooms to Italy 
   - Zoom to layer for the root-layer zooms to NRW
 

**Expected behavior**
Both versions should use the extent like defined in the WMS.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.2

**Screenshots / Logmessage**

WMS 1.3.0 Mapbender does not request WMS 1.3.0
![wms_request_layer](https://user-images.githubusercontent.com/996298/97975536-9592f400-1dc9-11eb-8792-31a3a171045f.png)

WMS 1.3.0 layer: Zoom to layer shows Italy instead of NRW
![wms_1 3 0zoom_to_layer](https://user-images.githubusercontent.com/996298/97975549-9a57a800-1dc9-11eb-8595-1faefc4a9adb.png)

**Comment by thzanger** [comment]
Thank you for this information. I could reproduce the behaviour and forwarded the issue to the internal Mapbender ticket system.

**Comment by astroidex** [comment]
You can reproduce the error also with the WMS OSM Demo:
1. Update the OSM Demo WMS which is part of the Mapbender installation already https://osm-demo.wheregroup.com/service?VERSION=1.3.0
(you can see that the WMS does not provide the BBox for every supported CRS)
2. Create an application in  EPSG:25832
3. max. Extent: minx 251000 miny 5400000 / maxx 475000 maxy  5850000
4. Start-Extent: minx 361000 miny 5619000 / maxx 371150 maxy 5625000
5. See error: OSM Demo is not requested (layers are grey)

**Comment by werrolf** [comment]
The service capabilities emit these values:
1.1.1: ```<BoundingBox SRS="EPSG:3034" minx="3.7054e+06" miny="2.61812e+06" maxx="4.0085e+06" maxy="2.86069e+06"/>```
1.3.0: ```<BoundingBox CRS="EPSG:3034" minx="2.61812e+06" miny="3.7054e+06" maxx="2.86069e+06" maxy="4.0085e+06"/>```
And that's the entire problem.

**Comment by werrolf** [comment]
> You can reproduce the error also with the WMS OSM Demo:
> 
> 1. Update the OSM Demo WMS which is part of the Mapbender installation already https://osm-demo.wheregroup.com/service?VERSION=1.3.0
>    (you can see that the WMS does not provide the BBox for every supported CRS)
> 2. Create an application in  EPSG:25832
> 3. max. Extent: minx 251000 miny 5400000 / maxx 475000 maxy  5850000
> 4. Start-Extent: minx 361000 miny 5619000 / maxx 371150 maxy 5625000
> 5. See error: OSM Demo is not requested (layers are grey)

No issue observed.
