### ISSUE TITLE
update README.md it contains outdated information

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1267]
README.md  of mapbender-starter
* https://github.com/mapbender/mapbender-starter/blob/master/README.md

* delete outdated information Ubuntu 14.04 (outdated)
* use https in links instead of http
* update information: f.e. a PHP 5.4 interpreter
* Check information about components. Some links refer to 3.0.6. Check fom / owsproxy
* Fix Download link: https://mapbender.org/download/ (page not found) -> should be https://mapbender.org/en/download/

**Versions**
 - Mapbender: 3.2.2

**Comment by thzanger** [comment]
Thank you for this information. The issues have been forwarded into the internal Mapbender ticket system.

**Comment by astroidex** [comment]
fixed in 3.2.3

**Comment by thzanger** [comment]
Sehr geehrte Damen und Herren,
    
    
    vielen Dank für Ihre Nachricht. Ich bin zurzeit im Urlaub. Sie
      können mich ab dem 19.01 wieder erreichen.
    
    
    MfG
    
    
Theresa Zanger
Studentische Hilfskraft

******************************************

WhereGroup GmbH
Eifelstraße 7
53119 Bonn
Germany

Fon: +49 (0)228 / 90 90 38 - 29

theresa.zanger@wheregroup.com
www.wheregroup.com

Geschäftsführer:
Olaf Knopp, Peter Stamm 
Amtsgericht Bonn, HRB 9885
-----------------------------------
