### ISSUE TITLE
[Frontend][featureInfo] dialog shows result from WMS that are not activate

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1268]
**Describe the bug**
FeatureInfo dialog shows tabs from WMS that are not active for feature info anymore. Get information from 2 WMS, then deactivate one WMS. The information from the deactivate WMS is still in the result tab.

See detailed description...

**To Reproduce**
1. Go to https://demo.mapbender.org/application/mapbender_user_yml
2. Load WMS http://www.wms.nrw.de/geobasis/wms_nw_tfis?Service=WMS&Request=getCapabilities&Version=1.1.1
3. click on the blue Mapbender icon close to Bonn Main station -> results for Mapbender-Use and WMS NW TFIS show up (two tabs)
4. Disable the WMS WMS NW TFIS
5. Click on the same blue Mapbender icon close to Bonn Main station
6. See error: Dialog still shows the result from the WMS WMS NW TFIS (Rheinische Friedrich-Wilhelms-Universität Bonn)
7. click somewhere where no Mapbender-user icon is
8. Still the tab for WMS WMS NW TFIS (Rheinische Friedrich-Wilhelms-Universität Bonn) is displayed
**-> Conclusion**: looks like old results tabs remain somewhere and show up although the WMS is not active anymore

**Expected behavior**
Featureinfo should only show actual results and only results from WMS that are activated for featureinfo

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.2

**Screenshots / Logmessage**

1. Both WMS active - looks ok: two result-tabs: one from each WMS
![mb322_fi1](https://user-images.githubusercontent.com/996298/98136780-960eb600-1ec1-11eb-8423-b8e1657577cc.png)

2. error: only WMS mapbender user is active: but WMS WMS NW TFIS deactivated, the result from before still shows up
![mb322_fi2](https://user-images.githubusercontent.com/996298/98136817-9e66f100-1ec1-11eb-9b2b-e2c7f994437d.png)

**Comment by rschwammborn** [comment]
Hello @astroidex,
thanks for this information. I could reproduce this - the issue has been forwarded into the internal Mapbender ticket system.

**Comment by astroidex** [comment]
error still occurs in 3.2.3

**Comment by werrolf** [comment]
Fixed in [7a2722cb4dc6323007d7e12ab3a3a80e7f854862](https://github.com/mapbender/mapbender/commit/7a2722cb4dc6323007d7e12ab3a3a80e7f854862)

**Comment by werrolf** [comment]
> Tested in version 3.2.4. Works fine.

Ok. Closing :)
