### ISSUE TITLE
Documentation link target not found

### ISSUE THREAD

**Issue by karstenv** [mapbender/mapbender#1274]
**Describe the bug**
I was reading the online documentation about the digitizer and found that the link to the digitizer search page is broken /  the page does not exist

I found this in both the German and English versions

https://doc.mapbender.org/en/functions/editing/search_digitizer.html
which is linked from this page https://doc.mapbender.org/en/functions/editing/digitizer.html

und hier 
https://doc.mapbender.org/de/functions/editing/search_digitizer.html
wo von der Seite
https://doc.mapbender.org/de/functions/editing/digitizer.html?highlight=digit
aus verlinkt ist

**Comment by astroidex** [comment]
The functionality is not available in 3.2.2.

**Comment by thzanger** [comment]
Thank you for this feature suggestion! We always try to improve Mapbender. 
Feature wishes can also be ordered at WhereGroup:

WhereGroup GmbH
info@wheregroup.com
https://wheregroup.com/kontakt.html

I will therefore close this issue.
Regards
