### ISSUE TITLE
[frontend][SearchRouter] mandatory field are not focussed if there are not filled

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1276]
**Describe the bug**
In searchrouter you can define mandatory fields. When you use a mandatory field the search will not run before you fill the field. Mandatory fields are makred with a red start. 
Problem: when you click ok, you do not see that the search does not start and is still waiting for the user to fill the field

For testing the following yml can be used: https://github.com/mapbender/mapbender-workshop/blob/release/3.2/app/config/applications/mapbender_demo_nrw.yml

**To Reproduce**
1. Go to SearchRouter
2. Go to a search with mandatory fields
3. Klick search without filling the fields
4. See error: nothing is happening - no highlight of the filed/choice and no info that input is needed

**Expected behavior**
Mandatory field should be somehow highlighted to show the user that an input is expected

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.2

**Screenshots / Logmessage**

**Additional context**

**Comment by thzanger** [comment]
Hello @astroidex, thank you for this information. The issue has been forwarded into the internal Mapbender ticket system.

**Comment by werrolf** [comment]
Missing red asterisks for required fields have been fixed in Mapbender v3.2.3.
