### ISSUE TITLE
[Digitizer] does not show the labels of the column headers in the feature table

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1277]
**Describe the bug**
For a digitizer configuration you can define columns to show in the table and a label for the header.

In 3.2.2 the header is not displayed anymore.  

I am not aware of a change in the configuration. Please have a look at the screenshots.

You can use the yaml from the workshop-bundle: 
https://github.com/mapbender/mapbender-workshop/blob/release/3.2/app/config/applications/mapbender_digitize_demo.yml

**To Reproduce**
1. Compare a 3.0.8.6 digitizer application with a 3.2.2 application

**Expected behavior**
Also display the header of the table colums as defined in the configuration

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.2

**Screenshots / Logmessage**

3.0.8.6
![Bildschirmfoto von 2020-11-20 13-32-36](https://user-images.githubusercontent.com/996298/99800690-090c6380-2b35-11eb-842d-c846ed182c44.png)

3.2.2
![Bildschirmfoto von 2020-11-20 11-01-52](https://user-images.githubusercontent.com/996298/99800717-132e6200-2b35-11eb-91ee-c604e538b991.png)

**Additional context**

**Comment by thzanger** [comment]
Thank you for this information! The problem has been forwarded into the internal Mapbender ticket system.

**Comment by astroidex** [comment]
tested with 3.2.3: works fine
