### ISSUE TITLE
[Frontend][Simplesearch] new parameter sourceSrs can not be defined in the administration backend (only in yaml)

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1278]
**Describe the bug**
Simple Search has a new parameter sourceSrs: to define the srs of the result of the Sorl Service. The default is set to EPSG:4326. This is a great new parameter that enables Mapbender to transform the result to the projection of the map.

- https://github.com/mapbender/mapbender/commit/ab8817178b0709047e4510d71dd60f570b432ac6#diff-4b605153645d6c52af9bc5ac7f05d1a91b98458858fa0c6278046eb4834786c1

**Problem**: You can define this parameter in the yaml definition of an application but not in the browserbase administration.

You can use the demo application to test: https://github.com/mapbender/mapbender-workshop/blob/release/3.2/app/config/applications/mapbender_demo_nrw.yml#L247

Problem: if you have a result in a different projection Mapbender will still assume that you use 4326 and will transform to that projection.

**To Reproduce**
1. Go to you administration backend
2. add an element simplesearch
3. Look for the sourceSrs definition

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.2

**Comment by rschwammborn** [comment]
Hello @astroidex  ,
thanks for forwarding this information - I created a ticket regarding this topic in the internal Mapbender ticket system.
We'll keep you updated!

**Comment by astroidex** [comment]
* tested in 3.2.3: works fine
