### ISSUE TITLE
[Frontend][PrintClient] Hochwert in print output is switched 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1280]
**Describe the bug**
In Version 3.0.8.6 the hochwert in the print output is not correct - They are switched. The value at the upper right should be at the lower left.

This is fixed in 3.2 see:
https://github.com/mapbender/mapbender/commit/2a01f7297b49c022878737d815ba5497f683eb3c#diff-03a4c9b662d234d98b9539f6ec141786e7c96fe8efb1e80abbdc0dded43abd6e

**To Reproduce**
1. Go to https://version-lts.mapbender.org/v3.0.8.6/application/mapbender_user_yml_printClient
2. Chosse print a4_landscape_offical coordinates
3. create a pdf and see the error

**Expected behavior**
Correct labeling of the print output.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.6 (error does not occur in 3.2)

**Screenshots / Logmessage**
frame with coordinates:
- lower left: 362590.89 5620040.05
- upper right: 369625.93 5623932.07
![frontend_print](https://user-images.githubusercontent.com/996298/100194571-3884ec80-2ef6-11eb-8875-37e11ae49043.png)

See error
![print_pdf_with_flipped_coordinates](https://user-images.githubusercontent.com/996298/100194605-42a6eb00-2ef6-11eb-8944-398c59f29cec.png)

**Comment by rschwammborn** [comment]
Hello @astroidex  ,
thanks for reporting the bug - I created a ticket in the internal Mapbender ticket system.
We'll keep you updated!
