### ISSUE TITLE
[app/console cache:clear]  doesn't delete whole cache

### ISSUE THREAD

**Issue by kartoffelfee** [mapbender/mapbender#1281]
**Describe the bug**
```
schulung@schulung:/data/mapbender$ sudo app/console cache:clear --env=prod
[sudo] Passwort für schulung: 

 // Clearing the cache for the prod environment with debug false                                                        

                                                                                                                        
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.                                          
                                                                                                                        

schulung@schulung:/data/mapbender$ ls ./app/cache/prod/
annotations.map                   appProdProjectContainerUrlGenerator.php       ContainerHcdsyjb         pools          twig
annotations.php                   appProdProjectContainerUrlGenerator.php.meta  ContainerK17r7bl         sessions       validation.php
appProdProjectContainer.php       appProdProjectContainerUrlMatcher.php         ContainerK17r7bl.legacy  templates.php
appProdProjectContainer.php.meta  appProdProjectContainerUrlMatcher.php.meta    doctrine                 translations
schulung@schulung:/data/mapbender$ 

```
afterwords MB is not loaded properly.

**To Reproduce**
s.a.

**Expected behavior**
cache/prod should be empty Mapbender should be loaded properly.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.2
 - Database: -
 - Browser_ -

**Comment by rschwammborn** [comment]
Hi,
thanks for reporting the bug - I created a ticket in the internal Mapbender ticket system.
We'll keep you updated!

**Comment by werrolf** [comment]
Mapbender does not implement the `cache:clear` command. It's a Symfony command.
The `cache:clear` command does exactly what it's supposed to do.
The `cache:clear` command cannot delete files owned by a higher-privileged user.

I suspect your cache files are owned by `root` or `www-data`. This is not a problem Mapbender or Symfony can solve for you.

The best solution to avoid file ownership issues on a single-user system is to make your web server run as you.
See https://askubuntu.com/a/164787 for an Apache solution.
