### ISSUE TITLE
[simple search] Marker moves when zooming

### ISSUE THREAD

**Issue by kartoffelfee** [mapbender/mapbender#1282]
**Describe the bug**
The marker of simple search looses it's geoposition, when zooming.
see  https://files.wheregroup.com/index.php/s/DEwrW7WMo6jTaYd

**To Reproduce**
http://schulung.foss.academy/mapbender/application/mapbender_user_db_imp

**Expected behavior**
Marker shoud stay at geoposition , e.g. house number 11 of eifelstraße

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.2
 - Database: -
 - Browser: ubunutu 20 chrome

**Comment by rschwammborn** [comment]
Hello @kartoffelfee ,
thanks for reporting the bug - I created a ticket in the internal Mapbender ticket system.
We'll keep you updated!

**Comment by werrolf** [comment]
> **To Reproduce**
> http://schulung.foss.academy/mapbender/application/mapbender_user_db_imp
Link broken.

Your icon will drift if "icon_offset" does not correctly indicate the "tip" of the icon.

If you use the classic pin_red.png, use `icon_offset: -6,-38`.
