### ISSUE TITLE
[backend] [DimensionsHandler] Shared Instances can not be added to dimensionsHandler

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1284]
**Describe the bug**
If you add a WMS-T (WMS with Time Dimensions) to your application you can add it to the element dimensions handler and use the time slider to see the different status at dfferent times.

Problem: This can not be configured for Shared Instances - The Shared Instance can not be added to the element Dimensions handler

**To Reproduce**
1. Add a WMS-T to you layerset f.e. http://geo4.service24.rlp.de/wms/hklika.fcgi?service=WMS&request=GetCapabilities&Version=1.3.0 (Liegenschaftskarte Rheinland-Pfalz)
3. Go to the Instance and activate Dimension
2. Convert the WMS-Instance to a Shared Instance
3. Add element Dimensions Handler to your application
4. The Element says: "No dimensions" - it does not register the Shared Instande
5. If you add the service again as a private Instance you can add it to the dimensions handler

**Expected behavior**
Also support Shared Instances

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.2

**Screenshots / Logmessage**
Activate Dimensions
![Bildschirmfoto von 2020-12-04 08-43-10](https://user-images.githubusercontent.com/996298/101137279-e38c5900-360e-11eb-8efb-45f4d4f66ba9.png)

Element: Diemensions Handler: See the message **no dimensions**  if the WMS-T is a Shared Instance
![Bildschirmfoto von 2020-12-04 08-57-23](https://user-images.githubusercontent.com/996298/101137298-e8e9a380-360e-11eb-9eaf-62d363e401f3.png)

Add WMS-T again as private Instance
![Bildschirmfoto von 2020-12-04 08-57-33](https://user-images.githubusercontent.com/996298/101137314-ee46ee00-360e-11eb-8100-c2ffc1e609d3.png)

Element: Diemensions Handler: registers the private instance
![Bildschirmfoto von 2020-12-04 08-57-48](https://user-images.githubusercontent.com/996298/101137322-f30ba200-360e-11eb-89b9-830fe35d3442.png)

**Comment by thzanger** [comment]
Thank you @astroidex, the issue has been noted and got forwarded into our internal MB ticket system.

**Comment by werrolf** [comment]
Fixed in 1ea7d6fa826adf9d818fa0491298859985df765e
