### ISSUE TITLE
[digitizer] maxResults parameter in digitizer configuration

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1285]
**Describe the bug**
With maxResults you could define how many features should be loaded to the application. This parameter is useful if you have many feature in your table but do not want to show them all the start of you application when you start.

Without maxResults (it is deprecated in 3.2.2 - Digitizer 1.4) all features are loaded on start. This can look like (screenshot 1).

Changelog where for 1.4-beta1 maxresults is marked as deprecated
https://github.com/mapbender/mapbender-digitizer/blob/1.4/CHANGELOG.md

**This causes problems:**
* client needs a long time to load the application and all the features
* client can crash when there are x-000 feature
* startup map does not look good
* handling of the client is always slowly as all this feature have to be handled

Solution
* please provide the maxResults parameter again, like it was provide for 1.1 digitizer.  
* see yaml: https://github.com/mapbender/mapbender-workshop/blob/release/3.0.8/app/config/applications/mapbender_user_digitzer.yml#L349

**To Reproduce**
1. Go to your digitize demo
2. Create x-0000 objects in you digitizer table
3. See the error: slow, many features

**Expected behavior**

                        schemes:
                            poi:
                                label: 'point digitizing'
                                maxResults: 500
                                featureType:
                                    connection: search_db
                                    table: poi
                                    uniqueId: gid
                                    geomType: point
                                    geomField: geom_25832
                                    srid: 25832
                                    filter: 'st_isempty(geom_25832) = false'

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.2

**Generate many points via**
You can easily create random points in your project area via ST_GeneratePoints.
* http://postgis.net/docs/ST_GeneratePoints.html

**Screenshots / Logmessage**
![Bildschirmfoto von 2020-12-04 09-52-32](https://user-images.githubusercontent.com/996298/101142768-5c42e380-3616-11eb-862a-a55f13289a0e.png)

**Comment by DeEgge** [comment]
I propose to implement native clustering via a OpenLayers (plugin)
* https://openlayers.org/en/latest/examples/cluster.html
* https://viglino.github.io/ol-ext/examples/animation/map.animatedcluster.html

**Comment by eschuerg** [comment]
Hello @astroidex,
I am sorry to let you know, that 'maxResults' is no longer supported in Mapbender. 
Clustering would be a good solution.


We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH
info@wheregroup.com
https://wheregroup.com/kontakt.html
