### ISSUE TITLE
[query-builder] Mapbender 3.2 support

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1286]
**Is your feature request related to a problem? Please describe.**
query-builder is used in some projects as additional element visualize data queries (not spatial) and download them as csv. The Queries can get defined in advance in a table.
Update query-builder to work with Mapbender 3.2 (that does not mean to have it in the standard installation package, but to be able to activate it via composer.json)

**Describe the solution you'd like**
It did not support newer Mapbender version. Would be great to have the element with 3.2. Only functionality allow_export and allow_search is needed. 
The other options may cause a security risk

**Additional context**
Code on github https://github.com/mapbender/query-builder

![Bildschirmfoto von 2020-12-04 12-12-56](https://user-images.githubusercontent.com/996298/101157361-4a6b3b80-362a-11eb-91a6-cf2139451af1.png)

**Comment by astroidex** [comment]
There is a PR from @frwg. He updated the repo to work with Mapbender 3.2. See changes PR or ask @frwg for more information.

- https://github.com/mapbender/query-builder/pull/3

**Comment by astroidex** [comment]
The enhancements from the PR are solved in the new version https://github.com/mapbender/query-builder/releases/tag/1.0.5

**Comment by werrolf** [comment]
Indeed
