### ISSUE TITLE
[Frontend] [featureinfo] new featureinfo-highlight behaviour 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1287]
**Describe the bug**
FeatureInfo-Highlight provides highlight for the polygon geometry that comes as WKT via feature Info (will come in Mapbender in 3.2.3).

Problem: 

- Problem 1: When you click on an area the last clicked area will still get highlighted. It should disappear when you click again.
- Problem 2: When you deactivate featureinfo-element the highlighted feature is still on the map and does not disappear

Test with application or import the yaml application
* http://mb31.wheregroup.lan/application/mapbender_user_featureinfo_highlight
* Application for Import via MB administration backend (browser) 
[export_featureinfo_highlight.txt](https://github.com/mapbender/mapbender/files/5642989/export_featureinfo_highlight.txt)

**To Reproduce**
1. Go to http://mb31.wheregroup.lan/application/mapbender_user_featureinfo_highlight
2. Click on plz or countries
3. Activate Feature Info and klick on an area. 
problem 1:
4. See error: When you click on another area you will see the area from the last featureinfo-click (it is not in the list of the actual 

problem2:
5. See error: deactivate the button featureinfo - the highlighted feature are still there

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3..2.3 dev

**Background Information about configuration**
You have to integrate WKT for your polygons to the FeatureInfo-Template. This works for MapServer, QGIS Server and GeoServer and also for different data formats.

Shape 

- see https://mapserver.org/mapfile/template.html?highlight=shpxy

```
<div id="[ADMIN_NAME]" class="geometryElement" data-collapsed="true" data-geometry="MULTIPOLYGON([shpxy xf=" " cs="," ph="(" pf=")" ps="," orh="(" orf=")" irh=",(" irf=")" precision=6])" data-srid="EPSG:4326">

WITH Buffer
<div id="[ADMIN_NAME]" class="geometryElement" data-collapsed="true" data-geometry="POLYGON([shpxy buffer=0.005 xf=" " cs="," ph="(" pf=")" ps="," orh="(" orf=")" irh=",(" irf=")" precision=6])" data-srid="EPSG:4326">
```

PostgreSQL

- provide your Geometry as WKT and refer to the column in the FI-Template
- ST_AsWKT(geom) or a simplified geometry ST_AsWKT(ST_SimplifyPreserveGeometry(geom)) 
- you can also Provide the EPSG from your data: ST_srid(geom)
- I you want to highlight points and lines you could buffer them before you produce the geometry

`<div id="[ADMIN_NAME]" class="geometryElement" data-collapsed="true" data-geometry="[geom_as_wkt]" data-srid="[geom_epsg]">
`

**Comment by eschuerg** [comment]
Thank you. I tested the behaviour and will create an internal ticket.
