### ISSUE TITLE
[backend][create new user] if you forgot to enter a password a "500 Internal Server Error" shows up

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1288]
**Describe the bug**
If you create a new user and you klick save without entering a password a "500 Internal Server Error" shows up

**To Reproduce**
1. Go to your mapbender http://localhost/mapbender/manager/user/new
2. enter name and email for a new user
3. Save without entering a pasword
4. See error: "500 Internal Server Error"

**Expected behavior**
There should be a mesage that you have to enter a password with at least 8 digits

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.2
-  Firefox / Chromium

**Comment by eschuerg** [comment]
Thank you!
I can reproduce the behaviour and will create an internal ticket.

**Comment by astroidex** [comment]
* tested in 3.2.3: works fine
