### ISSUE TITLE
Digitizer Mapbender 3.2.2 file type

### ISSUE THREAD

**Issue by galzsolt** [mapbender/mapbender#1289]
**Describe the bug**
If I have file type item in the popup, the save button don't work,  Current values don't saved and the popup don't close.
If I remove the file item, works OK.

If I click on Select button  the selected file is uploaded to uploads/featureTypes/table/column directory,
the Select text changed to the file name, but the save button don't work.

No error messages, I try dev mode but not find any messages that helps.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender:  3.2.2, Debian 10, PHP 7.2.32
 - Database: Postgresql 9.6
 - Browser  chrome, firefox

**Comment by werrolf** [comment]
This is fixed in an updated data-manager release (Digitizer inherits most form-related logic from data-manager now).
Please see what happens if you update the packages related to Digitizer. In the `application` directory:
```sh
bin/composer update mapbender/digitizer mapbender/data-manager
```

**Comment by galzsolt** [comment]
Thank you, I will try in this weekend.

**Comment by galzsolt** [comment]
The **bin/composer update mapbender/digitizer mapbender/data-manager** don't update when I run it.  
It propose to install again digitizer and data-manager and I accept. 
Nothing changed, I cant use file type item in the popup.
I have a warning about composer version. It is neccesary to upgrade composer?

**Comment by galzsolt** [comment]
I find a solution without update.
Because I have only one application I export it, make a new git-based installation and import my application back. 
Everything is Ok, it works with file item in the popup.
