### ISSUE TITLE
[DimensionsHandler] Available "steps" are not calculated correctly

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#1293]
**Describe the bug**
The 'steps' for the DimensionsHandler are not calculated correctly, if your dimensions have more than 100 values. The available steps for the slider are normalized to values from 0 to 100.

https://github.com/mapbender/mapbender/blob/master/src/Mapbender/WmsBundle/Resources/public/mapbender.element.dimensionshandler.js#L31

On a slide, the new value to display is calculated based off of that 0-100 scale, not from the original values.

Some of the steps cannot be selected, because of rounding errors

**To Reproduce**
1. Go to http://nahsh.wheregroup.com/mapbender/application/basisanwendung-internet
2. Click on the slider for the dimension "Qualität"
3. Use the arrow keys to make small steps to the left
4. Notice that some of the months are skipped

**Expected behavior**
All available time steps should be accessible through the time slider.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.7.7 (expect it in 3.2.3 too, because nothing changed in the javascript code)
 - Browser [Chrome, Firefox]

![image](https://user-images.githubusercontent.com/6780575/102782449-a7d8e980-4399-11eb-838e-41794b577ffe.png)
![image](https://user-images.githubusercontent.com/6780575/102782470-b0c9bb00-4399-11eb-8aed-38885a66b2e8.png)

![image](https://user-images.githubusercontent.com/6780575/102782701-15851580-439a-11eb-8e38-3592df577878.png)

**Comment by thzanger** [comment]
Thank you @DeEgge, I could reproduce the behaviour and forwarded the issue into our internal system. Regards

**Comment by werrolf** [comment]
Fixed in c17253751df217ea0e387bc44905960253705b7d
Do note that the total pixel width of the slider will still limit how many steps you can hit.
If your dimension has many (hundreds) of intermediate steps, we recommend limiting the range to ~the most current 100 steps via either the instance backend, or the DimensionsHandler backend.
