### ISSUE TITLE
[Frontend] Digitizer, Base source switcher

### ISSUE THREAD

**Issue by galzsolt** [mapbender/mapbender#1295]
**Describe the bug**

I create on application in wich **Sidepane** has two elements: **Layer tree** and **Digitizer**, in this order. 
When open/start the application the Digitizer  point layer symbols are visible. At start the **Layer tree** is selected!
I select/click on  **Digitizer** and select/click back on Layer tree and the symbols disappear and work Ok.

Base source switcher, at start has no effect, both Base map are displayed. After the first click/selection works Ok.

**Versions (please complete the following information if it helps to narrow down the bug):**
Mapbender 3.2.2
Debian 10
Postgresql 9.8
php 7.2

 - Browser  chrome, firefox

**Screenshots / Logmessage**

https://user-images.githubusercontent.com/36177302/103150960-08916900-4782-11eb-84ba-987180593ffe.mp4

**Comment by astroidex** [comment]
In Mapbender 3.2.x the behaviour of the BaseSourceSwitcher changed (sorry - it is not documented yet).

- in the configuration enable only the WMS instances that should be active on start (in former versions you could enable all WMS instances and Mapbender would activate only the first).

The advantage now is, that you can enable any WMS on start that you like.

Here is an example for a WMS instance that is not active at the beginning (see green marks):
![mb_basesourceswitcher](https://user-images.githubusercontent.com/996298/103520096-ed57e500-4e76-11eb-938f-18130a0fc17d.png)

**Comment by galzsolt** [comment]
Thank you!
