### ISSUE TITLE
[digitizer] datepicker: Firefox does not show datepicker symbol

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1298]
**Describe the bug**
When you use firefox browser the datepicker symbol is not displayed at the right of your textfield.

**To Reproduce**
1. Open a digitizer demo with firefox
2. Go to a filed of type date
3. See error: no datepicker symbol
4. With Chromium it looks fine 
5. see screenshots

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.3
 - Browser firefox

**Screenshots / Logmessage**
Firefox
![Bildschirmfoto vom 2021-01-06 11-17-39](https://user-images.githubusercontent.com/996298/103763521-3bf1b480-501a-11eb-8f30-4c302efe43f3.png)

Chromium
![Bildschirmfoto vom 2021-01-06 11-17-29](https://user-images.githubusercontent.com/996298/103763536-42802c00-501a-11eb-8d87-c6b876ba043f.png)

**Comment by rschwammborn** [comment]
Hi @astroidex !
Did a quick research on this and can confirm that it's not a Mapbender bug at all. The browser-handled date picker UI simply differs from browser to browser. Mozilla's date picker documentation shows a styling comparison between Firefox (no icon) & Chrome, Edge, Opera (icon):
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by astroidex** [comment]
Thanks a lot @rschwammborn
