### ISSUE TITLE
[Digitizer] [with featureType filter] does not update the feature-list and map visualisation when an object is saved and not included in the filter selection anymore

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1301]
**Describe the bug**
If you have a digitzer configuration with a filter (filter: 'name is NULL') , Mapbender will only show the feature that satisfy the filter.
In the example it would only show the objects where the column name is NULL.

**Problem: **
If you edit a feature and save something in column name, it should not be displayed anymore because of the filter. But the object is still visible in the map and in the attribute table. 

It does not disappear on normal navigation, but it disappears after you check "Select by current extent only". 

**Expected behavior**
The saved object should disappear immediately after saving, when it is not following the **featureType**-definition anymore.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.3 (digitizer 1.4)
 - Database: PostgreSQL
 - Browser firefox, chrome

**Comment by eschuerg** [comment]
Thank you. I will create an internal ticket.

**Comment by werrolf** [comment]
Why would you want to allow inserting / updating data that immediately vanishes? If the system behaved as you describe, this would only create the new issues "My new feature is not there" / "My feature disappeared after editing".

DO NOT define filters based on a manually editable field.

**Comment by eschuerg** [comment]
I will close this issue. If there are more questions, feel free to open it again.
Best wishes,
Eva

**Comment by astroidex** [comment]
Maybe the example described above did not show the use case properly. It was only to demonstrate the behaviour.

We use it in the following context:
- control trees: there are jobs defined to maintain trees. The tree maintainer see the jobs on the map and know what to do. When the job is finished they report it and set a date. There is a filter set for date is Null  (filter: 'datum is NULL') . After finishing the job by setting the date the tree should not show up in the map anymore.
- same concept is used in similar projects to control other objects
