### ISSUE TITLE
[Digitizer] date fields are filled with the date but the date is not displayed when you reopen die form

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1302]
**Describe the bug**
You can save dates and thre are saved in the database. But if you reopen the form it looks like the date field is not set. The form does not display the saved date.

```
            -
              type: date
              title: 'favorite Date'
              name: date_favorite
              mandatory: true
```

**To Reproduce**
1. Create a table like in the demo defined ( PG table with date_favorite date)
2. save an new object with a date
3. Reopen the form, no date is displayed

**Expected behavior**
The sdaved date should be shown

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbende: 3.2.3
 - Database: 11 PostgreSQL
 - Browser firefox

**Comment by thzanger** [comment]
Hello @astroidex, thank you for this information. The bug has been noted and will be fixed as soon as possible. Regards

**Comment by thzanger** [comment]
Dear @astroidex, the problem was tested with the same versions and configurations. No issue could be detected. Everything worked.
