### ISSUE TITLE
PDF link in fi-result  doesn't open in a new tab

### ISSUE THREAD

**Issue by kartoffelfee** [mapbender/mapbender#1310]
**Describe the bug**
a PDF that's linked via href in a feature-info result is not opened (in an new tab)

**To Reproduce**
1. Go to http://mb31.wheregroup.lan/application/mapbender_user_featureinfo_highlight?#36350@8.39162/51.91438r0@EPSG:25832
2. Click on any area of the layer 'Bebauungspläne der Stadt Gütersloh'
3. Open (+= one of the results in the feature-info result
4. left-click on 'Download hier'
5. nothing happens

**Expected behavior**
the linked PDF should open in a new TAB as in
http://www.geodaten.guetersloh.de/Bebauungsplaene

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: v. 3.2.3 (dev-master) - 23.02.2021 01:0

**Comment by thzanger** [comment]
Dear @kartoffelfee, thank your for this information. The bug has been forwarded into our internal Mapbender ticket system.

**Comment by astroidex** [comment]
* tested with 3.2.4: works fine
