### ISSUE TITLE
[backend] load WMTS fails as fees column only accepts 255 character

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1311]
**Describe the bug**
When you load a WMTS with a long fee definition the service can not be loaded in mapbender 3.2.3

See the error in the PostgreSQl logfile

**To Reproduce**
1. Try this WMTS https://www.wmts.nrw.de/geobasis/wmts_nw_dop/1.0.0/WMTSCapabilities.xml?Version=1.0.0&Service=WMTS&Request=getCapabilities

See table mb_wmts_wmtssource
* fees character varying(255) 
* there are more columns with 255 definition. They could cause problems also

**Expected behavior**
WMTS should be able to load 
**For WMS Mapbender accepts: fees text -> maybe take this for WMTS too**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.3

**Screenshots / Logmessage**
![Bildschirmfoto vom 2021-02-25 10-25-46](https://user-images.githubusercontent.com/996298/109187525-46b30500-7792-11eb-9151-6ed2a37a540c.png)

![Bildschirmfoto vom 2021-02-25 17-53-09](https://user-images.githubusercontent.com/996298/109187603-57637b00-7792-11eb-8263-3841a901ff10.png)

**Additional context**

**Comment by astroidex** [comment]
still in v3.2.4

**Comment by thzanger** [comment]
Dear @astroidex, I could not reproduce your problem. I was able to successfully implement the WMTS into 3.2.3 as well as 3.2.4

**Comment by thzanger** [comment]
Dear @astroidex, I initially tried to recreate your issue with sqlite. But I was now able to retrace the issue with postgresql. Thus, I will forward the issue to our internal ticket system. Regard

**Comment by thzanger** [comment]
Dear @astroidex, the problem is now fixed in the latest version of 3.2.4. Regards
