### ISSUE TITLE
WMTS Visualisation in Mapbender

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1313]
**Describe the bug**
WMTS are not displayed in Mapbender. You can load the WMTS but there so requests send although the WMTS should be displayed.
(hope is not a misconfiguration)

**To Reproduce**
1. Load the load WMTS for example
* https://basemap.at/wmts/1.0.0/WMTSCapabilities.xml
* https://osm-demo.wheregroup.com/service?REQUEST=GetCapabilities&SERVICE=WMTS&Version=1.0.0
* https://www.wmts.nrw.de/geobasis/wmts_nw_dop/1.0.0/WMTSCapabilities.xml?Version=1.0.0&Service=WMTS&Request=getCapabilities
2. Load the WMTS in your application
3. Start the application
4. See error: there is no request send to the WMTS

**Expected behavior**
WMTS should be displayed in the map

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.3
**Screenshots / Logmessage**
If applicable, add screenshots or a logmessage from app/logs to help explain your problem.

**Additional context**

**Comment by werrolf** [comment]
This seems to be an issue of restful WMTS vs KVP WMTS. There is currently no KVP support in Mapbender.

You can make the osm demo service work if you add it as a restful WMTS: https://osm-demo.wheregroup.com/wmts/1.0.0/WMTSCapabilities.xml

Mapproxy unfortunately separates the two based on the url used to fetch capabilities. See https://mapproxy.org/docs/nightly/services.html#web-map-tile-services-wmts
