### ISSUE TITLE
WMS Style handling in Mabender for WMS with multiple styles does not work

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1314]
**Describe the bug**
Some WMS offer more than one stlye for a layer.  You can choose the default style or other style/s.

For example the following WMS:
https://sg.geodatenzentrum.de/wms_info?REQUEST=GetCapabilities&VERSION=1.3.0&SERVICE=WMS

for dgm100 you get the style
* default
* * erfassungseinheiten
![Bildschirmfoto vom 2021-02-25 13-00-26](https://user-images.githubusercontent.com/996298/109322862-18492e80-7853-11eb-8506-d179b21b17df.png)

**To Reproduce**
1. Load WMS https://sg.geodatenzentrum.de/wms_info?REQUEST=GetCapabilities&VERSION=1.3.0&SERVICE=WMS
2. At the layerinstance configuration you should be able to change the style and choose between default and erfassungseinheiten
3. see error: instead an id 0 or 1 is offered
![Bildschirmfoto vom 2021-02-26 16-53-50](https://user-images.githubusercontent.com/996298/109323058-56465280-7853-11eb-9403-4e9badad3e0f.png)

4. if you choose an id it can not be saved
3. Normally it should save the style name in the column style in table mb_wms_wmsinstancelayer. If you do it manually you can see the style in the application
 UPDATE mb_wms_wmsinstancelayer SET style = 'erfassungseinheiten' WHERE id = 2182;
or 
 UPDATE mb_wms_wmsinstancelayer SET style = 'default' WHERE id = 2182;

Two maprequests with the different style

**STYLES=erfassungseinheiten**
https://sg.geodatenzentrum.de/wms_info?_signature=29%3AjV5wsl8E-T6F7y4wTa8kcFP9mKU&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=dgm1000&STYLES=erfassungseinheiten&_OLSALT=0.607130044635362&SRS=EPSG%3A25832&WIDTH=994&HEIGHT=1053&BBOX=262013.43498139342%2C5570719.530548535%2C537708.681887199%2C5862778.98225056
![wms_maprequest_erfassungseinheiten](https://user-images.githubusercontent.com/996298/109323939-509d3c80-7854-11eb-9839-a9341d8b3070.png)

**STYLES=default oder STYLES=**
https://sg.geodatenzentrum.de/wms_info?_signature=29%3AjV5wsl8E-T6F7y4wTa8kcFP9mKU&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=dgm1000&STYLES=default&_OLSALT=0.607130044635362&SRS=EPSG%3A25832&WIDTH=994&HEIGHT=1053&BBOX=262013.43498139342%2C5570719.530548535%2C537708.681887199%2C5862778.98225056

![wms_maprequest_default](https://user-images.githubusercontent.com/996298/109323963-57c44a80-7854-11eb-914a-db1674456d5e.png)

**Expected behavior**
It should be possible to change the style for a WMS if there are more styles than the default

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.3

**Comment by frwg** [comment]
I'm working on it

**Comment by frwg** [comment]
fixed: https://github.com/mapbender/mapbender/pull/1315

**Comment by astroidex** [comment]
tested with 3.2.4: works fine
