### ISSUE TITLE
[Backend][ApplicationSwitcher] allows you to select the actual application and offers it in the frontend 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1320]
**Describe the bug**
ApplicationSwitcher allows you to select the application that you are configuring at the moment. That does not make sense.

**To Reproduce**
1. Go to you application **A**
2. Go to Layout and add the new element ApplicationSwitcher
3. See error: you can select application **A**

**Expected behavior**
It should not be possible to select the application that you are configuring at the moment. 

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4

**Comment by thzanger** [comment]
Dear @astroidex, thank you for the information. I forwarded the issue to our internal ticket system.

**Comment by werrolf** [comment]
Already fixed in 3bc9be2294c3d32e5c0fdfe101b196937a8093de.

**Comment by werrolf** [comment]
It makes perfect sense. It shows you where you are currently.
