### ISSUE TITLE
[Backend][ApplicationSwitcher] does not respect ACLs

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1321]
**Describe the bug**
ApplicationSwitcher shows all available application and does not check whether the user who is configuring the element has access to the application

**To Reproduce**
1. Create a user **Meier**
2. Go ACL and add only application create
3. Login with user Meier and create an application
4. Add ApplicationSwitcher to the application
5. See error You can choose from all applications. You should only be able to choose from the applications that you are allowed to access/view
6. 
![Bildschirmfoto vom 2021-03-11 14-09-18](https://user-images.githubusercontent.com/996298/110792342-8ccc9600-8273-11eb-80e0-2b27c4a749e4.png)

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4

**Comment by thzanger** [comment]
Hello @astroidex, thank you for the information. I forwarded the issue to our internal MB ticket system.
