### ISSUE TITLE
reset_view does not show the correct activated title in the BaseSourceswitcher

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1322]
**Describe the bug**
reset_view does not show the activated BaseSource-Title in the BaseSourceswitcher after reset.

**To Reproduce**
1. Open application with basesourceswitcher
2. change the basesource to a different topic
2. add reset_view to the application -> click reset_view
3. See error: the map refers the right basesource but in the basesourceselection the title that you choosed before is still active

see screenshots

1. situation on start (Basesource is Standardkarte)
![hg0](https://user-images.githubusercontent.com/996298/110794665-4298e400-8276-11eb-8348-ab03ea936e15.png)

2. activate some WMS and change basesource to Luftbilder
![hg1](https://user-images.githubusercontent.com/996298/110794687-488ec500-8276-11eb-9a99-063fc60739c4.png)

3. zoom_home -> see error background  background is set back to Standardkarte but Luftbilder is still active 
![hg3](https://user-images.githubusercontent.com/996298/110794702-4c224c00-8276-11eb-9673-14ff653fb568.png)

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4
 - Firefox

**Comment by thzanger** [comment]
Dear @astroidex, I was able to reproduce your issue and forwarded it to our internal ticket system. Regards
