### ISSUE TITLE
Application is visible although it is not published

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1326]
**Describe the bug**
You can prepare an application and add all the services and prepare all the settings before you publish it (checkbox activate/button eye).
In version 3.2.4 all applications are active although activate = false.

**To Reproduce**
1. Deactivate an application
2. Assign it to IS_Autheticated_Anonymously
3. Logout
4. See error: The application is visible although it is not published

**Expected behavior**
Only applications that are published should show up

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4
 
![Bildschirmfoto vom 2021-03-15 08-51-46](https://user-images.githubusercontent.com/996298/111120731-06ae9900-856c-11eb-9e89-af10cad39300.png)

**Comment by thzanger** [comment]
Dear @astroidex, the issue has been noted. I will forward it to our internal ticket system
