### ISSUE TITLE
Element sketch input field for text shows up although text is not activated

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1327]
**Describe the bug**
Element sketch allows you to select different geometrytypes to draw. If you do not select text, the textfield is still displayed in the application

**To Reproduce**
1. Backend: Go to element Sketch in you application and deselect "text"
2. Frontend: Refresh the application and have a look at element sketch
3. See error: Textfield Beschriftung is still there although text was disabled

**Expected behavior**
Anly show Text field of text is activated

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4
 - 
**Screenshots / Logmessage**
![Bildschirmfoto vom 2021-03-15 10-48-38](https://user-images.githubusercontent.com/996298/111135549-14204f00-857d-11eb-91f4-41781405bc38.png)

![Bildschirmfoto vom 2021-03-15 10-48-20](https://user-images.githubusercontent.com/996298/111135572-1b475d00-857d-11eb-90e3-7701c830505d.png)

**Additional context**

**Comment by thzanger** [comment]
Dear @astroidex, thanks for this information. The issue has been noted.

**Comment by werrolf** [comment]
You can label any feature.
