### ISSUE TITLE
[Frontenend] Layertree as dialog with Thematic layers does not open anymore after a WMS was added my load WMS

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1331]
**Describe the bug**
When you have an application with the layertree opened by button and also with thematiclayer=true. The layertree-dialog does not open anymore if you have loaded a WMS before by WMSloader.

See error when you click on the layertree-button:
![Bildschirmfoto vom 2021-03-15 18-29-23](https://user-images.githubusercontent.com/996298/111195579-b3b10200-85bc-11eb-93ea-dcaee7619457.png)

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Errors/Unexpected_type

**To Reproduce**
1. Import mapbender_user_basic to your database
2. go to the layertree element and activate thematic layer -> reopen the element again and save
3. open your application
3. Load the mapbender_user WMS to your application via Button-WMSloader
4. Click Layertree-Button to open the layertree
4. See error: Layertree does not open. But you get the error message (see image)
5. https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Errors/Unexpected_type

**Expected behavior**
After the loading of a WMS it should show up in the layertree at the to and not in a layerset

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4

**Screenshots / Logmessage**
Layertree before you loaded the WMS
![Bildschirmfoto vom 2021-03-15 18-28-56](https://user-images.githubusercontent.com/996298/111196056-2f12b380-85bd-11eb-83c4-f9b63fc48732.png)

Load WMS
![Bildschirmfoto vom 2021-03-15 18-29-34](https://user-images.githubusercontent.com/996298/111196087-36d25800-85bd-11eb-86af-ebacb9050b9f.png)

**Additional context**

**Comment by thzanger** [comment]
Thank you @astroidex, I was able to reproduce your issue. I forwarded it to our internal MB ticket system.

**Comment by thzanger** [comment]
Dear @astroidex, the issue has been fixed for the latest version of 3.2.4. Regards.
