### ISSUE TITLE
Fullscreen template shows footer although there are no elements in the footer

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1332]
**Describe the bug**
If you disable all elements in the footer the application should not show the footer at all. At the moment a grey small bar is displayed. The effect is caused by     padding: 5px 10px 5px 10px;

```
.toolBar {
    opacity: 0.8;
    z-index: 4;
    user-select: none;
    padding: 5px 10px 5px 10px;
    border-color: #c6c6c6;
    line-height: 1;
}
```

**Expected behavior**
It would be good, if there is no toolbar displayed if there is no element in the toolbar

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4

![Bildschirmfoto vom 2021-03-18 10-29-38](https://user-images.githubusercontent.com/996298/111604647-d36f4280-87d5-11eb-9261-668ccade6d90.png)

**Comment by rschwammborn** [comment]
This is the current default behavior of all frontend panels - toolbar and sidepane act similar. Thus, this is a software enhancement and I will propose it as feature request to the developers.
