### ISSUE TITLE
Composer 2 Compatibility

### ISSUE THREAD

**Issue by binarious** [mapbender/mapbender#1333]
**Is your feature request related to a problem? Please describe.**
This project is currently not compatible with Composer 2, because it requires `"wheregroup/open-sans:1.x"` which requires `"robloach/component-installer:0.x"` which is deprecated and requires `"composer-plugin-api:^1.0"`.

**Describe the solution you'd like**
I'd like this project to be compatible to Composer 2.

By the way: Is there a plan to completely get rid of the deprecated Assetic and move to a more modern approach?

**Additional context**
```
Problem 1
    - robloach/component-installer is locked to version 0.2.3 and an update of this package was not requested.
    - robloach/component-installer 0.2.3 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - robloach/component-installer 0.2.3 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - wheregroup/open-sans 1.4.2 requires robloach/component-installer 0.x -> satisfiable by robloach/component-installer[0.2.3].
    - wheregroup/open-sans is locked to version 1.4.2 and an update of this package was not requested.
```

**Comment by thzanger** [comment]
Hello @binarious, thank you. We always try to improve Mapbender. I forwarded your question to our internal Developers. 

Please be aware that feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html

**Comment by thzanger** [comment]
Dear @binarious, Composer 2 is currently planned but its implementation will still take some time. Regards

**Comment by rschwammborn** [comment]
Mapbender 3.3 now supports Composer 2.1! For other major changes, please check the release tag: https://github.com/mapbender/mapbender-starter/releases/tag/v3.3.0
