### ISSUE TITLE
[printclient] if you set optional fields to null you get an error when you open your application

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1334]
**Describe the bug**
When you do not use optional fields you would set optional_fields to null. But this causes an error when you load your application.

**To Reproduce**
1. copy application mapbender_user
2. go to the print element and open the field optional fields and delete the text there
3. open your application

**Expected behavior**
Application should work also when there are no optional fields defined

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4
 - Database: [e.g. PSQL 9.5.12]
 - Browser firefox

**Screenshots / Logmessage**
![Bildschirmfoto vom 2021-03-19 12-50-26](https://user-images.githubusercontent.com/996298/111776224-05ee6d80-88b2-11eb-8fa0-8b5320f3d3c5.png)

Error when used via dialog
![Bildschirmfoto vom 2021-03-19 12-52-34](https://user-images.githubusercontent.com/996298/111776238-0981f480-88b2-11eb-819a-c535d34195ad.png)

Error when used via sidepane (element)
![Bildschirmfoto vom 2021-03-19 12-54-01](https://user-images.githubusercontent.com/996298/111776398-40580a80-88b2-11eb-97ed-256cefbcf65b.png)

**Comment by thzanger** [comment]
Hello @astroidex, thank you for this information. I was able to recreate the issue and forwarded it to our internal MB ticket system. Regards.

**Comment by astroidex** [comment]
tested with 3.2.5rc2 - works fine
