### ISSUE TITLE
CoordinateUtility displays wrong location for coordinates if the input uses , instead of .

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1335]
**Describe the bug**
If you define a coordinate in Bonn-Kennedybrücke it is this 7.107602 50.737834 (WGS 84). 

If you define the coordinate with comma instead of point 7,107602 50,737834 there is no error message but it does not zoom to Bonn-Kennedybrücke - but somewhere else (mapbender ignores the numbers after the , and uses 7 50).

**To Reproduce**
1. https://demo.mapbender.org/application/mapbender_user_yml
2. Go to 7.107602 50.737834 (WGS 84). 
3. Modify to 7,107602 50,737834 (WGS 84). 
4. Compare with 7 50 (WGS 84). 

**Here is a PR to fixx the issue: replace , with . before handling the input**
https://github.com/mapbender/coordinates-utility/pull/16

**Comment by rschwammborn** [comment]
Greetings @astroidex,
I could reproduce this issue and provided necessary information to our internal ticket system.

**Comment by astroidex** [comment]
This PR solved the error: https://github.com/mapbender/coordinates-utility/pull/16

**Comment by werrolf** [comment]
Merged into new releases:
https://github.com/mapbender/coordinates-utility/releases/tag/1.2.2 (Mapbender >= 3.2.6)
https://github.com/mapbender/coordinates-utility/releases/tag/1.1.4 (older Mapbender)
