### ISSUE TITLE
[Frontend][Metadata][featurInfo] show text of root-layer-title instead of title

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1336]
**Is your feature request related to a problem? Please describe.**
If you use the administration backend to configure your WMS-instances you can set a title and a root-layer title.

* root-layer-title is shows in the layer tree (1)and legend(2)
* title is shown in the metadata-dialog (3) and in the tab of the feature info dialog (4)

![mb_metadata_title_admin](https://user-images.githubusercontent.com/996298/112805207-975d9c80-9075-11eb-91f8-ce97dbb84479.png)

![mb_metadata_title](https://user-images.githubusercontent.com/996298/112805235-9f1d4100-9075-11eb-9b7c-f5ae058fcfa3.png)

**Describe the solution you'd like**
It would be great to only use the root-layer-title for all four positions. Like this you could use the title f.e. for background information

**Comment by thzanger** [comment]
Hello @astroidex,
Thank you for this suggestion. We always try to improve Mapbender. I forwarded the feature wish to our developers. 

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH
info@wheregroup.com
https://wheregroup.com/kontakt.html

**Comment by rschwammborn** [comment]
Dear @astroidex ,

since Mapbender 3.2.6, the root layer title is the default title for frontend elements.
For detailed info, check the changelog for the version: https://github.com/mapbender/mapbender/blob/master/CHANGELOG.md#v326

Greetings!
