### ISSUE TITLE
[digitizer] print:true does not print the feature information in the pdf output

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1338]
**Describe the bug**
Digitizer: Druck von Sachdaten zum Objekt via print: true

Im Digitzer war es möglich über ein Objekt einen Druck anzustoßen und Sachdaten im Druck auszugeben.
-> print: true
-> Verweis in der config.yml über featureTypes auf die Druckvorlagen

No featureinformation is in in the print output. Maybe this is due to the missing possinility to define the featureType via name #1337

**To Reproduce**
1. use the digitize demo to reproduce
2. odg: https://github.com/mapbender/mapbender-workshop/blob/release/3.2/app/Resources/MapbenderPrintBundle/templates/a4_portrait_official_feature_data_demo.odg
2. PostrgeSQL DB: https://github.com/mapbender/mapbender-workshop/blob/release/3.2/geobasis.backup
3. application: https://github.com/mapbender/mapbender-workshop/blob/release/3.2/app/config/applications/mapbender_digitize_demo.yml
4. Config https://github.com/mapbender/mapbender-workshop/blob/release/3.2/app/config/config.yml

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4

See the additional print button in the form when you set print: true
![Bildschirmfoto vom 2021-04-01 16-14-45](https://user-images.githubusercontent.com/996298/113307474-7317ef00-9305-11eb-8f7d-ad2329538cd7.png)

**Comment by rschwammborn** [comment]
Hello @astroidex,
thank you for this issue, I could reproduce the behaviour and created an internal ticket.

**Comment by astroidex** [comment]
works fine with Mapbender 3.2.5rc2 (tested with 1.4.8)
