### ISSUE TITLE
 [Frontend][Layertree] close folder in layer tree is not possible on Android devices with Google-Chrome-Brower

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1349]
**Describe the bug**
If you use an  Android devices with Google-Chrome-Brower it is not possible to close a folder of a WMS after you opened it. With Firefox it is no problem on a mobile Android device and on a desktop machine all browsers work fine.

**To Reproduce**
1. Take an Android device
2. Open https://demo.mapbender.org/application/mapbender_user_yml
3. Open the Folder Mapbender user or OSM Demo
4. Try to close the folder

**Expected behavior**
It should be possible to close the folder of a WMS in the layertree

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4

**Comment by thzanger** [comment]
Dear @astroidex, I was able to reproduce your issue and forwarded it to our developers. Regards

**Comment by thzanger** [comment]
The issue has been solved in 3.2.5.
