### ISSUE TITLE
[digitizer] saves '' instead of NULL for fields with no content

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1355]
**Describe the bug**
If you leave a field empty and save an object, Mapbender will save '' in that field instead of NULL. If there is no input the default should be to save NULL. 
If you have an integer field or a date field and you save it with no input you get an error.

Error integer:
![Bildschirmfoto vom 2021-05-03 08-38-23](https://user-images.githubusercontent.com/996298/116847567-143ae380-abeb-11eb-91bd-e60a32409604.png)

Error date:
![Bildschirmfoto vom 2021-05-03 08-51-44](https://user-images.githubusercontent.com/996298/116848405-da6adc80-abec-11eb-84af-68551f3848c5.png)

**To Reproduce**
1. Configure a digitizer
2. add a column f.e. plz type int
3. add it to your application
4. See error: you can not save an object as Mapbender trys to save '' in the integer field

**Expected behavior**
No input should not save '' but NULL in the column. It should be possible to save NULL for date, integer, float ...

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4 (also tested with 1.4.7

**Comment by thzanger** [comment]
Dear @astroidex, the issue has been noted and I forwarded it to our internal ticket system. Regards

**Comment by werrolf** [comment]
Error on submit of empty string to numeric column has been fixed in [data-source >= 0.1.21](https://github.com/mapbender/data-source/releases/tag/0.1.21).
Nullable int/float/decimal column will receive null. Non-nullable int/float/decimal column will receive 0.

Fix is bundled since Mapbender Starter v3.2.6.

Manual update in existing project:
```sh
bin/composer update mapbender/data-source
```

**Comment by astroidex** [comment]
Please note that for columns of type double precision Mapbender >= v3.2.6. and <= 3.2.8 still tries to save '' for fields with no input and runs into an error
