### ISSUE TITLE
[weight] for application elements is not set properly - elements are mixed

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1357]
**Describe the bug**
There is a column weight in mb_core_element. This column contains an integer value. It can occur that the buttons in the sidepane do not show up in the defined order or each time in a different order as the weight is not set right. This can be fixed in the database when you set the weight manually. 
It occurred in Mapbender installations where a database update was performed.

```
SELECT * FROM public.mb_core_element
ORDER BY application_id, weight ASC ;
```

**To Reproduce**

**Expected behavior**
Elements should be displayed in the defined order.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4
 - Database:
 - Browser

**Comment by thzanger** [comment]
The problem has been fixed in 3.2.6. Regards
