### ISSUE TITLE
layerset not connected to layertree / type error in public.mb_core_element.configuration? doctrine?

### ISSUE THREAD

**Issue by arimonma** [mapbender/mapbender#1358]
Since migration from MB 3.0.8.1 to 3.2.4 we have the following issue:

**To reproduce** via backend:
1.	Create new layerset containg some layers,
2.	Connect to map,
3.	Connect to layertree

**Result/issue/bug** at frontend: 
Layers contained in the new Layerset are listed in application‘s layertree – but on highest tree level and not within the new or any other folder! New folder/layerset head itself is not visible. Migrated layersets still are displayed correctly.

After an intensive search I detected an issue in the database (PostgreSQL) in table „**public.mb_core_element**“, column „**configuration**“, containing a DC2Type/JSON array:

Related to each application there exists an array according to „themes“ (~ active layersets within layertree) containing these snippets:

-	for all existing/migrated entries (example: id=28):

… s:6:"themes";a:11:{i:0;a:6:{s:2:"id";**s:2:"28"**;s:5:"title";s:3:"BLE";s:8:"useTheme";b:1;s:6:"opened";b:0; s:16:"sourceVisibility";b:0; s:11:"allSelected";b:0;} …

-	for all new entries (example: id=75):

… … i:10;a:4:{s:2:"id";**i:75**;s:6:"opened";b:0;s:5:"title";s:14:"TEST-Layerset";s:8:"useTheme";b:1;} …

As far as I understand, here the IDs of the layersets in „public.mb_core_layerset“ are referenced (there: integer). For test purposes I replaced i:75 by s:2:“75“ within the JSON/DC2Type array – now the folder appears as desired! A wrong (?) entry always seems to be created when connecting a layerset to a layertree via application manager-->Layouts.

Now the **question**: why does this occur? A bug? During Migration somewhere else corrupted configuration data? How can one fix this (except filling/correcting table entries manually ;-) ?

MB 3.2.4
PostgreSQL: 9.6.16
Browser: Firefox 88.0

Thanks, Martin

**Comment by astroidex** [comment]
Hi @arimonma,

this issue is already fixed for 3.2.5. It is reported in ticket: https://github.com/mapbender/mapbender/issues/1330

**Comment by rschwammborn** [comment]
As @astroidex spotted correctly, this issue has already been documented and a fix is on its way, therefore I'm closing the duplicate.
