### ISSUE TITLE
owsproxy issue in MB version 3.2.4

### ISSUE THREAD

**Issue by arimonma** [mapbender/mapbender#1359]
Hi all,
after updating our mapbender QS instance from version 3.0.8.1 to 3.2.4 we run into some issues with requests over owsproxy (webproxy). Our IT operations dept. reports this:

"We made some local tcpdumps and found out that the http headers are truncated after the first letter. In production environment with mapbender 3.0.8.1 the headers are correct.
Here an example on how the http headers are passed to the webproxy:

HTTP-Header-content | v. 3.0.8.1 | v. 3.2.4
--------------------- | ------------ | ------------
sec-fetch-dest: | document | d
sec-fetch-mode: | navigate | n
sec-fetch-site: | none | n
sec-fetch-user: | ?1 | ?
x-forwarded-for: | 192.168.1.34 | 1

There are a few more, but allways only the first letter of the content.
The incorrect header values result in the forwarded requests not being forwarded by various web proxy servers with verification of the HTTP layer. 
The web proxies recognise the incomplete header value as an error and therefore do not forward the requests.
Perhaps only the first position of an array is read out? Hope someone can help out."

Thanks & regards, Martin

**Comment by rschwammborn** [comment]
Hi @arimonma ,

this issue has been fixed in owsproxy 3.7.1. Take a look at the owsproxy-changelog and update Mapbender accordingly: https://github.com/mapbender/owsproxy3/releases/tag/v3.1.7

I'm closing the issue. If the bug should somehow still consist, feel free to reopen it.

Greetings!
