### ISSUE TITLE
403 error occurs when user clicks on a link where no access rights are available

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1363]
**Describe the bug**
When you create a user with no special ACL rights you get the Link "Security". If you click on the link you get a 403 error. 

Maybe the Security link should not be displayed at all.

**To Reproduce**
1. Go to your mapbender installation
2. Create a user
3. login as this user
4. 4. Click on link security

**Expected behavior**
Do not show the link security if no special rights for the user are provided

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.5
 - Browser firefox

**Screenshots / Logmessage**
![Bildschirmfoto vom 2021-06-16 15-01-37](https://user-images.githubusercontent.com/996298/122224053-05b33d80-ceb4-11eb-88c4-d1450359c63f.png)

![Bildschirmfoto vom 2021-06-16 15-01-46](https://user-images.githubusercontent.com/996298/122224076-0a77f180-ceb4-11eb-893a-4de6332c6bc9.png)

**Comment by thzanger** [comment]
Dear @astroidex, the issue has been noted and was forwarded to our internal ticket system. Regards
