### ISSUE TITLE
[backend][button] add new button element without target - mandatory message is displayed wrong

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1365]
**Describe the bug**
If you add a button element and do not provide the mandatory fields before saving the browsers is blocked by the error message.

**To Reproduce**
1. Go to backend application
2. add a button
3. do not fill target 
4. See error: see screenshot - you can not close the error message and go on with editing. No ok / cancel button is displayed.

**Expected behavior**
Show mandatory field 

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.5
 - Browser chrome firefox

**Screenshots / Logmessage**
![error_button](https://user-images.githubusercontent.com/996298/122349916-02b85b80-cf4d-11eb-9d01-db7aa3e530fe.png)

**Additional context**

**Comment by thzanger** [comment]
Dear @astroidex, thank you for the information. The issue has been noted. Regards

**Comment by thzanger** [comment]
The issue has been solved in 3.2.6. Regards
