### ISSUE TITLE
[digitizer] does not initialize properly if there are empty geom datasets

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1366]
**Describe the bug**
If the table contains some datasets with no geom entry the applications does not show any feature. 
Throws console error: Uncaught TypeError: this.wkt is null

You could handle the error in the configuration with filter: 'geom is not null' but a general solution without the filter would be great.

**To Reproduce**
1. Create a digitize application
2. delete the content of one geom column
3. open your application
4. See error: no features are displayed and console error Uncaught TypeError: this.wkt is null occurs

**Expected behavior**
Datasets without a geom should be ignored.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.5

**Comment by thzanger** [comment]
Dear @astroidex, I was able to recreate the issue and will make a report into our internal ticket system.

**Comment by astroidex** [comment]
Tested with digitizer 1.4.9: works as expected. Datasets without a geom are ignored.
