### ISSUE TITLE
PDF Link in GetFeatureInfo doesn't open in google chrome

### ISSUE THREAD

**Issue by DanielKnoop** [mapbender/mapbender#1377]
**Describe the bug**
I use mapbender to publish "Bebauungspläne". To provide additional information to the user, I added hyperlinks to PDF-Files in the GetFeatureInfo (html formatted). The PDF-Files should be opened in a new tab (target="_blank"). The WMS Server is mapserver. All working well with firefox but not in google chrome. Every time I click on the hyperlink, chrome throws an error "ERR_BLOCKED_BY_CLIENT". Mapserver and Mapbender are on different domains, but all CORS Entries are available and valid.

**To Reproduce**
1. add WMS Service to Mapbender with Infoformat text/html
2. Open the featureinfo window in chrome with a link inside to open a PDF File in new Tab (target="_blank")
3. click on the hyperlink
4. See error "ERR_BLOCKED_BY_CLIENT"

**Expected behavior**
The PDF should be opened in a new tab

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: v3.2.4
 - Database: 
 - Browser: Google Chrome 92, Microsoft Edge (chrome based), Opera... (works in Firefox)

**Screenshots / Logmessage**
Chrome reported ERR_BLOCKED_BY_CLIENT

**Additional context**
I think I found that this beavior is driven by the iframe sandbox parameters. I added `allow-popups-to-escape-sandbox` to the sandbox parameter list and now it is working in chrome too.

```
        _showOriginal: function(source, layerTitle, data, mimetype) {
            var self = this;
            switch (mimetype.toLowerCase()) {
                case 'text/html':
                    var script = self._getInjectionScript(source.id);
                    var iframe = $('<iframe sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox">');
                    iframe.attr("srcdoc",script+data);
                    self._addContent(source, layerTitle, iframe);
                    break;
                case 'text/plain':
                default:
                    this._addContent(source, layerTitle, '<pre>' + data + '</pre>');
                    break;
            }
        },
```

File: mapbender.element.featureInfo.js

**Comment by ThorstenHi** [comment]
The fix for the PDF links (this ticket) works well in Mapbender version 3.2.8.
For PDF downloads and ZIP files (or other downloads) see also: https://github.com/mapbender/mapbender/pull/1387
