### ISSUE TITLE
[frontend][link] Element show label althought label is disabled

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1383]
**Describe the bug**
The element links shows the title as label althought the checkbox is disabled.

**To Reproduce**
1. Add a link to the application
2. Disable checkbox Show label
4. See error: label is still there

**Expected behavior**
If no label is selected the labeling should not be displayed
**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender 3.2.7

**Screenshots / Logmessage**
![Bildschirmfoto vom 2021-10-06 10-54-48](https://user-images.githubusercontent.com/996298/136172818-8ea8d9aa-0360-46cb-aa3a-5437c1a3bbb6.png)

![Bildschirmfoto vom 2021-10-06 11-24-54](https://user-images.githubusercontent.com/996298/136176465-c75b8bad-6ee2-4fb8-9b66-1d7d3928864a.png)

**Comment by astroidex** [comment]
still open in 3.2.8

**Comment by werrolf** [comment]
Fix is pending for v3.2.9 / v3.3.0

**Comment by astroidex** [comment]
Tested. Works fine in Version 3.2.9
