### ISSUE TITLE
[digitizer] if there is no input in a textfield digitizer stores two '' instead of NULL

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1385]
**Describe the bug**
In digitizer you can define type input for a textfield. When you do not fill the field mapbender will save '' instead of NULL. In older Mapbender version NULL was saved.

 ```
    -
          type: input
          title: Abstract
          mandatory: false
          name: abstract
```

**To Reproduce**
1. donwload Mapbender 3.2.7 with digitizer 
2. add a type:input field 
3. leave the field empty
4. See error: check your table in postgresql and see that there is not NULL saved but ''

**Expected behavior**
no input should save NULL

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.7
 - Database:  13.2
 - Browser all

**Screenshots / Logmessage**
![Bildschirmfoto vom 2021-10-08 14-01-41](https://user-images.githubusercontent.com/996298/136564087-5deff006-ac07-447b-9c97-59d513e82eb5.png)

![Bildschirmfoto vom 2021-10-08 14-01-14](https://user-images.githubusercontent.com/996298/136564134-db725847-a0a7-4155-8061-b2a96160fde3.png)

**Comment by Phocacius** [comment]
duplicated, see https://github.com/mapbender/mapbender/issues/1396
