### ISSUE TITLE
[backend] WMS instance deactivate all layers is disabled

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1388]
**Describe the bug**
In the WMS instance configuration there is a checkbox to disable all layer. This checkbox is extremly usefull when you have WMS with many layers (sometimes > 50) to disable all and then activate the layer you are interested in.

The functionality is not available anymore.

Sidenote: sure it does not make sense to deactivate all layer. the root layer has to be active in the end to use the WMS in the application. 

![backend](https://user-images.githubusercontent.com/996298/139440207-d5a4b874-dc30-40b1-91ab-a0eccc35c239.png)

**To Reproduce**
1. Go to your application
2. add a WMS
4. See error. You can not deactivate all layer at once

**Expected behavior**
enable the checkbox again

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.7
 - Browser firefox, chrome

**Comment by rschwammborn** [comment]
Dear @astroidex,
I redirected your request into our internal ticket system.
Greetings

**Comment by werrolf** [comment]
Fix is pending for v3.2.9 / v3.3.0.
