### ISSUE TITLE
[digitizer] allowEditData: false does not open form on click on the object in the map

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1390]
**Describe the bug**
When you define **allowEditData: false** the attributes can be seen but not saved. The form should open on click on the feature table and on click on the object in the map. There is no save button in the form.

In version 3.2.7/3.2.8 the form opens on click on the object in the table, but it does **not** open form on click on the object in the map.

**To Reproduce**
1. Create a digitizer Application for example https://github.com/mapbender/mapbender-workshop/blob/release/3.2/app/config/applications/mapbender_digitize_demo.yml
2. set  allowEditData: false
2. Click on a feature in the map to open the form
4. See error -> the form does not open
5. if you click on the table at the left on an object the form opens as expected

**Expected behavior**
Form should open on click on the object in the map.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.8, also 3.2.7
 - Database: PostgreSQL 13 / PostGIS 3.1
 - Browser Firefox, Chromium

**Screenshots / Logmessage**
![digitizer](https://user-images.githubusercontent.com/996298/139838977-b8c0d03c-8026-4df9-9db2-6f675fea6cfc.png)

**Additional context**

**Comment by rschwammborn** [comment]
Hi @astroidex , I could recreate this issue, so I wrote an internal ticket.

**Comment by werrolf** [comment]
Fixed in [Digitizer 1.5.3](https://github.com/mapbender/mapbender-digitizer/releases/tag/1.5.3)
