### ISSUE TITLE
[digitizer] saves '' instead of NULL for fields of type double precision

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1396]
**Describe the bug**
Addition to ticket  #1356
If you save an empty value for a field of type **double precision** Mapbender tries to save ''. 
Mapbender works fine and saves Null for fields of type  int/float/decimal

**To Reproduce**
1. Configure a digitizer
2. add a column f.e. test type **double precision**
3. add it to your application
4. See error: you can not save an object as Mapbender trys to save '' in the double precision field
5. 
**Expected behavior**
Also save NULL for empty double precision type columns as this data type is very common.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.8

**Comment by werrolf** [comment]
Fixed in data-source [0.2.5](https://github.com/mapbender/data-source/releases/tag/0.2.5) and [0.1.28](https://github.com/mapbender/data-source/releases/tag/0.1.28).

Update using `bin/composer update mapbender/data-source.
