### ISSUE TITLE
[PrintClient] does not produce pdfs in the right scale for WGS84/WebMercator

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1398]
**Describe the bug**
When you generate a print output in WGS 84 or WebMercator the scale in the print output is not right. When you print in a carthesian projection like UTM or GK (EPSG:25832 or EPSG:31466) the output scale is ok. 
(Sidenote: the measure functionality works fine fr WGS84/WebMercator)

In older Mapbender versions the print output worked fine for WGS84/WebMercator.

**To Reproduce**
1. Go to https://demo.mapbender.org/application/mapbender_user_yml
2. Generate a print output in WGS84 and another one in 25832 (switch EPSG)
4. See error in the output pdf

**Expected behavior**
Print output scale should be ok

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.8

**Comment by werrolf** [comment]
Fixed in [v3.3.2](https://github.com/mapbender/mapbender/releases/tag/v3.3.2)
