### ISSUE TITLE
Backend datasources - tab applications improvements as there are inconsistencies

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1399]
**Describe the bug**
Here are some improvements for the datasources-application overview. There are some 
- The datasources-application overview does not show the Instance-id for private instances
- OK status: inactive: (WMS-eye-closed) -> is only shown for WMS were the layerset  is integrated in the application (map-element-layerset is checked)
- ERROR status: inactive is not shown for WMS were the layerset is not active in the application -> is only shown for WMS were the layerset is integrated in the application

**Expected behavior**
- show instance-id for all WMS Instances not only for Shared-Instances
- show inactive status when the WMS is not active in the application as the layerset is not checked in map-element
 
**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.8
 - 
**Screenshots / Logmessage**
![Bildschirmfoto vom 2021-12-13 10-00-09](https://user-images.githubusercontent.com/996298/145784470-e0c348e5-fe0e-4645-83bf-a3df11db80ce.png)

![Bildschirmfoto vom 2021-12-13 09-59-49](https://user-images.githubusercontent.com/996298/145784507-73ae025a-0282-4ca7-8579-7610659b4e03.png)

**Comment by rschwammborn** [comment]
I'm closing the issue as because of feedback (1) and testing (2) on 3.2.8:

1. Expected behavior 1: "Works as intended" (feedback).
2. Expected behavior 2: I could not reproduce the inconsistency for the "inactive" button on both versions - for me, it appeared in every scenario you mentioned above.
