### ISSUE TITLE
Fresh install: can't add element to new application

### ISSUE THREAD

**Issue by Revo2022** [mapbender/mapbender#1405]
**Describe the bug**
- Create a new application
- E.g. pick a layer tree
- Target field shows an empty list with nothing to pick from (and therefore won't be added to the application)

![image](https://user-images.githubusercontent.com/98014852/150118299-4e6f748f-4109-42da-b5ee-a248638aa339.png)
![image](https://user-images.githubusercontent.com/98014852/150118856-21e3fd9b-e547-454c-9d8a-6850bf2935d8.png)

**Versions (in which version of the documentation does the error occur):**
 - starter-latest
 - Used doc: Debian server

**Improvement**
- Is this a bug or a missing step in installation?

**Comment by astroidex** [comment]
you should add a map element first

**Comment by rschwammborn** [comment]
> you should add a map element first

That should be it. For more info on adjusting an application in the right (descending) order, please check the configurational exercise steps in Quickstart: https://doc.mapbender.org/en/quickstart.html#try-it-yourself

**Comment by Revo2022** [comment]
Thank you that fixed it.

In the docs I only found the possibility to lock certain elements behind the included right system. What we need would be to hide applications inside the application summary window and layers inside a running system. Could this be achieved with mapbender3 as it is possible with our old mapbender?

**Comment by astroidex** [comment]
Hi Revo2022,
here are the answers to your questions.

1. hide applications inside the application summary window: on every application you find the tab security. There you can define who is allowed to use the application. Non authorized users will not see the application and can not access it
2. hide layers inside a running system: you can only see the layers in an application that are activated. If you disable layers in the administration they are not available in the application. But you can not define a per user/group access to layers within an application.
