### ISSUE TITLE
[mobile] FeatureInfo the result is shown in a small frame and does not cover the whole dialog

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1406]
**Describe the bug**

**To Reproduce**
1. Go to https://demo.mapbender.org/application/mapbender_mobile_yml
2. Click for FeatureInfo on a Mapbender user symbol
4. See error: result is shown in the upper section of the dialog

**Expected behavior**
The result should cover the whole dialog

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.8
 - 
**Screenshots / Logmessage**
![Bildschirmfoto vom 2022-01-20 12-44-36](https://user-images.githubusercontent.com/996298/150332659-9206f2b0-9135-44ce-931e-8a5481da736c.png)

**Comment by astroidex** [comment]
Can get fixed with something like

.tabContainer .container {
  height: 90%;
}

**Comment by werrolf** [comment]
Please try again with [v3.3.2](https://github.com/mapbender/mapbender/releases/tag/v3.3.2)

**Comment by astroidex** [comment]
Looks good frame is bigger
