### ISSUE TITLE
Permission denied when I used app/console doctrine:schema:update --dump-sql. after going to upgrade a newest version

### ISSUE THREAD

**Issue by YourErik** [mapbender/mapbender#1407]
**Describe the bug**
Permission denied when I used app/console doctrine:schema: update --dump-SQL. after going to upgrade the newest version

**To Reproduce**
app/console doctrine:schema:update --dump-sql
permission denied

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender:  3.2.8
 - Database: [e.g. PSQL 9.5.12]

**Screenshots / Logmessage**
  

**Additional context**

**Comment by astroidex** [comment]
Hi YourErik,
no problem with PostgreSQL and version 3.2.8 on our side.
Does your user has enough privileges to do the update?
You can try to run the SQLs displayed by --dump-sql in your a PostgreSQL client like pgAdmin or DBeaver.
Make sure to make a backup of your database first.

**Comment by YourErik** [comment]
> Hi YourErik, no problem with PostgreSQL and version 3.2.8 on our side. Does your user has enough privileges to do the update? You can try to run the SQLs displayed by --dump-sql in your a PostgreSQL client like pgAdmin or DBeaver. Make sure to make a backup of your database first.

Thank you for the response. Does mapbender support php version 8.1.2?

**Comment by rschwammborn** [comment]
Hello @YourErik ,
as of right now, Mapbender does support PHP versions from 5.6 to 7.4. The team is working on supporting PHP 8 in upcoming Mapbender versions. Stay tuned!

**Comment by YourErik** [comment]
> Hello @YourErik , as of right now, Mapbender does support PHP versions from 5.6 to 7.4. The team is working on supporting PHP 8 in upcoming Mapbender versions. Stay tuned!

Thank you. :)
