### ISSUE TITLE
[html] can not add html element or edit existing

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1410]
**Describe the bug**
You can not add a html element or edit existing html elements.

The following error occurs
![Bildschirmfoto vom 2022-03-10 11-03-41](https://user-images.githubusercontent.com/996298/157638741-cc649e0d-2ff5-4eb1-a042-0631aac72dad.png)

**To Reproduce**
1. Go to an application
2. add a html element
4. See error on save, check via F12

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.3.0
 - PHP 7.4
 - PostgreSQL 

**Additional context**
Worked fine in version 3.2.9

**Comment by rschwammborn** [comment]
Fixed in both 3.2.10 and 3.3.1.

**Comment by astroidex** [comment]
Tested with 3.3.1: works fine
