### ISSUE TITLE
[PrintClient] print frame can not be moved when a ruler element is actice

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1412]
**Describe the bug**
With the ruler element you can draw lines and areas. The lines and areas can be printed via PrintClient. It can be necessary to move the print frame before you print. This is not possible anymore. Mapbender trys to draw line/area instead

**To Reproduce**
1. Go to https://demo.mapbender.org/application/mapbender_user_yml
2. Click on Measure line and draw a line
3. Open the print dialog and try to move the print frame
4. See error meaure is still active & the frame can not be moved

**Expected behavior**
When the print frame is visible it should be possible to move the frame

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.8, 3.2.9, 3,3
 - Browser firefox, chrome

**Screenshots / Logmessage**
![princlient](https://user-images.githubusercontent.com/996298/161549211-bfb887eb-114c-4415-af41-e7aa06d7e4c4.png)

**Comment by rschwammborn** [comment]
Fixed in both Mapbender 3.2.10 and 3.3.1.

**Comment by astroidex** [comment]
Tested with 3.3.1: works fine
