### ISSUE TITLE
layersetId is used but not defined

### ISSUE THREAD

**Issue by frwg** [mapbender/mapbender#1426]
https://github.com/mapbender/mapbender/blob/9ca5539be3f7337cd8239feb53ec49e4a799e760/src/Mapbender/CoreBundle/Resources/public/mapbender-model/MapModelBase.js#L545

**Comment by astroidex** [comment]
@werrolf do you knwo the status?

**Comment by werrolf** [comment]
The error message you get tells you exactly what's wrong with your application.
It is impossible for a vanilla mapbender frontend to use sources that are _not_ associated with a layerset.
