### ISSUE TITLE
WMS Legend not displayed for INSPIRE servers with strict error reporting (Geoserver)

### ISSUE THREAD

**Issue by morcom** [mapbender/mapbender#1428]
Looks like that Legend is not displayed on systems which require a strict requests like INSPIRE - where version must be in every data request.
In requests for Inspire View Services we need always define version. In the GetLegend request from Mapdefender version is missed.

`<img src="https://inspire.caris.nl/geoserver/gnwms/ows?service=WMS&amp;request=GetLegendGraphic&amp;format=image%2Fpng&amp;width=300&amp;height=220&amp;layer=NamedPlace&amp;style=GN.GeographicalNames.Default">`

Direct link generated from Mapbender: [GetLegend example - failed](https://inspire.caris.nl/geoserver/gnwms/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=300&height=220&layer=NamedPlace&style=GN.GeographicalNames.Default)

Working link: [Example Get Legend for INSPIRE](https://inspire.caris.nl/geoserver/gnwms/ows?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image%2Fpng&width=300&height=220&layer=NamedPlace&style=GN.GeographicalNames.Default)

To reporoduce:
1. Add new WMS source: https://inspire.caris.nl/geoserver/gnwms/ows?service=WMS&request=GetCapabilities&version=1.3.0
2. Add the layer to application Demo
3. Open application and activate Legend View - images for legend are not displayed

Solution - force in GetLegend requests to use &version=1.3.0

**Comment by morcom** [comment]
Looks like it is more GeoServer issue as in the Legend link there is no version in GetCapabilities. Closing for now and reviewing with GeoServer settings

**Comment by astroidex** [comment]
Yes ist i more a service problem. Version is missing in the getCapabilities link. When I add Version it works fine.
https://inspire.caris.nl/geoserver/gnwms/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=300&height=220&layer=GN.GeographicalNames&Version=1.3.0
