### ISSUE TITLE
Adding an inscription above an object in the map

### ISSUE THREAD

**Issue by gols1963** [mapbender/mapbender#1431]
How can I add an inscription of one field from FeatureInfo next to the object when opening the map. The data in FeatureInfo is shown only by pressing the FeatureInfo button, and I want to immediately show text from one field on the map.

**Comment by rschwammborn** [comment]
Hello @gols1963 ,

Just a small heads-up that I'm closing this issue (kind of a duplicate) as you already found the correct place for communicating your question in the Mapbender-users mailing list.

Greetings!

**Comment by astroidex** [comment]
- @rschwammborn yes please close the ticket.
See the discussion on the mailing list https://lists.osgeo.org/pipermail/mapbender_users/2022-September/006092.html
