### ISSUE TITLE
Is mapbender-starter-3.3.2-RC1 support php 8.1. i got HTTP ERROR 500 after installing. Thank you.

### ISSUE THREAD

**Issue by YourErik** [mapbender/mapbender#1435]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: [e.g. 3.0.6.3]
 - Database: [e.g. PSQL 9.5.12]

**Screenshots / Logmessage**
If applicable, add screenshots or a logmessage from app/logs to help explain your problem.

**Additional context**

**Comment by astroidex** [comment]
Hi @YourErik Mapbender 3.3.2rc1 and fresh 3.3.2 work with PHP 8.1. Please check your installation.
