### ISSUE TITLE
Mapbender doesn't show Ukrainian translation

### ISSUE THREAD

**Issue by sacredkesha** [mapbender/mapbender#1443]
**Describe the bug**
Mapbender doesn't show Ukrainian translation.

**To Reproduce**
1. Created 11 *.uk.yml files (https://github.com/mapbender/mapbender/pull/1442)
2. Set mapbender locale as "uk"
3. Clear cache 
4. Set browser's language to "uk"
6. See error, Mapbender shows English content

**Expected behavior**
Mapbender has to show Ukrainian language content.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.3.3
 - Browser Opera, Chrome

**Additional context**
Even if i turn off mapbender_autolocale in parameters.yml, Mapbender shows only English language website

**Comment by astroidex** [comment]
@sacredkesha please add the locale to AutomaticLocaleListener.php and try again.

https://github.com/mapbender/mapbender/blob/master/src/Mapbender/FrameworkBundle/EventListener/AutomaticLocaleListener.php#L32

**Comment by sacredkesha** [comment]
I’m extremely grateful for your desire to help but it seems this method does not work for my situation, instead it shows mapbender content only in English, if my browser language set as Ukrainian. 
With other languages it works correctly.

**Comment by astroidex** [comment]
I tried with firefox your translations and it looks like it works (although I can not understand anything)
![settings](https://user-images.githubusercontent.com/996298/214234859-dcba5dcc-12ce-45e2-ba9e-594a092cf36d.png)

**Comment by eSlider** [comment]
* uk - united kingdom
* ua - ukraine

**Comment by Phocacius** [comment]
the ISO-2 **Country** code for Ukraine is UA, however, the ISO-2 **language** code for Ukrainian is UK. It is confusing, but that's the current state. See [https://www.iso.org/obp/ui/#iso:code:3166:UA](https://www.iso.org/obp/ui/#iso:code:3166:UA)

**Comment by astroidex** [comment]
hey @eSlider Nice to see your comment.

**Comment by eSlider** [comment]
@Phocacius, about ISO language codes, just to understand, ISO-2 means two characters and ISO-3 means a character tree.

Here we go again:
* ISO-2: ua 
* ISO-3: ukr

The code for the Ukrainian language is **never** UK! :)

**Comment by eSlider** [comment]
> @eSlider You are right about the 2 and 3 three characters. However, here's a screenshot of the page I linked above: ![grafik](https://user-images.githubusercontent.com/3438255/232730544-28f9ca47-a6e9-475e-8c94-5168f184267c.png)
> 
> And here's the firefox language selection page:
> 
> ![grafik](https://user-images.githubusercontent.com/3438255/232731086-3edc679d-e957-4859-8257-b71afd39119b.png)


Yes of course these are confusing standards, but here is another screenshot from the site you pointed out above

<img width="733" alt="image" src="https://user-images.githubusercontent.com/1188335/233058921-c59cc94a-6bc8-4398-8e7c-47d1ac54d5fa.png">

**Comment by eSlider** [comment]
I confused iso language and country. in the case of language it is uk.
