### ISSUE TITLE
[Layertree] Clarify checkbox function "Hide visibility by folders"

### ISSUE THREAD

**Issue by rschwammborn** [mapbender/mapbender#1445]
**Is your feature request related to a problem? Please describe.**
In Mapbender, the Layertree checkbox name "Hide visibility by folders" is a not-so-clear description of what the actual checkbox can do. (Documentation is not helpful in that scenario either, so a new description name that can be easily referred by Documentation would be nice.)

**Describe the solution you'd like**
Clarify what the feature can do and rename or remove it.

**Additional context**
In German Mapbender the feature is called "Visibility bei Ordnern ausblenden".

**Comment by astroidex** [comment]
- no change in version 3.3.4
- should be solved in next version

**Comment by Phocacius** [comment]
This is a very specific feature but I managed to find out what it does.

Precondition: A layer that has children and is set to toggled, but where "allow toggle" is off:
![grafik](https://github.com/mapbender/mapbender/assets/3438255/dc4079df-e0c7-49b5-8d44-e9b36b370979)

If the checkbox "Hide visibility by folders" is on, the checkbox does not appear at all:

![grafik](https://github.com/mapbender/mapbender/assets/3438255/d3f4c9fc-0aae-4e7c-867b-04f8f2e56613)


If the checkbox is off, the checkbox is visible as disabled:

![grafik](https://github.com/mapbender/mapbender/assets/3438255/2cb9473d-dbf4-43f2-a708-6f0430bdaedb)

**Comment by astroidex** [comment]
Thanks a lot. @rschwammborn will add it to the documentation.

**Comment by rschwammborn** [comment]
@Phocacius and I discussed the meaning of the feature and came to the conclusion to remove the checkbox - and with it, the feature itself - from Mapbender. I'll remove the relevant sentence from the docs.

**Comment by astroidex** [comment]
yes please remove the feature

**Comment by Phocacius** [comment]
checkbox removed in #1543.
For replacement for the functionality see linked PR.
