### ISSUE TITLE
Please help error on prod.log

### ISSUE THREAD

**Issue by YourErik** [mapbender/mapbender#1484]
![Clipboard01](https://github.com/mapbender/mapbender/assets/18585429/f68db354-917c-45bc-b2f2-7a49042efed8)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: [e.g. 3.0.6.3]
 - Database: [e.g. PSQL 9.5.12]

**Screenshots / Logmessage**
If applicable, add screenshots or a logmessage from app/logs to help explain your problem.

**Additional context**

**Comment by YourErik** [comment]
Yes, I installed all the requirements.
![Clipboard01](https://github.com/mapbender/mapbender/assets/18585429/6bd39ce1-39ca-4cf3-bbd9-bb6d4c917df0)
![Clipboard02](https://github.com/mapbender/mapbender/assets/18585429/a496d674-d105-4aae-a594-d6ce4c7788b7)
![Clipboard03](https://github.com/mapbender/mapbender/assets/18585429/78bf3fe3-1115-49a1-ae27-bfdcfe8a2921)

**Comment by YourErik** [comment]
Thanks for the help. :)

Operating System: Ubuntu 22.04
php version: php 8.2.7
Webserver: Apache2

**Comment by YourErik** [comment]
We solve it. I installed PHP 7.4-PGSQL package. Thanks a lot...

**Comment by Phocacius** [comment]
I'm glad it worked!
