### ISSUE TITLE
parameters.yml enhancement

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1498]
There are some ideas to enhance the parameters.yml file

- https://github.com/mapbender/mapbender-starter/blob/master/application/app/config/parameters.yml.dist
- link to documentation https://doc.mapbender.org/en/customization/yaml.html#parameters-yml

1. review the comments

2. block about locale add missing languages. Is it still up to date as locales comes from browser setting

```
    # locale en, de, es, fr, it, nl, pt, ru, tr, uk are available
    fallback_locale:   en
    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

```

3. add branding block

```
# Define your own branding parameters - could look like
    branding.project_name: Geoportal powered by Mapbender
    branding.logo: ./bundles/mapbendercore/image/OSGeo_project.png

# Definition for the Login-Landscape-Image
    branding.login_backdrop: ./bundles/mapbendercore/image/login-backdrop.jpg
```   

4.     mapbender.disabled_elements:
- which element should be discabled?
- please enable  - Mapbender\DataManagerBundle\Element\DataManager

5. is somthing missing in parameters.yml?

**Comment by Phocacius** [comment]
fixed in https://github.com/mapbender/mapbender-starter/pull/117
