### ISSUE TITLE
[Layertree]  Smartphone usage with Chrome or Opera: you can not de/activate layer in the layertree.

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1506]
**Describe the bug**
If you use a Mapbender application (Version 3.3.5) on a Smartphone with Chrome or Opera you can not aktivate/deactivate layer in the layertree.
Everything is fine with firefox.
No problems with older Mapbender Versions
- see  3.3.5 auf https://demo.mapbender.org/application/mapbender_user_yml

**Expected behavior**
Layer handling should work with all browsers

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.3.5
 - Browser Chrome / Opera

**Additional context**
Maybe the error is connected to the changes via PR https://github.com/mapbender/mapbender/pull/1457

**Comment by rschwammborn** [comment]
Hello @astroidex ,
we just tested this and could not reproduce the checkbox behavior (Chrome on iOS). Feel free to reopen this if the issue does still persist, maybe with more details concerning the device and operating system used.

**Comment by astroidex** [comment]
Please note that the issue occurs on for example on Google Pixel 4a & 6. So I reopen the ticket.

**Comment by astroidex** [comment]
Error still occurs on with Chrome. I could reproduce it with version 4.0. Should be solved in Verison 4.0

**Comment by Phocacius** [comment]
Fix will be available in the 4.0 release.

Temporary fix for older versions: Replace the file `application/mapbender/src/Mapbender/CoreBundle/Resources/public/jquery-ui-touch-punch/jquery.ui.touch-punch.js` with the contents of this file: https://github.com/RWAP/jquery-ui-touch-punch/blob/master/jquery.ui.touch-punch.js
