### ISSUE TITLE
[digitizer] when you delete a digitizer object via form you can not create a new object afterwards

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1514]
**Describe the bug**
When you delete a digitizer object via form you can not create a new object afterwards as the buttons are blocked.

**To Reproduce**
1. Go to you digitize application
2. Open the for of an existing object
3. See: the toolbar buttons are deactivated when a form is opened
4. Delete the object
5. See error: the toolbar buttons are still deactivated

see also https://github.com/mapbender/data-manager/blob/2.0.7/README.md#configuring-tabular-item-listing

**Expected behavior**
After deleting an object the toolbar buttons should be active again

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.3.5

**Screenshots / Logmessage**
![digitizer_delete_object](https://github.com/mapbender/mapbender/assets/996298/f6d1bd8a-767f-4d16-aeb9-bbe5c000d2d1)

**Comment by frwg** [comment]
3. See: the toolbar buttons are deactivated when a form is opened - currently (10620b7053e5c21fe8fd7e0da7b86f4fd654f6d3), the toolbar buttons don't get deactivated when a form is opened
