### ISSUE TITLE
[Layertree] - metadata dialog horizontal scrollbar is missing 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1532]
**Describe the bug**
In the metadata dialog the horizontal scrollbar is missing. This occurs in the mobile application but also in the "normal" application.

**To Reproduce**
1. open the mobile application
2. go to the layertree menu and open the metadata dialog
3. If necessary reduce the size so not all the text is visible

**Expected behavior**
if the dialog is to small a horizontal and vertical scroll bar should show up

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.3.5, 4.0dev
 - Browser chromium, firefox

**Screenshots / Logmessage**
![mb_metadata_missing_scrollbar](https://github.com/mapbender/mapbender/assets/996298/722a0e77-5eed-47b7-a9b3-1ef60183f532)

**Comment by Phocacius** [comment]
Fixed in #1541
