### ISSUE TITLE
"500 Internal Server Error". when exporting image

### ISSUE THREAD

**Issue by YourErik** [mapbender/mapbender#1545]
**Describe the bug**
"500 Internal Server Error". when exporting image. The GD extension was loaded already when run app/console/config/ however when i run the php gd script it will tell the gd not even installed 

**Screenshots / Logmessage**
![Screenshot 2024-02-13 095619](https://github.com/mapbender/mapbender/assets/18585429/15ea6023-b1b0-4e3b-b50a-ce3def67f760)

**Comment by Phocacius** [comment]
Hi @YourErik,

sorry for the late response. The error message suggests that you're missing some php extensions, at least GD image and intl that are not installed for the PHP version you're using. Depending on your operating system and php version you can install it using e.g.

```bash
sudo apt-get install php8.3-gd php8.3-intl
```
Refer to the [Mapbender starter's Readme file](https://github.com/mapbender/mapbender-starter/?tab=readme-ov-file#requirements) for an overview of the required php modules.
