### ISSUE TITLE
"500 Internal Server Error" when encountering a network error during printing

### ISSUE THREAD

**Issue by enno-t** [mapbender/mapbender#1549]
**Describe the bug**
If mapbender is setup behind a proxy and a remote WMS-Layer is active (e.g. the OSM Demo layer from mapbender_user) printing fails with a 500 Error. Mapbender tries to get the remote resource as an image, but it does not check if it succeeded. 

In '[src/Mapbender/PrintBundle/Component/Transport/ImageTransport.php](https://github.com/mapbender/mapbender/blob/fe5fa11ef0e2646becd47ee90c47a58076c1d3f2/src/Mapbender/PrintBundle/Component/Transport/ImageTransport.php#L38)' between line 38 and 39 there should be a check like : 
```php
if ($image == false) {
      /*
       * emit_log("failed to create image from remote resource at $url");
       */
      return null;
}
```

(Note: a check like that was removed with "[701e88a:  Update print image download error handling (nothing rows \RuntimeException)](https://github.com/mapbender/mapbender/commit/701e88aaba3d09fd6ef34b4a8738488c2e221db6)"

With this fix applied the 500 Error is fixed, but the resulting PDF file contains only the pdf-template.

**To Reproduce**
1. Setup mapbender and don't allow the server to contact the internet
2. Try to print one of the demo apps
3. Observe either a 500 error or an empty PDF (aside from the template)

**Expected behavior**
Either a correct PDF or an error that mapbender could not fetch a remote resource.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.3.5
 - Database: postgres-15.6
 - Browser: Not relevant

**Comment by astroidex** [comment]
It looks like your server can not get the image from the remote server. Please note that the print is done by the server. So the server has to be able to get the image from the remote WMS.

You have to check your paramters.yml file and configure the proxy settings.
https://doc.mapbender.org/de/customization/yaml.html#proxy-einstellungen

**Comment by enno-t** [comment]
Hey thanks for the quick reply.

> It looks like your server can not get the image from the remote server. Please note that the print is done by the server. So the server has to be able to get the image from the remote WMS.

Correct, but this issue is not abut the server not being able to fetch the remote resource. Mapbender does not check ***if*** the fetching was successful which leads to a '500 Internal Server Error' with a line in the log noting that imagesavealpha()'s first argument must be a GdImage and not a bool. In other words, $image in ImageTransport.php can be an invalid input to imagesavealpha() (if imagecreatefromstring() fails).

**Comment by Phocacius** [comment]
Hi @enno-t, thanks for the bug report, we can reproduce the behaviour. If you have the ability to provide a fix, we're happy to accept pull requests, otherwise we'll approach this bug for a feature release.

**Comment by enno-t** [comment]
Hey, thanks for the reply.

> Hi @enno-t, thanks for the bug report, we can reproduce the behaviour. If you have the ability to provide a fix, we're happy to accept pull requests, otherwise we'll approach this bug for a feature release.

Since I've yet to figure out how mapbender actually logs stuff I can not provide a proper patch for this.

**Comment by enno-t** [comment]
> If you want to know how to log something: Inject `\Psr\Log\LoggerInterface` into your class and use `LoggerInterface::warning` / `LoggerInterface::error` to emit a log.

Thanks, that's what I needed to know :)

I've got the following patch (adding here so I can test it once I've got access to the working instance again):

```
diff --git a/src/Mapbender/PrintBundle/Component/Transport/ImageTransport.php b/src/Mapbender/PrintBundle/Component/Transport/ImageTransport.php
index 67d8001cb..5e3f87d81 100644
--- a/src/Mapbender/PrintBundle/Component/Transport/ImageTransport.php
+++ b/src/Mapbender/PrintBundle/Component/Transport/ImageTransport.php
@@ -3,7 +3,7 @@
 
 namespace Mapbender\PrintBundle\Component\Transport;
 
-
+use Psr\Log\LoggerInterface;
 use Mapbender\Component\Transport\HttpTransportInterface;
 use Mapbender\PrintBundle\Util\GdUtil;
 
@@ -36,6 +36,16 @@ class ImageTransport
         try {
             $response = $this->baseTransport->getUrl($url);
             $image = imagecreatefromstring($response->getContent());
+            if ($image == null) {
+                /*
+                 * If $image is null, the download probably failed, most likely
+                 * because of network issues or restrictions (like a HTTP proxy).
+                 *
+                 * See #1549
+                 */
+                LoggerInterface::warning('Could not download image from url {$url}.');
+                return null;
+            }
             imagesavealpha($image, true);
             if ($opacity <= (1.0 - 1 / 127)) {
                 $multipliedImage = GdUtil::multiplyAlpha($image, $opacity);

```

If everything works, I'll create a pull request.

Should I only create one for -develop or also for -master?
