### ISSUE TITLE
Layertree text does not adjust

### ISSUE THREAD

**Issue by JensC2506** [mapbender/mapbender#1586]
In Mapbender 4.0 beta, the text does not adjust when the window in the layer tree is dragged smaller or larger. He also marks the scale on the right side.

Video:
https://streamable.com/ycv568

**Comment by astroidex** [comment]
HI @JensC2506 the video is not availbale anymore. Can you make anotherone or a screenshot?

**Comment by JensC2506** [comment]
Hi @astroidex 

Here it is: https://streamable.com/mehfj3

**Comment by astroidex** [comment]
Hello @JensC2506,
-  I can not reproduce the marks of the scale objects. Which browser do you use?
- at the moment the text in the sidepane is only hided, no linebreak. We thought it is ok like that.

Screenshot from the video showing the blue marked scale objects
![Uploading sidepane_slider.png…]()
