### ISSUE TITLE
[File Upload] GPX and KML uploads fails on OS X 

### ISSUE THREAD

**Issue by Phocacius** [mapbender/mapbender#1603]
**Describe the bug**
In the file uploading element, the upload fails showing the message "Unsupported file type:" when trying to upload a gpx or kml (maybe also other types) on Mac OS X or iOS

**To Reproduce**
- Use a macbook/imac or iphone (any browser)
- Add a File Upload element to your application
- Upload any .gpx or .kml file to the "upload" element (e.g. from [here](https://www.radroutenplaner-deutschland.de/veraDaten_EN.asp))

**Expected behavior**
The file is uploaded and shown on the map

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 4.0.0
 - Database: n.a.
 - tested on Firefox and Chrome, but probably any on OS X

**Additional Context:**
The upload element uses the JavaScript `File` API. To determine which data type was uploaded, `File.type` is used. The mdn docs state ([source](https://developer.mozilla.org/en-US/docs/Web/API/Blob/type)): 

``` 
blob.type is generally reliable only for common file types like images, HTML documents, audio and video. 
Uncommon file extensions would return an empty string
```

An alternative way of determining the file type needs to be found.

**Comment by PhilVanB** [comment]
gpx files from https://www.radroutenplaner-deutschland.de/veraDaten_EN.asp don't work either on Windows with chrome browser
