### ISSUE TITLE
new application with map-Element does not show WMS but NaN

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1605]
**Describe the bug**
When you create an application from scretch. Add map-element, cretae layerset and add wms the wms is not displayed.

**To Reproduce**
1. create empty application from fullscreen
2. add layerset with WMS
4. add map (keep settings)
5. See error when you open the application no wms is displayed
https://schulung.foss.academy/mapbender/application/aa_leer

**Expected behavior**should show map

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 4.0.0

**Comment by Phocacius** [comment]
fixed by #1612
