### ISSUE TITLE
max_extent EPSG:25832 can not be set for whole Germany

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1629]
**Describe the bug**
I would like to make a map for Bonn with the possibility to zoom to max extent of Germany using EPSG 25832.
This is not possible in 4.0.1

**Comment by Phocacius** [comment]
Can you please add an export of a demo application? I can't see a problem on my installation.

**Comment by astroidex** [comment]
yes. No problem. I added an applictaion. It is mapbender-demo  changed to 25832 
with start Bonn and Max. Extent set to BRD Extent 

[mapbender_user_db_25832_brd.json](https://github.com/user-attachments/files/17097833/mapbender_user_db_25832_brd.json)

**Comment by astroidex** [comment]
Looks like the max_extent was to small to the west and east. I extened the extent and now it works fine.

So we can close the ticket.
