### ISSUE TITLE
[Bug][map] min x configuration with negative values > -100 fails NaN

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1642]
**Describe the bug**
see https://lists.osgeo.org/pipermail/mapbender_users/2024-October/006423.html

**To Reproduce**

EPSG: 4326

works fine with 
-180 -90 125 85
-100 -74  -5 1.5

Looks like we have a problem when min x (for initial extent) is bigger then -100 (for example -99)

but fails with minx (initial) > -100

**Comment by swinkelmann** [comment]
The values of the start extent are passed to the model as strings.
Openlayers checks if the extent array is valid. This is the corresponding function:
```
function isEmpty(extent) {
    return extent[2] < extent[0] || extent[3] < extent[1];
  }
```
This fails in many cases.
Javascript shows a strange behavior when strings are compared with < and >

'1' < '-100' = false
'-1' < '-100' = true
'-5' < '-85' = true
'-5' < '-100' = false
...

However, it works fine if the values are numeric.
I have added a 'parseFloat' to the create function of the map element:
https://github.com/mapbender/mapbender/pull/1645

**Comment by astroidex** [comment]
- tested with Buenos Aires and max Extent South America
- works fine. Thanks a lot for fixing

see the parameters I used

![extent](https://github.com/user-attachments/assets/fcf8d412-bbd9-43e0-af31-cc8708d7b6ef)
