### ISSUE TITLE
SearchRouter Backend admin - validate timeoutfactor

### ISSUE THREAD

**Issue by cwygoda** [mapbender/mapbender#197]
As of now, anything can be entered for timeoutFactor, but only positive integers shall be allowed

**Comment by AxxL** [comment]
Let's fix this issue.

**Comment by LazerTiberius** [comment]
To fix this we should use Symfonys Validation Constraints. With the Assert/Callback Annotation, we can check single properties of the configuration. Maybe we should also consider implementing a generic validation stub in the Element Entity.
http://symfony.com/doc/current/reference/constraints.html
http://symfony.com/doc/2.8/reference/constraints/Callback.html

**Comment by eSlider** [comment]
@LazerTiberius, you right! It's better, if we use symfony annotation validation. 
I like simple annotation approach: http://symfony.com/doc/2.8/validation.html#using-the-validator-service

**Comment by AxxL** [comment]
@LazerTiberius ping. pong?

**Comment by LazerTiberius** [comment]
Still in  the pipe but I didn´t have any time to work on it

**Comment by AxxL** [comment]
Documentation and Requirements in #519

**Comment by AxxL** [comment]
Wontfix because of Symfony.
