### ISSUE TITLE
Sketch: define an extra label for description

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#202]
*FOR DISCUSSION: add a row to define an explanation text. 

The explanation text could be: "Please click in the map an enter a radius for the circle in your map units" --> or "Radius in Meters"

The text must be different for different sketches.

Please discuss first before you work on a solution

**Comment by AxxL** [comment]
I close this issue since it is outdated. If this requirement is still relevant, feel free to (re)open again.
