### ISSUE TITLE
Login window nested in edit-element window

### ISSUE THREAD

**Issue by hr61369256** [mapbender/mapbender#211]
After lunch break I tried to edit an element within an open mapbender session and got the attached reaction/screen.
![2014-03-31_mberr](https://cloud.githubusercontent.com/assets/6905055/2567736/109f01fa-b8d9-11e3-92a2-0f534812e029.png)

**Comment by eSlider** [comment]
If session time is out, the login screen loads on the top. Fixed in  [495c13435014e25d8baa6ac3711ec2b93c1d87e4](https://github.com/mapbender/fom/commit/495c13435014e25d8baa6ac3711ec2b93c1d87e)
