### ISSUE TITLE
ssl certificate problem with image export

### ISSUE THREAD

**Issue by hr61369256** [mapbender/mapbender#215]
On a ssl http server: After choosing a format (png or jpg does not matter) the following screen shows up (see attachement): "SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed"
![2014-04-07_mberr004](https://cloud.githubusercontent.com/assets/6905055/2634383/e6dbaf48-be79-11e3-9b6b-f47f1ddc93e9.jpg)

**Comment by hwbllmnn** [comment]
That's probably a problem with your certificate. If you have a proper certificate, you should check whether your PHP/curl installation is working properly, for a quick check whether that's the case see here: http://www.nextscripts.com/tutorials/how-to-check-if-curlssl-is-working-properly/
