### ISSUE TITLE
Level curve (new feature/element)

### ISSUE THREAD

**Issue by hr61369256** [mapbender/mapbender#217]
A new element, for displaying a level curve would be very helpful. Some ideas to this: user sould draw a line or polyline on a map and the level curve shows up in a diagramm, within an own panel (similar to other element functions); moving the cursor along this line/polyline will display the equivalen height position within the diagramm.

**Comment by AxxL** [comment]
I close this issue since it is outdated. If this requirement is still relevant, feel free to (re)open again.
