### ISSUE TITLE
Frontend: Layertree shows layers in reversed order than backend

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#237]
Steps to reproduce: Load  a WMS with more than one layer. Check the layer order in the backend (layerset instance). Open the application. Check the layer order of this WMS in the layertree. It's reversed.

Layertree should honor the order of the backend.

WMS Specification says that "a WMS shall render the requested layers by drawing the leftmost in the list bottommost, the next one over that, and so on.". The layertree can honor that in its order: Bottommost: Left. Over that: right of that.

**Comment by hwbllmnn** [comment]
Is this still an issue? I seem to remember we fixed something like this for 3.0.5.0.

**Comment by eSlider** [comment]
I can agree, that this is fixed.
