### ISSUE TITLE
Two layertrees: One doesn't react to events

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#239]
The standard application of Mapbender3 contains 2 Layertrees. One in the sidepane, the other that you can open via the toolbar. It's probably a rare usecase that an application needs a configuration like this, but whatever...

If both Layertrees are opened, the one in the sidepane reacts correctly on the load-events of the map (the spinning circle icon appears). The one opened by the toolbar-button doesn't react. The spinning circle icon is always visible.

So: One layertree reacts on the events, one doesn't.

Mapbender 3.0.3.1

**Comment by hwbllmnn** [comment]
Fixed for release 3.0.5.1.
