### ISSUE TITLE
Adding specific source [giswebservice.massgis] leads to serious problems

### ISSUE THREAD

**Issue by hr61369256** [mapbender/mapbender#243]
1st: Adding this wms service (http://giswebservices.massgis.state.ma.us/geoserver/wms?request=getCapabilities&version=1.1.0&service=wms) as new source leads to a blank page with nothing on it. But if you press the browser back button, you see the new source in the source list.
2nd: It is not possible to open the source (for getting info about layers, bounding box a.s.o.). Instead of a open source you get a blank page again.
3rd: Delition of this source is not possible. It takes long time until the reaction (blank page, what else) appears.

**Comment by hwbllmnn** [comment]
Fixed for 3.0.5.1
