### ISSUE TITLE
Search Router - Templates crashes with quotes

### ISSUE THREAD

**Issue by mbissue** [mapbender/mapbender#246]
When using quotation marks for table names with large letters in the search router configuration, crashes the template. Doctrine even supports quotes for escaping.

Here an example:
The Problem exists mainly by the parameter "form":
 
class: Mapbender\CoreBundle\Component\SQLSearchEngine
class_options:
    connection: search_db
    relation: relation.relation
    attributes:
        - '"Variante"'
    geometry_attribute: geom
form:
    '"Variante"':
        type: text
        options:...
        ....

Crashes with the folling message:
"An exception has been thrown during the rendering of a template ("The name ""Variante"" contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"), hyphens ("-") and colons (":").") in MapbenderCoreBundle:Element:search_router.html.twig at line 5."

"CRITICAL - Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The name ""Variante"" contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"), hyphens ("-") and colons (":").") in "MapbenderCoreBundle:Element:search_router.html.twig" at line 5. (uncaught exception) at /home/geop/mapbender3/app/cache/dev/classes.php line 9747"

Mapbender 3.0.3.2

**Comment by astroidex** [comment]
* will be fixed in Mapbender3 3.0.5.2

Define columns with upper case like this "Variante" and it will work

**Comment by Urbai** [comment]
Hello, 
Is Mapbender3 really compatible with postgresql?
Or is the Mapbender3 version compatible with postgresql 9.5? because the version of postgres I'm currently using.
