### ISSUE TITLE
Line Comments in JavaScript in FeatureInfo Templates lead to misfunctioning JavaScript

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#253]
Some UMN WMS allow JavaScript in FeatureInfo Templates. It's a common feature to fill the content of the FeatureInfo depending on the value of the unique feature.

```javascript
<script type="text/javascript">
 var the_type =  "[TYPE]";
 // comment
 if (the_type == "9") {
    document.getElementById("mytype").innerHTML = "Yes";
  } else  {
    document.getElementById("mytype").innerHTML = "No";
}
</script>
```

If there is a line comment like above, Mapbender3 cannot perform the Script itself, because the JavaScript code is placed in one line. Everything after the comment delimiter (`//`) is therefore ignored, because it is interpreted as a comma. A workaround is to place the Comment in block-comment delimiters (`/**/`). Because we cannot assure, that everybody is using block-comments, the javascript code in Mapbender has to be placed in several lines.

It's part of the function _featureInfoCallback

```javascript
_featureInfoCallback: function(data, jqXHR){
[...]
    .replace(/\n/g, '')
```

**Comment by hwbllmnn** [comment]
Can you prepare a demo WMS so I can test the issue? The code isn't exactly as it was, so perhaps the bug is already fixed.

**Comment by AxxL** [comment]
Is fixed.
