### ISSUE TITLE
Backend: File prefix name is meisleading - it should be named File name

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#262]
- File prefix name is misleading - it should be named _File name_ as the download file will use the name defined here and will not add .pdf automatically
- File prefix: could be Mapbender_print.pdf

**Comment by hwbllmnn** [comment]
Is this issue still up to date? It seems the file prefix is indeed a prefix nowadays.

**Comment by AxxL** [comment]
I close this issue since it is outdated. If this requirement is still relevant, feel free to (re)open again.
