### ISSUE TITLE
Frontend: SearchRouter reset deletes only the results of the last search in the map

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#263]
- you can do more then one search after each other. The search results are displayed in the map. But the older search results are still displayed.
- when you use reset not all result marker in the map are deleted - only the marke from the last search result are deleted

solution
- reset the results in the map after every search, like it is done in the result list
- reset all results in the map on click on button reset

**Comment by arsgeografica** [comment]
Is this still a problem. Assigning astroidex for followup.

**Comment by AxxL** [comment]
I close this issue since it is outdated. If this requirement is still relevant, feel free to (re)open again.
