### ISSUE TITLE
this.Mapbender.Model.getCurrentProj() doesn't get CurrentProj

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#270]
Steps to reproduce:
Open any mapbender app. Type in JS-Console: this.Mapbender.Model.getCurrentProj();
Change SRS. Type in JS-Console: this.Mapbender.Model.getCurrentProj();
The currentProj should reflect the changed SRS.

**Comment by eSlider** [comment]
@AxxL, do get  SRS without ```this```
```javascript
Mapbender.Model.getCurrentProj() 
```
