### ISSUE TITLE
OpenLayers 3

### ISSUE THREAD

**Issue by ximex** [mapbender/mapbender#272]
Upgrade to OpenLayers 3

**Comment by AxxL** [comment]
We have that in mind. An experimental map component exists here: https://github.com/mapbender/mapbender-map-ol3

**Comment by AxxL** [comment]
Right now we are in direct concept-phase of this and are considering OL4 for the next map-api.

I close the issue here since it is outdated and create a new one, to clean this issue list here a bit.
