### ISSUE TITLE
Add a Free Scale input Box to Mapbender3

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#300]
At the Moment an admin defines per csv list the possible Map Scale values.
The MB3 user cannot zoom to an specific(own) scale in the application.

A free scale Input box would be nice for MB3 like the module in MB2. 
See:
http://www.mapbender.org/ScaleText

It would be nice if the feature could be enhanced to the printFrame too .

**Comment by ruhri** [comment]
Nice idea, but this should be configurable by the admin; we're using WMS in TileMode with FileCaching and free scales would totally mess up our cache.

**Comment by AxxL** [comment]
@ruhri That is correct. Cached Services like WMTS or TMS and WMS in tile mode put additional requirements into this function. Consequence would be that the images from the cached services are interpolated. And you can choose to put this element into your app (or not).
