### ISSUE TITLE
Make MB3 Layersets more flexible

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#301]
At the moment you can create Layersets for an Application.
The configuration of these Sets can be very  complex.
It is not possible to copy this configuration to another application

I would like to see the Layerset configuration at a central point in The Mapbender Administration.
You could then assign a layerset configuration(non-redundant) to one or many Application.

**Comment by AxxL** [comment]
In concept- and estimation phase. I'll leave this ticket open and see if we fill it up with the specification and concept or create a new one.

**Comment by AxxL** [comment]
The concept of this is publicly available at: https://github.com/mapbender/mapbender/wiki/reusable_layerinstances

**Comment by AxxL** [comment]
I made a project in Github, let's see how that works.
https://github.com/mapbender/mapbender/projects/2

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
