### ISSUE TITLE
Add a WMS from the Mapbender Repository

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#302]
At the moment MB3 offers an WMS-Loader where user can add a WMS by link.
see:
http://doc.mapbender3.org/en/bundles/Mapbender/WmsBundle/elements/wms_loader.html
Mapbender may got a lot of WMS registred in it's repository.
But a user got no acess to the repository because the Mapbender permission system is not build (so far) for Layersets. 
I would be good if Mapbender offers a Module like the addWmsFromFilteredListAjax Module in Mapbender2 .
see:
http://www.mapbender.org/Add_WMS_from_filtered_list_%28AJAX%29

**Comment by marmancs** [comment]
maybe see this enhancement in context.
https://github.com/mapbender/mapbender/issues/301

**Comment by ruhri** [comment]
please contact me...
