### ISSUE TITLE
Mobile Template WMS Themes cannot be activated

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#304]
In the new Mobile Template in MB 3.0.5 you cannot activate a theme layer if the layer is deactivated by default.
Steps to reproduce.
1. Log in to Mapbender as root
2. Edit Mobile Template
3. Go to Layersets.
4. Edit the Wms Service Mapbender_user
5.Set the check boxes like in the image below
![mapb](https://cloud.githubusercontent.com/assets/984349/8856155/4ab2171a-3169-11e5-8380-e07f4341fb10.png)
6. Open the Mobile Template(application)
7. Try to activate Mapbender User in app

**Comment by astroidex** [comment]
* You have to activate the layer f.e user, that you want to see if the Service is active
* root-layer (Mapbender user) can be off
* set checkbox isbasesource to off

With this configuration the service will show up in the mobile Layertree which handles whole services
* when you switch the service on, all the layer that are active will be displayed

* read more about the configuration soon at http://doc.mapbender3.org/en/book/mapbender_templates.html#mobile-template

**Comment by marmancs** [comment]
this works,
thanks for the reply.
