### ISSUE TITLE
Missing assets in Mapbender Templates

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#306]
In Mapbender  3.0.5.0 we should provide working Templates.
If creating a new application from scratch.

* Fullscreen
* Mapbender Mobile Template

works fine. 

But all the other templates doesn't work:
* Classic template
* fullscreen alternative
* Regional
* Resposive

firebug throws an error (missing assets)

**Comment by astroidex** [comment]
You are right. We should fix this in the bug fixrelease 3.0.5.1

**Comment by kellertomy** [comment]
Fixed templates:
* Classic template
* Fullscreen alternative
* Responsive

Regional: We have to discuss what will happen with this template. It is not working at the moment.
