### ISSUE TITLE
some missing german translations

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#307]
There are some elements in Mapbender Manager that hasn't been translated to german yet.
See Screenshots below:
![new_group](https://cloud.githubusercontent.com/assets/984349/8870180/14ce8f7e-31ec-11e5-813c-8d914a7a43a2.png)
![username](https://cloud.githubusercontent.com/assets/984349/8870184/1893471c-31ec-11e5-9aa8-d221430e4cb4.png)
![user_2](https://cloud.githubusercontent.com/assets/984349/8870186/1b31a266-31ec-11e5-98fd-b41f2ad8d547.png)
![forrmat](https://cloud.githubusercontent.com/assets/984349/8870187/1d9fe68e-31ec-11e5-8e03-d9b9426fc803.png)
![application](https://cloud.githubusercontent.com/assets/984349/8870223/7f5d1892-31ec-11e5-8d3c-7ff69c0418d0.png)

**Comment by marmancs** [comment]
The digitize-Module hasn't been translated yet.

**Comment by dikey** [comment]
Some missing  german translations are done!
These changes will be available in new release.

**Comment by hwbllmnn** [comment]
PR has been merged.
