### ISSUE TITLE
Future of regional template

### ISSUE THREAD

**Issue by kellertomy** [mapbender/mapbender#310]
Regional: We have to discuss what will happen with this template. It is not working at the moment.

**Comment by marmancs** [comment]
I think it would be nice to got a 4 Region Template

Left-Siedepane
Right Sidepane
Header
Footer
and the Map Content 

It would also be good if the Map(frame) is not (visible) behind that regions.
So Mapserver would produce smaller Maps.
Maybe see like this (for example):
http://geoportal.wuppertal.de/deegree/invoke.jsp?wmc=wmc_STADTPLANGRUPPE

**Comment by astroidex** [comment]
* you could create it and make a pull request
* it would be nice to be able to hide the regions left and right sidepane
* but for the beginning a template with fixed  left and right sidepane would be fine

**Comment by marmancs** [comment]
Hi Astrid,

i created a new Template and defined a few Regions (in my Template.php).
see this:


public static function getRegions()
    {
  //      return array('toolbar', 'sidepane', 'content', 'footer');
        return array('toolbar', 'rechts', 'links','content', 'footer');
}

The Region's are now visible under:
application/myNewApplication/edit
I can add Elements and Configure them.
But i cannot delete Elements in the Administration. 
Did i miss Something to configure??
Or is it a bug?
Maybe see this ticket in Contex.
https://github.com/mapbender/mapbender/issues/324

**Comment by astroidex** [comment]
* was deleted for this version
