### ISSUE TITLE
Missing icons in Mobile-Template

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#311]
The Mobile-Template is just working with the font-awesome icons.
If you choose another icon (f.e. Layer themes) see:
![icon](https://cloud.githubusercontent.com/assets/984349/8874125/02c2faa0-320e-11e5-84da-c73ba79bb684.png)
 The application image is broken. see:
![layertree_mobile-template](https://cloud.githubusercontent.com/assets/984349/8874135/28e56ac4-320e-11e5-8e62-11a183e47074.png)

**Comment by AxxL** [comment]
Right now the mobile template works only with the FontAwesome Styles. We take a look if that is intended.

**Comment by astroidex** [comment]
* tested. it works
* fixed
