### ISSUE TITLE
Add new feature (digitizer)

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#314]
I tried to add a new feature(polygon) in the new digitize module.
see:
![neues_feature](https://cloud.githubusercontent.com/assets/984349/8907507/b3dd1806-3476-11e5-878f-eaa85d24273d.png)

After saving the dialog everything seems to be Okay.
![neues_feature_speichern](https://cloud.githubusercontent.com/assets/984349/8907509/b7d5c3d6-3476-11e5-89f9-e3f637cae04b.png)

The feature stays in Mapbender Map but nothing happens at the database.
(And no error Message at the Postgres log)

Modifying an existing feature works fine.

**Comment by astroidex** [comment]
Hi Marc,

we are working on new funtionality for digitizer and bugfixes.

Please try the branch: https://github.com/mapbender/mapbender-starter/tree/feature/digitizer

And have a look at the documentation at: https://github.com/mapbender/mapbender-documentation/blob/feature/digitizer/en/bundles/Mapbender/CoreBundle/elements/digitizer.rst

Lot of yery cool features are on the way ;)

**Comment by marmancs** [comment]
I will try to install from branch the next few days. 
Will give some feedback then.

**Comment by astroidex** [comment]
cool. Thank you.

**Comment by ruhri** [comment]
IMHO its a bug:
my experience: the feature will only be persisted to the DB after opening and closing the belonging formular...
example: you edit an existing feature-geometry, open the form, closethe  form without changes, now the feature will be written to the DB...

**Comment by astroidex** [comment]
Save polygon shoul work in the up to date version 3.0.5.1:
* http://release.mapbender3.org/application/mapbender_digitize_demo

@ruhri: the object will only be updated in the db on save. Normally opening and closing of the form shoul dnot save the object. See 3.0.5.1: http://release.mapbender3.org/application/mapbender_digitize_demo

**Comment by marmancs** [comment]
Tested it in MB 3.0.5.1 and worked fine for me.

**Comment by astroidex** [comment]
Thanx @marmancs for testing
