### ISSUE TITLE
copy application 3.0.4.1 to 3.0.5.0: some information is not copied to the new application

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#319]
If you have an existing Mapbender3 application and you udate to 3.0.5.0 you have problems when you copy an application taht was created with version 3.0.4.x.

Some information is not copied to the new application:

•	BaseSourceSwitcher (Target und die Angaben der Instancesets) 
•	Layertree (Target)
•	Overview (Target und ausgewählte Layerset nicht aktiviert)
•	Map (ausgewählte Layerset nicht aktiviert)

**Comment by eSlider** [comment]
Fixed by @psch (internal id: 3952)
