### ISSUE TITLE
BaseSourceSwitcher - More than one source active at the beginning

### ISSUE THREAD

**Issue by sportsfan15** [mapbender/mapbender#322]
Hello!
I think there is a bug with regard to BaseSourceSwitcher.
When starting an application two background sources are active like shown in the screenshot below.

![basesourceswitcher_haltestellen](https://cloud.githubusercontent.com/assets/13622529/9035889/5e97a0bc-39dc-11e5-8c2b-46efe5a4b6b7.png)

There should only be "Stadtplan (grau)" active, which is one source of the group "Stadtplan (grau / farbig)". In addition the source "Luftbilder 2013" (group "Orthophotos") is also active. After switching to "Deutsche Grundkarte" for example, no more source is acitve besides this map and the BaseSourceSwitcher works like described in the Documentation:
http://doc.mapbender3.org/en/bundles/Mapbender/CoreBundle/elements/basesourceswitcher.html

The parent layer of "Luftbilder 2013" is disabled in the WMS configuration like shown below.
I think this is the correct choice, right?

![basesourceswitcher_haltestellen_dop2013](https://cloud.githubusercontent.com/assets/13622529/9036152/ef455ad0-39de-11e5-90c7-5e04e3b1ded7.png)

Regards
Moritz

**Comment by hwbllmnn** [comment]
How did you configure the base source switcher? Are the instances all base sources? I can not reproduce the behaviour with 3.0.5.0 or the current release branch.

**Comment by marmancs** [comment]
All the Instances are Basesources. To reproduce the error you have to create two different layerGroups in the basesourceswitcher.
Maybe see this live example. 
http://geoportal.remscheid.de/mapbender305/application/haltestellen

**Comment by ruhri** [comment]
I can confirm this bug.
See: luftbilder.geoportal.ruhr
Two baseSource-Elements, one of them is a group (Luftbilder)

If you have just single (non-grouped) baseSources, there is a workaround.
In layerset choose the specific base-source-instance and do the following settings at the  root-layer in the "choosen"-section ("ausgewählt"-Spalte): set "allowed:true", but "enabled:false" (ausgewählt: Haken, an: kein Haken)
This workaround doesn't work grouped baseSources.

**Comment by astroidex** [comment]
* I can reproduce the bug
* have a look at http://release.mapbender3.org/manager/application/Geoportal_BaseSourceSwitcher

**Comment by psch** [comment]
Fixed.
Only the first bss-position is activated by start.

**Comment by astroidex** [comment]
* merged to release/3.0.5 https://github.com/mapbender/mapbender/pull/356
* fixed
