### ISSUE TITLE
TileBuffer And BboxBuffer

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#323]
in layerset configuration you can set the 2 options.
But in Version 3.0.5 nothing happens in the application if you change the value.
The Tilebuffer is seems to be (always) at 5 and you cannot set the Bbox-Faxtor to 0 too.
This produces a lot of traffic at the WMS Server.

**Comment by AxxL** [comment]
Confirmed and fixed in hotfix branches.

**Comment by hwbllmnn** [comment]
Has this been fixed in a merged PR? If so, please close.

**Comment by AxxL** [comment]
Merged from branch hotfix/wms-ratio-buffer and hotfix/add-source.
