### ISSUE TITLE
Nicer transition effects for tiled Layers

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#327]
In Openlayers you can use some nicer transition-effects by using a few simple css3 statements.
see:
http://dev.openlayers.org/apidocs/files/OpenLayers/Layer/Grid-js.html#OpenLayers.Layer.Grid.removeBackBufferDelay

you can test it by adding following lines to the css-editor:

.olLayerGrid .olTileImage {
    -webkit-transition: opacity 0.2s linear;
    -moz-transition: opacity 0.2s linear;
    -o-transition: opacity 0.2s linear;
    transition: opacity 0.2s linear;
 }

Maybe we could add this in a default-css 
or give a hint at Mapbender-documentation.
What do you mean?

**Comment by ruhri** [comment]
THX :+1:

**Comment by AxxL** [comment]
We don't want to put that into the bugfix releases for 3.0.5.x. Therefore I added the milestone to 3.1. If you want to integrate it into 3.0.5.x, please use this feature branch.

**Comment by eSlider** [comment]
Is fixed and available in 3.0.5.2.
