### ISSUE TITLE
Mapbender with osm WMS (No Layer Name)

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#328]
Mapbender 305 has included some osm WMS provided by wheregroup.
The OSM-Layer got a missing layer name.
see:
![empty-layer](https://cloud.githubusercontent.com/assets/984349/9161642/7f678eae-3f42-11e5-8baf-aa0b9751f776.png)

If you want to add  that configured layer to a new application.
Firebug says:
########
TypeError: href is undefined
...('Your element with id ' + id + ' (widget ' + data.init + ') failed to initializ...
########
And Application loading fails.

**Comment by hwbllmnn** [comment]
Fixed for 3.0.5.1.
