### ISSUE TITLE
mapbender application import failed

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#333]
Import Application by yaml or json failed.
In app_dev mode this shows up.
![import fails](https://cloud.githubusercontent.com/assets/984349/9268049/1d84d410-425a-11e5-82c2-9443f8858e01.png)

**Comment by psch** [comment]
already fixed (s. c7ebb88188b86f22d7993d0e9b1909fbce47c19e)
use v3.0.5.1
