### ISSUE TITLE
Mobile Template (Application too small)

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#338]
In Mapbender 305 is a Mobile friendly Javascript  
located  in
mapbender/src/Mapbender/CoreBundle/Resources/views/index.html.twig
```javascript
if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
            document.write('<meta name="viewport" content="width=device-width; initial-scale=0.6; maximum-scale=0.6; minimum-scale=0.6; user-scalable=no;target-densityDpi=240dpi"/>');
}
```
This is useful for Desktop/Responsive designs,
but should not be loaded in Mobile Template.
It will shrink the images/text so that the Template is not that useful then in normal mode.
Maybe we could move the Script to another Twig Template.

**Comment by AxxL** [comment]
Our template are based on a master template and this code is also for the fullscreen template. But we are working on a modified mobile template so we are going to change it.
