### ISSUE TITLE
Simplesearch (icon offset)

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#343]
In mapbender configuration(v.3.5.0) you can set an offset to an defined icon.
But there is a bug in the field seperator.
As described in Mapbender Docu  it is a comma (,).
But this doesn't work. 
Take a look to the file: 
/mapbender3-3.0.5.0/mapbender/src/Mapbender/CoreBundle/Resources/public/mapbender.element.simplesearch.js 
(Line 79)
The  Field seperator is: ", ;"

**Comment by AxxL** [comment]
fixed for 3.0.5.1
