### ISSUE TITLE
Featureinfo default behavoir

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#344]
If you create a new layerset from WMS in an Application 
the default Featureinfo-Format is "text/plain".
But the default shoiuld be "text/html" because otherwise FI-queryies doesnt work in the Application.

**Comment by AxxL** [comment]
I cannot reproduce that. Try this temporary WMS
http://wms.wheregroup.com/cgi-bin/mapserv64?map=/data/umn/schwalmtal/schwalmtal.map&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0

**Comment by marmancs** [comment]
Maybe you can reproduce it with this WMS.
http://geoportal.remscheid.de/cgi-bin/mapserv_5.20?map=/opt/umn/remscheid/points_of_interest.map&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0

![infoformat](https://cloud.githubusercontent.com/assets/984349/9516405/b676b1a4-4ca8-11e5-9623-7cd382e1fdfa.png)



The first getFeatureinfoFormat the Service provides is (text/plain)
So Mapbender set this to the default Format.

**Comment by AxxL** [comment]
Now I see. Mapbender3 uses the same order than the WMS delivers. I cannot reproduce it with 6.4 here. If I put WEB | METADATA |  WMS_FEATURE_INFO_MIME_TYPE "text/html" into the mapfile, text/html is first. Maybe the order depends on the mapserver version. 

For me the MB3 mechanism is OK, getting the order from the wms. You can set the Infoformat in the layerset instancewith one or two more clicks. I would like to close that issue for now unless you give me a huge reason. :-)

Best regards.
Axel

**Comment by marmancs** [comment]
You're right about the MB3 mechanism. And two more click's are suitable. But the mainProblem is, that mapbender does not show the FI if the setting is on text/plain . No popup is rendered even if the Server delivers a plain text. Currently the setting must be text/html.

**Comment by astroidex** [comment]
* At the moment Mapbender3 does not show text/plain when only valid is checked. As no html/body is in the result it is interpreted as not valid.
* only valid unchecked will display  the result
* only valid checked is implemented to avoid showing empty results. We should rediscuss what it means to be not valid
* @marmancs also good idea to handle text/html as default
![featureinfo_textplain](https://cloud.githubusercontent.com/assets/996298/10300941/6cc69334-6bfd-11e5-8ab9-31fb882dd7b7.png)

**Comment by AxxL** [comment]
Uncheck the only valid checkbox, if you want to display text/plain in FeatureInfo dialog.
