### ISSUE TITLE
Feature Digitizer (yaml Configuration)

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#350]
In Version 3.0.5.1
YAML Configuration is destroyed in digitizer when you have saved the Element.
If you reload the Element in Manager an YAML/JSON mixin appears which isn't that nice to configure.

**Comment by eSlider** [comment]
@astroidex, this is a mapbender3 import/export bug and can be assigned to @psch

**Comment by AxxL** [comment]
Pasting a YML into Digitizer scheme and opening again reformattes the YML code (missing line-breaks). That is a bit confusion for editing small changes.

**Comment by eSlider** [comment]
@marmancs, this is [fixed](https://github.com/mapbender/mapbender-digitizer/commit/e9247bba2a8a9e42e8ec36860c64dab1a90e07a5)!
