### ISSUE TITLE
Simplesearch (Form-Enter)

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#351]
The simplesearch Form should prevented from Enter Key.
If you hit the Key in the applicatication you will redirect to a new page with an empty array.
SEE:
http://geoportal.remscheid.de/mapbender305/application/remscheid_desktop

It would be nice to use the arrow keys (up/down) to browse through the search result.
(Maybe at this point an Enter )

**Comment by psch** [comment]
fixed
