### ISSUE TITLE
WMC Loader

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#353]
WMC Loader doesn't work as expected.
1. Load from Listbox doesn't consider WMS that are included in BaseSourceSwitcher 
2. Load from link (&wmcid=) append the WMS to the existing Layertree of the application. 
(doesn't Consider BSS too)

**Comment by AxxL** [comment]
Yepp. We take a look at it.

**Comment by AxxL** [comment]
I see the following error: Load from Listbox puts the Basesources into the Layertree (shouldn't do it when Layertree is configured not to show them)

But if I have switched the Background layer and load the wmc, the basesource is switched.

My scenario: Two Basemaps, layertree is confgured not to show them.

**Comment by AxxL** [comment]
We changed that behaviour in the 3.0.5.2 release. The WMC doesn't have information about the BaseSourceSwitcher itself (therefore it's not a real bug, the WMC cannot hold the correct information). You can try to switch the WMC Loader to Keep Sources = BaseSources to see the effect.
