### ISSUE TITLE
digitizer (add new feature..... then remove it)

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#359]
With MB 3.0.5.1 (feature digitizer) you cannot add a new feature and then delete it directly in one session.
You have to reload the application to do it.

**Comment by eSlider** [comment]
Thank you for the bug report!
The digitizer is a included library in mapbender and has own repository and issues list.
So we can test and close issues module depended.

Please report new digitizer issues directly to repository:
https://github.com/mapbender/mapbender-digitizer

I recreated the ticket here:
https://github.com/mapbender/mapbender-digitizer/issues/4
