### ISSUE TITLE
digitizer.... abort feature creation

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#360]
if you want to create a new feature(per digitizer) in MB 3.0.5.1.
You cannot abort a feature creation.
Steps to reproduce.
Set a new point. => Attribute dialog appears.
From this Moment you cannot abort the creation Process.
  * Formular-Delete Button (does nothing.)
  * Formular-Abort Button (feature stays at given Position)
  * Fill the complete dalog 
      ==>Saving and remove the feature after it doesn't work too. 

      (see ticket  #359 in context)

**Comment by eSlider** [comment]
Thank you for the bug report!
The digitizer is a included library in mapbender and has own repository and issues list.
So we can test and close issues module depended.

Please report new digitizer issues directly to repository:
https://github.com/mapbender/mapbender-digitizer

I recreated the ticket here:
https://github.com/mapbender/mapbender-digitizer/issues/5
