### ISSUE TITLE
digitizer move feature

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#361]
When you move a feature in Mapbender 3.0.5.1 (per digitizer) you have to to click 
the elemet another time to open the feature dialog.
A new option to digitizer Element like:
 * openDialogAfterElemetMoved
OR
 * saveFeatureAfterElementMoved
would be nice.

**Comment by eSlider** [comment]
Thank you for the bug report!
The digitizer is a included library in mapbender and has own repository and issues list.
So we can test and close issues module depended.

Please report new digitizer issues directly to repository:
https://github.com/mapbender/mapbender-digitizer

I recreated the ticket here:
https://github.com/mapbender/mapbender-digitizer/issues/3
