### ISSUE TITLE
GetfeatureInfo on Samsung devices

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#362]
In the mobile Template getFeatureInfo doesn't work nice on Samsung Devices(Tested with Galaxy Tab and S6 phone) with Android Browser.
The Map only moves to north. No Info appears

**Comment by eSlider** [comment]
@AxxL, I think @psch can fix it.

**Comment by AxxL** [comment]
Cannot confirm on a stock android browser on another system.

@eSlider: can you confirm?

Is the stock browser a browser that we should support? Does the browser depend on the android version?

**Comment by eSlider** [comment]
@AxxL  this day we only support Android 5 stock browser, which is automatically updated and now is Chrome 44.0.2403.133
