### ISSUE TITLE
digitizer duplicated feature

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#364]
Found another issue with the digitizer Element in Version 3.0.5.1.
Steps to reproduce.
1. goTo release.mapbender3.org and open digitizer Application.
2. create a new polygon feature
3. zoom to the new feature
4. switch ckeckbox "Select by current extent only"
5. the new feature appears twice in Elemet tab.
6. Both can be edited seperately. (and even saved)
6. After an reload(application) the second feature doesn't appear

**Comment by eSlider** [comment]
Thank you for the bug report!
The digitizer is a included library in mapbender and has own repository and issues list.
Please report new digitizer issues directly to repository:
https://github.com/mapbender/mapbender-digitizer

So we can test and close issues module depended.
I recreated the ticket for here:
https://github.com/mapbender/mapbender-digitizer/issues/2
