### ISSUE TITLE
Is support for tiled layers planned?

### ISSUE THREAD

**Issue by miloskroulik** [mapbender/mapbender#379]
Do you plan to add support for tiled layers, such as http://wiki.openstreetmap.org/wiki/Tiles?

**Comment by AxxL** [comment]
Yes. There are project specific implementations for WMTS and TMS that will be included into Mapbender3.

For the other tile possibilities we have to see. Mapbender 3.1 will presumably include a Datasource Interface so that it is easier to include other datasources as well.

**Comment by miloskroulik** [comment]
​Thanks, I'm looking forward to this feature.​

2015-11-04 10:31 GMT+01:00 Axel Schaefer <notifications@github.com>:
