### ISSUE TITLE
there is no root user in "mapbender-starter" project

### ISSUE THREAD

**Issue by gouchaoer** [mapbender/mapbender#385]
hey, I have deploy the "mapbender-starter" project successfully.  But I find there's no root user in the database, so I can't login. In the "mapbender-starter" repo's guide you said:
```
Demo users

Some of the demos may require you to login. In the delivered security.yml, two users are hardcoded (name/password):

user/user root/root
```
But there's no such user...could you tell me how to fix the problem or how to add a root user?
(I can't find the issues page in that repo, so I ask in this repo :)

**Comment by astroidex** [comment]
Hello,

on installation you create a user with the command:
app/console fom:user:resetroot

You can give the user a name you like f.e. root or admin. This user will 
be created in the database in the table fom_user.

You find information about installation at:

http://doc.mapbender3.org/en/book/installation.html

Have a look at the detailed description

http://doc.mapbender3.org/en/book/installation/configuration.html

Astrid Emde

Am 2015-12-10 05:13, schrieb gouchaoer:
> hey, I have deploy the "mapbender-starter" project successfully. But I
> find there's no root user in the database, so I can't login. In the
> "mapbender-starter" repo's guide you said:
> 
> Demo users
> 
> Some of the demos may require you to login. In the delivered
> security.yml, two users are hardcoded (name/password):
> 
> user/user root/root
> 
> But there's no such user...could you tell me how to fix the problem or
> how to add a root user?
>  (I can't find the issues page in that repo, so I ask in this repo :)
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/mapbender/mapbender/issues/385

-- 

Mit freundlichen Grüßen

Astrid Emde
GIS-Consultant

********************************************
Where2B Konferenz 2015
10. Dezember 2015 in Bonn
www.where2b-conference.com
********************************************

  Astrid Emde
  WhereGroup GmbH & Co.KG
  Eifelstraße 7
  53119 Bonn
  Germany

  Fon: +49(0)228 90 90 38 - 19
  Fax: +49(0)228 90 90 38 - 11

  astrid.emde@wheregroup.com
  www.wheregroup.com

  Folgen Sie der WhereGroup auf twitter: 
http://twitter.com/WhereGroup_com

Amtsgericht Bonn, HRA 6788
-------------------------------
Komplementärin:
WhereGroup Verwaltungs GmbH
vertreten durch:
Olaf Knopp, Peter Stamm
-------------------------------
  pgp-public key:
  http://pgp.mit.edu:11371/pks/lookup?search=0x06DA52D72D515284
   Signierte und/oder verschlüsselte Nachrichten sind sehr willkommen
   Signed and/or encrypted mail is highly appreciated

**Comment by gouchaoer** [comment]
It's works!
thank you very much :)

**Comment by astroidex** [comment]
my todo: enhance the documentation ("mapbender-starter" repo's guide) so noone gets confused. refer to http://doc.mapbender3.org/en/book/installation.html
