### ISSUE TITLE
[digitizer]  geomType: multipolygon saves polygon

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#386]
* if you define a featureType geomType: multipolygon mapbender3 still saves polygon instead of multipolygon if you save a new digitized object

**Comment by AxxL** [comment]
Digitizer will be set on 1.0. for Mapbender 3.0.5.x

**Comment by eSlider** [comment]
Fixed. 

https://github.com/mapbender/mapbender-digitizer/commit/bb27fe9ae2470fa8caedd3c3664a9e11e93a860c
