### ISSUE TITLE
featureInfoextension

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#387]
New element to influence feature info
- add WMS from featureInfo
- hightlight results from featureInfo in map
- https://github.com/mapbender/mapbender/tree/feature/featureinfo-extension
- https://github.com/mapbender/mapbender-documentation/blob/feature/featureinfo-extension/en/bundles/Mapbender/CoreBundle/elements/feature_info_extension.rst

**Comment by eSlider** [comment]
@astroidex, this shold be done as an separate module. 
Please read [contribution guide](https://github.com/mapbender/mapbender-starter/blob/release/3.0.6/CONTRIBUTING.md)
