### ISSUE TITLE
new Feature: context dependent legends

### ISSUE THREAD

**Issue by ruhri** [mapbender/mapbender#396]
A new feature is requested: UMN Mapserver and QGIS-client still suppport context dependant legends (I think QGIS-Server does it too), which means, the WMS-GetlegendGraphic gets more dynamic - the server just shows features in the legend, which are actually visible.
The GetLegend-Request needs to be extended with a few more - vendor specific - parameters, which should be well known from the GetMap-Request (BBOX, CRS, Width and Height). The legend needs to be refreshed, everytime the map is panned/zoomed.

Example-Requests:
default-legend:
http://geodaten.metropoleruhr.de/spw/spw_web?language=ger&SERVICE=WMS&VERSION=1.3.0&SLD_VERSION=1.1.0&REQUEST=GetLegendGraphic&FORMAT=image/png&LAYER=oepnv_linien&STYLE=

context-dependent-legend:
http://geodaten.metropoleruhr.de/spw/spw_web?language=ger&SERVICE=WMS&VERSION=1.3.0&SLD_VERSION=1.1.0&REQUEST=GetLegendGraphic&FORMAT=image/png&LAYER=oepnv_linien&STYLE=&BBOX=361500,5701000,363000,5702000&CRS=EPSG:25832&WIDTH=1500&HEIGHT=1000

Have a look at the UMN-implementation:
http://mapserver.org/development/rfc/ms-rfc-101.html

This interesting feature could help to produce more clean maps/legends and wouldn't break WMS-specs nor should it be rocket science to realize... ;-)

**Comment by eschuettler** [comment]
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html
