### ISSUE TITLE
Request getMap and getFeatureInfo: parameter exceptions is missing in request or set wrong

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#400]
Request getMap 
- parameter exceptions is missing in the request (f.e. EXCEPTIONS=exception_format)
- in the backoffice you can define an exception format, but it does not have any effect.

Read more. Have a look at:
- http://cite.opengeospatial.org/OGCTestData/wms/1.1.1/spec/wms1.1.1.html#wmsops.getmap.overview

In the getFeatureInfo Request Exceptions is passed but is is always set to EXCEPTIONS=application/vnd.ogc.se_xml
- http://cite.opengeospatial.org/OGCTestData/wms/1.1.1/spec/wms1.1.1.html#wmsops.getfeatureinfo.overview

**Comment by AxxL** [comment]
It's in 3.0.5.4. You have to save your Layerset-Instance to update the mb3-repository.

**Comment by astroidex** [comment]
* Tested with 3.0.6.0

* looks like this issue is not fixed
Background
* depending on the version of WMS you have different Exception formats
* in Mapbender backoffice you can switch between the possible Exception-formats. But in the requests always &EXCEPTIONS=XML is used for getMap and getFeatureInfo 

WMS Version 1.1.1
* http://wms.wheregroup.com/cgi-bin/mapbender_user.xml?VERSION=1.1.1&REQUEST=GetCapabilities&SERVICE=WMS
`<Exception><Format>application/vnd.ogc.se_xml</Format><Format>application/vnd.ogc.se_inimage</Format><Format>application/vnd.ogc.se_blank</Format></Exception>`

WMS 1.3.0
* http://wms.wheregroup.com/cgi-bin/mapbender_user.xml?VERSION=1.3.0&REQUEST=GetCapabilities&SERVICE=WMS
`<Exception><Format>XML</Format><Format>INIMAGE</Format><Format>BLANK</Format></Exception>`
