### ISSUE TITLE
Redlining: edit text does not chnage text color in the map and ancor is not visible

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#401]
- redlining allows to change existing objects. for point, line, polygon the objects are changed from red to blue, when you click on button pen to edit the object

Bug
- button pen, does not change the color of the text to blue (when you have many textes you do not see which one is choosed)
- the ancor of the text is at the lower-left of the text. But you do not see it.

Solution
- change color of text that you want to edi to blue
- show the ancor point of the text (maybe as a point)

You can test it in demo;

http://version.mapbender3.org/3053/application/mapbender_user

**Comment by eSlider** [comment]
There is alreasy one fix from @psch, this should resolve the problem:
https://github.com/mapbender/mapbender/tree/hotfix/redlining-text

The fix need to be tested, but  given example URL doesn't work. 
 @astroidex do we have another example or can you check this fix?

**Comment by eSlider** [comment]
Pull-request to release/3.0.5: https://github.com/mapbender/mapbender/pull/456

**Comment by astroidex** [comment]
* This is fixed in 3.0.7.0rc2. Text is displayed in blue when you choose edit
* but a new problem occurs. Textes should not have the red circle when you drawn them and print them. Only when you move them. I opened a new ticket for this issue #862
