### ISSUE TITLE
User login problems!

### ISSUE THREAD

**Issue by Amrizhan** [mapbender/mapbender#402]
Hi there
I install mapbender and get it works on my server. And when I go to **"server ip"/mapbender3** I can't login with user witch was created via "User control" on "app_dev" mode, I tried to login with root user and also it gives me "bad credential".
Environment is:
Ubuntu 14.04
Apache2
Postgres DB
What I am doing wrong????

**Comment by AxxL** [comment]
You can check if an error occurs in mapbender/app/logs/dev.log or prod.log (depends on app_dev.php or app.php start) and if an error occurs in the apache/error.log

You can check the repository in the MB3-repository if the user is in the table fom_user. You should have "root" with a password and salt and your user with password and salt.

**Comment by Amrizhan** [comment]
@AxxL Thank for reply
I checked errors on prod.log and there is request.ERRORS like it can't found css styles, png images and last one is:

> No route found for "Get /user/app_dev.php"

on dev.log there is only debug msg

I check DB table fom_user and my "test" user is there, but seems like password is crypted

**Comment by Amrizhan** [comment]
FIX that with uncommnet `require_once __DIR__.'/.../app/AppCache`;
