### ISSUE TITLE
Customize Mapbender3

### ISSUE THREAD

**Issue by Amrizhan** [mapbender/mapbender#404]
I want to thank you for this awesome project. It’s real helpful platform for small GIS projects!!

I install mapbender3 using tutorials and add my sources via Geoserver and everything works great. 

Now my question. I am not software engineer and I am looking for customize start page. Is there any documents I can read for this procedures??

Under customize I mean: change Title, change Icons, change “menu” language? Where I need to look?

**Comment by astroidex** [comment]
Read more in the thread in the the mapbender-users mailing list http://lists.osgeo.org/pipermail/mapbender_users/2016-March/004905.html
