### ISSUE TITLE
Redline text does not print

### ISSUE THREAD

**Issue by fingeo** [mapbender/mapbender#407]
Bug: 
when using the redlining tool the Point, Line, Polygon, and Rectangle drawings all appear when printed but any Text created using redlining does not appear when printed.

Using Mapbender 3.0.5.3 on firefox, chrome, and IE.

**Comment by AxxL** [comment]
Hi @fingeo.

Sorry, I cannot reproduce. Have you set a text on redlining? I've got a printout here (PDF) that shows my text on Redlining (3.0.5.3, Firefox).

[http://i.imgur.com/OfiG5qg.png](http://i.imgur.com/OfiG5qg.png)

Axel

**Comment by fingeo** [comment]
Hi Axel

how do you mean have i set a text? 

top image is a screenshot of the map, second image is screenshot of printed pdf.
http://imgur.com/a/38cQZ

**Comment by eSlider** [comment]
Hi @swinkelmann, can you help here?

**Comment by AxxL** [comment]
Well, that issue isn't really reproducable so it's a bit tricky to get to know what happens.

Does your print work in general?
Do you have the font-files in application/app/Ressources/MapbenderPrintBundle/fonts? There has to be 3 OpenSans fonts. Like here: https://github.com/mapbender/mapbender-starter/tree/master/application/app/Resources/MapbenderPrintBundle/fonts

Does the logfiles say anything? (app/logs/prod.log oder app/logs/dev.log if you call it with http://localhost/mapbender3/app_dev.php)

Axel

**Comment by fingeo** [comment]
Thank you @AxxL @swinkelmann 

the problem was that those 3 OpenSans fonts files were missing from the version of MapBender I have. In /var/www/mapbender3/app/Resources/MapbenderPrintBundle/fonts/ there was arial.ttf, Trebuchet_MS_Bold.ttf, Trebuchet_MS.ttf.

I copied OpenSans-Semibold.ttf, OpenSans-Regular.ttf, and OpenSans-Bold.ttf from a different version of mapbender and added them to /var/www/mapbender3/app/Resources/MapbenderPrintBundle/fonts/ flushed the mapbender cache, restarted apache and it worked perfect.
