### ISSUE TITLE
composer update TransportException (mapbender-starter)

### ISSUE THREAD

**Issue by ThorstenHi** [mapbender/mapbender#408]
Current composer throws an error message. _composer update_ 

not working: Composer version 1.0-dev (a8e9df55dc62d8806360be2f79ad112b8678d397) 2016-03-17 11:42:19
working: Composer version 1.0-dev (a54f84f05f915c6d42bed94de0cdcb4406a4707b) 2015-10-13 13:09:04

igosuki/compass-mixins use http instead of https

Error Message:
...
  - Installing igosuki/compass-mixins (0.12.6)
    Downloading: Connecting...    Downloading: Connecting...    Downloading: Connecting...
                                                                                                                                            
  [Composer\Downloader\TransportException]                                                                                                  
  Your configuration does not allow connection to http://github.com. See (https://getcomposer.org/doc/06-config.md#secure-http) for details.
...

**Comment by AxxL** [comment]
Hi @ThorstenHi.

Thanks for that. I put @eSlider into this. I guess it's sufficient to put secure-http: false in the config-section of composer.json.

Axel

**Comment by ThorstenHi** [comment]
Yes, but I think _secure-http: false_ is only a temporary solution. The use of HTTPS would be good. Perhaps https://github.com/Igosuki/compass-mixins/ solve the problem at the source.
