### ISSUE TITLE
Simple Search error: a.replace is not a function

### ISSUE THREAD

**Issue by fingeo** [mapbender/mapbender#409]
Hi,

when selecting an item from the results list of the simple search nothing happens. There are no errors in apache or mapbender logs. Firebug returns this error message just after a search result item is clicked:

TypeError: a.replace is not a function
http://10.50.10.204/mapbender3/application/Work-Plans/assets/js
Line 5837

Screen capture http://imgur.com/EjwlY7T
Using mapbender 3.0.5.3 this error happens in firefox, chrome, IE.
For search element settings i use the same as in the documentation https://github.com/mapbender/mapbender-documentation/blob/feature/featureinfo-extension/en/bundles/Mapbender/CoreBundle/elements/simplesearch.rst

**Comment by AxxL** [comment]
@fingeo: The issue occured if a entry doesn't contain a geometry.

If you encounter another issue with this, please reopen this one here or create a new one.
