### ISSUE TITLE
app/console doctrine:schema:validate

### ISSUE THREAD

**Issue by hounded** [mapbender/mapbender#413]
[Mapping]  FAIL - The entity-class 'Mapbender\WmcBundle\Entity\Wmc' mapping is invalid:
- Field 'logourl' in class 'Mapbender\WmcBundle\Entity\Wmc' must be private or protected. Public fields may break lazy-loading.
- Field 'descriptionurl' in class 'Mapbender\WmcBundle\Entity\Wmc' must be private or protected. Public fields may break lazy-loading.

[Mapping]  FAIL - The entity-class 'Mapbender\WmsBundle\Entity\WmsInstance' mapping is invalid:
- The association Mapbender\WmsBundle\Entity\WmsInstance#source refers to the inverse side field Mapbender\WmsBundle\Entity\WmsSource#instance which does not exist.

[Mapping]  FAIL - The entity-class 'Mapbender\WmsBundle\Entity\WmsInstanceLayer' mapping is invalid:
- The association Mapbender\WmsBundle\Entity\WmsInstanceLayer#sourceItem refers to the inverse side field Mapbender\WmsBundle\Entity\WmsLayerSource#id which is not defined as association.
- The association Mapbender\WmsBundle\Entity\WmsInstanceLayer#sourceItem refers to the inverse side field Mapbender\WmsBundle\Entity\WmsLayerSource#id which does not exist.

[Mapping]  FAIL - The entity-class 'Mapbender\WmsBundle\Entity\WmsLayerSource' mapping is invalid:
- Field 'latlonBounds' in class 'Mapbender\WmsBundle\Entity\WmsLayerSource' must be private or protected. Public fields may break lazy-loading.
- Field 'boundingBoxes' in class 'Mapbender\WmsBundle\Entity\WmsLayerSource' must be private or protected. Public fields may break lazy-loading.
- Field 'scale' in class 'Mapbender\WmsBundle\Entity\WmsLayerSource' must be private or protected. Public fields may break lazy-loading.
- Field 'scaleHint' in class 'Mapbender\WmsBundle\Entity\WmsLayerSource' must be private or protected. Public fields may break lazy-loading.
- Field 'attribution' in class 'Mapbender\WmsBundle\Entity\WmsLayerSource' must be private or protected. Public fields may break lazy-loading.
- Field 'identifier' in class 'Mapbender\WmsBundle\Entity\WmsLayerSource' must be private or protected. Public fields may break lazy-loading.
- Field 'authority' in class 'Mapbender\WmsBundle\Entity\WmsLayerSource' must be private or protected. Public fields may break lazy-loading.

[Mapping]  FAIL - The entity-class 'Mapbender\WmsBundle\Entity\WmsSource' mapping is invalid:
- The mappings Mapbender\WmsBundle\Entity\WmsSource#instances and Mapbender\WmsBundle\Entity\WmsInstance#source are inconsistent with each other.
- Field 'getCapabilities' in class 'Mapbender\WmsBundle\Entity\WmsSource' must be private or protected. Public fields may break lazy-loading.
- Field 'getMap' in class 'Mapbender\WmsBundle\Entity\WmsSource' must be private or protected. Public fields may break lazy-loading.
- Field 'getFeatureInfo' in class 'Mapbender\WmsBundle\Entity\WmsSource' must be private or protected. Public fields may break lazy-loading.
- Field 'describeLayer' in class 'Mapbender\WmsBundle\Entity\WmsSource' must be private or protected. Public fields may break lazy-loading.
- Field 'getLegendGraphic' in class 'Mapbender\WmsBundle\Entity\WmsSource' must be private or protected. Public fields may break lazy-loading.
- Field 'getStyles' in class 'Mapbender\WmsBundle\Entity\WmsSource' must be private or protected. Public fields may break lazy-loading.
- Field 'putStyles' in class 'Mapbender\WmsBundle\Entity\WmsSource' must be private or protected. Public fields may break lazy-loading.

[Database] FAIL - The database schema is not in sync with the current mapping file.

**Comment by eSlider** [comment]
Thx @hounded for the advice! Entities are now fixed and merged in current "release/3.0.5" branch. 
https://github.com/mapbender/mapbender/pull/421

**Comment by RobinSchwammborn** [comment]
Hi @eSlider,
a few entities still need to be fixed:

SymfonyProfiler:
http://localhost:8000/_profiler/a896c3?panel=db 


Also, take a look at this screenshot:

![appconsole_doctrine_lazyloading](https://cloud.githubusercontent.com/assets/21199730/25179685/346376c4-250b-11e7-839f-f87605e67a87.png)

**Comment by eSlider** [comment]
@RobinSchwammborn, thanks for council!
