### ISSUE TITLE
WMS with many layers fails on layerset instance

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#414]
* Add WMS Source
http://geodaten.metropoleruhr.de/poi/poi?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities

* Create application

* Load layerset instance

If saving works, go back in. You'll see that some layer information is missing (layernames or scales or both).

**Comment by AxxL** [comment]
The effect has a direct connection to the number of options that are checked in the LayerInstance form. Somewhere at layer 90 (Parkour) you see that you the form isn't saved correctly if you have at least 3 columns completely checked (active, allow and on).

Please set the **max_input_vars** in php.ini to a higher level. For example 2000.

This depends a bit on the number of layers of the WMS. The layerinstance formular has a lot of checkboxes to set. These are send to the backend and it depends on this parameter.

**Comment by AxxL** [comment]
I put up a FAQ to document stuff like this. :)

English translation is WIP.

http://doc.mapbender3.org/de/book/faq.html

**Comment by RobinSchwammborn** [comment]
I was able to reproduce the bug with the WMS above - see the screenshots.
However, I didn't adjust php.ini, which is probably the easiest "fix" for this problem.


![wms_parkour_lastlayer](https://cloud.githubusercontent.com/assets/21199730/25710911/ec9989fc-30ed-11e7-9e37-dc95e4e1c759.png)

![layerset_instance_error_message](https://cloud.githubusercontent.com/assets/21199730/25710909/ec9815d6-30ed-11e7-8e99-380016da8c22.png)

![wms_symfony_error](https://cloud.githubusercontent.com/assets/21199730/25710910/ec98d34a-30ed-11e7-8f27-8b2177a4212c.png)

**Comment by AxxL** [comment]
@RobinSchwammborn So, "max_input_vars" is your solution or do I have to reopen the issue?

**Comment by astroidex** [comment]
YES - max_input_vars is the solution. You should always set it to a high value if you have many layer in your services.
http://doc.mapbender3.org/en/book/faq.html

Suggestion: Don't put this information at FAQ. Better put it directly at the installation page. It does not hurt to set this variable.


`;; 1000 (default) or more
max_input_vars = 1000`

**Comment by AxxL** [comment]
Thanks for clarifying.

**Comment by LazerTiberius** [comment]
Just for clarification, this CSRF-Token error is also caused by exhausting the max input vars.
