### ISSUE TITLE
Line/Area Ruler: algorithm for measuring

### ISSUE THREAD

**Issue by arimonma** [mapbender/mapbender#417]
Line/Area Ruler
The algorithm for measuring needs improvement and should mention the different scale in north-south and west-east extension, depending on chosen projection. 

Example for Germany:

North end of Sylt Island (WGS84: x=8.41 y=55.06) to south end of Königsee Lake (WGS84: x=12.97 y=47.52)
EPSG:25832, EPSG:31467 ~ 900 km (what is OK)
EPSG:4326              ~ 980 km (what is acceptable)

West / Aachen (WGS84: x=6.05 y=50.78) to East / Görlitz (WGS84: x=14.97 y=51.16)
EPSG:25832, EPSG:31467 ~ 625 km (what is OK)
EPSG:4326              ~ 990 km (what is NOT OK)

QGis for example calculates correct distances.

**Comment by AxxL** [comment]
Think this is related to the inability to measure correct values with WGS84. We'll see what we can do - for example to project to a different system for measuring.

**Comment by arimonma** [comment]
Hi Axel,
couldn’t you try to find out how QGIS does this? There it works correctly, even with EPSG:4326. Also have a look at https://www.kompf.de/gps/distcalc.html. It should be possible with PROJ.4 (I guess Mapbender3 uses it, too).
Cheers, Martin


Von: Axel Schaefer [mailto:notifications@github.com]
Gesendet: Freitag, 1. Juli 2016 14:11
An: mapbender/mapbender <mapbender@noreply.github.com>
Cc: Arimont, Martin <Martin.Arimont@ble.de>; Author <author@noreply.github.com>
Betreff: Re: [mapbender/mapbender] Line/Area Ruler: algorithm for measuring (#417)


Think this is related to the inability to measure correct values with WGS84. We'll see what we can do - for example to project to a different system for measuring.

**Comment by AxxL** [comment]
Okey, wir schauen uns das an.

**Comment by AxxL** [comment]
https://github.com/mapbender/mapbender/tree/hotfix/measure-add-geodesic

Will be part of the next bugfix release.
