### ISSUE TITLE
Composer: components/datatables vs. bower-asset/datatables

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#422]
When using composer update or composer install you might get the message: 

> Package components/datatables is abandoned, you should avoid using it. Use bower-asset/datatables instead.

We will remain on components/datatables and change later because:
- bower is yet in beta-stadium (https://packagist.org/packages/beelab/bowerphp)
- bower requires Symfony v2.4+

**Comment by debugteam** [comment]
bower-asset/datatables is a virtual package definition and this suggestion means that the guy who formerly came up with the idea "1 job, 1 tool" is wrong. The suggestor seems to think that "1 job, >1 tools" is better... Why not use 2 phones to call 1 person?

So, ...we have to use composer for php, and bower for javascript and hear my words you filthy tooligans: there will be a css packagemanager soon - propably written in "secure-scss-scripting-language (SSSL)" which will be a programming language that let's you create webapplications and selflearning robots from pure object oriented - MVC concepted css  (don't google that! - don't!!)... 

jokes apart ... i think we should not let that happen and stick to 1 tool for 1 job. "Creating a webapplication written in php with assets" is one job... Now what?

**Comment by LazerTiberius** [comment]
https://github.com/bower/bower/issues/2298

**Comment by eSlider** [comment]
I prefer to use https://packagist.org/packages/datatables/datatables instead of integrating bower.
