### ISSUE TITLE
Search Router and POI (MeetingPoint) are working with SRS ETRS 89 / UTM zone 32N only

### ISSUE THREAD

**Issue by sylviaobk** [mapbender/mapbender#458]
The elements Search Router and POI (MeetingPoint) are working when SRS ETRS 89 / UTM zone 32N is selected in footer but other EPSG-Codes are not supported.
If I select for example DHDN / 3-degree Gauss-Kruger Zone 2 the Search Router changes the scale but not the position of the map.
If I select for example DHDN / 3-degree Gauss-Kruger Zone 2 the MeetingPoint Element generates the URL http://wmsobk2.intern.obk.de/mapbender3/app.php/application/RIO-Sylvia-Test?poi%5Bpoint%5D=2619720%2C5646140&poi%5Bscale%5D=2500&poi%5Blabel%5D=Treffpunkt%3AGK+2
After opening this URL I get a map without Meeting Point marker and not on the right Position.
## I think DHDN / 3-degree Gauss-Kruger Zone 2 and Zone 3 etc. should be supported, too.

Example:
1. Suchen Search Router
Bei Suchen nach Ort, Flurstückskennzeichen, Adresse, Eigentümer muss in der Fußzeile in der SRS Auswahl UTM32 ETRS89 ausgewählt sein, bei den anderen Projektionssystemen erfolgt nur eine Änderung des Kartenmaßstabes ohne Änderung des Kartenmittelpunktes 

Sidepane:
Element hinzufügen:
Suchen
Ermöglicht die Konfiguration von individuellen Suchen

Configuration:
Target: Karte

class: Mapbender\CoreBundle\Component\SQLSearchEngine
connection: meineSuchPostgisdatenbank
relation: meineSuchPostgistabelle (Ort, Flurstückskennzeichen, Adresse, Eigentümer)

Footer:
Element hinzufügen:
SRS Auswahl

Target: Karte
1. Treffpunkt/ MeetingPoint (POI)

Content:
Element hinzufügen:
MeetingPoint (POI)
Target: Karte

Toolbar:
Element hinzufügen:
Button
Icon: POI
Target: MeetingPoint

SRS Auswahl: Gauß-Krüger 2 auswählen
Dieser Link wird generiert und per E-Mail versendet:
http://wmsobk2.intern.obk.de/mapbender3/app.php/application/RIO-Sylvia-Test?poi%5Bpoint%5D=2619720%2C5646140&poi%5Bscale%5D=2500&poi%5Blabel%5D=Treffpunkt%3AGK+2
Beim Kopieren dieser URL in die Adresszeile des Internetbrowsers erscheint der Mittelpunkt des OBK ohne Markierung:
Unfortunately I can't upload the Image.

Auf die Koordinaten in der URL wird nicht positioniert.

**Comment by AxxL** [comment]
We'll take a look into it. We patched things in the SearchRouter and POI so we will check it against the release/3.0.5 branch.

**Comment by DeEgge** [comment]
POI coordinate transformation was added with https://github.com/mapbender/mapbender/commit/5c9fb711f47faaabb57554abb6e9dd2f5285db6a#diff-85fc8eab5c7b63d1ba387567aa1cea85 and thus behaves normal (i.e. you share a POI in GK2 and view it in WGS84 and it is located at the same position).
