### ISSUE TITLE
GetMap and GetFeatureInfo on secured WMS fails

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#461]
Steps to reproduce

*  Secured Service
* Load into Mapbender
* Set Proxy to true at Layerset instance
* GetMap and GetFeature Info request fails with error message:

> request.CRITICAL: Uncaught PHP Exception Exception: "No URL signature provided" at /srv/mapbender/mapbender-starter/application/owsproxy/src/OwsProxy3/CoreBundle/Controller/OwsProxyController.php line 105 {"excepti\
on":"[object] (Exception(code: 500): No URL signature provided at /srv/mapbender/mapbender-starter/application/owsproxy/src/OwsProxy3/CoreBundle/Controller/OwsProxyController.php:105)"} []

**Comment by psch** [comment]
fixed
