### ISSUE TITLE
Frontend: Digitizer input fields - HTML script injection

### ISSUE THREAD

**Issue by mkaare** [mapbender/mapbender#464]
Mapbender version: 3.0.5.3
Component: Digitizer

![mapbender_issue](https://cloud.githubusercontent.com/assets/1218490/18954637/8f0c6f20-865c-11e6-8fbd-4529216fd523.jpg)

**Comment by eSlider** [comment]
Thank you @mkaare. Digitizer ist now fixed: 
1.0.43: https://github.com/mapbender/mapbender-digitizer/commit/d5fde896afdf9b46c5612d92c10baf1486e43e5e

1.1.41: https://github.com/mapbender/mapbender-digitizer/commit/d5fde896afdf9b46c5612d92c10baf1486e43e5e
