### ISSUE TITLE
SearchRouter in Sidepane move buttons ok and reset under the Form not under the result

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#488]
* in 3.0.5.x the buttons ok and reset from SearchRouter are placed under the result. With many results you always have to scroll down to the bottom to reset or klick ok
* change https://github.com/mapbender/mapbender/blob/release/3.0.6/src/Mapbender/CoreBundle/Resources/views/Element/search_router.html.twig to position the bottoons right under the form

**Comment by astroidex** [comment]
* created pull request: https://github.com/mapbender/mapbender/pull/489

**Comment by AxxL** [comment]
fixed.
