### ISSUE TITLE
Backend - Element - Map max_resolution auto

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#49]
- element is not implemented properly. At the moment it has no effect
- check out http://dev.openlayers.org/docs/files/OpenLayers/Layer-js.html

**Comment by hwbllmnn** [comment]
Is this still an issue? I'm also a bit unclear what you'd expect to happen.

**Comment by astroidex** [comment]
* close. Do not bedit auto and you are fine

**Comment by AxxL** [comment]
I close this issue on your comment.
