### ISSUE TITLE
LDAP Integration

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#494]
Provide a LDAP integration in the official Mapbender repository.

Put the [LDAP integration bundle](https://github.com/mapbender/ldapIntegrationBundle) into Mapbender.

You'll be able to secure application and elements on users and groups provided in LDAP. If you use LDAP you'll have no Mapbender users (except root) and only get authentication info from the LDAP respository.

The supported LDAP structure is:

* Users are like: `cn=user1,ou=user,dc=wheregroup,dc=com` and inherit from `inetOrgPerson` and `top`.
* Groups are like: `cn=mapbender,ou=groups,dc=wheregroup,dc=com` and inherit from `groupOfNames` and `top`. They have several attributes `member` which each contain the DN of a user.

Some cleanups and fixes have to be done first.

**Comment by eschuettler** [comment]
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html
