### ISSUE TITLE
review english labeling and translation in manager bundle

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#495]
* some translation can be improved. fix typos

**Comment by astroidex** [comment]
* two pull requests created
* https://github.com/mapbender/mapbender/pull/496
* https://github.com/mapbender/mapbender/pull/497

**Comment by AxxL** [comment]
Pull https://github.com/mapbender/mapbender/pull/497 nicht in Ordnung.

**Comment by AxxL** [comment]
@astroidex Wenn die Änderungen nicht von Dir gefixt werden, können wir das leider nicht übernehmen. Ich schlage vor, wir verschieben und schauen, was nach dem Hacking Event in Paris rausgekommen ist.

**Comment by astroidex** [comment]
will be fixed with the translation branch. So we can close it later i.e. next week

**Comment by AxxL** [comment]
@astroidex Can we delete the according pull requests and the branches?

**Comment by astroidex** [comment]
* yes. please delete the pull request and branches.
* All translations are done in branch hotfix/translations https://github.com/mapbender/mapbender/tree/hotfix/translations
* hotfix/translations is ready for 3.0.7
