### ISSUE TITLE
translation: corebundle review english and german translation 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#498]
* merge en and de structure
* fix typos

**Comment by astroidex** [comment]
fixed in branch see pull request hotfix/translation-core-typos  and  hotfix/translation-core-typos-1
* https://github.com/mapbender/mapbender/pull/499
* https://github.com/mapbender/mapbender/pull/500

**Comment by AxxL** [comment]
Pull #500 has comments from Andriy
