### ISSUE TITLE
FeatureInfo - print all result tabs

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#501]
* new button to print all result tabs
* when you klick the button a window opens with all results (starting first tab to last)

Requirement
* should be configurable in administration
* should work with accordeon and tabs layout

**Comment by AxxL** [comment]
The PR #502 was closed because it didn't fit into the current code anymore. Please review the code again and create a new PR. Thanks.

**Comment by astroidex** [comment]
I will check the code and make another PR

**Comment by astroidex** [comment]
Not implemented yet.
I close the issue and will open it or a new one if the feature is there
