### ISSUE TITLE
map Element - parse icon/size/offset as url-parameter on application start

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#507]
Mapbender can be started with different url parameter: 
http://doc.mapbender3.org/de/bundles/Mapbender/CoreBundle/elements/map.html#kontrolle-uber-url-parameter

You can parse pois with coordinates and labels. But you can't define an icon for a poi

Enhancement: define new parameters
* poi[0][icon]=http://localhost/grillplatz.png -> Url zu einem Icon
* poi[0][icon_width]=40& ->  width & height
* poi[0][icon_height]=40
* poi[0][icon_xoffset]=20 -> Offset  Icon
* poi[0][icon_yoffset]=20

**Comment by astroidex** [comment]
* branch for mapbender 3.0.5 https://github.com/mapbender/mapbender/tree/feature/map-getparameter-poi-icon
* have a look at pullrequest for release/3.0.5 https://github.com/mapbender/mapbender/pull/508

**Comment by astroidex** [comment]
Request could be
http://localhost/mapbender/application/mapbender_user?poi[0][point]=363374,5621936&poi[0][label]=Label&poi[0][icon]=http://localhost/mapbender/bundles/mapbendercore/image/grillplatz.png&poi[0][icon_width]=40&poi[0][icon_height]=40&poi[0][icon_xoffset]=20&poi[0][icon_yoffset]=20

Could you please check whether the url that is pared could cause trouble?

**Comment by AxxL** [comment]
I'm closing this issue now since no progress in PR. Feel free to open again if the PR is ongoing and we can check the feature.
