### ISSUE TITLE
Translations: Create/edit application: Base data tab

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#510]
When I create/edit an application the base-data tab has a translation error. Language is DE.

It shows:

    mb.manager.admin.application.edit.base_data

instead of

    Basisdaten

Looking into the translation files, it appears for DE, EN and FR. Other translations have a different structure.

    src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml
    src/Mapbender/ManagerBundle/Resources/translations/messages.en.yml
    src/Mapbender/ManagerBundle/Resources/translations/messages.fr.yml

Has to be:

```diff
    diff --git a/src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml 
    b/src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml
    index 1fd4adc..5a20ddf 100644
    --- a/src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml
    +++ b/src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml
    @@ -95,7 +95,9 @@ mb:
           template: Vorlage
           application:
             view: 'Anwendung anzeigen'
    -        edit: 'Anwendung bearbeiten'
    +        edit:
    +          title: 'Anwendung bearbeiten'
    +          base_data: 'Basisdaten'
             layouts: Layouts
             layersets: Layerset
             custom_css: CSS
```

**Comment by AxxL** [comment]
Commited in branch: https://github.com/mapbender/mapbender/tree/fix/translations_manager
Commit https://github.com/mapbender/mapbender/commit/9d92f49bd276207a1cda250caf5dce3427323d6b

**Comment by AxxL** [comment]
@eslider: Please, can you doublecheck with the other translations. Occured as a new issue here but the git logs doesn't show any change in the translation nor the php code.

pls look over the code for occurrences with your magic editor.

**Comment by eSlider** [comment]
@AxxL, thee logs are shown in pull-request. 
Here were go: https://github.com/mapbender/mapbender/pull/511/files
