### ISSUE TITLE
Internal Documentation Symfony Upgrade 2.3 > 2.8

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#514]
Finish the documentation for the developed steps from the Symfony upgrade 2.3>2.8 to support the forthcoming upgrade to symfony 3.x.

Place it into the repository or into the github wiki of mapbender-starter to make the documentation permanent and to provide it to the community.

**Comment by AxxL** [comment]
Reminder: @eSlider @LazerTiberius

**Comment by eSlider** [comment]
@AxxL, there is no Mapbender3 special code to know how to migrate. 

Anyway, I add two links howto do it right:
*  how to migrate from 2.3 to 2.7 https://gist.github.com/mickaelandrieu/5211d0047e7a6fbff925
*  how to migrate from 2.3 to 2.8 https://knpuniversity.com/screencast/symfony3-upgrade/upgrade-2.8
