### ISSUE TITLE
Fehler bei Anzeige von WMS Details wenn dieser in pgsql gespeichert

### ISSUE THREAD

**Issue by LazerTiberius** [mapbender/mapbender#515]
Beim Versuch die Details bestimmter WMS anzuzeigen kommt es zu einer Fehlermeldung 

`An exception has been thrown during the rendering of a template ("Notice: unserialize(): Error at offset 55 of 62 bytes").`

Bzw.

```
'[2017-05-03 10:30:20] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime:
"An exception has been thrown during the rendering of a template
("Could not convert database value "a:1:{i:0;O:35:"Mapbe..." to Doctrine Type array")." 
at /srv/mb3targz/mapbender3-starter-3.0.6.0/mapbender/src/Mapbender/WmsBundle/Resources/views/Repository/view.html.twig line 143'
```

Beim Anlegen der LayerInstance in der DB scheint der Wert nicht komplett geschrieben zu werden.
Wert sieht folgender maßen aus: (wmslayersource::style)

`a:1:{i:0;O:35:"Mapbender\WmsBundle\Component\Style":6:{s:7:"`

Man kann hier sehen, dass die JSON-Struktur nicht vollständig ist.
Folgend ein korrekter Wert für styles :
`a:1:{i:0;O:35:"Mapbender\WmsBundle\Component\Style":6:{s:4:"name";N;s:5:"title";N;s:8:"abstract";N;s:9:"legendUrl";O:39:"Mapbender\WmsBundle\Component\LegendUrl":3:{s:14:"onlineResource";O:44:"Mapbender\WmsBundle\Component\OnlineResource":2:{s:6:"format";N;s:4:"href";s:173:"http://wms.wheregroup.com/cgi-bin/mapbender_user.xml?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=Mapbender_User&format=image/png&STYLE=default";}s:5:"width";N;s:6:"height";N;}s:13:"styleSheetUrl";N;s:8:"styleUlr";N;}}`

**Comment by LazerTiberius** [comment]
Fehler tritt bei sqllite und laut @AxxL nicht be MySQL auf

**Comment by LazerTiberius** [comment]
@eSlider  Ist das der fix? Fehler behebt bei mir das Problem. @AxxL  Kannst du das bestätigen
https://github.com/mapbender/mapbender-starter/commit/4c4918cf3660c05e7f1c259c9e65bc7d5538a5e1

**Comment by AxxL** [comment]
@eSlider @LazerTiberius 
testing...

**Comment by eSlider** [comment]
Fixed here:
* https://github.com/mapbender/mapbender/commit/a418b1ed1960cc570bb989d2f1a6af8976c5ef8e
* https://github.com/mapbender/mapbender/commit/16495c82c3522e1d0b552978fc285cb2b19a1540
* https://github.com/mapbender/mapbender/commit/dac782091e8ad47f5ddbf1acb6bb892ce68f5074
* https://github.com/mapbender/mapbender/commit/e869cd2e5f47417fde1dad9bb3b1f852d90d88d6

 @RobinSchwammborn, please test it!

**Comment by RobinSchwammborn** [comment]
Bei mir läuft soweit alles rund bei der Detailanzeige, es kommen keine Fehlermeldungen mehr. Gibt es einen bestimmten WMS, der gehakt haben könnte? Ansonsten würde ich von "Bug fixed" ausgehen..

**Comment by eSlider** [comment]
@RobinSchwammborn, schön, dann machen wir die Ausgabe zu. :+1:
