### ISSUE TITLE
[WMCEditor] Set default configurations for width and height in WmcEditorAdminType

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#516]
New values of width and height in WMC-Editor.

They are set in WMC Editor Element (getConfiguration()).

- width: 480
- height: 500

Please get this configuration params in WmcEditorAdminType/buildForm() so that the backend shows it.

**Comment by AxxL** [comment]
For frontend we created code in Pull-Request #517

**Comment by eSlider** [comment]
Fixed and merged into https://github.com/mapbender/mapbender-starter/commit/810c433d515725e6c55f247d5c92f928cf9c2a16
