### ISSUE TITLE
Integrate link to help in MB3 backend 

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#518]
We ship the documentation with bin/composer docs.

Make a link in backend to link to

* the documentation <mapbender>/docs/index.html
* the api: <mapbender>/docs/api/index.html

One possible location for that links:

* Left in the tree as a new menu: "Help" with the entries "Documentation" and "API"

Some people don't do bin/composer docs, so there is the possibility that these files are not shipped with mapbender and not present.

* Check, if the documentation is integrated in MB3, otherwise link to the online ones: http://doc.mapbender3.org/ and http://api.mapbender3.org

**Comment by AxxL** [comment]
Removed @LazerTiberius and back again into cycle.

**Comment by werrolf** [comment]
API docs are already out.  
End user documentation may become a standalone thing, too.  
Anyone who wants this can really just drop a customized twig in app/Resources, or add an HTMLElement or Button to their application.
