### ISSUE TITLE
Document Contributing.md: Configuration Entities in Element

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#519]
Howto create them? Good coding example?

https://github.com/mapbender/search/edit/master/Entity/SearchConfig.php

**Comment by AxxL** [comment]
@werrolf Short sentence in Contributing that everything in Mapbender is standard symfony.

**Comment by werrolf** [comment]
The linked Entity is neither a Doctrine Entity nor an Element entity.  
There are no Configuration entities. The entity modeling Element configuration is the [Element Entity](https://github.com/mapbender/mapbender/blob/v3.0.7.7/src/Mapbender/CoreBundle/Entity/Element.php) itself, which is the same for any type of Element.
