### ISSUE TITLE
Print map: scale wrong

### ISSUE THREAD

**Issue by tbaschetti** [mapbender/mapbender#520]
When printing a map the scale is wrong in Mapbender 3.0.6. Tested on demo.mapbender3.org, application mapbender_user, just try the initial view in 1:25000. Choose Print => default values, 1:25000. The created pdf uses a much smaller scale, the printed scale and scalebar still refer to 1:25000
[mapbender3_20170507164426.pdf](https://github.com/mapbender/mapbender/files/981651/mapbender3_20170507164426.pdf)

**Comment by AxxL** [comment]
Seems that everything is shifted with a 0.

**Comment by AxxL** [comment]
Fix is on it's way.

**Comment by swinkelmann** [comment]
Fixed in the simplest possible way.
https://github.com/mapbender/mapbender/commit/b04b1dc419972dd3b25e6a7a49a342d729a615a1
