### ISSUE TITLE
- in package name when bin/composer build is used

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#522]
When I run the build comand 

`bin/composer build tar.gz mbtest_ 3060`

I except a package with the name **mbtest_3060.tar.gz**

But a package with the name **mbtest_-3060.tar.gz** is created

Suggestion. Delete - in code so people can fully define the package name.

**Comment by eSlider** [comment]
@astroidex, second provided parameter is an name of the project, third one is the version. 
The project name isn't called as "mbtest_".  Anyway, I can fix the way you wont, but I think this is bad idea.

**Comment by debugteam** [comment]
Better use this:

bin/composer build tar.gz mbtest 3060

And get this:

mbtest-3060.tar.gz

Underscore is ugly :zap:

**Comment by AxxL** [comment]
So wontfix.
