### ISSUE TITLE
update install_mapbender3.sh to version 3.0.6.0

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#523]
* https://github.com/OSGeo/OSGeoLive/blob/master/bin/install_mapbender3.sh
* schedule http://wiki.osgeo.org/wiki/Live_GIS_Disc#Schedule
* 22.5.2017 - installers complete

**Comment by AxxL** [comment]
@astroidex  Please describe in your ticket what happened in the work with Mapbender3, where you think an error occured and what you expected to happen.

Everything else should not be part of an issue tracker.

**Comment by astroidex** [comment]
thanks
