### ISSUE TITLE
change link to symfony documentation in parameters.yml.dist

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#524]
https://github.com/mapbender/mapbender-starter/blob/release/3.0.6/application/app/config/parameters.yml.dist

Now it says:
`http://symfony.com/doc/2.1/reference/configuration/framework.html#cookie-lifetime`

better

`http://symfony.com/doc/current/reference/configuration/framework.html#cookie-lifetime`

**Comment by LazerTiberius** [comment]
I would suggest that we use 2.8 docs http://symfony.com/doc/2.8/reference/configuration/framework.html#cookie-lifetime
