### ISSUE TITLE
Print: Specific WMS cannot be printed

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#525]
Specific WMS with raster data cannot be printed. Print service logs cryptic Print-URL. Maybe problem in the Capabilities?

See internal ticket 8185 for URL.

**Comment by AxxL** [comment]
Test running for:

"mapbender/mapbender": "dev-hotfix/print-content-type as 3.0.6.1",

- JPG, GIF
- Export Map.

**Comment by swinkelmann** [comment]
@AxxL please test it again. Should also work with jpeg and gif.

**Comment by AxxL** [comment]
OK thanks.
