### ISSUE TITLE
config.php is missing at mapbender3/web/config.php

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#526]
* as the file is missing in 3.0.6.0 you can't check http://localhost/mapbender3/config.php
* was there a reason to skip the file?
* it is refered in the Mapbender3 quickstart. http://doc.mapbender3.org/en/book/quickstart.html#start-mapbender-in-the-developer-mode-app-dev-php We would have to change the documentation if there is a reason to skip the file.

**Comment by AxxL** [comment]
@eSlider: Do we still need that file? Reasons for skipping?

**Comment by eSlider** [comment]
@AxxL, @astroidex this file comes originaly from Symfony Framework and is only for development purposes not for distribution. If you run `config.php`, then you becomes informed about PHP interpreter Version and installed components, also how they configured or misconfigure,  system installed components, not about Mapbender itself, so we don't need `config.php` file. 

@astroidex, config.php isn' trefered.

**Comment by astroidex** [comment]
HI @eslider - I know all this. We shipped it in all the last versions and it is very usefull. It is also mentioned in the documentation.
It makes it very easy for the Mapbender3 admin to check the system. And it is only accessible via localhost.

So please provide it again.

**Comment by eSlider** [comment]
@astroidex, done here: https://github.com/mapbender/mapbender/issues/526

**Comment by astroidex** [comment]
Thanks you ;)

**Comment by AxxL** [comment]
@eSlider @astroidex 

Andriy said it's for **development** purposes. The only reason is to check some settings in php.ini but you do that one time per php installation. I prefer to do it **not** in the release. If you need that file download it from Symfony itself.

I vote for removal.

**Comment by astroidex** [comment]
when I install mapbender3 from the release package on a new machine, I check with config.php whether all necessary extensions, parameters (time zone, extensions) are set for symfony. Nice feature. Only accessable from localhost. Nice to have.

**Comment by AxxL** [comment]
Back in 3.0.6.x. See #531 for nice enhancement.
