### ISSUE TITLE
Backend - Class .checkbox overlaps entries 

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#528]
Class .checkbox overlaps entries in Layer instances and ACL if there are more than ~ 50 entries.
All entries at the beginning of the list are not reachable by click (.checkbox html element overlaps these entries).

```
.checkbox{
  @include absolute(-9999px '' '' 0);
  height: 100%;
  width: 100%;
  @include opacity(0);
}
```

Tested with version 3.0.5.3, code also exists in 3.0.6 (bug probably exists there too).

To reproduce:
Load a WMS into Layer instance with many layers. Or configure many ACL entries.

**Comment by LazerTiberius** [comment]
@debugteam You fixed this in an another mb3-based project, don´t you?

**Comment by debugteam** [comment]
Haha, yeah... by setting 

  @include absolute(-999999px '' '' 0);

to bring the fullscreen checkbox :1st_place_medal: !!! out of view,

Consider it a dirty hack for a dirty process (the right way would be to display a "too many layers" error.

**Comment by LazerTiberius** [comment]
I don´t think that this should be an error if there are too many layers but we should maybe consider to implement paging or get rid of the broken way to hide the real checkboxes.  Maybe just go the bootstrap way and set the checkbox to display:none

**Comment by debugteam** [comment]
yeah paging, of course... but you have to take care on the "select all" functionality, which makes it kind of difficult to make a real improvement... and inline editing... and if you talk to more people you will find much more ways to improve this... However, IMHO creating more than 50 layers is the bug, not the software... 

display:none and moving a checkbox out of view makes a difference afaik

**Comment by AxxL** [comment]
@debugteam I don't understand exactly your comment but nevertheless:

We fix it with the css setting and increasing the position. Can you do that an make a pull request.

**Comment by CharlyUnicorn** [comment]
You can try this Landschaftspläne-WMS for testing: 
http://geo.kreislippe.de/cgi-bin/lp_alle.exe?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0
I don't have a test WMS with so many layers. 

If you load the WMS into the 3.0.5.3 MB3, then you can see the layers in the layerinstance, but you can't click or make every events.
If you load the WMS into the 3.0.6 MB3, then you can't see the layers or the layerinstance and you get a lot of errors/ warnings like this: 

```
[2017-05-17 10:24:24] php.INFO: Accessing type "checkbox" by its string name is deprecated since version 2.8 and will be removed in 3.0.
 Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\CheckboxType" instead. 
{"type":16384,"file":"/var/www/mapbender3_test/application/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php","line":100,"level":28928} []
```

**Comment by AxxL** [comment]
See internal #8193 for Testserver.

**Comment by AxxL** [comment]
So we have two things

- [ ] Layerset Instances dialogue (which I couldn't reproduce)
- [ ] ACL list (which is reproducable at internal testserver)
