### ISSUE TITLE
srs-Selector - on change the getMap-request is not right for WMS 1.3.0 and GK 2

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#529]
* srs-Selector - on change to GK2 the getMap-request is not right for WMS 1.3.0
* problem: request with wrong BBOX is requested for WMS 1.3.0

* see internal:  #7913 

* on change to GK2 the WMS "Mapbender user" in Version 1.3.0 is requested with the wrong BBOX (Coordinates in BBOX with WMS 1.3.0 must switch x and y)
*  BBOX wrong http://wms.wheregroup.com/cgi-bin/mapbender_user.xml?_signature=0%3AhDYlpow95Vwcp9kOyf1uCZTEY5E&TRANSPARENT=TRUE&FORMAT=image%2Fpng&VERSION=1.3.0&EXCEPTIONS=XML&SERVICE=WMS&REQUEST=GetMap&STYLES=,&LAYERS=Mapbender_User,Mapbender_Names&_OLSALT=0.3877219136654131&CRS=EPSG%3A31466&BBOX=2575607.7352352,5621505.6332728,2579841.0770352,5623247.4770343&WIDTH=2400&HEIGHT=987
* bbox right (was modified by hand) http://wms.wheregroup.com/cgi-bin/mapbender_user.xml?_signature=0%3AhDYlpow95Vwcp9kOyf1uCZTEY5E&TRANSPARENT=TRUE&FORMAT=image%2Fpng&VERSION=1.3.0&EXCEPTIONS=XML&SERVICE=WMS&REQUEST=GetMap&STYLES=,&LAYERS=Mapbender_User,Mapbender_Names&_OLSALT=0.3877219136654131&CRS=EPSG%3A31466&BBOX=5621505.6332728,2575607.7352352,5623247.4770343,2579841.0770352&WIDTH=2400&HEIGHT=987

**Comment by AxxL** [comment]
Branch https://github.com/mapbender/mapbender/commits/hotfix/srs_selector

**Comment by AxxL** [comment]
Pull Request: #564

**Comment by AxxL** [comment]
We changed the call to OpenLayers2 with the file mapbender.element.map.mapaxisorder.js which includes the coordinate systems that have the X/Y axis order reversed.

**Comment by swinkelmann** [comment]
The print is also ready for WMS version 1.3.0.
@AxxL please test printing with different EPSG an WMS versions.
still on branch: hotfix/change-axis-order

**Comment by AxxL** [comment]
@swinkelmann Error in Overview Map. Template attached.


[a4portrait.odg.zip](https://github.com/mapbender/mapbender/files/1155759/a4portrait.odg.zip)

**Comment by AxxL** [comment]
@swinkelmann @LazerTiberius Please check the pull-request and comment it here. Thanks. :)

**Comment by AxxL** [comment]
@swinkelmann @LazerTiberius Please check the pull-request and comment it here. Thanks. :)

@LazerTiberius Your thumb up is not a comment of the pull-request. :-)

**Comment by swinkelmann** [comment]
merged into release/3.0.6
