### ISSUE TITLE
Provide a console command to check Mapbender requirements

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#531]
Create a console command that can be run after installation of Mapbender3 to check some requirements and to give some information of the system-environment.

* Check Database Connections from parameters.yml
* Check required PHP libraries (see system-requirements)
* Tell if directories are writeable (Linux: who is owner and what are the rights)
  * app/logs
  * app/cache
  * web/uploads
  * web/xmlschemas
  * web (which rights, which user)
* Give out the contents of web/bundles and if they are symlinks or hardcoded.
* Check if running as FastCGI or as Modul (if possible)
* Give out several PHP.ini parameters (values if they are set, "not set" if they are not set).
  * enabled extensions
  * date.timezone
  * max_input_vars
  * MaxRequestLen
  * max_execution_time
  * memory_limit
  * upload_max_filesize
  * oci8.max_persistent
  * oci8.default_prefetch
  * session.save_handler
  * zend_extension
  * opcache.enable
  * opcache.memory_consumption
  * opcache.interned_strings_buffer
  * opcache.max_accelerated_files
  * opcache.max_wasted_percentage

Write the command that way that it can be integrated later into the Backend (after login as root) to run the checks in the webserver-environment (webserver user)

**Comment by eSlider** [comment]
@WGSZissner, you can use http://php.net/manual/de/function.ini-get-all.php function to get configuration variables.

**Comment by WGSZissner** [comment]
This Command Checks the Requirements for the Server

Step 1 (checkDatabaseConnection):
Check all configurated Database connections

Step 2 (checkPhpVersion):
check the Servers PHP version

Step 3(checkSystemRequirements):
checks if 'sqlite3', 'curl', 'gd', 'intl', 'mbstring', 'fileinfo', 'openssl' and 'bz2' are loaded
and if using php version 7 or greater check also if 'zip' and 'xml' are loaded

Step 4 (checkAssets):
Lists all Assetfolders and indicate whether they are symlinks or not.

Step 5 (checkFastCGI):
checks if FastCGI is enabled

Step 6 (checkModRewrite):
checks if ModRewrite is enabled

Step 7 (checkPhpIni):
Shows the Configurated parameter for 'date.timezeone', 'max_input_vars', 'MaxRequestLen', 'max_execution_time', 'memory_limit', 'upload_max_filesize', 'oci8.max_persistent', 'oci8.default_prefetch', 'session.save_handler', 'zend_extension', 'opcache.enable', 'opcache.memory_consumption', 'opcache.interned_strings_buffer', 'opcache.max_accelerated_files' and 'opcache.max_wasted_percentage'.
 
Step 8 (getLoadedPhpExtensions):
List all Loaded PHP extensions
 
Step 9 (checkPermissions):
Displays the Permission Owner and Group for 'app/logs/', 'app/cache/', 'web/uploads/', 'web/xmlschemas/' and 'web/' Directory

**Comment by AxxL** [comment]
Soweit super.

Change-request: Angabe der PHP.INI Datei beim Kommando. Per Default halt das CLI php.ini.

Bitte auch oben ausgeben, welche PHP.ini verwendet wird und dass die für das Web eventuell eine andere ist.

Für die Zukunft: Web-Seite (alleine, nicht in MB3), die die richtige MB3 nutzt.

**Comment by astroidex** [comment]
There is a new app/console command that checks the requirements.

`app/console mapbender:config:check`

We can close the ticket.
