### ISSUE TITLE
Upgrading LDAP solution for Symfony 2.8 

### ISSUE THREAD

**Issue by eSlider** [mapbender/mapbender#534]
For some special projects, which are based on Mapbender3  we build some custom LDAP solution based on the top of IMAG LDAP library, this we never shiped directly as solution with mapbender it self, but as `ImagLdapBundle`.

Now, after Symfony 2.3 -> 2.8 upgrading we have the Problem, this IMAG LDAP is never been updated since last 3 years and existing custom solution(s) will never working. Proof: https://github.com/BorisMorel/LdapBundle

But, since Symfony 2.8 there is an new LDAP component module avaible, this is surly "better-faster-stronger " and should be integrated.
Proof: http://symfony.com/blog/new-in-symfony-2-8-ldap-component

Background of required Symfony upgrading 2.3 ro 2.8 for releasing 3.0.6 version is the end of Symfony 2.3 life (no security updates anymore). Proof: http://symfony.com/doc/current/contributing/community/releases.html#schedule

Moreover we extract LDAP hidden functionality from "mapbender" and "fom" sub-modules to his own composer module(https://github.com/mapbender/ldap) as own playground this we can ship over composer as generic configurable solution for 3.0.7 Mapbender release.

Additional, this we have one more custom soltion: https://github.com/mapbender/ldapIntegrationBundle. 

What is required:
* [x] Mapbender LDAP Composer Module with his own Github repository: https://github.com/mapbender/ldap
* [ ] Integration of https://github.com/mapbender/ldapIntegrationBundle to Mapbender LDAP Composer Module 
* [x] Integrate new Symfony LDAP solution
* [x] Disintegrate IMAG LDAP 
* [ ] LDAP test environment as docker container 
* [ ] Composer module versioning definition
* [ ] Configuration and README documentation 
* [ ] Backward compatibility for existing projects  

Assotiated with: #494

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
