### ISSUE TITLE
Digitizer - allowCancelButton permanently displayed

### ISSUE THREAD

**Issue by nmoelkner** [mapbender/mapbender#536]
If you set "allowCancelButton: true", then there is a Cancel Button in the popup window, if you set it to "false", then there is no Cancel Button.
Problem: if there is no yaml definition for the Cancel Button, it is visible in the popup window!

use the yaml example from the digitizer element and add:
`allowCancelButton: true      #false`

**Comment by eSlider** [comment]
@nmoelkner, `allowCancelButton` is an option with `true` as default value. If you need to hide, overwrite or change position of the cancel button you may use this option.
