### ISSUE TITLE
Digitizer - allowDeleteByCancelNewGeometry default true?

### ISSUE THREAD

**Issue by nmoelkner** [mapbender/mapbender#537]
Suggestion: set the parameter allowDeleteByCancelNewGeometry: true by default

Test:
use the yaml example from the digitizer element and add:
`allowDeleteByCancelNewGeometry: true #false`

**Comment by AxxL** [comment]
+1

- [ ] Set the default-value in Digitizer to true.
- [ ] Document in Documentation

@eSlider Your opinion?

**Comment by eSlider** [comment]
@AxxL, I propose to change default behaviour for the next digitizer version (1.2).
https://github.com/mapbender/mapbender-digitizer/milestone/4
