### ISSUE TITLE
Backend Application Export - order application list by name

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#539]
* when you have many applications and you want to export one it is hard to find the application in the dropdown list as it is not ordered
* suggestion - order the list by abc

**Comment by eSlider** [comment]
@AxxL, we can use [select2](https://select2.github.io/) for this requirment.

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
