### ISSUE TITLE
Search Router - OpenLayers Error in application after update  to version 3.0.6.1

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#543]
I updated multiple Mapbender3 from version 3.0.5.3 to version 3.0.6.1. 
I used the search router element in my applications without any problems.
After the update I opened the application and couldn't use any functions related to the map-element/ OpenLayers.

The following error pops up: 

```
unreachable code after return statement
TypeError: OpenLayers is undefined

further Information Link: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default
```

- If I remove the searchrouter the application works. 
- If I delete the searchrouter and add a new searchrouter element the error still shows up.  
- If I update the existing element the error still shows up.
- If I create a new application or copy an existing application (with the error) the application works.

![auswahl_042](https://cloud.githubusercontent.com/assets/13517141/26587337/52b4a974-4552-11e7-8287-4e3bf96e78db.png)

**Comment by CharlyUnicorn** [comment]
perhaps it would be helpful, if you could load the assets from the map and then the assets from the searchrouter

**Comment by CharlyUnicorn** [comment]
new error workflow: 
if you have an application with the searchrouter and the digitizer then the application works after the update - but if you change something at the digitizer-yaml, then the same error pops up.

**Comment by CharlyUnicorn** [comment]
You can test this with the following application: 
* https://demo.mapbender3.org/application/mapbender_user_reference

**Comment by eSlider** [comment]
@RobinSchwammborn, can u check this?

**Comment by RobinSchwammborn** [comment]
I checked it, critical bug has been fixed.

**Comment by Urbai** [comment]
how to set up seach router in mapbender3 when we have for SGBD postgresql?

**Comment by Urbai** [comment]
Good morning every body,  how to set up seach router in mapbender3 when we have for SGBD postgresql?

**Comment by Urbai** [comment]
Hello, please help me.
 how to set up seach router in mapbender3 when we have for SGBD postgresql?

**Comment by astroidex** [comment]
Hello,

please update to https://mapbender.org/builds/3.0.6.3/ not 3.0.6.3

Urbai - please better send a mail to the mailing list. You can register here: https://lists.osgeo.org/mailman/listinfo/mapbender_users

**Comment by Urbai** [comment]
ok thank you, we are going to try it.
