### ISSUE TITLE
Move EPSG Axisorder into the database

### ISSUE THREAD

**Issue by LazerTiberius** [mapbender/mapbender#546]
The in 3.0.6.3 introduced declaration for the axis order for specific EPSG-Codes is currently  defined in one javascript array. We should move this into the database and extend it to all OpenLayers.projection.defaults, so we can manage these defaults in the future.

**Comment by AxxL** [comment]
See #529 
Changes are done in the file.
Pull Request was: #564

**Comment by AxxL** [comment]
Vorschlag von @eSlider Vereinheitlichen mit der epsg-code Tabelle in der MB3 Datenbank!
Gute Idee. 
*daumen hoch*
