### ISSUE TITLE
Remove OL2 from mapquery

### ISSUE THREAD

**Issue by LazerTiberius** [mapbender/mapbender#547]
We should consider resolving our Ol2 dependency directly over the openlayers/ol2 repo instead of using the build in version of mapquery. There are still some people fixing bugs in OL2. I think it should be possible to override the mapquery version of ol2 with the newest release of ol2 using the component installer.  Another solution would be to regularly update our mapquery fork.

**Comment by eSlider** [comment]
@LazerTiberius we should update OpenLayers2 inside of mapquery itself, course of custom OL2 bug fixes.

Mapquery library location: https://github.com/WhereGroup/mapquery/tree/master/lib/openlayers
