### ISSUE TITLE
Button - Highlight and selection of POI-button in group

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#549]
You can add buttons in the toolbar of an application. You can group these buttons by the function "group". This function adds the element to a group. Only one button of the group may be activated and these button is highlighted in a different color. 
If you close the window of the selected button, then the highlighted button is deactivated and the special coloring should disappear. 

This function works very well except for the button of the POI-function. 
If you add a button for the poi-funktion, add it to the group and activate this button, then these button is highlighted in a different color. But when the button is disabled, the color highlighting is still active until you click another button. 

![auswahl_028](https://user-images.githubusercontent.com/13517141/27431088-79a333a6-574b-11e7-9b96-5b6304085d5c.png)

You can test this: 
- https://demo.mapbender3.org/application/buttons_group
- Click on a button and close the popoup via the "close" button
- should work fine exept for the poi-button

**Comment by AxxL** [comment]
@CharlyUnicorn Was willst Du denn mit den Gruppen erreichen?
Soweit ich sehe, hat die Legende das gleiche Problem.

**Comment by werrolf** [comment]
Auto-closed by Github commit message parsing. Fixed in [ea18664](https://github.com/mapbender/mapbender/commit/ea18664fc2e618ae77de3233376896a207cb754f).
