### ISSUE TITLE
SRS Definition - EPSG-Codes 3034, 3035 and 4258

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#550]
The EPSG-Codes 3034, 3035 and 4258 are in the proj4js._epsg.txt and you should be able to display your data at the map by adding the codes in your map-element. 

```
 /var/www/mapbender3_test/application/mapbender/src/Mapbender/CoreBundle/Resources/proj4

  EPSG:4258|ETRS89|+proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs
[...]
  EPSG:3034|ETRS89 / LCC Europe|+proj=lcc +lat_1=35 +lat_2=65 +lat_0=52 +lon_0=10 +x_0=4000000 +y_0=2800000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
  EPSG:3035|ETRS89 / LAEA Europe|+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
```

- Load an WMS (with the requested EPSG-Codes 3034, 3035 and 4258 in the WMS_SRS) in your Layerset
- Add the EPSG-Codes  3034, 3035 and 4258 in your map-element and activate the srs-selector
- Switch between the srs in the application (add other epsg-codes like 4326 to see something....)

You can test with this wms: 
- http://wms2016.wheregroup.com/cgi-bin/mapserv?map=/data/umn/test/test.map&Version=1.3.0&Service=WMS&REQUEST=getCapabilities

**Comment by eSlider** [comment]
Related to: #562

**Comment by AxxL** [comment]
@CharlyUnicorn I've tested it in branch hotfix/epsg-code-list.

EPSG:3034 doesn't give an answer and that happens also in QGIS.

**Comment by AxxL** [comment]
Related to #529 not #562
