### ISSUE TITLE
Frontend: FeatureInfo Button Print does not have its own translation and shows mb.core.printclient.popup.btn.ok

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#552]
* Button print in Feature Info has not its own translation. So when you disable printClient the translation is missing and instead the text **mb.core.printclient.popup.btn.ok** is displayed
* has to be fixed in script https://github.com/mapbender/mapbender/blob/release/3.0.6/src/Mapbender/CoreBundle/Resources/public/mapbender.element.featureInfo.js#L416

* new translation has to be added to and all other languages: https://github.com/mapbender/mapbender/blob/release/3.0.6/src/Mapbender/CoreBundle/Resources/translations/messages.en.yml#L8

![feature_print_missing_translation](https://user-images.githubusercontent.com/996298/27826904-2f512204-60b5-11e7-96f8-c715483c8691.png)

**Comment by eSlider** [comment]
Fixed here https://github.com/mapbender/mapbender/commit/d11dd2fd1bde139225a388ddb6d125cb24562260

**Comment by astroidex** [comment]
HI eSlider - please check this hotfix: https://github.com/mapbender/mapbender/pull/553

**Comment by AxxL** [comment]
@eSlider Can you please check if https://github.com/mapbender/mapbender/commit/d11dd2fd1bde139225a388ddb6d125cb24562260 or #553 is better.

If #553, then revert/refix your change in https://github.com/mapbender/mapbender/commit/d11dd2fd1bde139225a388ddb6d125cb24562260

Thanks.

**Comment by eSlider** [comment]
@AxxL, I revert the commit https://github.com/mapbender/mapbender/commit/d11dd2fd1bde139225a388ddb6d125cb24562260
