### ISSUE TITLE
New Option in Layerset Instances "Layer order reversed"

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#554]
With the rising emergence of the fabulous QGIS Server we need to add an option how WMS layers are put into the layertree and in which order they are rendered. Right now we followed the mapserver approach, where we parsed the capabilities from top to bottom. First layer was drawn first, second layer at second on top of the first and so on. With QGIS Server the Capabilties document follows the configuration of the QGIS project and the desktop layer order of the layertree. So in general points are at top and polygons at the bottom.

So, place an option into the layerset dialog (when adding a wms to an application) where you set:

- [x] Layerorder reversed (QGIS style)

For backwards compatibility: Set it to false for default.

That means: If the option is not checked, the layers are placed into the layertree like it is, beginning at the bottom and ending at the top. The service is displayed in the layertree in reversed order.

If checked, layers are placed into the layertree from top to bottom, the layertree shows the service not in reversed order but like the definition in the Capablities

``` org
|                                        | layer order not reversed | layer order reversed |
|----------------------------------------+----------------------+--------------------------|
| WMS Capabilities (from top to bottom)  | polygon, line, point | point, line, polygon     |
| Layerset-Instance (from top to bottom) | polygon, line, point | point, line, polygon     |
| Layertree  (from top to bottom)        | point, line, polygon | point, line, polygon     |
```

Why do we know what is the default? See the OGC WMS 1.3 Demo and Reference Server documentation: http://www.opengeospatial.org/standards/wms/quickstart

WMS-URL: http://metaspatial.net/cgi-bin/ogc-wms.xml?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3

**Comment by AxxL** [comment]
A new demo-WMS:

https://wms2016.wheregroup.com/cgi-bin/schwalmtalgroup/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

Layers:

- 1Punkt
  - 11Bohrungen
- 2Linie
  - 22Hoehenlinien
- 3Polygon
  - 31Bodenarten (not visible per default)
  - 32Landnutzung (this is the visible one per default)

**Comment by AxxL** [comment]
New demo app: https://test.mapbender.org/mapbender/application/test_554

**Comment by AxxL** [comment]
Example for OGC Reference WMS (traditional style): https://test.mapbender.org/mapbender/application/test_554_b
Is in Britain.

**Comment by AxxL** [comment]
https://github.com/mapbender/mapbender/pull/704

**Comment by AxxL** [comment]
Documentation: https://github.com/mapbender/mapbender-documentation/pull/30

**Comment by CharlyUnicorn** [comment]
I support the opinion of @astroidex in the following comment: https://github.com/mapbender/mapbender/pull/704#issuecomment-358225055

A checkbox instead of selectbox would be nice for the workflow and design. The label with "QGIS Server" is not realy correct - the label should be kept neutral and not limited to software...
