### ISSUE TITLE
PrintClient error when printing legend - Notice: Undefined variable: yStartPosition

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#555]
* when you print with legend an error occurs when you do not use legend on first page

```
Notice: Undefined variable: yStartPosition
500 Internal Server Error - ContextErrorException 
```

**Comment by AxxL** [comment]
Can you give an example to test the pull-request #556?

**Comment by astroidex** [comment]
just print with legend on second page.

**Comment by astroidex** [comment]
Issue is not a big thing. Showed it @eSlider already. With the change 

> yStartPosition will only be checked when legend-frame on first page exits

I tested the change.

**Comment by AxxL** [comment]
> just print with legend on second page.
in 3.0.6.1: 
[mapbender3_20170713141210.pdf](https://github.com/mapbender/mapbender/files/1145062/mapbender3_20170713141210.pdf)

**Comment by astroidex** [comment]
looks fine. Before pdf was not created and print failed because variable yStartPosition was not defined.

**Comment by AxxL** [comment]
@astroidex Die Entwickler brauchen ein Beispiel, um den Code zu prüfen und den Pull-Request zu reviewen. Es ist klar, dass der Fehler ist, dass "variable yStartPosition was not defined." Aber unter welchen Umständen, weil es funktioniert ja scheinbar in 3.0.6.1.

**Comment by astroidex** [comment]
I talked with @eSlider about the PR already. Just a minimal change in the script. Please talk to Andriy. He read the code.

In some installations the following error occurs, but not in all....
```
Notice: Undefined variable: yStartPosition
500 Internal Server Error - ContextErrorException 
```

**Comment by eSlider** [comment]
@astroidex, we talk about the topic, but still don't have an example, this represent errors you have, so we decide to move this ticket to the next release

**Comment by CharlyUnicorn** [comment]
Hello, 
I tested it with the following wms: 
http://wms.wheregroup.com/cgi-bin/mapserv62?map=/data/umn/germany/germany_group.map&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0

workflow: 
- add the wms to your application 
- zoom to germany
- choose the template a4portrait
- enable print legend 
- start print
- error appears
- no error if you disable print legend or print with the legend on the first page (template a4landscape)

```
in mapbender/src/Mapbender/PrintBundle/Component/PrintService.php at line 1134  -
                        // print legend on first page
                        if(($y-$yStartPosition) + $tempY + 10 > $height && $width > 100 && $legendConf == true){
                            $x += $x + 105;
                            $y = $yStartPosition + 5;
                            if($x - $xStartPosition + 20 > $width){

at ErrorHandler ->handleError ('8', 'Undefined variable: yStartPosition', '/var/www/legend-image-refactoring/application/mapbender/src/Mapbender/PrintBundle/Component/PrintService.php', '1134', array('height' => '297.00008333333', 'width' => '210.00155555556', 'x' => '5', 'y' => '65', 'legendConf' => false, 'legendArray' => array('laender mit info' 
=> 'http://wms.wheregroup.com/cgi-bin/mapserv62?map=/data/umn/germany/germany_group.map&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=laender_info&format=image/png&STYLE=default') 
[...]


```

**Comment by eSlider** [comment]
@CharlyUnicorn, did you test this merge request https://github.com/mapbender/mapbender/pull/556?

**Comment by CharlyUnicorn** [comment]
Hello, 
I tested the workflow with the merge request #556
It works fine!

**Comment by AxxL** [comment]
This is reproducable **under certain circumstances**:

If you run the bootstrap script with app/console server:run, the error occurs. If you register the application in Apache the default way, the error doesn't occur.

@eSlider Any hints on that?

**Comment by AxxL** [comment]
Steps to reproduce:

* Checkout master
* Run bootstrap
* Open localhost:8000
* Import the application / import service
* Print with legend on

**Comment by eSlider** [comment]
@AxxL, maybe you have different PHP versions in CLI(Bootstrap) and binded on Apache?

**Comment by AxxL** [comment]
No. Both: v7.0.22-0ubuntu0.16.04.1

Maybe the CLI version is missing some libraries? Therefore the fix wouldn't be needed because missing system-requirements in CLI?

**Comment by AxxL** [comment]
@eSlider To be clear: The error is a notice:

> Notice: Undefined variable: yStartPosition
500 Internal Server Error - ContextErrorException

**Comment by eSlider** [comment]
Ok, @AxxL. this is an notice and yes notice is a error and this error is a possible bug. 
Now we can reproduce the error-notice aka possible-bug. What is the next step?

More about notice error in PHP [here](http://php.net/manual/en/errorfunc.configuration.php#ini.error-reporting)

**Comment by AxxL** [comment]
We leave it like it is but next time we have to assure that bugs are reproducable and the steps to reproduce are clear.

Again: That issue didn't occur in any of the testing environments.

**Comment by astroidex** [comment]
This error occurs with a fresh Ubuntu 16.4. with the default configuration.
- Apache 2.4.x
- PHP 7.0.x

Default error reporting configuration in php.ini

> error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

**Comment by werrolf** [comment]
Done. I.e. reverted the revert.
See pull #656.
We fix notices full stop.
