### ISSUE TITLE
Translation update

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#557]
* update existing translations (en, de, it, es, ru, nl, pt)
* add new translations

ToDo
* check all yml files from existing languages
* check the documentation - is all information provided to write translations? https://github.com/mapbender/mapbender-documentation/blob/hotfix/translations/en/book/translation.rst
* add new languages

**Comment by astroidex** [comment]
french translation was done by @patrice-geo in fom and mapbender. already merged the pull requests
- https://github.com/mapbender/fom/pull/32
- https://github.com/mapbender/mapbender/pull/579


- issue was opened by @patrice-geo #578 Translations: Some text don't have a placeholder and can't be translated

**Comment by werrolf** [comment]
Everything merged a good while ago.
