### ISSUE TITLE
Link-redirection doesn't always work correctly

### ISSUE THREAD

**Issue by Robert-SLA** [mapbender/mapbender#558]
Hey there,

this is Robert from the SLA in Hannover (where Astrid did a nice workshop for me and my colleagues last week). We're already using Mapbender for several projects but are still comparatively new to the whole thing.

One of the things we're trying to do is to create a framework for someone outside of our office, so he can fiddle around a bit, get used to it and ultimately create a framework for himself and his colleagues. So far no problem there.
The matter is though, for every of his actions Mapbender has to redirect the URL-address because he's not allowed to enter our network directly. And that isn't working everywhere in the GUI. Some buttons always use the redirected address while others never do so.
With Mapbender behaving that way it's impossible for our guy to use it, since some functions are just out of his reach.

I've tried to make a list of what's working and what's not, hoping to recognize some kind of pattern. But I can't really find one (apart from lots of 'Cancel'-buttons). In the attached txt-file ou can see what I got.
[Mapbender_TEST_Errors.txt](https://github.com/mapbender/mapbender/files/1135987/Mapbender_TEST_Errors.txt)

Maybe one of you has an idea or sees something that we don't. Any help or advice is appreciated.

Cheers, Robert

**Comment by astroidex** [comment]
Hello Robert,

thanks for the ticket and list. With the list we can check where the problem is an why some links are right and some not.

Astrid

**Comment by AxxL** [comment]
@Robert-SLA Hi Robert. Can you please call me directly here at the WhereGroup to clarify your issue so that we can investigate and update this ticket? Thanks. :-)

**Comment by AxxL** [comment]
OK, some insights:

* The URL in backend on the left menu: Application -> New Application is relative (/mapbender/manager/application/new)
* The URL on the Plus button on the right upper corner (for a new application) is absolute.(http://localhost/mapbender/manager/application/new)

First step: @eSlider we check if this can be made relative. That would lead to a more homogen form.

**Comment by Robert-SLA** [comment]
Hey there,

thanks again for the insights.
Can you tell me, when you plan to implemented these changes (_meaning: all buttons using relative URLs_)? Or is there already a version doing that and it's simply under our radar?

Cheerio, Robert

**Comment by werrolf** [comment]
Not clear from the description what the problem is but we [recently changed ManagerBundle url generation](https://github.com/mapbender/mapbender/pull/1061) to improve compatibility with reverse proxies with URL prefixes or internally unknown host names.

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
