### ISSUE TITLE
Update proj4js_epsg.txt

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#562]
Update File src/Mapbender/CoreBundle/Resources/proj4/proj4js_epsg.txt

**Comment by AxxL** [comment]
Change:

- [ ] 4326 Geographisch, weltweit:
- [ ] 25832 ETRS89 / UTM zone 32N und 33N:
- [ ] 25833 ETRS89 / UTM zone 32N und 33N:
- [ ] 31466 Gauß-Krüger Zonen 2 bis 5:
- [ ] 31467 Gauß-Krüger Zonen 2 bis 5:
- [ ] 31468 Gauß-Krüger Zonen 2 bis 5:
- [ ] 31469 Gauß-Krüger Zonen 2 bis 5:
- [ ] 3044 ETRS89 / UTM zone 32N und 33N
- [ ] 3045 ETRS89 / UTM zone 32N und 33N
- [ ] 5243 ETRS89 / LCC Germany (Lambert) E-N und N-E
- [ ] 4839 ETRS89 / LCC Germany (Lambert) E-N und N-E
- [ ] 3857 WGS 84 / Pseudo-Mercator -- Spherical Mercator
- [ ] 31254 MGI Austria GK West
- [ ] 31255 MG Austria GK Central
- [ ] 31256 MG Austria GK East
- [ ] 3035 ETRS89 / LAEA

**Comment by LazerTiberius** [comment]
Please add also 
* [ ] EPSG:25832 ETRS89 / UTM zone 32N
* [ ] EPSG:3068 DHDN / Soldner Berlin
to the list

**Comment by AxxL** [comment]
@LazerTiberius Thanks.

Checked the systems and created pull reques #563

**Comment by AxxL** [comment]
command:

``` zsh
/srv/mapbender/306/application (git)-[release/3.0.6] % php app/console doctrine:fixtures:load --fixtures=mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Epsg/ --append
  > loading Mapbender\CoreBundle\DataFixtures\ORM\LoadEpsgData
EPSG updated: 3910, imported: 2
```
