### ISSUE TITLE
WMS: If a ScaleHint is defined, Mapbender uses Scale 1:1 for Sublayers

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#565]
Create new WMS DataSource:

http://wms2016.wheregroup.com/cgi-bin/mapserv?map=/data/umn/test/test.map&Version=1.3.0&Service=WMS&REQUEST=getCapabilities

Put Layerset-Instance in application.

Watch the Max-Scale/Min-Scale for the Layers "Mapbender Users" and "Mapbender Info". It is 1:1.

The Capabilities defines a Scale-Hint. Mapserver gives it out differently.
For 1.3.0:

```xml
<Layer>
  <Name>TEST_EPSG</Name>
  <Title>TEST EPSG</Title>
  [...]
  <MinScaleDenominator>1</MinScaleDenominator>
  <MaxScaleDenominator>1e+17</MaxScaleDenominator>
```

For 1.1.1
```xml
  <Layer>
    <Name>TEST_EPSG</Name>
    <Title>TEST EPSG</Title>
    [...]
    <ScaleHint min="0.000498902848429637" max="49890284842963.7" />
```

That is set correctly in the Root Layer for the Layerset-Instance. The min 1 / max 1 scales are wrong and are not defined in the WMS Capabilities.

See attached screenshot.

![auswahl_043](https://user-images.githubusercontent.com/2235393/28156534-790e4872-67b3-11e7-95f4-c2fc450a0da3.png)

**Comment by LazerTiberius** [comment]
#572

**Comment by eSlider** [comment]
@AxxL, please check `fix/wrong-scaleHint-in-sublayers` branch

**Comment by AxxL** [comment]
Tested with:

* http://wms2016.wheregroup.com/cgi-bin/mapserv?map=/data/umn/test/test.map&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0

* http://wms2016.wheregroup.com/cgi-bin/mapserv?map=/data/umn/test/test2.map&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0

OK.
