### ISSUE TITLE
Alternative for proj4js_epsg.txt

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#567]
File `src/Mapbender/CoreBundle/Resources/proj4/proj4js_epsg.txt` is for fixtures install 
```sh
app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Epsg/ --append
```

We updated and checked the definitions for the most common ones ( #562 ), but the file needs an update for lesser common ones.

- [x] Find an alternative source for the file or define a script to update the file.
- [ ] You can change the structure of the file if you like (JSON, whatever)
- [ ] Adjust the fixtures command, if the structure has changed.
- [ ] Add the possiblity in the fixture command to update the database. If clearing neccessary, let's ask the community first.

**Comment by eSlider** [comment]
Alternative EPSG codes source can be:
* PostGIS `spatial_ref_sys`  datbase table  
* Spatialite `spatial_ref_sys` datbase table
* OSGeo proj.4 definitions file https://github.com/OSGeo/proj.4/blob/master/nad/epsg

**Comment by AxxL** [comment]
see https://github.com/mapbender/mapbender/issues/546

Can be closed.
