### ISSUE TITLE
Change Translation-Format from XLIF to YAML for Modules

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#568]
Some modules still have the XLIF format for translations. Our experiences with YAML in mapbender-module are good. So in the process of improve the translations itself we change the format from XLIF to YAML in the corresponding modules.

These are:

- [x] FOM: https://github.com/mapbender/fom/pull/31
- [x] OwsProxy: https://github.com/mapbender/owsproxy3/pull/10
- [x] Map-Tools: https://github.com/mapbender/map-tools/pull/3

**Comment by astroidex** [comment]
* see also Ticket #557 about translations

**Comment by astroidex** [comment]
* map-tools, fom, owsproxy - changed from xlif to yml

**Comment by eSlider** [comment]
* FOM: https://github.com/mapbender/fom/pull/31
* OwsProxy: https://github.com/mapbender/owsproxy3/pull/10
* Map-Tools: https://github.com/mapbender/map-tools/pull/3

**Comment by AxxL** [comment]
This is the technical issue, not the content-specific translations-issue. This here is about the (fundamental) change in Mapbender3, for version-information.

**Comment by astroidex** [comment]
I think we can close this issue
