### ISSUE TITLE
Connect to SSL WMS with wrong certificate

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#569]
I know this is a network issue and should be fixed in the web-server of the corresponding WMS provider. But is it possible to make a checkbox in "Add WMS Server" to connect to HTTPS with an invalid certificate? User should know what he messes with.

Error in prod.log is:

`"CommonProxy->handle :SSL: no alternative certificate subject name matches target host name [...]"`

Possible solution:

- [ ] Checkbox on "Add WMS": Connect, even if insecure TLS
- [ ] Avoid certificate error
- [ ] Give it a nice symbol in the list of WMS services. Like a red lock as in the webbrowsers.

**Comment by AxxL** [comment]
Discussion in open. Please put your opinion in the comments. :)

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
