### ISSUE TITLE
Redlining: Printing Text is too small for DPI=288

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#573]
If you redline something and print it out in 288 DPI, the text appears to small and should be 4x higher. Is a regression.

edit: Points can also gain some additional weight, please.

**Comment by AxxL** [comment]
A small example (https://demo.mapbender3.org/application/mapbender_user_wms2016)

**Comment by swinkelmann** [comment]
This bug was already fixed.
See #493
It has not been merged yet. I dont know why.

**Comment by LazerTiberius** [comment]
@swinkelmann  #493  has still an open issue like @eSlider commented in the pull request

**Comment by astroidex** [comment]
@swinkemann - could you have a look at #93 and the pull request? It should be more or less ok

**Comment by swinkelmann** [comment]
Fixed.
branch: hotfix/print-redline-size
Pull Request: #575

@AxxL please have a look.

**Comment by AxxL** [comment]
Fixed.

**Comment by AxxL** [comment]
Merged.

Waiting on Branch delete and update composer.json and composer.lock

**Comment by eSlider** [comment]
Composer dependence became upgedated
https://github.com/mapbender/mapbender-starter/commit/c3521f5f385ad31e60e04766cf3260d308413b08
