### ISSUE TITLE
Translations: Some text don't have a placeholder and can't be translated

### ISSUE THREAD

**Issue by patrice-geo** [mapbender/mapbender#578]
While translating to French, I saw that a quite a few text doesn't have a placeholder that would enable translation for it. I changed the language to DE and ES and some of the text stays in english.

**Comment by astroidex** [comment]
Hello @patrice-geo,
thanks for the feedbak. Yes you are right. Still some textes are still in english. They are referred fixed like this in the elements.

I thought it will be the next step to have a look at all the elements and find the places where no translation exists. Maybe @BLorenzWG can do this in the next time. After that we have to make a second smaller sprint to translate the missing words.

**Comment by astroidex** [comment]
Thanks for the comment. Added label Translation and removed milestone 3.0.8

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
