### ISSUE TITLE
Adding elements in backend can fail with "Warning: usort(): Array was modified ..."

### ISSUE THREAD

**Issue by werrolf** [mapbender/mapbender#586]
Trigger / test by going to the backend, edit any application, click the "+" to add an element, choose a Button. On some PHP versions, the next dialog (Button properties) already fails to render. Success depends on PHP version currently (see below).

The error occurs (or not, on unaffected PHP version) when sorting the dropdown values for the "Target" of the new Element.
The error is traced to TargetElementType::buildView:
https://github.com/mapbender/mapbender/blob/v3.0.6.2/src/Mapbender/CoreBundle/Element/Type/TargetElementType.php#L134

This is a bug in PHP where usort "believes" any comparison callable with exception handling is modifying the array to sort.
https://bugs.php.net/bug.php?id=50688

Affected PHP issues a warning with text "Warning: usort(): Array was modified by the user comparison function" at /data/mapbender3062/mapbender/src/Mapbender/CoreBundle/Element/Type/TargetElementType.php line 137", which Symfony promotes to a Symfony\Component\Debug\Exception\ContextErrorException.

The PHP ticket is not updated with fix targets and has not been mentioned in PHP changelogs. We do know PHP 7.0.8 / 7.1.5 are not affected. Really old PHP is not affected. The PHP bug was introduced in PHP 5.2.11. The PHP bug and this Mapbender issue have been observed in the wild on PHP 5.6.4.

Suggestion: replace usort with array_multisort. PR is being prepared.

**Comment by CharlyUnicorn** [comment]
Please change the documentation, if the php version 5.6.4 or older versions are not supported. Only needed if the bug isn't fixed in the next version: 
*  https://doc.mapbender3.org/en/book/installation/systemrequirements.html

> Mapbender3 needs the following components in order to run:     PHP 5.5.4 or later (php5)
