### ISSUE TITLE
Unique text and user-description for WMS sources

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#591]
Add two fields to the Sources (https://test.mapbender3.org/manager/repository):

- Custom_Name: Unique and custom name for my WMS source. Empty at first. Optional. But unique (hope that works). But I can give it a name. The user can give a name as he likes, but prevent some characters like umlauts and blanks. It has to be technical. Background: Easy identification for exporting and importing yaml applications. You cannot uniquely identify a WMS by its Capabilities. A WMS has a name (mostly "WMS") and a title (in my case mostly "Schwalmtal", but they are different WMS.) ;-). So I can give it a custom name.

BTW (informational): INSPIRE defines a unique WMS. Hurray! But not all WMS are INSPIRE. Booh.

- Custom_Description: A description for the WMS source. I personally have 5 Schwalmtal testservices from 2 different WMS providers (Mapserver and QGIS Server). Sometimes I can not differentiate them. Therefore I want to have a description field to write something to that like: "This is my QGIS testserver".

Both fields have a different purpose. Custom_name is for later, for application copying, moving Mapbender from a test-machine to a production machine. Description is really the nice thing.

Where to display the fields:

- On creating a new data-source (http://localhost/mapbender/manager/repository/new) as writeable fields.

![auswahl_044](https://user-images.githubusercontent.com/2235393/33891170-6bb99f86-df55-11e7-848f-9220f4f5eb60.png)

- At the list of all data-sources (http://localhost/mapbender/manager/repository) as read-only.

![auswahl_045](https://user-images.githubusercontent.com/2235393/33891178-7212ffee-df55-11e7-82b3-98df9d093d28.png)

- At the details of a data-source as a writeable field, because you need a place to change the text (http://localhost/mapbender/manager/repository/source/1). You can put it into "Metadata tab" or create a new one.

![auswahl_046](https://user-images.githubusercontent.com/2235393/33891189-7bf2a47e-df55-11e7-8c94-d4d1b3124309.png)

- At the list, where I add a Layerset-instance to my application as a read-only field in the list of data-sources (Application, Layersets, the plus-button of a layerset (the smaller one, not the big one).

![auswahl_047](https://user-images.githubusercontent.com/2235393/33891195-7fcb77b0-df55-11e7-9473-e4d6f53ac0d7.png)

**Comment by eschuettler** [comment]
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html
