### ISSUE TITLE
PrintClient - Print is not in new tab (application dissapears) 3.0.6.3

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#598]
By starting a print job in the application a print job is started in a new tab. In the previous tab the application is still open. After the print job has finished, the second tab is closed and the PDF has been ejected.

Bug: In version 3.0.6.3, the print job is opened in the same tab as the application and the application tab disappears when the PDF is finished. The previous behavior should be restored, because your whole workspace dissapears.

Test sequence: 

1.  Open application (see below)
2.  Activate print button
3.  Select print scale etc. and press Print. Waiting...

You can test this with the following applications: 
- https://version.mapbender3.org/3062/application/mapbender_user (correct behaviour)
- https://version.mapbender3.org/3063/application/mapbender_user (false behaviour)

**Comment by CharlyUnicorn** [comment]
Does not happen anymore... i watch this.

**Comment by AxxL** [comment]
I close this as invalid until the error reappears. Thanks. :)
