### ISSUE TITLE
Element Change Background with sorting function

### ISSUE THREAD

**Issue by Poldy1705** [mapbender/mapbender#599]
Element Change Background Layer: (Mapbender 3.0.6.3)
It's very hard to configure your Baselayers without the possibility to sort them. Espacily when you try to insert new configured Layers at a certain position. Currently you have to reconfigure all of your Instancesets.
I think it's better to give the element the possibility to sort the Instancesets by Drag&Drop and insert new Instancesets at any desired position.

**Comment by astroidex** [comment]
Hello @Poldy1705 , you are absolutely right with the wish to be able to sort the Instancesets by Drag&Drop.

Let's ask @AxxL and the developer to estimate the effort.

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
