### ISSUE TITLE
Appearance of WMS Layer on Mobile Devices

### ISSUE THREAD

**Issue by Poldy1705** [mapbender/mapbender#600]
Mapbender 3.0.6.3 (Mobile template)

The appearance of WMS Layer on mobile devices looks very blurry.
I implemented the same wms sources in a leaflet web application and it looks much better.
In the layer description of the leaflet project i have the possibility to specify a parameter wich is called "detectRetina: true" which is responsible for the appearance on mobile devices.

**Comment by CharlyUnicorn** [comment]
HiDPI Support is in OL3+ implemented: https://github.com/openlayers/openlayers/blob/bdced571625ef2493377ba661fc48b8c0afa0e12/examples/wmts-hidpi.js

Apperance in other WebClient (left) and Apperance in Mapbender3 (right): 

![white](https://user-images.githubusercontent.com/13517141/29362244-7aceff24-828b-11e7-847d-3e025da5f495.jpg)

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
