### ISSUE TITLE
Display Baselayers in Sidepane Layerlist

### ISSUE THREAD

**Issue by Poldy1705** [mapbender/mapbender#601]
Mapbender 3.0.6.3

I configered the Element "Change Background Layer" in a sidepane. Currently there is no possibility to display the layers in a list form. It's only poosible for the Layer Tree Element

**Comment by CharlyUnicorn** [comment]
you can configure your basesourceswitcher in the sidepane via css-configuration: 

```
  .mb-element-basesourceswitcher li {
      padding: 4px 150px 4px 30px;
      background-color: transparent;
      color: black;
      transition: all 0.2s ease-in-out;
      position: relative;
      border: solid 0.5px grey;
          border-right-width: 0.5px;
          border-left-width: 0.5px;
      border-right-width: 0px;
      border-left-width: 0px;
  }
```

if you use the configuration shown above your basesourceswitcher looks like this: 


![basesourceswitcher](https://user-images.githubusercontent.com/13517141/29362638-10e2a69a-828d-11e7-876d-ce400c19406e.png)

**Comment by CharlyUnicorn** [comment]
Nice info from the mailinglist about this topic: 
http://osgeo-org.1560.x6.nabble.com/Tipps-and-Tricks-Mapbender-BaseSourceSwitcher-german-and-english-version-td5320634.html

**Comment by Poldy1705** [comment]
Thanks.
But the Layer Tree is in list form by default

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
