### ISSUE TITLE
Print: scale bar units

### ISSUE THREAD

**Issue by arimonma** [mapbender/mapbender#603]
"Nice to have" (MB 3.0.6.3):

Within the Map Viewer the scale bar shows "m" or "km" - depending on scale. Unlike this the print version (PDF) always shows "m". When using small scales this is not appropriate (e.g. at scale 1:5,000,000 I would prefer "250km" instead of "250000m".

As I'm not a php developer I fixed this only locally. Maybe you wish to apply it (or something similar) within the standard mb3 version:

File: ...\htdocs\mapbender\src\Mapbender\PrintBundle\Component\PrintService.php

In: "private function addScaleBar()"...
...I changed:
```
        $length = 0.01 * $this->data['scale_select'] * 5;
        $suffix = 'm';
```
...to:
```
        if ($this->data['scale_select'] > 20000) {
        	$length = 0.00001 * $this->data['scale_select'] * 5;
        	$suffix = 'km';
        } else {
        	$length = 0.01 * $this->data['scale_select'] * 5;
        	$suffix = 'm';
        }

```
![mb3_print_scalebar_oldversion](https://user-images.githubusercontent.com/18737232/29464008-d57dbd34-8434-11e7-9801-142ce4a18a8b.PNG)
![mb3_print_scalebar_newversion](https://user-images.githubusercontent.com/18737232/29464123-2a390932-8435-11e7-977f-ada3f4f5055f.PNG)

**Comment by AxxL** [comment]
Note to me: Needs estimation

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
