### ISSUE TITLE
Console app crashes after awry input

### ISSUE THREAD

**Issue by Tooowanda** [mapbender/mapbender#607]
Mapbender v.3.0.6.1
While trying to generate an element via app/console mapbender:generate:element I had a typo (missing quotation marks in filepath ). The console app then crushed totally, displaying only the following exception:
[InvalidArgumentException] The name must not contain "."
(There was no dot anywhere in the command)
Neither could I break/exit the console app nor execute any other commands.

The provisional solution was to comment out the concerned Bundle at the registerBundles-Function in the AppKernel.php.

Is there maybe a way to avoid this kind of behaviour (apart from reducing the typo-risk)?

**Comment by AxxL** [comment]
@Tooowanda The guide of generating elements in the documentation is under complete restructuring. I'll ask around at the devs.

**Comment by AxxL** [comment]
@Tooowanda Sorry for the long delay. Comments following.

**Comment by werrolf** [comment]
Automatic element generation is deprecated and will not be for this world for much longer.
We can't reproduce the problem at this point though. I just tried a 
$ app/console mapbender:generate:element 'Mapbender\PrintBundle' MyNewElement mapbender/src
And got a working element complete with PHP class, twig template and JavaScript out of it.

What was your command line?

**Comment by AxxL** [comment]
@Tooowanda Since we are not able to reproduce this, Please reopen the issue if this still occurs.
