### ISSUE TITLE
PNG8-Printing crashes

### ISSUE THREAD

**Issue by ruhri** [mapbender/mapbender#608]
Some Services Crash the printing due to the lack of Image Format Support of 'image/png; mode=8bit' .
It seems, that there exist different mime-type notations 8-bit-PNG-Images...

See also closed ticket:
https://github.com/mapbender/mapbender/pull/481

Test-WMS:
http://www.wms.nrw.de/geobasis/wms_nw_dop_overlay?service=wms&request=getcapabilities&version=1.3.0

**Comment by ruhri** [comment]
In theory there could also exist 1-bit an 32-bit...

**Comment by eSlider** [comment]
@swinkelmann, can you please check this.

**Comment by swinkelmann** [comment]
We already fixed that Problem. Some regex magic was added to handle all kinds of png / gif / jpeg.
See issue #525 and PR #540
