### ISSUE TITLE
PrintClient Legend: Legend is printed for root-layer and group layer

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#611]
* in pdf print the legend is printed for the layer and also for root-layer and group layer if they have legends
* like that you get double legend entrys 

* internal ticket #8416
[druck_legende_root_layer.pdf](https://github.com/mapbender/mapbender/files/1242669/druck_legende_root_layer.pdf)
[druck_legende_mit_gruppen.pdf](https://github.com/mapbender/mapbender/files/1242670/druck_legende_mit_gruppen.pdf)

**Comment by AxxL** [comment]
Is this really an error or a WMS configured for that case? The WMS defines a legend for the root layer?

What should the workflow be? Ignore every Legend for the Root-layer? Ignore every Legend of a Group-Layer? Do you know the rules that the WMS defines?

**Comment by astroidex** [comment]
* behaviour makes troubel in some project. Mapbender should not request the group legend.

**Comment by astroidex** [comment]
WMS for internal testing: http://wms2016.wheregroup.lan/cgi-bin/mapserv?map=/data/umn/germany/germany_group.map&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0
