### ISSUE TITLE
backend - add filter in add element dialog

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#612]
* when you want to add an element to your application you have to sroll for the element in the list
* it would be great to have a filter field like you have it for applications annd layersets
* see screenshot 
![add_element_filter_field](https://user-images.githubusercontent.com/996298/29712080-57ffa296-8998-11e7-82aa-2afe2917f735.png)

**Comment by AxxL** [comment]
@astroidex  Sorry, right now not in our feature-list.

**Comment by astroidex** [comment]
Hi,
I reopen the ticket, as I implemented the filter textfield for add element dialog (used same technique like for fltering source, layersets, services)

See PR https://github.com/mapbender/mapbender/pull/766

**Comment by astroidex** [comment]
The feature will be available in 3.0.7.0
