### ISSUE TITLE
Document the new theme.scss concept on an easy base

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#614]
Theming description.

theme.scss in Ressources folder.

file example is in dev-team protocol wiki page, but needs some explanation.

**Comment by eSlider** [comment]
@AxxL, as discussed before, there is one  simple solution this allows to bind project SCSS file to an aplication by using CSS editor tab. Probably is the solution not ready for publishing.  Anyway this can be done as follow:

```css
@import 'theme.scss'
```

If the `theme.scss` file is located in `application/web` folder

**Comment by werrolf** [comment]
There is no theme.scss in Mapbender and there is no special treatment of files called theme.scss in Mapbender.
