### ISSUE TITLE
Move various ui-builder function from global js scope to dedicated helper object

### ISSUE THREAD

**Issue by LazerTiberius** [mapbender/mapbender#615]
These files have to be moved to a dedicated  helper object outside the FOMBundle: 
- application/fom/src/FOM/CoreBundle/Resources/public/js/widgets/radiobutton.js
- application/fom/src/FOM/CoreBundle/Resources/public/js/widgets/checkbox.js
- application/fom/src/FOM/CoreBundle/Resources/public/js/widgets/dropdown.js
- application/fom/src/FOM/CoreBundle/Resources/public/js/widgets/radiobutton.js
- application/fom/src/FOM/CoreBundle/Resources/public/js/widgets/radiobuttonExtended.js

**Comment by eSlider** [comment]
I suggest to use FormGenerator instead. whetever they needed.

* Check box: https://github.com/eSlider/vis-ui.js#check-box 
* Radio button: https://github.com/eSlider/vis-ui.js#radio-button
* etc..

And never touch existing "super-fine" JS FOM code.

**Comment by LazerTiberius** [comment]
At least we should output a notice in the js-console with a deprecated warning.

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
