### ISSUE TITLE
replace old OSGeo project logo with OSGeo project logo

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#617]
* https://github.com/mapbender/mapbender/blob/release/3.0.6/src/Mapbender/CoreBundle/Resources/public/image/OSGeo_project.png

Neues Logo
![osgeo_project](https://user-images.githubusercontent.com/996298/30273274-99ffe8c8-96f8-11e7-9afe-e166e25fbf9b.png)

**Comment by astroidex** [comment]
you find the file here https://github.com/OSGeo/osgeo/tree/master/incubation/project

**Comment by RobinSchwammborn** [comment]
See #654

**Comment by astroidex** [comment]
Olf logo is still included in Mapbender: https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/image/OSGeo_project.png

Talked about it with @AxxL . He will have a look.

**Comment by AxxL** [comment]
PR #982

**Comment by rschwammborn** [comment]
Closing this now, see pull #861
