### ISSUE TITLE
replace Mapbender logo in print templates

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#618]
* 4 Templates use the Mapbender logo
* see folder https://github.com/mapbender/mapbender-starter/tree/release/3.0.6/application/app/Resources/MapbenderPrintBundle/templates

* a4portrait.pdf
* a4landscape.pdf
* a3portrait.pdf
* a3landscape.pdf

Please replace logo with the new logo

**Comment by CharlyUnicorn** [comment]
application/app/Resources/MapbenderPrintBundle/images/legendpage_image.png

**Comment by RobinSchwammborn** [comment]
see #57 in mapbender-starter repository

**Comment by AxxL** [comment]
PR is in Mapbender-Starter 
https://github.com/mapbender/mapbender-starter/pull/57

**Comment by werrolf** [comment]
Template updates merged.
