### ISSUE TITLE
replace mapbender logo with new logo

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#619]
/mapbender/src/Mapbender/CoreBundle/Resources/public/image/logo_mb3.png

* change name to mapbender-logo.png
* change name in parameters.yml

**Comment by AxxL** [comment]
Please do not change the name of the logo. Unneccessary changes in parameters.yml are unneccessary. It' not important for that file to have another name. But every update has to update the parameters.yml.

Also: @RobinSchwammborn has made the change in PR: https://github.com/mapbender/mapbender-starter/pull/57/files but hasn't provided the file.

We revert the change of the parameters.yml and you can change the logo later in this ticket. But please only the logo, not the parameters.yml.dist.

**Comment by AxxL** [comment]
Done.

**Comment by salimtraore** [comment]
Bonjour à tous,

j'ai faire la découverte de Mapbender il y a peu de temps je travail déçu actuellement. Mais J'ai un souci, j'ai faire un clone sur lequel je veux apporter des modifications, mais au niveau de la midification du logo ça marche pas. malgré avoir suivie les indications dans les documents ça passe pas.
 Pourrais-je avoir un coup de main dans ce sens.
Cordialement.
