### ISSUE TITLE
replace legendpage_image.png with the new mapbender logo

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#620]
* app/Resources/MapbenderPrintBundle/images/legendpage_image.png
* please keep the name

**Comment by RobinSchwammborn** [comment]
see pull request #57 in mapbender_starter

**Comment by AxxL** [comment]
@RobinSchwammborn If you link to different repositories, put the full URL. The real PR is: https://github.com/mapbender/mapbender-starter/pull/57

**Comment by werrolf** [comment]
Mapbender start pull #57 is completely unrelated.
Starter pull: https://github.com/mapbender/mapbender-starter/pull/57
