### ISSUE TITLE
OSGeo webside check logo and replace

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#623]
* http://wiki.osgeo.org/wiki/Mapbender

**Comment by CharlyUnicorn** [comment]
please update the wiki

**Comment by RobinSchwammborn** [comment]
editing the wiki is only possible with the privilege of an reviewed account. i created one, the status is pending atm. i'll check back if i am ready to go!

**Comment by RobinSchwammborn** [comment]
Account is now activated, so I updated the wiki. Had a problem with updating the logo - new png-logo is shown with a 3 in the wiki although it it displayed correctly in nautilus. Strange...

**Comment by CharlyUnicorn** [comment]
Looks like you revertet to the version with the 3 in the logo: 
http://wiki.osgeo.org/wiki/File:Mapbender_logo.png

**Comment by RobinSchwammborn** [comment]
Added the new high-res logo, should be working now.
