### ISSUE TITLE
check wikipedia page content

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#625]
* https://de.wikipedia.org/wiki/Mapbender
* https://en.wikipedia.org/wiki/Mapbender

**Comment by CharlyUnicorn** [comment]
- please update the sides from mapbender and remove the 3 in the text
- add the logo

**Comment by RobinSchwammborn** [comment]
Included:

- Mapbender logo in Wikimedia Commons

- new version number and available languages where it was not up-to-date

Removed:

- the number 3 a few times

- some deprecated links
