### ISSUE TITLE
replace logo at https://doc.mapbender3.org/

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#627]
* logo with text below instead of only logo
* please use logo without greay background
* https://github.com/mapbender/mapbender-documentation/blob/release/3.0.6/_static/mapbender3_logo.png

**Comment by werrolf** [comment]
* your sentences so we know what

**Comment by AxxL** [comment]
Did it with the signet again, due to design aspects. The labeled one didn't look appealing. This here is really nice and fits with the Navigation div.

Commit: https://github.com/mapbender/mapbender-documentation/commit/4b2a6d6dd324e17df5cd49226f0498a0bc7c03a2
