### ISSUE TITLE
OSGEoLive check file install_mapbender3.sh

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#629]
* check https://github.com/OSGeo/OSGeoLive/blob/master/bin/install_mapbender3.sh
* version
* download desktop icon at: wget -nv -N "https://svn.osgeo.org/mapbender/trunk/build/osgeolive/mapbender3_desktop_48x48.png"

**Comment by astroidex** [comment]
* replaced desktop icon https://trac.osgeo.org/mapbender/browser/trunk/build/osgeolive/mapbender_desktop_48x48.png

ToDo
* Mapbender3 -> change to Mapbender
* find a good place for desktop icon - not in svn
* for next version 12.0 refer to new version

**Comment by werrolf** [comment]
This issue tracker for issues concerning files in this repository; at most, in the mapbender repository group.
We do not accept tickets that have no bearing on external files.

**Comment by astroidex** [comment]
Thanks

**Comment by astroidex** [comment]
* talked to @axel and as conclusion move this ticket so somewhere else
