### ISSUE TITLE
Editing WMS instances with many (sub) layers

### ISSUE THREAD

**Issue by kartoffelfee** [mapbender/mapbender#630]
This two example WMS can be added as new datasource and then added as a new layer to a layerset.
After editing the instance of the layerset the edits cannot be saved. Message 'Your WMS instance is not valid' appears and the changes are'nt saved.

https://services.bgr.de/wms/grundwasser/huek200_hgw/?Service=WMS&request=GetCapabilities&version=1.3.0

http://www.geoproxy.geoportal-th.de/geoproxy/services/DLM?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.1.1

tested in app georohstoff on demo.mapbender3.org and in app 
https://version.mapbender3.org/3063/application/mapbender_user_yml

**Comment by AxxL** [comment]
@kartoffelfee http://docs.mapbender.org/current/de/book/faq.html#arbeiten-mit-groszeren-wms-diensten

Too many checkboxes lead to adjusting a PHP parameter.

**Comment by AxxL** [comment]
I guess we did that already, so I close now. Don't hesitate to reopen if any further question occur.

**Comment by AxxL** [comment]
I reopen it, because @LazerTiberius wanted to look into the code.

@kartoffelfee This doesn't change the systemrequirement to set the php.ini settings.
