### ISSUE TITLE
CustomDoctrineParamConverter not working with Symfony 2.8

### ISSUE THREAD

**Issue by LazerTiberius** [mapbender/mapbender#631]
https://github.com/mapbender/mapbender/blob/be7a48476cd4269997a52c7884151341a5b41d02/src/Mapbender/Component/CustomDoctrineParamConverter.php#L31

This is still used in some CustomBundles and is not working in the current release. I will create a hotfix for this file.

**Comment by werrolf** [comment]
Pull #645 has been merged.
