### ISSUE TITLE
backend Application - layerset - choose datasource - resize dialog - make it bigger

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#632]
* the dialog to chosse a WMS for your layerset is very small - height:400px  witdh:500px
* would be great to have it bigger for usebility
* suggestion height: 700px and width: 700px

.popup {
    min-width: 300px;
    min-height: 250px;
    position: relative;
    z-index: 9999;
    width: 500px;
....
}
![chosse_datasource_small](https://user-images.githubusercontent.com/996298/30368265-f96f7eee-9870-11e7-9882-6d678ff97ac0.png)
![chosse_datasource_big](https://user-images.githubusercontent.com/996298/30368276-01f26d10-9871-11e7-83ad-cfa524911616.png)

**Comment by LazerTiberius** [comment]
Is there any reason why we should use 700px. 700 seems to be a bit random. I would suggest to just open a full-screen overlay there. There is no possibility to interact with something other than the open pop up. 
 But I´m not sure which other elements use the CSS class .popup.

**Comment by astroidex** [comment]
* 700x700 is random. Full--screen would be ok for me too. Only something bigger and easy to handle to improve the usebility

**Comment by astroidex** [comment]
@axxl @werrolf @LazerTiberius - please have a look again. Would enhance the usabiility.

**Comment by inacht** [comment]
popup dialog height and wide resized to 700 pixel
See PR https://github.com/mapbender/mapbender/pull/1004

**Comment by astroidex** [comment]
I tested. Please put height to 500 and change width to 700. As on smaller screens else you will not be able to see the ok button at the bottom

**Comment by inacht** [comment]
@astroidex ok, changed height to 500, and width to 700 pixel.
