### ISSUE TITLE
[Documentation][digitizer] checkbox - add information about default for checkbox

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#636]
* In the documentation the information is missing whether the checkbox should be pre-selected (checked) on load

- http://doc.mapbender.org/en/bundles/Mapbender/CoreBundle/elements/digitizer.html#checkboxes-type-checkbox
- row 701: https://github.com/mapbender/mapbender-documentation/blob/release/3.0.6/en/bundles/Mapbender/CoreBundle/elements/digitizer.rst 

```
- type:  checkbox        # Type checkbox creates a checkbox. When activated, the specified value (here 'TRUE') is written to the database.
  title: Is this true?   # Label (optional)
  name:  public          # table column
  value: true            # parameter when activating the checkbox is stored in DB (here 'TRUE').
  checked: false         # behaviour of the checkbox (true or false). default is false. Defines whether checkbox is pre-selected (checked) on load
```

**Comment by AxxL** [comment]
Please make a PR to the master of the documentation.

**Comment by astroidex** [comment]
I added the information to the documentation
