### ISSUE TITLE
[FOM] Using SSPI in MB3.0.6 results in wrong argument exception

### ISSUE THREAD

**Issue by LazerTiberius** [mapbender/mapbender#638]
Setting SSPI : true in a firewall configuration in the Symfony security.yml will result in a wrong argument exception. The FOM/SSPIListener class still uses the old deprecated Symfony Interface. Because we use our own security service in newer MB version, an MB Security Context Object is passed into the constructor and the exception is thrown.

**Comment by AxxL** [comment]
@LazerTiberius Change the assignnees in the PR and in the ticket. Ticket: 1 assignee, PR: dozens/throusands!!!111elf
