### ISSUE TITLE
feature passing POIs requires attribute "&poi[srs]="

### ISSUE THREAD

**Issue by MrSheffield** [mapbender/mapbender#642]
Hi there,

after updating mapbender3 from version 3.0.5.3 to 3.0.6.3, I recognized a change in the behavior of the feature "passing POIs".

The feature now accepts URLs containing the attribute "&poi[srs]=SomeEpsgCode" only.
For example: 
?poi[point]=363374,5621936&poi[label]=Label&poi[scale]=5000 **&poi[srs]=25833**

The manual leaves that attribute to be optional. 
[https://doc.mapbender3.org/en/bundles/Mapbender/CoreBundle/elements/map.html#passing-pois](url)

Best regards,
Max

**Comment by LazerTiberius** [comment]
Hi Max,

this is for sure a bug. I will take a look at it and fix it asap.

**Comment by LazerTiberius** [comment]
Bug is fixed and POI will work again in the next release like it is described in the docu .
