### ISSUE TITLE
Install mapbender documentation -  Update documentation sys requirements

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#644]
We tried to install mapbender and started with the components for php and system requirements. 
https://doc.mapbender3.org/en/book/installation/systemrequirements.html

Here we found a missing parameter that causes an error. Furthermore perhaps we can change the order of the php versions and put php7 up/ php 5 down. 

error: 
```
$ sudo a2enmod php7
ERROR: Module php7 does not exist!
```

please add: 
`sudo apt-get install libapache2-mod-php7.0`

**Comment by AxxL** [comment]
- Can you provide the name of the libs for PHP in your machine? It depends on version of Ubuntu/Debian how they are called. Sometime they have metapackages.

- We don't provide installation instructions for Apache, so any libs, the user wants to have in his/her Apache is not of Mapbenders concern.

- Considering order of PHP 7 above PHP 5. Before that we have to adjust the documentation structure.

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
