### ISSUE TITLE
[Enhancement] Time or Datetime in Digitizer

### ISSUE THREAD

**Issue by thilob** [mapbender/mapbender#646]
Would be great to extend Digitizer so you can't only use a Datepicker, but also a Timepicker or DateTime-Values. WMS-T wouldn't be longer limited to days, but can be used with hours or minutes then.

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
