### ISSUE TITLE
Scale-Selector Element displays wrong scale

### ISSUE THREAD

**Issue by philvanbwg** [mapbender/mapbender#647]
This bug may be reproduced like so:
If the scale is changed via the Zoombar, then the Scale-Selector in the footer is adjusted correctly.

But if afterwards the scale is changed again via the Scale-Selector in the footer, then the Map and the Zoombar are adjusted correctly but not the displayed value in the Scale-Selector.

This issue concerns the stable Mapbender-release 3.0.6.3 and still occurs in the nightly-build 3.0.6-440 - 2017-08-07

See Screenshot.

Maybe this is related to this Issue: [Scale Selector] No refresh on slow WMS services #595

---------------------------------------------------------------------------------------------------------------------------

Scale-Selector-Element zeigt falschen Wert an:
Der Fehler kann so reproduziert werden:
Wenn man zuerst über das Navigationswerkzeug (Zoombar) den Maßstab verändert, wird dieser im Scale-Selector im Footer korrekt angepasst.

Wenn man anschließend über die Auswahlbox des Scale-Selectors im Footer einen anderen Maßstab wählt, dann wird zwar die Karte und das Navigationswerkzeug (Zoombar) korrekt angepasst, aber der ausgewählte Wert wird nicht im Scale-Selector angezeigt.

Der Fehler betrifft die aktuelle Mapbender Version 3.0.6.3 und tritt auch noch im Nightly-Build 3.0.6-440 vom 2017-08-07 auf

vielleicht hängt der Fehler mit diesem Ticket zusammen: [Scale Selector] No refresh on slow WMS services #595

s. auch Screenshot

![screenshot_scale_selector](https://user-images.githubusercontent.com/24896163/31708004-1fab08ba-b3ee-11e7-89de-19ec01f1d4b2.jpg)

**Comment by werrolf** [comment]
Can't find any functional change beside
1) a better (but still bad) method of clearing the readyCallbacks list after invocation
2) a better way to activate a ```select > option``` (```val``` on the select instead of setting ```selected``` on the option)
Is that the fix?

Because all else I see is variable hoisting, whitespace reformatting and a few extra comments.
