### ISSUE TITLE
Search Route functionality

### ISSUE THREAD

**Issue by sBoga1** [mapbender/mapbender#659]
Hello,
I'm working for the fisrt time with mapbender software.  
I'm using the search router element to allow viewing points on the map, filtering the information through some search fields.
I would like to know if it is possible to view the detailed information of a point, when selected,, in a window or other object.
The element digitizer allows the access to the information for editing, it would like a a similar solution but only for consultation.

The search rouuter code is in a attached file.
Best regards
[SearchRouterCode.txt](https://github.com/mapbender/mapbender/files/1487486/SearchRouterCode.txt)

**Comment by astroidex** [comment]
Hello @sBoga1, 
great that you discover Mapbender.

We are working on a solution to use digitizer for consultation - search and display information. 

That will be a feature that will come in the future. It is not fully financed yet. If you want to get involved, you can contact me at astrid.emde@wheregroup.com

**Comment by AxxL** [comment]
@sBoga1 Closing this issue. If you need more information contact us or reopen again. Thanks.
