### ISSUE TITLE
[Documentation] English translation of: HTML-Element

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#668]
Translate the changes of @nmoelkner into proper english:

HTML-Element german: de/functions/misc/html.rst
HTML Element english: en/functions/misc/html.rst

Main Commit of Nina: https://github.com/mapbender/mapbender-documentation/commit/a0c66c2f7e7c9324d59f82219441a184546e1d05

V.a. Kapitel "Konfigurationsbeispiele"

**Comment by RobinSchwammborn** [comment]
Committed translation into branch /translation2

**Comment by werrolf** [comment]
Referenced commit is merged on release/3.0.6 and master. Closing.
