### ISSUE TITLE
[OL] [Implementierung] WMS Loader

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#678]
- [x] load WMS / basic
- [x] load WMS with username and password
- [x] support "splitLayers" option (unaffected)
- [x] loaded WMS appears in Layertree(s)
- [ ] support layer merging / source deduplication

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
