### ISSUE TITLE
[OL] [Implementierung] SrsSelector

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#681]
Dependencies are in https://github.com/mapbender/mapbender/issues/890

edit (axxl): The WGS84 projection is still shaky with WMS 1.1.1. A possible solution would be calculation the resolution based on the extent information of the coord-sys. May have a dependency to: #962

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
