### ISSUE TITLE
[OL] [Implementierung] Layertree

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#688]
- [x] Schalten von einzelnen Layern
   - [x] Schalten von Layergruppen
   - [x] Schalten von Quellen
   - [x] Schalten von Themen ("thematischer Layertree")
   - [x] FeatureInfo schalten
   - [x] [Layer umsortieren](https://github.com/mapbender/mapbender/issues/951)
      - [ ] Forward update to other layertrees
   - [x] Quellen umsortieren
      - [ ] Forward update to other layertrees
   - [x] Themen umsortieren
      - [ ] Forward update to other layertrees
   - [x] Opacity-Slider
   - [x] Metadaten
   - [x] Zoom To
   - [x] Dimensions

**Comment by werrolf** [comment]
Stopping progress for now with open TODOs.

**Comment by werrolf** [comment]
We've decided in the team meeting today that synchronization between multiple LayerTree elements is not a mandatory core feature.  
Since these are the only open topics, I'm tagging as resolved.  

If you need multi-LayerTree cross sync, please open a new ticket.
