### ISSUE TITLE
PrintClient feature.data print does not handle Umlaute öüä utf8_decode is needed

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#690]

**Comment by astroidex** [comment]
* very small issue
* see pull request https://github.com/mapbender/mapbender/pull/691

**Comment by AxxL** [comment]
We cannot reproduce this error. What happens?

**Comment by astroidex** [comment]
* see also ticket for the new feature https://github.com/mapbender/mapbender/issues/695
* see also documentation for the new feature 

https://github.com/mapbender/mapbender-documentation/blob/feature/printclient-feature-data-print/en/bundles/Mapbender/CoreBundle/elements/printclient.rst
description starts at row: 229

**Comment by astroidex** [comment]
* pull requests merged #691 #701
