### ISSUE TITLE
Source instance delete confirmation broken (locale en)

### ISSUE THREAD

**Issue by werrolf** [mapbender/mapbender#694]
Commit a9834b441f6487ea6fc34f1d8a913a1e30189fa2 changed the translation key ```mb.manager.admin.instance.delete.title``` to just ```mb.manager.admin.instance.delete``` (dropping the .title) in form-layersets.html.twig, some translation yamls were updated, ignoring that there also was a ```mb.manager.admin.instance.delete.confirm``` translation key used for the dialog that pops up when you click the cross icon. This key is no longer defined.

Now the confirmation dialog says, e.g.
mb.manager.admin.instance.delete WMS BB ALKIS?
The hover tooltip for the cross icon is the same, too in locale en.

We *need* a different text for the body of the confirmation box.
Revert the folding of both translations onto a single key.

Assigning to the person who commited the change.

**Comment by astroidex** [comment]
* please note that benno worked on the translation and fixed it for all bundles. The fixed translation is in branch **hotfix/translations**  and is waiting for being merged in the next version.

https://github.com/mapbender/mapbender/tree/hotfix/translations

**Comment by astroidex** [comment]
* translation was done in summer (Juli 2017) during the Translation Sprint at FOSS4G Europe in Paris - see email https://lists.osgeo.org/pipermail/mapbender_users/2017-July/005259.html
* You find the translation ticket here https://github.com/mapbender/mapbender/issues/557
* there is no pull request yet for hotfix/translation as I did not know to which branch  to make the pull request 
* please see internal Ticket chili 8345 for more information

**Comment by eSlider** [comment]
@werrolf you are wrong. I added the `title`.

**Comment by eSlider** [comment]
@werrolf, please review https://github.com/mapbender/mapbender/pull/696

**Comment by eSlider** [comment]
@werrolf, depence on #497

**Comment by werrolf** [comment]
Resolved in pull #700
