### ISSUE TITLE
load WMS / WMC covers redlining

### ISSUE THREAD

**Issue by kartoffelfee** [mapbender/mapbender#698]
A WMS added with WMS or WMC loader covers the redlining layer.
Redlinging-Layer should be pushed to the top after loading additional WMS.

see:
https://release.mapbender.org/application/wmcredlining

wms to add:
http://ows.terrestris.de/osm/service?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities

**Comment by AxxL** [comment]
PR: https://github.com/mapbender/mapbender/pull/770
