### ISSUE TITLE
HTML-element: application crashes if content is incorrect

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#707]
application crashes if content is incorrect in the html element
-----------------------------------------------------------------------------
   
check it out
---------------

example-url: http://wms2016.wheregroup.com/mapbender3.0.6/application/html-crash

HTML-element content: 
`content: <p>Hello, World!</p><p>Application: {{ application.title |trans }</p>   `

Steps to reproduce the bug
-------------------------------------
   
 Follow these simple steps   
   - start your mapbender-application-backend and go to the layout tab
   - insert a html element with the following content: `content: <p>Hello, World!</p><p>Application: {{ application.title |trans }}</p>   `
   - open the application -> everything works fine
   - change the html-content and remove a } in the content: `content: <p>Hello, World!</p><p>Application: {{ application.title |trans }</p>   `
   - open the application -> everything crashes!

And now? 
--------------
I would expect the application to still be reachable despite the incorrectly configured element and that only the html-element will not be displayed correctly. Instead of the correct content, the error text or an error message should simply appear here - feature or bug?

Would you kindly look at the behavior and check it out?

**Comment by AxxL** [comment]
I wouldn't say it's a bug. It's an annoying missing check of things the user can script into an element. The user should know what to do and must check if it's correct. 

@werrolf Any technical possibility to achive a check or as @CharlyUnicorn said throw only an element error to the user-interface?

**Comment by CharlyUnicorn** [comment]
@AxxL I would rather say that it is a bug because the element kills the whole application. Actually that should not happen... with every other element, the application areas will work even if the configuration is incorrect.
 @werrolf in the digitizer, the yaml syntax is checked ... maybe you can include a html syntax check as a feature?

**Comment by werrolf** [comment]
Please see pull #708. This handles only twig templating errors in the HTML element.
I agree that validation would be cool, but that's a new feature and a bit bigger in scope.
