### ISSUE TITLE
Layertree: checkboxes in menus not functional

### ISSUE THREAD

**Issue by werrolf** [mapbender/mapbender#709]
In the generated markup, the layer menu is added as a child of the ```.layer-menu-btn```. Click events anywhere in the menu are handled in the toggle button, breaking checkbox / radio interactions.

See https://github.com/mapbender/mapbender/blob/release/3.0.6/src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js#L893

Proposing to simply change the $element.append to $element.after, so the toggle button and the menu itself become siblings and can function independently.

**Comment by AxxL** [comment]
PR merged.
