### ISSUE TITLE
Plus Button in startpage without login

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#713]
The "add application" button is visible in the list of applications when you are not logged in. If you click it you have to login. Previous versions haven't shown this button. See attached screenshot.

![mb_306_plus](https://user-images.githubusercontent.com/2235393/34762303-9cd97854-f5e7-11e7-9504-fd2ca086e80b.png)

Please remove this button again if you are not logged in. Show this button only if you are logged in and able to create apps.

**Comment by werrolf** [comment]
Pull ist bereit.

**Comment by werrolf** [comment]
Fix has been approved and merged (into FOM).

**Comment by werrolf** [comment]
Both FOM and Mapbender pulls merged.

**Comment by AxxL** [comment]
OK
