### ISSUE TITLE
WMS-Dienste werden 2x geladen

### ISSUE THREAD

**Issue by philvanbwg** [mapbender/mapbender#715]
Beim Aufruf einer Kartenanwendung wird ein aktivierter WMS-Dienst 2x geladen, mit 2 unterschiedlichen Werten für den _OLSALT-Parameter. 

Wird ein WMS-Dienst später über den Layertree oder Hintergrundwechsler aktiviert, finden ebenfalls zwei Requests statt, einmal mit und einmal ohne _OLSALT-Parameter.

Das Verhalten kann z.B. hier (in der Entwicklerkonsole) nachvollzogen werden: https://release.mapbender3.org/application/doubleloadedWMS (die Mapbender-Version ist angegeben mit: v. release branch 3.0.6 after 3.0.6.3)

Das Problem ist möglicherweise schon mal bearbeitet worden: https://github.com/mapbender/mapbender/pull/474 

![unbenannt](https://user-images.githubusercontent.com/24896163/34936410-8c757c44-f9e1-11e7-8d65-e4a3f9ef1e39.png)

**Comment by DeEgge** [comment]
Nur beim ersten "Neuaufruf" (Layer im Layertree ausschalten und wieder einschalten) erhält man zwei Aufrufe. Jeder weitere Aufruf, auch durch das Verschieben des Kartenausschnitts, wird nur einmal durchgeführt.

Ich beschreibe mal das Verhalten und die Unterschiede für den MB-User Layer `http://wms.wheregroup.com/cgi-bin/mapbender_user.xml?`

1. Laden der Anwendung (alles was gleich bleibt, habe ich entfernt)
```
...&LAYERS=Mapbender_User,Mapbender_Names&_OLSALT=0.3092962203671281&CRS...
```

2. Ausschalten und Einschalten im Layertree (hier erfolgt der doppelte Aufruf: 1. Gleicher _olsalt, aber vertauschte Layerreihenfolge, 2. vertauschte Layerreihenfolge, neuer _olsalt)
```
...&LAYERS=Mapbender_Names,Mapbender_User&_OLSALT=0.3092962203671281&CRS...
...&LAYERS=Mapbender_Names,Mapbender_User&_OLSALT=0.6041864799742682&CRS...
```

3. Erneutes Aus- und Einschalten, Verschieben, Zoom etc (alles was ein redraw bei OpenLayers auslöst; neuer _olsalt)
```
...&LAYERS=Mapbender_Names,Mapbender_User&_OLSALT=0.5011618074738386&CRS...
```

**Comment by werrolf** [comment]
Stimmt.

Das ganze kann auch ohne großes Setup mit der Applikation mapbender_user_yml nachvollzogen werden.

CRS, BBOX, width und height sind bei den Requests identisch.

In 3.0.5 wird die Anfrage nur einmal geschickt.
