### ISSUE TITLE
Mapbender fails to install under Windows

### ISSUE THREAD

**Issue by LazerTiberius** [mapbender/mapbender#718]
Trying to install Mapbender via composer install will fail on all supported Windows platforms because Mapbender is affected by this apigen bug https://github.com/apigen/apigen/issues/316 . The suggested fix is not working because release 2.8.2 of apigen is nonexistent.   Calling ```composer install --no-dev ```  can be used as a workaround for non-dev installations. This is indeed not a direct Mapbender problem but my suggestion is to add a notice to the documentation.

**Comment by pwheregroup** [comment]
Same happened on my osx high sierra system few weeks ago. The working solution for me was to update composer first via
`composer selfupdate` cause the project had an outdated `composer.phar` delivered.

**Comment by werrolf** [comment]
Apigen dependency has been removed for greater PHP7.2 incompatibility issues (not just on Windows).
This change is included in Mapbender 3.0.7.3.
