### ISSUE TITLE
Coordinate-Utility: Jump to coordinate, click coordinate functionality

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#723]
We finished the Coordinate-Utility which jumped out of a project in December.

It will be available in MB 3.0.7. Documentation prepared on https://github.com/mapbender/mapbender-documentation/blob/feature/coordinates-utility-svit/de/functions/misc/coordinate_utility.rst

@sveta-wl Please give the current master of coordinate-utility the version 1.0 and put that into mapbender-starters composer.json to include it in MB. make a PR for that change in mapbender-starter. Thanks for your work.

@werrolf for your information.

Internal ticket: 13 including testing results by @nmoelkner

**Comment by sveta-wl** [comment]
Done in https://github.com/mapbender/mapbender-starter/commit/99085b6da347bbb684fb8547cf1c6010a90d0fef
