### ISSUE TITLE
 Coordinate-Utility - when you choose center, map should not zoom. Only center

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#724]
* feedback for new element in next version https://github.com/mapbender/coordinates-utility
* if you choose center coordinate the map should be centered without zoom
* at the moment a fixed ZOOM 10 level is defined in the code (see links)
* this does not look good, depending on the scales you defined for your project

* https://github.com/mapbender/coordinates-utility/blob/master/Resources/public/mapbender.element.coordinatesutility.js#L29
* https://github.com/mapbender/coordinates-utility/blob/master/Resources/public/mapbender.element.coordinatesutility.js#L516

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
