### ISSUE TITLE
SearchRouter: Add highlight feature on map when hover (mouseover) over searchresult

### ISSUE THREAD

**Issue by pwheregroup** [mapbender/mapbender#730]
Example

* https://demo.mapbender.org/application/mapbender_user_reference

Steps to reproduce

* You can try it with the SearchRouter in the application. Search for a mapbender user then hover over the result. You will see the result on the map is not highlighted.

Enhancement

* When you hover over the results on the resultlist the object will be highlighted on the map. There is no additional configuration parameter in yaml necessary.

**Comment by astroidex** [comment]
Is available in version 3.0.3
