### ISSUE TITLE
[3.0.5] Disabling publish status kills applications

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#739]
Setting a DB-based application to unpublished renders it completely unavailable to Mapbender. Once it is unpublished, it can't be published, edited or even deleted anymore.

There was a fix for 3.0.6 (https://github.com/mapbender/mapbender/commit/cd04e517d1cbbcd44de317c7767b2c23c7f2c645#diff-e3a95078c76039f5bdc9d41ed6eaee52) that never made it into 3.0.5. The fix was necessary, after some refactoring of `Mapbender.php` (https://github.com/mapbender/mapbender/commit/d262fec03ceca745a7e9a93056f81e3975354b8e#diff-e3a95078c76039f5bdc9d41ed6eaee52).

I see two possible ways to fix this

1.
```php
//...
    if ($entity) {
            $entity->setSource(Entity::SOURCE_DB);
            return $entity; #add this line
        } else {
            /** @var ObjectRepository $repository */
        $yamlMapper = new ApplicationYAMLMapper($this->container);
        $entity     = $yamlMapper->getApplication($slug);
        }

        if (!$entity || !$entity->isPublished()) {
            return null;
        }

        return $entity;
//...
```

2.
```php
//...
    if ($entity) {
            $entity->setSource(Entity::SOURCE_DB);
            //return $entity;
        } else {
            /** @var ObjectRepository $repository */
        $yamlMapper = new ApplicationYAMLMapper($this->container);
        $entity     = $yamlMapper->getApplication($slug);
        }

        if (!$entity || !$entity->isPublished()) { #remove this if statement
            return null;
        }

        return $entity;
//...
```

**Comment by werrolf** [comment]
We'll just cherry-pick cd04e517d1cbbcd44de317c7767b2c23c7f2c645 into release/3.0.5
[In ApplicationController, when accessing the application frontend](https://github.com/mapbender/mapbender/blob/release/3.0.5/src/Mapbender/CoreBundle/Controller/ApplicationController.php#L166), isPublished is checked anyway in [checkApplicationAccess](https://github.com/mapbender/mapbender/blob/release/3.0.5/src/Mapbender/CoreBundle/Controller/ApplicationController.php#L267).

So this second check seems redundant even in 3.0.5.

**Comment by werrolf** [comment]
After cherry-picking locally, DB and YAML applications behave as expected.
Unpublished apps are not listed when not logged in, and cannot be opened (they redirect to login).
When logged in, they are still listed in the backend and can be reactivated.

**Comment by werrolf** [comment]
Done.
