### ISSUE TITLE
WMS Metadata Dialog: Do not show WMS Title only show WMS Instance Title 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#742]
Problem
* metadata dialog shows WMS information like WMS title
* in metadata dialog WMS Title and Instance Title are shown even if they are the same text
* background information: admin can change WMS Instance Title to a text that makes sense (sometimes WMS title is not suitable)

Example

- https://demo.mapbender.org/application/mapbender_user_reference

Steps to reproduce
- open Example application
- go to layertree
- get Metadata dialog for WMS Mapbender User
- see Title+ Instance-Title: Mapbender User(MAPBENDER USER)
- Mapbender User -> WMS title comes from WMS getCapabilities
- MAPBENDER USER -> was defined by the user in the administration 

Enhancement
* do not show WMS title, Show only instance title
* motion to change row L28: https://github.com/mapbender/mapbender/blob/release/3.0.6/src/Mapbender/WmsBundle/Component/WmsMetadata.php#L28
* change row L28 to
`$source_items[] = array("title" => SourceMetadata::getNotNull($this->instance->getTitle()));`

before
![mb_wms_instance_title_before](https://user-images.githubusercontent.com/996298/36029416-64d70128-0da3-11e8-9af0-490dfaf9b2ad.png)

after
![mb_wms_instance_title_after](https://user-images.githubusercontent.com/996298/36029420-6b8d6b10-0da3-11e8-9aea-f51ac1f698f6.png)

**Comment by AxxL** [comment]
I'm not voting for it. This poopup displays the WMS Capabilities information. If I open the origin-url I expect to see the capabilities information according to this dialog. So it's the "connection" to the service, not the changes of the admin. So both information is good. Likewise in the layers-tab.

I would propose to put a blank in. :)

**Comment by astroidex** [comment]
**A solution could be:**

- If the text is the same (WMS Title = Instance-Title) -> then only display the text one time not twice
- else display both with a blank

**Comment by AxxL** [comment]
> else display both with a blank

I'll close that and open a new one. Thanks.

**Comment by astroidex** [comment]
* I added the blank and do not show both title if they are the same
* see PR https://github.com/mapbender/mapbender/pull/767
