### ISSUE TITLE
Correct some wrong tagged Syntax-Highlightings for code blocks

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#753]
Some code-blocks, especially for PHP code are tagged the wrong way (as "bash", for example). So the syntax-highlighting doesn't work.

Check them and change it so that syntax-highlighting is supported.

**Comment by pwheregroup** [comment]
@AxxL 
Beginning to work on the ticket I have found wrong syntax-highlighting for php, javascript, xml, bash, yml, ini. Can you please modify the ticket so I can change all wrong specified syntax-highlighting tags.

You can see wrong highlighting in these files:
http://localhost/tmp/mb-docu/output/en/development/element_generate.html
http://localhost/tmp/mb-docu/output/en/functions/search/simplesearch.html

**Comment by AxxL** [comment]
Happy Friday.
PR: https://github.com/mapbender/mapbender-documentation/pull/40
