### ISSUE TITLE
editorconfig for Documentation

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#755]
Propose an editorconfig for the Documentation.

Spaces instead tabs for example.

**Comment by pwheregroup** [comment]
I have added the .editorconfig file to the project. To enable editorconfig  you have to download the plugin for your IDE.
You can investigate the project in detail here: http://editorconfig.org .

**Comment by AxxL** [comment]
PR: https://github.com/mapbender/mapbender-documentation/pull/37
