### ISSUE TITLE
Backend - PrintClient - not possible refer to template files (odg,pdf) in your own directory

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#76]
At the moment the template files (odg,pdf) have to be saved at app/Resources/MapbenderPrintBundle/templates/
- flexibility is needed. User wants to save the template files (odg,pdf) in an individual directory

**Comment by eSlider** [comment]
@swinkelmann: it's done now?

**Comment by AxxL** [comment]
I close this issue since it is outdated. If this requirement is still relevant, feel free to (re)open again.
