### ISSUE TITLE
Frontend - Overview - zoom by ZoomBox is not possible

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#77]
- it would be very usefull to zoom by rectangle in the overview map
- http://dev.openlayers.org/releases/OpenLayers-2.13/doc/apidocs/files/OpenLayers/Control/ZoomBox-js.html
- http://dev.openlayers.org/releases/OpenLayers-2.13/doc/apidocs/files/OpenLayers/Control/OverviewMap-js.html#OpenLayers.Control.OverviewMap.mapOptions

**Comment by eSlider** [comment]
@AxxL: we can do it for 3.0.5.3 release!

**Comment by eSlider** [comment]
@astroidex there is dead demo links. Is it now part of current release?

**Comment by AxxL** [comment]
The overview map doesn't support a zoom Box. Zooming is done in the main map. We don't consider this feature. I close this issue since it's outdated. Feel free to open it again if a real requirement comes.
