### ISSUE TITLE
Mapbender.org new Text

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#779]
Update the text on mapbender.org. Template is the german flyer, that we've updated. Translate the texts and we will put them on the right page.

**Comment by astroidex** [comment]
good task for OSGeo Code Sprint.

**Comment by astroidex** [comment]
* Text is already there. Not on first page. But on Klick weiterlesen. But maybe we have to improve the text on first page. Too. Let's have a look at this at OSGeo Code Sprint
* https://mapbender.org/node/20

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
