### ISSUE TITLE
[BaseSourceSwitcher] with group - group is opened on start of the application and modified click behaviour

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#785]
* occurs actual Mapbender from 2018-03-08
* BaseSourceSwitcher group dropdown is opened on start of application (this is a behaviour that is not wanted) -> looks strange with many entries (overlaps map)
* On click on a different menu the first one does not close

### Demo Application the check the behaviour

- https://release.mapbender.org/application/Geoportal__BaseSourceSwitcher_785

### How can you reproduce the error?

- open the application -> wrong behaviour:  Basesourceswitcher is opened already
- check what happens when you click on the menu items
- click on OSM -> OSM mit Opacity -> wrong behaviour -> menu is still open

### Check application to see how it should work
- https://luftbilder.geoportal.ruhr/

![mb_bs1](https://user-images.githubusercontent.com/996298/37211797-658ac382-23ad-11e8-937c-24b4f629e4db.png)
![mb_bs2](https://user-images.githubusercontent.com/996298/37211803-6aac2a54-23ad-11e8-8340-5ab5a9f3191d.png)

**Comment by AxxL** [comment]
Das Beispiel nutzt Gruppen im im BaseSourceSwitcher. 

- Die 3 ersten Instancesets gehören zur einer Group "nrw"
- Die nächsten 2  gehören zu einer Group "osm".
- kein Hintergrund hat keine BaseSource ausgewählt. Und keine Gruppe.
- WebAtlAS Graustufen ist einzeln und gehört zu keiner Gruppe.

# Beobachtete Fehler:

- Bei diesen Menüs, die dann durch die Groups entstehen wird das erste (hier nrw bestehend aus DOP2 et al) automatisch geöffnet. Wenn man das zweite Menü öffnet (hier OSM), dann überdeckt das das erste.

Ich gehe davon aus, dass der Fehler nur darin besteht, dass das erste Menü (NRW) automatisch geöffnet wird.

**Comment by CharlyUnicorn** [comment]
When I upgraded Mapbender in January 2018, I noticed the same misbehavior:
Using a group in the BaseSourceSwitcher always opens the group at application startup.
Only by clicking on an entry, the group closes.
Testet on an intern Instance at https://bev-dev.wheregroup.com/mapbender/app_dev.php

**Comment by werrolf** [comment]
Can't reproduce in 3.0.5, seems like purely a 3.0.6 issue (which will make it easier to fix).

**Comment by DeEgge** [comment]
This line https://github.com/mapbender/mapbender/blob/release/3.0.6/src/Mapbender/CoreBundle/Resources/public/mapbender.element.basesourceswitcher.js#L35 is activating the first layer item from the drop down list on startup. 
@astroidex @CharlyUnicorn @AxxL @werrolf  Is this intended? Or is a configuration possible, in which the 2nd, 3rd, nth layer will be activated on startup? Otherwise

```javascript
...
this.element.find('.basesourcesetswitch:first').
this.element.find('.basesourcegroup').click();
...
```

will fix this.

**Comment by werrolf** [comment]
I think that's a crude and bad way to ensure the first configured base source layer gets activated when the application loads.
We don't need this anymore. [BaseSourceSwitcher plugs into the active layer config directly on application load](https://github.com/mapbender/mapbender/blob/release/3.0.6/src/Mapbender/CoreBundle/Element/BaseSourceSwitcher.php#L203)

**Comment by AxxL** [comment]
@DeEgge Was this fixed during FOSSGIS?

**Comment by astroidex** [comment]
![mb_master_basesourceswitcher](https://user-images.githubusercontent.com/996298/39347794-ba937780-49f4-11e8-9e34-ea515192bd35.png)

* seams to be still not ok.
* tested with actual master from 20.4.2018 https://github.com/mapbender/mapbender-starter/commit/cf1d81c43abe59740d81cb14af2d16b1795e8d06

**Observed behaviour**
* on start basesourceswitcher is closed -> ok
* but: when you use it the dropdowns still stay open after selection (see screenshot)

**Comment by astroidex** [comment]
* tested. Works fine in Mapbender 3.0.7.0 rc2
