### ISSUE TITLE
Logo und Hintergrund

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#796]
Hintergrund und Logo sollen anders abgetrennt sein:

Hintergrundfarbe grau: So wie die Farbe im TOC, wenn der Topic nicht ausgewählt ist (\#e0e0e0).

Schriftart "Mapbender" und "Version" in Schwarz.

Siehe Screenshot

![auswahl_019](https://user-images.githubusercontent.com/2235393/37592182-336130c6-2b6e-11e8-900b-bae8dfb4ed41.png)

**Comment by pwheregroup** [comment]
Was included in `feature/rtd_theme` . Checkout please.
