### ISSUE TITLE
Quickstart Ausdruck PDF

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#797]
Der Quickstart wird in Workshops ausgedruckt übergeben. In dem alten Thema (z.B. noch über https://docs.mapbender3.org/3062/de/book/quickstart.html) ist der Ausdruck über den Webbrowser ganz OK.

Mit dem neuen Theme ist der Ausdruck über den Webbrowser nicht besonders gut: Die Kopf- und Fußzeilen werden über den Inhalt überschrieben.

TODO: Anpassung des Styles, so dass der Quickstart aus dem Webbrowser ausgedruckt werden kann.

Alternative: Mögliche Anpassung des Bauens der Doku, so dass der Quickstart ausgedruckt übergeben werden kann.

**Comment by pwheregroup** [comment]
Cant see any issue here. Take a look at the attached screenshots:
<img width="1280" alt="bildschirmfoto 2018-03-19 um 13 59 18" src="https://user-images.githubusercontent.com/25791018/37596880-e1ae3462-2b7d-11e8-9c95-747123420408.png">
<img width="1280" alt="bildschirmfoto 2018-03-19 um 13 59 12" src="https://user-images.githubusercontent.com/25791018/37596879-e13a55c4-2b7d-11e8-9296-a8f85a50683e.png">
