### ISSUE TITLE
Users and Security - user with ACL Application can see hidden elements from other users

### ISSUE THREAD

**Issue by nmoelkner** [mapbender/mapbender#805]
Tried to create a user, who can import an application but cannot see the hidden applications from other users, like this:

1. Created the new user and gave him the rights: view, edit (even as master, the user can't create or import applications)
2. As described in the documentation, the user needs to have the right **Create** in the ACL "Application" (https://doc.mapbender.org/en/bundles/FOM/UserBundle/examples.html) to create or import and export applications, so I gave him the rights to view and create applications
3. As soon as the user got these rights, it was possible for him to create and import applications, but he could also see hidden applications from other users, like the root user

Tested this with the Mapbender versions 3.0.6.1 and 3.0.6.3

If this is how it should work, then a better documentation of the different features of the ACL with more examples of how to create users with different rights would be nice. Especially how users can create and import applications but cannot see the hidden ones from other users. 
If this is not how it should work, maybe it's a bug?

**Comment by rschwammborn** [comment]
Tested this in Mapbender 3.0.7.7. The described ACL bug is not recreatable anymore, so I'm closing this issue.
