### ISSUE TITLE
Metadata Dialog [Frontend] Internal Server Error message for WMS loaded via WMS Loader

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#809]
* Mapbender Shows Metadata for WMS via Layertree context menu in a dialog
* Problem: for WMS that are loaded via WMS Loader the metadata can't be displayed. Instead Mapbender Shows the message "**Internal Server Error**"

### Demo Application the check the behaviour
* https://release.mapbender.org/application/Geoportal_Metadata_internal_Server_error_809

### How can you reproduce the error?

- open the application 
- add a WMS via add WMS
- Check WMS metadata via context menu and Show Metadata

### Further Information
* mapbender.element.layertree.tree.js -> calls  _showMetadata: function(e) {..
* Error Message: Warning: Missing argument 2 for OwsProxy3\CoreBundle\Component\Exception\HTTPStatus502Exception::__construct(), called in /data/git/mapbender/application/owsproxy/src/OwsProxy3/CoreBundle/Component/WmsProxy.php on line 91 and defined

### possible Solution
* a solution could be to show a message: No Metadata available

![mb_metadata_dialog](https://user-images.githubusercontent.com/996298/38680132-db55c3be-3e65-11e8-83be-1340dc83c172.png)

**Comment by AxxL** [comment]
@astroidex This is fixed. Check out the newest on release.

**Comment by astroidex** [comment]
* great news, that it is fixed. 
* in which branch can I find it? I tried release/3.0.6

**Comment by AxxL** [comment]
Ah, seems to be a regression and not easy to replicate.

- Doesn't work on any application without login.
- Doesn't work on YAML Applications.
- Works on applications after login (which was I have tested).

Sample WMS: http://wms2016.wheregroup.com/cgi-bin/schwalmtal/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

**Comment by AxxL** [comment]
There is a connection to #841 and we need to get this thing together.

Please test against: https://www.wms.nrw.de/umwelt/HW_Gefahrenkarte?service=wms&version=1.1.1&request=getcapabilities

**Comment by AxxL** [comment]
The Source-ID in the request is wrong.

```
http://localhost/mapbender/app_dev.php/application/mapbender_user_yml/metadata

Parameter:

layerName | Hochwasser_Gefahrenkarte

sourceId | 3


```

**Comment by AxxL** [comment]
a solution could be to show a message: No Metadata available

**Comment by astroidex** [comment]
Thanks @philvanbwg for the fix. Works fine.
