### ISSUE TITLE
Coordinate Switcher 3.0.5.x doesn't honor GK

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#813]
Steps to reproduce:

- Take the 3.0.5.x branch.
- Open the mapbender_user_yml application
- Change the Coordinate-System to DHDN-Gauss-Krueger-3 or DHDN-Gauss-Krueger-2

Visible error:
- You are now somewhere in the Sahara area and the map-display is cluttered.

Expected behaviour:
- You see Bonn in GK2 or GK3 System.

**Comment by AxxL** [comment]
May be related to @LazerTiberius inclusion of Coordinate-Systems and projections.

**Comment by astroidex** [comment]
* this should be fixed from 3.0.6.2 on
* see CP Ticket 7913
