### ISSUE TITLE
[Documentation] new documentation is missing index of contents for the element

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#816]
The element documentation is structured in captions/sections. In the old documentation you could see the 	index of contents for the captions at the left side and jump to a chapter inside the element documentation easly. 

**Steps to reproduce**
* old documentation - see index of contents at the left: https://docs.mapbender.org/3063/en/bundles/Mapbender/CoreBundle/elements/map.html
* new - so index of content for the element: https://doc.mapbender.org/en/functions/basic/map.html

**Suggestion**
* reactivate the index of contents for a better overview

**Comment by AxxL** [comment]
The index on the left side cannot handle too much detailed subsections. I dont know of a way to make that work and more detailed.
