### ISSUE TITLE
[PrintClient] print error with PHP 7.1 as fontsize for extent_ur_y usw. runs on an error

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#817]
Steps to reproduce:
* make a print pdf print on Windows Apache 2.4 with PHP 7.1 
 

Observed behaviour:

* pdf ist not generated
* exit with notice Notice: A non well formed numeric value encountered

```
in vendor\setasign\fpdf\fpdf.php at line 516  -+     $this->FontFamily = $family; 
    $this->FontStyle = $style; 
    $this->FontSizePt = $size; 
    $this->FontSize = $size/$this->k; 
    $this->CurrentFont = &$this->fonts[$fontkey]; 
    if($this->page>0) 
        $this->_out(sprintf('BT /F%d %.2F Tf ET',$this->CurrentFont['i'],$this->FontSizePt));
```

`at PrintService ->addCoordinates () 
in mapbender\src\Mapbender\PrintBundle\Component\PrintService.php at line 485  -+         if (isset($this->conf['fields']['extent_ur_x']) && isset($this->conf['fields']['extent_ur_y']) 
                && isset($this->conf['fields']['extent_ll_x']) && isset($this->conf['fields']['extent_ll_y'])) 
        { 
            $this->addCoordinates(); 
        } 
`
* see actual master: https://github.com/mapbender/mapbender/blob/master/src/Mapbender/PrintBundle/Component/PrintService.php#L644

If you define a fixed font size the error does not occur anymore an pdf is generated
* f.e.
`        $pdf->SetFont('Arial', '', 6 );`

* reproduced the error with David on Windows Apache 2.4 with PHP 7.1

**Comment by astroidex** [comment]
* maybe the error occurs as the text is rotated? For all other textes the syntax is similar and works fine

**Comment by DeEgge** [comment]
To reproduce this, you need a print template the uses coordinates, i.e. *a4_portrait_offica*, which is located at `application/app/Resources/MapbenderPrintBundle/templates`. By default, this will not be configured in your print element, so you have to add it manually.

**Comment by astroidex** [comment]
Works fine. Thanks @DeEgge
