### ISSUE TITLE
SimpleSearch Solr search does not show results at search-column

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#822]
* in master mapbender-starter from 20.4.: https://github.com/mapbender/mapbender-starter/commit/948e547b02f4b0b429b9114616e0ddb24837e60a

Steps to reproduce:
* add SimpleSearch to your application
* search for something f.e. Brunnen
* no results are shown
* but with firebug->network you can see that the result has results
*  (status of this mapbender is pre 3.0.7.0 tag) works fine in application at https://release.mapbender3.org/application/solr_search

Observed behaviour:
* works fine in application at https://release.mapbender3.org/application/solr_search (to reproduce you can take the configuration from here)

Working with 3.0.6.3
![mb_simple_search_behaviour_in_3063](https://user-images.githubusercontent.com/996298/39613861-53d5b630-4f6b-11e8-91ec-f024a78a58e4.png)

Not working with master 20.4.2018 
![mb_simplesearch_tag_3070](https://user-images.githubusercontent.com/996298/39613870-6423acae-4f6b-11e8-89d5-529d1a9449a2.png)

**Comment by astroidex** [comment]
* still not working with mapbender-starter from 14.5.2018
* same behaviour see above
* https://github.com/mapbender/mapbender-starter/commit/4063d5a2478ecfe1019fb0baab4836f2fd1277b6

**Comment by werrolf** [comment]
This problem seems to be isolated to the built-in web server (`app/console server:run` or implicitly in `bootstrap`). I cannot reproduce the error when running through Apache. I can definitely reproduce the error when running through the built-in server.

**Comment by astroidex** [comment]
Yes - thanks @werrolf. Everything works fine when you use "normal" Apache Alias so we can close the issue.
