### ISSUE TITLE
[Digitizer] fails to initialize properly. Digitizer form is not displayed properly

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#823]
* in master mapbender-starter from 20.4.: https://github.com/mapbender/mapbender-starter/commit/948e547b02f4b0b429b9114616e0ddb24837e60a

Steps to reproduce:
* add digitizer to your application. See https://doc.mapbender3.org/en/functions/editing/digitizer.html
* load your application
* error: Digitizer does not initialize

![mb_digitizer_tag_3070_error_initialize](https://user-images.githubusercontent.com/996298/39613908-b22955ca-4f6b-11e8-9216-e98fe07c7c43.png)

**Comment by AxxL** [comment]
Cannot reproduce. Is there an error in your YAML configuration?

**Comment by AxxL** [comment]
@astroidex Confirmed. PR: https://github.com/mapbender/mapbender-starter/pull/75/

**Comment by LazerTiberius** [comment]
https://github.com/mapbender/mapbender-starter/pull/76
But please do not merge right now. The vis-ui version is not ready now

**Comment by werrolf** [comment]
Please try again on [current master](https://github.com/mapbender/mapbender-starter/commit/017edb65fa529d405f7124c604ada6dde4611de2).

Version bumps for the involved packages jquery, datatables, vis-ui, digitizer, have been integrated.

**Comment by astroidex** [comment]
* vis-ui was not loaded in with mapbender-starter from 14.5.2018
* https://github.com/mapbender/mapbender-starter/commit/4063d5a2478ecfe1019fb0baab4836f2fd1277b6

**Comment by astroidex** [comment]
fixed. Thanks @LazerTiberius
