### ISSUE TITLE
reactivate the build of Mapbender nightly versions

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#826]
* Documentation refers to nightly versions at https://mapbender.org/node/10
* https://mapbender.org/builds/nightly/
* since some time no nightly versions are build properly

**ToDo**
* reactivate nightly builds
* how can you make sure that the nighly build contains the last commit of each repository (check composer,json)?

**Comment by werrolf** [comment]
Nightly builds are an internal topic. The process is [already documented internally](https://repo.wheregroup.com/mapbender3/starter/wikis/installation_update/Neuinstallation,-Update-und-die-cutting-edge#cutting-edge-paketieren).
