### ISSUE TITLE
fix text on download pages

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#827]
There is additional text a on the download pages (see below).  Some links text should be fixed.

**Suggestions**

* https://mapbender.org/builds/
* FIX: Welcome to the list of Mapbender3 downloads. -> Mapbender
* FIX Have a look at the Mapbender3 page at -> Have a look at the Mapbender page at https://mapbender.org

* https://mapbender.org/builds/nightly/
* FIX link to Mapbender2 downloads is: http://mapbender2.org/download/
* FIX Have a look at the Mapbender3 page at http://mapbender3.org -> Have a look at the Mapbender page at https://mapbender.org/

also at http://mapbender2.org/download/
* FIX to Mapbender2 : Welcome to the Mapbender2 Download Page
* FIX For Mapbender Version 3.x builds go to https://mapbender.org/builds/

**Comment by astroidex** [comment]
@AxxL - I can do the fixes.

**Comment by AxxL** [comment]
@astroidex 

- Since I was on the mapbender.org page with A. I fixed the links at the Download page.
- I fixed the mapbender.org/builds Header and Footer.


- I haven't changed the mapbender2.org page (no login).

**Comment by astroidex** [comment]
* great

Also fixed with P:
* http://mapbender2.org/download/
* https://mapbender.org/builds/
* https://mapbender.org/builds/nightly/
