### ISSUE TITLE
support php 7.2

### ISSUE THREAD

**Issue by gerald2545** [mapbender/mapbender#828]
trying to use mapbender on a centos 7 server with php 7.2.4, failed with : 
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /save/devcrgs/src/mapbender/mapbender3-starter-3.0.6.3/vendor/nette/nette/Nette/common/Object.php on line 53

I managed to use it (just tried public applications) without errors after renaming the Object class in the source code.

Is there some work ongoing to support php 7.2 and higher?
can I suggest a pull request with these modifications?

Gérald

**Comment by gerald2545** [comment]
I began to have a look at this pull request...but not so straightforward.
In fact, I modified my mapbender instance (replaced Object class to Object2 class) directly... and in fact, I just saw that I modified files in nette framework..... to suggest a pull request, i would have to upgrade the nette framework to 2.4 minimum (https://github.com/nette/utils)....but really not enough time for the moment....sorry 


Gerald

**Comment by AxxL** [comment]
@gerald2545 A key-element for Mapbender and Symfony/PHP is the composer.json file where the external libraries are loaded. Nette comes with apigen and we are looking to update apigen to a version that also works with the minimum PHP version we have to support which is somewhere at PHP 5.6. But fortunetaly apigen is only used for creating the API documentation and therefore not needed for the run of Mapbender.

For a current workaround you can say: `bin/composer install --no-dev`and this will omit the contents on the require-dev part of the composer.lock. If you say `bin/composer update --no-dev` it will grab the newest libraries according to the specifications in composer.json but without the libraries in the require-dev part.

You can safely delete the contents of the vendor directory before that step. The composer command will fill that up again.
