### ISSUE TITLE
Template "Responsive" not documented

### ISSUE THREAD

**Issue by JakobMiksch** [mapbender/mapbender#829]
Mapbender provides 5 templates:

![image](https://user-images.githubusercontent.com/15704517/39994934-14d12aa6-577b-11e8-9182-e8fc9502e4e2.png)

The [documentation](https://doc.mapbender.org/en/customization/mapbender_templates.html) describes only 4 of them. "Responsive" is missing.

**Comment by astroidex** [comment]
Hello @JakobMiksch. Please note that some of the templates are deprecated and will not be available in future version. Fullscreen and Mapbender mobile Template are used. Classic Template, Responsive and Fullscreen alternative are templates for testing.

**Comment by AxxL** [comment]
Created an issue of this: https://github.com/mapbender/mapbender/issues/854

Comments there are welcome.
