### ISSUE TITLE
WMS Loader: PNG instead of BMP and FeatureInfo

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#841]
Steps to reproduce:

Load this nice WMS: https://www.wms.nrw.de/umwelt/HW_Gefahrenkarte?service=wms&version=1.1.1&request=getcapabilities

- [ ] image/png instead of image/bmp. because of transparency and size.

- [ ] featureinfo doesn't work.

**Comment by astroidex** [comment]
In element WMSLoader you can define defaultformat and defaultfeatureinfoformat that should be used when you load a WMS. Functionality still works with 3.0.6.3 (WMS is loaded as pngand featureInfo works)
* https://doc.mapbender.org/en/functions/misc/wms_loader.html

**Comment by astroidex** [comment]
Does splitLayers and useDeclarative stll work? https://doc.mapbender.org/en/functions/misc/wms_loader.html

**Comment by AxxL** [comment]
see #843, #844
