### ISSUE TITLE
WMS Loader Use declarative

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#843]
Steps to reproduce:

Build an application with the following parameters:

WMS Loader:

- Set use declarative as true.

FeatureInfo:
- Set show original = false
- Set only valid = false

Start application.

Load WMS: http://wms2016.wheregroup.lan/cgi-bin/mapserv?map=/data/umn/schwalmtal/schwalmtal.map&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.1.1 (internal)

Zoom to region.
FeatureInfo.

Two links are in the result of the landuse (Flurstücke): show link1 and show link 2. Both should load Mapbender Users.

What should happen:

- The Mapender Users service loads with two layers. Mapbender Info is deactivated. Mapbender Users is activated.

What happens:

- Nothing.

**Comment by werrolf** [comment]
[Feature-Info URL (get) Layer "landnutzung"](http://wms2016.wheregroup.lan/cgi-bin/mapserv?map=/data/umn/schwalmtal/schwalmtal.map&_signature=45%3AZX8Imo7J5o15iHQPjZwZomF2iFU&LAYERS=landnutzung&QUERY_LAYERS=landnutzung&STYLES=&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&EXCEPTIONS=application%2Fvnd.ogc.se_xml&BBOX=306260.99492%2C5673535.112184%2C311341.00508%2C5675934.887816&FEATURE_COUNT=10&HEIGHT=907&WIDTH=1920&FORMAT=image%2Fpng&INFO_FORMAT=text%2Fhtml&SRS=EPSG%3A25832&X=915&Y=405)  

=> ```msWMSFeatureInfo(): WMS server error. Requested layer(s) are not queryable.```

???

[Feature-Info URL Layer "Flurstuecke"](http://wms2016.wheregroup.lan/cgi-bin/mapserv?map=/data/umn/schwalmtal/schwalmtal.map&LAYERS=Flurstuecke&QUERY_LAYERS=Flurstuecke&STYLES=&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&EXCEPTIONS=application%2Fvnd.ogc.se_xml&BBOX=306260.99492%2C5673535.112184%2C311341.00508%2C5675934.887816&FEATURE_COUNT=10&HEIGHT=907&WIDTH=1920&FORMAT=image%2Fpng&INFO_FORMAT=text%2Fhtml&SRS=EPSG%3A25832&X=932&Y=405) works.

Click on "mb-action" link reloads feature info iframe.

Event bindings do not cross iframes. Suggest binding [mb-action click handler](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.distpatcher.js) into FeatureInfo's iframe [in a load event handler](https://stackoverflow.com/a/13782102).

**Comment by werrolf** [comment]
With visible feature info, the following JS console code loads the WMS....
```
Mapbender.declarative['source.add.wms']($(($('a[mb-action]', $('iframe').contents()))[0]))
```

**Comment by astroidex** [comment]
* should also work with Display Original: true (in featureInfo-Element)
* I opened a separate ticket: #847 847
