### ISSUE TITLE
Print: Change prefix for output file to mapbender

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#855]
The current prefix for the outputfile is hardcoded to mapbender3.

Change that to mapbender.

Steps to reproduce:

- Print
- Save.
- The file is called by default something like "mapbender3-<date>".

Expected:

- The file should be called by default something like "mapbender-<date>". So without the 3.

**Comment by werrolf** [comment]
Resolved in [f540768](https://github.com/mapbender/mapbender/commit/f540768a7f8fd58e824ae643789b5292f0db9acb), came out in v3.0.7.2.
