### ISSUE TITLE
import of applications via app/console assigns different numbers to title and slug

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#860]
You can import applications via app/console comand:

`app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Application/ --append`

If you have a Mapbender running since a long time it can happen, that you run this command more often to see what happened in the template applications. And sometimes you rename an application to use it in some context.

Now I discovered that the counter for the column title is different than the counter for the column slug (see table mb_core_application)

smb://center/wheregroup/Austauschordner/astrid/Mapbender/mb_differnt_count_after_yml_import_via_app_console.png

**To Reproduce**
1. run app/console

`app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Application/ --append`

2. rename title column for imported application and set numbe to 100 f.e

3. run app/console again

`app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Application/ --append`

4. check table mb_core_application and have a look at the columns title and slug

**Versions (please complete the following information):**
 - Mapbender: 3.0.7.0
 - Mapbender: 3.0.6.3

**Comment by eschuettler** [comment]
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html
