### ISSUE TITLE
[Redlining] text  should not appear in the map and print with a red circle 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#862]
With redlining you can draw temporary objects to produce a nice print output.
* see: https://doc.mapbender.org/en/functions/editing/redlining.html

![redlining1](https://user-images.githubusercontent.com/996298/41463107-844c4b76-7095-11e8-9a5b-aff5dcb19600.png)

With 3.0.7.0rc2 textes look like this: 
* they have a red circle at  bottom left when you draw them
* This does not look good in the application and in pdf output (in **image export** the circles are not drawn)

Example of a pdf output:
![mb_redlining_print](https://user-images.githubusercontent.com/996298/41463454-cf454e9c-7096-11e8-8738-76f0f1c68eac.png)

**To Reproduce**
1. use redlining and draw a text
2. print pdf

**Suggestion**
* do not draw the circle in the client and not in the PDF output (draw them only when you edit the text)

**Versions (please complete the following information):**
 - Mapbender: 3.0.7.0

**Comment by werrolf** [comment]
Points beside the labels are intended. They allow you to see what you labeled. See [#401](https://github.com/mapbender/mapbender/issues/401).

Point labels print fine now.

**Comment by werrolf** [comment]
Please abstain of reopening this issue for further discussion of whether or not there should be visible points next to a label. Use [#1126](https://github.com/mapbender/mapbender/issues/1126) for that. Besides, it's intended.
