### ISSUE TITLE
[Button] choose target offers all elements (buttons elements included and element itself included)

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#863]
When you create a button element you often want to set the target to an "action-element" f.e. print. But never you want to refer to another button.

For this reason at all versions <= 3.0.6.3 only the elements are offered that make sense -> that are all elements except buttons and the element itself

You can test the right behaviour at the old version 3.0.6.3:
* https://version.mapbender.org/3063/

**To Reproduce**
1. create a button element **myNewButton**
2. go to target: you see many elements offered -> many of them are other button elements
3. Save the button
4. reopen the button and go to target again: you can choose the button **myNewButton**

**Versions (please complete the following information):**
 - Mapbender: 3.0.7.0

**Comment by AxxL** [comment]
@astroidex This is fixed in the current master of Mapbender. Please check if it works in your environment. Please reopen if still present. My checks are Ok.
