### ISSUE TITLE
[OL] [Element scannen] About Dialog

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#868]
"Mapbender\\CoreBundle\\Element\\AboutDialog"

- [ ] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] greift auf olLayer zu?
- [ ] greift auf olMap zu?
- [ ] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by GeOSMRob** [comment]
The element doesn't have any mentioned dependencies.
