### ISSUE TITLE
[OL] [Element scannen] Button

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#871]
"Mapbender\\CoreBundle\\Element\\Button"

- [ ] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] greift auf olLayer zu?
- [ ] greift auf olMap zu?
- [ ] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by pwheregroup** [comment]
- [ ] Greift auf mqlayer zu (Mapquery)?
- [ ] Greift auf Mapbender.source zu?
- [ ] Greift auf Openlayers.popup zu?
- [ ] Greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] Greift auf olLayer zu?
- [ ] Greift auf olMap zu?
- [ ] Hat andere Zugriffe auf OpenLayers?
- [ ]  Hat andere Zugriffe auf Mapquery?
