### ISSUE TITLE
[OL] [Element scannen] Gps Position

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#875]
"Mapbender\\CoreBundle\\Element\\GpsPosition",

- [ ] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [x] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [x] greift auf olLayer zu?
- [x] greift auf olMap zu?
- [x] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by GeOSMRob** [comment]
olMap:
- [getLayersByName()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L70)
- [removeLayer()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L81)
- [destroy()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L82)
- [addLayer()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L95)
- [getLayersByName()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L101)
- [getProjectionObject()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L110)
- [getExtent()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L136)
- [panTo()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L140)
- [zoomToExtent()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L162)

Openlayers.style:
- [OpenLayers.Layer.Vector](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L86)
- [addFeatures()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L94)
- [OpenLayers.Feature.Vector](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L120)
- [createRegularPolygon()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L121)
- [OpenLayers.Geometry.Point](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L123)

Openlayers:
- [OpenLayers.Projection](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L109)
- [OpenLayers.LonLat](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L112)
- [transform()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js#L113)

**Comment by werrolf** [comment]
[Implementation](https://github.com/mapbender/mapbender/issues/875) finished, looking fine in testing.
