### ISSUE TITLE
[OL] [Element scannen] Layertree

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#877]
"Mapbender\\CoreBundle\\Element\\Layertree",

- [ ] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] greift auf olLayer zu?
- [ ] greift auf olMap zu?
- [ ] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by DeEgge** [comment]
Keine der o.g. Abhängigkeiten, aber sehr viel Model, was ich hier mal aufnehme

**model**

* [var sources = this.model.getSources();](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js#L71)
* [var layerset = this.model.findLayerset({](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js#L102)
* [this.model.setSourceLayerOrder(sourceId, layerIdOrder.reverse());](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js#L191)
* [this._createTreeNode(added.source, added.source, this.model.getScale(), added.children[layerid], $(](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js#L420)

**Comment by werrolf** [comment]
Most dependencies already resolved. The only major todo left open is layer / source / theme reordering. 
See [implementation ticket](https://github.com/mapbender/mapbender/issues/688).  
Closing this one, thanks.
