### ISSUE TITLE
[OL] [Element scannen] Map

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#879]
"Mapbender\\CoreBundle\\Element\\Map",

- [x] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [x] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [x] greift auf olLayer zu?
- [x] greift auf olMap zu?
- [x] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by GeOSMRob** [comment]
olMap:
- [OpenLayers.ProxyHos(https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.map.js#L22)

**Comment by werrolf** [comment]
[Implementation ticket](https://github.com/mapbender/mapbender/issues/689).

Map is already functional.  
Unclear if we even need to reimplement the assorted introspection methods (getZoom etc).
