### ISSUE TITLE
[OL] [Element scannen] Overview

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#880]
"Mapbender\\CoreBundle\\Element\\Overview",

- [ ] greift auf mqlayer zu (Mapquery)?
- [x] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] greift auf olLayer zu?
- [x] greift auf olMap zu?
- [x] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by DeEgge** [comment]
**Mapbender.source**

* [Mapbender.source[layerDefinition.type].getLayersList(layerDefinition, layerConfiguration.children[0], true);](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L113)

**olMap**

* [mbMap.map.olMap.addControl(widget.overview);](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L91)

**OpenLayers**

* [new OpenLayers.Size(options.width, options.height)](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L72)
* [widget.overview = new OpenLayers.Control.OverviewMap(overviewOptions);](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L89)
* [url = OpenLayers.ProxyHost + encodeURIComponent(url);](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L122)
* [new OpenLayers.Layer.WMS(layerDefinition.title, url, {](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L125)
* [newextent.transform(extentObj.projection, projection);](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L158)
* [var center = ovMap.getCenter().transform(oldProj, srs.projection);](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L174)
* [greift auf eine ganze Menge Properties einer olMap zu](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L176)
```
ovMap.projection = srs.projection;
ovMap.displayProjection = srs.projection;
ovMap.units = srs.projection.proj.units;
ovMap.maxExtent = widget._transformExtent(widget.mapOrigExtents.max, srs.projection);
```
* [layer.initResolutions();](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L190)
* [overview.update();](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L193)
* [ ovMap.setCenter(center, ovMap.getZoom(), false, true);](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L194)

**Comment by DeEgge** [comment]
olMap.addControl(widget.overview) -> https://openlayers.org/en/latest/apidoc/ol.control.OverviewMap.html

**Comment by werrolf** [comment]
[Implementation](https://github.com/mapbender/mapbender/issues/915) is already 71.625% complete. OL2 dependencies are resolved. Remaining TODOs in implementation ready to adress.
