### ISSUE TITLE
[OL] [Element scannen] POI

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#881]
"Mapbender\\CoreBundle\\Element\\POI",

- [ ] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] greift auf olLayer zu?
- [x] greift auf olMap zu?
- [x] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by DeEgge** [comment]
**olMap**

* [ll = olMap.getLonLatFromPixel(new OpenLayers.Pixel(x, y)),](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.poi.js#L55)
* [this.mbMap.map.olMap.addLayer(this.poiMarkerLayer);](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.poi.js#L69)
* [var proj = this.mbMap.map.olMap.getProjectionObject();](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.poi.js#L82)
* [self.mbMap.map.olMap.removeLayer(self.poiMarkerLayer);](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.poi.js#L126)

**OpenLayers**
* [ll = olMap.getLonLatFromPixel(new OpenLayers.Pixel(x, y)),](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.poi.js#L55)
* [var proj = this.mbMap.map.olMap.getProjectionObject();](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.poi.js#L82)
* [this.poiMarkerLayer = new OpenLayers.Layer.Markers();](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.poi.js#L68)
* [this.poiMarkerLayer.clearMarkers();](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.poi.js#L71)
* [var poiMarker = new OpenLayers.Marker(ll, new OpenLayers.Icon(](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.poi.js#L72)
* [this.poiMarkerLayer.addMarker(poiMarker);](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.poi.js#L81)
* [scale: mbMap.model.getScale(),](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.poi.js#L91)
* [self.poiMarkerLayer.destroy();](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.poi.js#L127)

**Comment by werrolf** [comment]
Getter for lon / lat used only for placing marker layer. Should be [provided by model in context of vector layer handling](https://github.com/mapbender/mapbender/issues/925#issuecomment-398339773).  
Projection getter is used only for presentation (visible number formatting, different rounding behaviour "geodesic").
