### ISSUE TITLE
[OL] [Element scannen] Ruler

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#883]
"Mapbender\\CoreBundle\\Element\\Ruler",

**Comment by inacht** [comment]
- [ ] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] greift auf olLayer zu?
- [ ] greift auf olMap zu?
- [ ] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by werrolf** [comment]
Control: the element creates an OpenLayers.Control.Measure. I.e. the entire runtime behaviour is implemented by Openlayers.

I can't find an equivalent [in Openlayers 4](https://github.com/openlayers/openlayers/tree/v4.6.5/src/ol/control).

**Comment by werrolf** [comment]
Projection: used exclusively to check for "geodesic" projection, and forwarding to the Control.

Style: initialized once, single StyleMap, never touched again.

**Comment by werrolf** [comment]
[Implementation ticket](https://github.com/mapbender/mapbender/issues/683) is already making good progress.  
Closing this one, thanks.
