### ISSUE TITLE
[OL] [Element scannen] Scale Bar

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#884]
"Mapbender\\CoreBundle\\Element\\ScaleBar",

**Comment by pwheregroup** [comment]
- Greift auf mqlayer zu (Mapquery)? => Nein
- Greift auf Mapbender.source zu? => Nein
- Greift auf Openlayers.popup zu? => Nein
- Greift auf Openlayers.style oder Openlayers.stylemap zu? => Nein
- Greift auf olLayer zu? => Nein
- Greift auf olMap zu? => Ja
- Hat andere Zugriffe auf OpenLayers? => Ja
--OpenLayers.Control.ScaleLine
- Hat andere Zugriffe auf Mapquery? => Nein

**Comment by werrolf** [comment]
[Implementation](https://github.com/mapbender/mapbender/issues/913) is done. Thanks y'all!
