### ISSUE TITLE
[OL] [Element scannen] Scale Selector

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#886]
"Mapbender\\CoreBundle\\Element\\ScaleSelector",

- [ ] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] greift auf olLayer zu?
- [x] greift auf olMap zu?
- [ ] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by GeOSMRob** [comment]
- olMap
https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.scaleselector.js#L58

**Comment by werrolf** [comment]
Call can be replaced with [getScale / setScale](https://github.com/mapbender/mapbender/issues/941).
