### ISSUE TITLE
[OL] [Element scannen] Sketch

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#889]
"Mapbender\\CoreBundle\\Element\\Sketch",

**Comment by inacht** [comment]
# Checkliste

- [ x] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] greift auf olLayer zu?
- [ x] greift auf olMap zu?
- [ ] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

Mapquery/olMap Zugriffe:
var mq = this.map.data('mapQuery');  // Z. 91
mq.olMap.addControl(cntrl); // Z. 96
mq.olMap.addLayer(self.layers[type]); // Z. 100
mq.olMap.addControl(self.controls[type]);  // Z. 102
mq.olMap.removeControl(self.controls[type]); // Z. 113
mq.olMap.removeLayer(self.layers[type]);  //. Z. 114

**Comment by werrolf** [comment]
[Implementation](https://github.com/mapbender/mapbender/issues/910) is ready.  
Closing this one, thanks.
