### ISSUE TITLE
[OL] [Element scannen] Wmc Loader

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#893]
"Mapbender\\WmcBundle\\Element\\WmcLoader"

- [ ] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] greift auf olLayer zu?
- [ ] greift auf olMap zu?
- [ ] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by sveta-wl** [comment]
The element has dependencies to the WMC Handler, check [
[OL] [Element scannen] Wmc Handler](https://github.com/mapbender/mapbender/issues/927)

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
