### ISSUE TITLE
[OL] [Element scannen] Wmc List

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#894]
"Mapbender\\WmcBundle\\Element\\WmcList",

- [ ] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] greift auf olLayer zu?
- [ ] greift auf olMap zu?
- [ ] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by philvanbwg** [comment]
greift auf keine der erwähnten Sachen zu
