### ISSUE TITLE
[OL] [Element scannen] Wmc Editor

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#895]
"Mapbender\\WmcBundle\\Element\\WmcEditor",

**Comment by pwheregroup** [comment]
- [ ] Greift auf mqlayer zu (Mapquery)?
- [ ] Greift auf Mapbender.source zu?
- [ ] Greift auf Openlayers.popup zu?
- [ ] Greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] Greift auf olLayer zu?
- [ ] Greift auf olMap zu?
- [ ] Hat andere Zugriffe auf OpenLayers?
- [ ]  Hat andere Zugriffe auf Mapquery?

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
