### ISSUE TITLE
[OL] [Element scannen] Suggest Map

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#896]
"Mapbender\\WmcBundle\\Element\\SuggestMap",

- [ ] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [x] greift auf olLayer zu?
- [x] greift auf olMap zu?
- [x] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by GeOSMRob** [comment]
olMap:
- [getProjectionObject()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/WmcBundle/Resources/public/mapbender.element.suggestmap.js#L70)

olLayer:
- [ OpenLayers.Bounds.fromArray()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/WmcBundle/Resources/public/mapbender.element.suggestmap.js#L75)

model:
- [sourceById()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/WmcBundle/Resources/public/mapbender.element.suggestmap.js#L66)
- [mqLayerBySourceId()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/WmcBundle/Resources/public/mapbender.element.suggestmap.js#L69)
- [getProj()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/WmcBundle/Resources/public/mapbender.element.suggestmap.js#L50)
- [addSource()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/WmcBundle/Resources/public/mapbender.element.suggestmap.js#L77)
- [changeProjection()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/WmcBundle/Resources/public/mapbender.element.suggestmap.js#L79)
- [getMapState()](https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/WmcBundle/Resources/public/mapbender.element.suggestmap.js#L157)
