### ISSUE TITLE
[OL] [Element scannen] Digitizer

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#899]
"Mapbender\\DigitizerBundle\\Element\\Digitizer",

- [ ] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [x] greift auf Openlayers.popup zu?
- [x] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [x] greift auf olLayer zu?
- [x] greift auf olMap zu?
- [x] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by DeEgge** [comment]
**Style**
* [var style = new OpenLayers.Style(styleData, {uid: styleId});](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L2749)
* []()

**OpenLayers**

* [layer.removeAllFeatures()](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L2729)
* [layer.addFeatures(features)](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L2730)
* [layer.redraw();](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L2759)
* [layer.setVisibility(true)](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L3202)

**Comment by GeOSMRob** [comment]
RowNumber:  2171-2713

olMap:
- [getControlsByClass](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L1258)
- [getMap](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L2308)
- [zoomToExtent](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L2311)
- [zoomToScale](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L2313)
- [getScale](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L2349)

Openlayers:
- [OpenLayers.Control.SelectFeature](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L1253)
- [OpenLayers.Feature](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L1280)
- [OpenLayers.Feature.drawFeature](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L2204)
- [OpenLayers.Strategy.Cluster](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L2361)
- [OpenLayers.Feature.drawFeature](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L2204)

**Comment by philvanbwg** [comment]
Andere Zugriffe auf OpenLayers:

- [OpenLayers.Control.SelectFeature](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L 638)

- [OpenLayers.Control.ModifyFeature](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L 643)

- [OpenLayers.Format.WKT](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L 643)

- [OpenLayers.Format.GeoJSON](https://github.com/mapbender/mapbender-digitizer/blob/release/1.2/Resources/public/mapbender.element.digitizer.js#L 854)

**Comment by inacht** [comment]
**mqlayer zu (Mapquery)**
[$('#' + options.target).data('mapbenderMbMap').map.olMap], Zeile 523

**Comment by inacht** [comment]
Zeilen 1030-1627: 
 
 **olMap**
- olMap.zoomToExtent, Z.: 1174 
- olMap.zoomToScale, Z. 11777 
 
 
**andere Zugriffe auf OpenLayers
- new OpenLayers.Control.SelectFeature, ab Z. 1253



new OpenLayers.Control.SelectFeature(layer, {
    hover:        true,
    clickFeature: function(feature) {

    },
    overFeature:  function(feature) {
    },
    outFeature:   function(feature) {
    }
});
 
- OpenLayers.Feature (als Funktionsparameter), Z. 1445
- new OpenLayers.Format.WKT().write(feature), Z. 1526
- new OpenLayers.Format.GeoJSON(), Z. 1587

**Comment by AxxL** [comment]
Implementation see #902
