### ISSUE TITLE
[OL] [Implementierung] ImageExport

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#903]
PR  https://github.com/mapbender/mapbender/pull/957
I think, in summary, it runs well now.
However, some print style options like hoverStrokeColor, hoverStrokeOpacity etc. i did not see a way, where to retrieve them from, and therefore did  hard code them (like i saw them used at http://demo.mapbender3.org). This should be checked later, if to get them from a kind of default  option object, or whatever.

**Comment by werrolf** [comment]
I'm observing collateral regressions when exporting after [adding Redlining geometries](https://github.com/mapbender/mapbender/issues/908). Redlining itself has feature style regressions atm.  
There is likely a common cause TBD.

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
