### ISSUE TITLE
[OL] [Implementierung] ZoomBar

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#909]
Documentation Zoombar: https://doc.mapbender.org/de/functions/basic/zoom_bar.html

- Pan (at the top)
- History (jump back to the previous 10 extents, jump again forwards).
- ZoomBox (if you are too lazy to hold Shift and left Mouse)
- Zoom to max extent (defined in map-control)
- ~~Zoom in/out~~ (deprecated, is part of the Zoom Slider)
- Zoom Slider (from the scales defined in the map-control).

**Comment by pwheregroup** [comment]
Greift auf mqlayer zu (Mapquery)? => Nein
Greift auf Mapbender.source zu? => Nein
Greift auf Openlayers.popup zu? => Nein
Greift auf Openlayers.style oder Openlayers.stylemap zu? => Nein
Greift auf olLayer zu? => Nein
Greift auf olMap zu? => Ja
Hat andere Zugriffe auf OpenLayers? => Ja
-- OpenLayers.Util.getScaleFromResolution(...)
-- OpenLayers.Control.NavigationHistory(...)
-- OpenLayers.Control(...)
-- OpenLayers.Util.extend(...)
-- OpenLayers.Handler.Box(...)
-- OpenLayers.Pixel(...)
-- OpenLayers.Bounds(...)
-- OpenLayers.Bounds(...)
Hat andere Zugriffe auf Mapquery? => Nein

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
