### ISSUE TITLE
[OL] [Implementierung] POI

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#914]
POI needs
* a vector / marker layer to display its markers
* conversion from pixel coordinate to projection-space coordinate
* getter for current map scale

- [ ] evaluate POI link
   - [x] Jump to approrpiate POI center / zoom when entering the application with a `?poi=...` parameter
   - [ ] display marker layer
- [ ] ? Generate POI link via POI Element

**Comment by werrolf** [comment]
Hint: you can test _any_ Mapbender application for POI evaluation by appending the following to your URL:
```
?poi%5Blabel%5D=Wuppertal%21&poi%5Bpoint%5D=372850%2C5680757&poi%5Bsrs%5D=EPSG%3A25832
```

**Comment by werrolf** [comment]
Previous POI initialization:
https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.model.js#L120  
https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/mapbender.model.js#L133

**Comment by werrolf** [comment]
Works fine, closing.
