### ISSUE TITLE
[OL] [Implementierung] Overview

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#915]
- [x] Basic function, follow main map
- [x] "anchor" settings (top left / bottom right etc)
- [ ] width / height settings: e.g. with a slighly weird w200 x h250, the canvas is snapped to the top ~half, the rest is white
- [x] "maximized" option on + off
- [ ] "fixed" option; only behaves as expected when off
- [x] [adapt to main map srs changes](https://github.com/mapbender/mapbender/issues/958)

**Comment by werrolf** [comment]
Progress paused with open TODOs.
I've left some [comments in the code](https://github.com/mapbender/mapbender/blob/edc7b2bcdbd958a5dff2156d74a4f68a46d94aaf/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L73) to document what I've tried with the`fixed` option.

`fixed`=true should nail the overview down to a fixed extent (fitting the maximum extent configured on target Map) and zoom level. A `fixed` overview should never pan and never change resolution. It should only update its little box border.

I need someone to continue this.

Hint: you can have multiple overview maps with different settings in the same application. Just use different corners.

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
