### ISSUE TITLE
[OL] [Implementierung] Legend

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#916]
- [ ] react to layer activation / deactivation
- [x] react to source activation / deactivation
- [x] react to layer reordering
- [x] react to source reordering

**Comment by werrolf** [comment]
Progress paused.
Open TODO:
* react to layer activation /deactivation when layer toggled in layertree

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
