### ISSUE TITLE
AssetPipeline anlegen

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#922]

**Comment by werrolf** [comment]
[Asset-Weiche für Engine-Assets auf Applikationsebene](https://github.com/mapbender/mapbender/blob/2417e8edb4b5682dbb1c897ae256c884f26ace78/src/Mapbender/CoreBundle/Component/Application.php#L143)  

[Element::getMapEngineCode als Basis für Fallunterscheidungen in Element::getAssets](https://github.com/mapbender/mapbender/blob/2417e8edb4b5682dbb1c897ae256c884f26ace78/src/Mapbender/CoreBundle/Component/Element.php#L799)  

Nebenschauplatz: [Engine-Code ('ol4'; legacy: 'mq-ol2') im Javascript global verfügbar gemacht unter `Mapbender.configuration.application.mapEngineCode`](https://github.com/mapbender/mapbender/blob/2417e8edb4b5682dbb1c897ae256c884f26ace78/src/Mapbender/CoreBundle/Component/Presenter/Application/ConfigService.php#L76)
