### ISSUE TITLE
Fehlende Abstraktionen definieren

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#925]

**Comment by werrolf** [comment]
Häufig benötigt:
* getter f. aktuellen Projektionscode [WmcHandler](https://github.com/mapbender/mapbender/issues/927)
* zoom zu "bounds" (meistens Koordinaten + EPSG) [WmcHandler](https://github.com/mapbender/mapbender/issues/927)

**Comment by werrolf** [comment]
Vector layers are needed for static and dynamic features and markers. Vector layers should be centrally managed (so visibility ordering is reliable).  

Vector layer API must provide functions to
* prespecify and modify feature styling
* add, hide, display, list, modify, delete features and markers belonging to an Element
* convert from viewport pixel space to projection-specific coordinates and back
* list existing features and markers at viewport pixel space coordinate
* add and alter hover and click event hooks on features and markers

Vector layers are used by
* [POI](https://github.com/mapbender/mapbender/issues/881)

**Comment by werrolf** [comment]
Need getters for current Scale (float). Used by
* [POI](https://github.com/mapbender/mapbender/issues/881)

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
