### ISSUE TITLE
[OL] [Element scannen] Wmc Handler

### ISSUE THREAD

**Issue by sveta-wl** [mapbender/mapbender#927]
"Mapbender\WmcBundle\Resources\public\mapbender.wmchandler.js"

- [ ] greift auf mqlayer zu (Mapquery)?
- [ ] greift auf Mapbender.source zu?
- [ ] greift auf Openlayers.popup zu?
- [ ] greift auf Openlayers.style oder Openlayers.stylemap zu?
- [ ] greift auf olLayer zu?
- [x] greift auf olMap zu?
- [x] hat andere Zugriffe auf OpenLayers?
- [ ] hat andere Zugriffe auf Mapquery?

**Comment by sveta-wl** [comment]
**olMap**
- [model.map.olMap.getProjectionObject](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/WmcBundle/Resources/public/mapbender.wmchandler.js#L61)

**OpenLayers**
- [OpenLayers.Bounds.fromArray](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/WmcBundle/Resources/public/mapbender.wmchandler.js#L81)
- [OpenLayers.Bounds.fromArray](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/WmcBundle/Resources/public/mapbender.wmchandler.js#L89)

**Comment by werrolf** [comment]
Projection getter / setter only used to optimize away setting same projection. Model should handle this.
See https://github.com/mapbender/mapbender/issues/925#issuecomment-398339773
