### ISSUE TITLE
Popup mit Geobezug

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#930]
1. Klick-Handler auf der Karte registrieren

2. Neue Javascript-Klasse für das OL4-Popup, Konstruktor bekommt:
  - Koordinaten (Pixel)
  - Content (optional!)
  - Close-Event-Handler
  + Setter für Content und Position (=Verschieben bei offenem Popup)
  
3. Mapbender.Model in der OL4-Version erzeugt das Popup, leitet einfach den Konstruktor-Aufruf durch, und gibt das Objekt zurück.

**Comment by AxxL** [comment]
@LazerTiberius Bitte Testszenario identifizieren und dann in Testing schieben.

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
