### ISSUE TITLE
change demo applications and refer to translation variable instead of fixed english text

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#931]
If you use Mapbender not in an english context (f.e. in Germany or France) you would like to have the Mapbender application in german or french.
* the demo applications are always in english and
* if you take the demo applications as template you always have to change the textes after import of the applications 

This is because in the mapbender yml applications the englis text is used and not the translation variable f.e.:
In row 59 it says **Layertree** -> and it should refer to the variable **mb.core.layertree.class.title**:

see: 
https://github.com/mapbender/mapbender-starter/blob/master/application/app/config/applications/mapbender_user.yml#57

This can easily be fixed when you use the varibles from the messages.[lang].yml f.e. messages.de.yml. Some words are missing at the moment (f.e. tooltip, line, area) and could be added easily in the section of the element.

https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/translations/messages.de.yml#L207

I already translated the mapbender_user.yml to mapbender_user_trans.yml - so you can try.
* you find the file here: https://gist.github.com/astroidex/d1672db03264608cbdfd3a550f05b962

**To Reproduce**
1. put the file to you app/config/application directory
2. change locale to de in parameters.yml
3. clear cache
4. open mapbender - find the new application in german
5. import the applications from yaml via 
` app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Application/ --append`
6. find the new application imported in german

**Versions (please complete the following information):**
 - Mapbender: 3.0.7.0

**Comment by astroidex** [comment]
I changed all demo applications to use the translation variables instead of fixed text
* see PR https://github.com/mapbender/mapbender/issues/931

**Comment by astroidex** [comment]
* ticket also refers to #771  [Documentation] please add information about how an application can switch to another language

**Comment by CharlyUnicorn** [comment]
@AxxL @astroidex the changes from pull 81 are very nice, perhaps the adaption of the translation-file is necessary bevore you aprove the changes -> no missing translations in the demos

**Comment by astroidex** [comment]
PR 81 was merged (27 Aug 2018): https://github.com/mapbender/mapbender-starter/pull/81
Works fine
I close the ticket
