### ISSUE TITLE
OL2 zu OL4 Style Wrapper

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#937]
OL2 benutzt reines JSON Format innerhalb eines VectorLayer Styles. OL4 erfordert Callback funktionen innerhalb des Styles, die aber eine Sicherheitslücke von UserStyles bedeuten würden. Deshalb muss das desinfiziert werden.

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
