### ISSUE TITLE
[OL4] restrict Map to configured zoom levels

### ISSUE THREAD

**Issue by werrolf** [mapbender/mapbender#953]
Map backend configuration has  `scales` and `maxResolution` fields, restraining the map to discrete zoom levels.  

These fields do not have any effect yet on the ol4 branch.  

Implement these restrictions in view setup for Openlayers 4.

Depends:
- [x] [Methods to get / set zoom and convert zoom <=> scale](https://github.com/mapbender/mapbender/issues/941)

**Comment by werrolf** [comment]
Analysis reveals that backend field `maxResolution` is not evaluated at all in OL2 version. Defaults to `'auto'`, is stored, but doesn't do anything else.  

This field will be removed from the backend.

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
