### ISSUE TITLE
[OL4] ScaleBar does not follow Srs Changes from projection metric <=> degrees

### ISSUE THREAD

**Issue by werrolf** [mapbender/mapbender#961]
When changing between projections with metric units (EPSG:4326, EPSG:25832 etc) to a "geodesic" projection with units = degrees, the scalebar widget does not follow the change and calculates displayed scale based on the old projection's units.   

E.g. when the (correctly calculated and displayed) ScaleBar widget shows 500m on an EPSG:25832 projection, a switch to WGS84 leads to a displayed scale of 10km. This is directly related to the conversion factor between deegrees and meters.

NOTE: this is **not** about the configurable display units. If the ScaleBar is configured to display meters, it should display anything it calculates in meters or km as appropriate. In particular, it should continue to display in meters and km for a geodesic projection system.  
The issue is about the calculated number itself.

[I've left some artifacts in the event receiver](https://github.com/mapbender/mapbender/blob/3eec74fa74ba0b14f64ca6ed1b3f11a7dcb628e5/src/Mapbender/CoreBundle/Resources/public/mapbender.element.scalebar.js#L57).   
You can also look at [the origin of the event](https://github.com/mapbender/mapbender/blob/3eec74fa74ba0b14f64ca6ed1b3f11a7dcb628e5/src/Mapbender/CoreBundle/Resources/public/mapbender.element.map.js#L207) to see the data that will be available to the event handler.

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
