### ISSUE TITLE
[OL4] can't apply BBOX URL param switch between xy and yx projections at runtime on WMS1.3.0

### ISSUE THREAD

**Issue by werrolf** [mapbender/mapbender#963]
This is a regression vs previous OL2 implementation, where it also took a loooong time to solve.   

Srs switching is currently working fine on WMS1.1.1.  
Also working fine on WMS1.3.0 if you stay within a group of projections with equal axisOrientation.  

The [current implementation monkey-patches the (private) `.projection_` property on the source](https://github.com/mapbender/mapbender/blob/3eec74fa74ba0b14f64ca6ed1b3f11a7dcb628e5/src/Mapbender/CoreBundle/Resources/public/mapbender-model/mapbender.model.ol4.source.js#L99). This properly updates the SRS (or CRS) request params and the BBOX calculations _per_ _se_ are also working fine.  
However, if you go from, say, EPSG:25832 to EPSG:31466 or vice-versa, the OL4 source _does_ _not_ update the order in which it formats its generated `BBOX=` WMS parameter.  

This is not really designed into the OL4 API, and we're trying to figure out the best possible hack, really.  

References:
* [Main SRS switching logic in new OL4 Model](https://github.com/mapbender/mapbender/blob/3eec74fa74ba0b14f64ca6ed1b3f11a7dcb628e5/src/Mapbender/CoreBundle/Resources/public/mapbender.model.ol4.js#L999)
* [Location of current initialization hack that forces WMS VERSION=1.1.1](https://github.com/mapbender/mapbender/blob/3eec74fa74ba0b14f64ca6ed1b3f11a7dcb628e5/src/Mapbender/CoreBundle/Resources/public/mapbender-model/mapbender.model.ol4.source.js#L47)
* [Origin of supplied event data for mbmapsrschanged](https://github.com/mapbender/mapbender/blob/3eec74fa74ba0b14f64ca6ed1b3f11a7dcb628e5/src/Mapbender/CoreBundle/Resources/public/mapbender.element.map.js#L207)

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
