### ISSUE TITLE
Respect configured tileSize for WMS with option 'tiled'=true (currently uses OL4 default 256x256)

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#971]
Apply the configured tile size (in Mapbender Map Element backend).  
Currently we use OL4 default tile size of 256x256.  

Challenge: non-default tile sizes can only be set when also setting an extent. This will probably cause new, potentially difficult interactions with the SrsSelector Element.

[OL4 example for custom tile size initialization](https://openlayers.org/en/latest/examples/wms-tiled.html)

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
