### ISSUE TITLE
Layertree synchronization not working

### ISSUE THREAD

**Issue by rschwammborn** [mapbender/mapbender#974]
Several layertrees in an application are not working cohesively - i.e. a layertree element in sidepane and a layertree dialogue implemented via a button are not synchronized. When (un)checking a layer in one layertree, it remains (un)checked in the other and vice versa.

**Comment by AxxL** [comment]
Thanks @RobinSchwammborn. We have this as a known issue and we discuss to cut that feature.

**Comment by rschwammborn** [comment]
Comment that layertree sync is not a mandatory feature: https://github.com/mapbender/mapbender/issues/688#issuecomment-401045529

Nevertheless, Mapbender 3.0.8 seems to support layertree synchronisation quite nicely (OL2). Closing the issue for now.
