### ISSUE TITLE
Line/Area Ruler: Pan Map Bug

### ISSUE THREAD

**Issue by rschwammborn** [mapbender/mapbender#976]
There are bugs concerning the ruler features:

Line ruler. While clicking the second node of a line, the tool "freezes". Instead of drawing a line, panning is activated around the node clicking location. Zooming is possible, but you cannot move the mouse around independently anymore. Only way to escape from this situation is to click the Close button in the distance calculation window or the line ruler button in the toolbar.

Area ruler. Almost the same situation as above, but on the first node. There does not appear a line following the cursor. Moreover, the pan tool is activated on the second click. Escaping is possible via Close or toolbar button.

Moreover, a live calculation of the length or area is not possible yet.

**Comment by AxxL** [comment]
@inacht takes a look at it.

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
