### ISSUE TITLE
Redlining: "Stealth Mode" Bug

### ISSUE THREAD

**Issue by rschwammborn** [mapbender/mapbender#977]
It seems that the Redlining feature has several bugs.

Firstly, drawing geometries is possible, but almost all types disappear from the map after the drawing process is done.
The geometries become invisible and are still there, as it is possible to let them reappear via pressing the "edit" button. Zooming and deleting is also possible ( - but they are only visible in edit mode).
Exception: "Text (annotations)" works properly and does not disappear.

Secondly, switching the SRS disrupts the geometries' location. They change based on the chosen EPSG-code. Relations between them stay the same (distance, shape, etc.)

**Comment by DeEgge** [comment]
> Firstly, drawing geometries is possible, but almost all types disappear from the map after the drawing process is done.
The geometries become invisible and are still there, as it is possible to let them reappear via pressing the "edit" button. Zooming and deleting is also possible ( - but they are only visible in edit mode).
Exception: "Text (annotations)" works properly and does not disappear.

671447c should fix this issue

> Secondly, switching the SRS disrupts the geometries' location. They change based on the chosen EPSG-code. Relations between them stay the same (distance, shape, etc.)

@RobinSchwammborn Could you please open a new issue for this? Thanks!

**Comment by DeEgge** [comment]
> Secondly, switching the SRS disrupts the geometries' location. They change based on the chosen EPSG-code. Relations between them stay the same (distance, shape, etc.)

I've just noticed this is the exact same behaviour as with ol2, because the is no transformation happening.

**Comment by AxxL** [comment]
Redlinig doesn't support SRS change

**Comment by AxxL** [comment]
Reopen because of unmerged #980

**Comment by werrolf** [comment]
Redlining OpenLayers 2 base was a completely broken, barely functional mess at the start of the initial OL4 push and should never even have started the porting process.  
The OL2 base is in much, much better shape now. The previous OL4 porting attempt results have lost their value.
