### ISSUE TITLE
GPSPosition not working

### ISSUE THREAD

**Issue by rschwammborn** [mapbender/mapbender#978]
It is not yet possible to track down a valid GPS position with the GPSPosition feature. Mapbender shows error message "Es ist nicht möglich, Ihre Position zu bestimmen".

**Comment by LazerTiberius** [comment]
Do you use https or are you on localhost?

**Comment by RobinSchwammborn** [comment]
Default OL4 server; this application: http://ol4/ol4/application/test_map

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
