### ISSUE TITLE
Support PostgreSQL 10

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#983]
Currently Mapbender doesn't support PostgreSQL 10 because it is shipped with `doctrine/dbal v2.5.13`. Doctrine DBAL 2.7.0 supports PSQL 10. It is not possible to change the composer.json to `"doctrine/dbal": "~2.7.0"` because of Twig buildup.

Errors occuring are: 

```
[Doctrine\DBAL\Exception\InvalidFieldNameException]
  An exception occurred while executing 'SELECT min_value, increment_by FROM "acl_classes_id_seq"':

  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
  LINE 1: SELECT min_value, increment_by FROM "acl_classes_id_seq"
                 ^
  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
  LINE 1: SELECT min_value, increment_by FROM "acl_classes_id_seq"
                 ^
  [PDOException]
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
  LINE 1: SELECT min_value, increment_by FROM "acl_classes_id_seq"
```

There is a workaround to change code in the vendor package of Doctrine:

https://github.com/doctrine/dbal/issues/2868#issuecomment-332119007

See also internal ticket: 48 from our testing scenarios.

**Comment by werrolf** [comment]
From 2.6.0 onwards, [doctrine/orm requires PHP 7.1 at a minimum].

**Comment by eschuettler** [comment]
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html
