### ISSUE TITLE
Support PHP 7.2, APIGEN alternative

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#984]
Currently Mapbender supports PHP 7.2, but cannot built against it with the developer options.

Reason is the apigen package (for api-documentation) which uses some package that has incompatibility with PHP 7.2.

- nette/nette has an object-error (https://github.com/nette/utils/issues/160). Fix available in 2.4.9 (https://github.com/nette/utils/releases/tag/v2.4.9)

- Apigen uses nette/nette and has with the updated version a conflict with Symfony 2.8.

- Apigen 2.8.x needs an old nette version, which doesn't run with PHP 7.2
- Apigen 4.0.x needs Symfony 2.6 (we use 2.8)
- Apigen 5.x-RC needs Symfony 3.x

Workaround right now:

- Build mapbender without dev-libraries: `composer [update/install] --no-dev`
- Remove apigen from `composer.json`

TODO:
- Different apigen library package.

**Comment by werrolf** [comment]
There will be no replacement bundled apigen version.  
The original motivation for including API doc build infrastructure with the code has been long lost to time, and the developers don't need anything like that. The best practice for transforming annotations and other bits of the code into an API documentation is to install the tool you like _separately_ and point it to the code you want inspected.  

You can still install apigen anywhere you want and run it on the Mapbender code. You just can't install it as a part of the Mapbender project root (in composer speak).
