### ISSUE TITLE
coordinates utility in 3.0.7 - improve usability

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#991]
Currently you zoom in on a fixed scale after clicking on "Center map". 
It would be nice if this scale could be influenced at some point, eg. as in the search. 
Users may expect that the scale does not change (it is named as "center", not "zoom to"). 

But it is a very nice tool!

**Comment by AxxL** [comment]
>  It would be nice if this scale could be influenced at some point, eg. as in the search.

Agree. Looking into when and how to implement.

**Comment by rschwammborn** [comment]
Closing this issue as it is actually a duplicate. For more, head over to #724 :+1:
