### ISSUE TITLE
Redlining in 3.0.7 - error to deactivate in sidepane and missing display in map

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#992]
in the new version 3.0.7 I created the following error behavior: 

If the element is loaded into the sidebar, the sketch functions are never deactivated when the checkbox "deactivate after closing" is not active and no further functions can be used after the starf of a sketch. If the checkbox "deactivate after closing" is activated, then you can not activate / use the tool after the first drawing action.

If the element is included as a dialog, then the sketch functions works until the window is closed. If, after closing the dialog window, the module is activated again via the button, the elements no longer appear in the map. The list in the dialog will continue to list all items, but you don’t see them.

**Comment by CharlyUnicorn** [comment]
see also https://github.com/mapbender/mapbender/issues/862

**Comment by AxxL** [comment]
> If the element is loaded into the sidebar, the sketch functions are never deactivated when the checkbox "deactivate after closing" is not active 

The "deactivate after closing" has no effect on the Redlining if it is used in the sidebar.

> no further functions can be used after the starf of a sketch.

Confirmed.


> If the checkbox "deactivate after closing" is activated, then you can not activate / use the tool after the first drawing action.

Cannot confirm. But I guess you are referring to the workflow above: Sidebar, draw, choose another entry, raw again.

> If the element is included as a dialog, then the sketch functions works until the window is closed. If, after closing the dialog window, the module is activated again via the button, the elements no longer appear in the map. The list in the dialog will continue to list all items, but you don’t see them.

#995

**Comment by werrolf** [comment]
Please also see #995 (fix merged)
Plese see #1016 (fix pending)

**Comment by werrolf** [comment]
I can confirm that we still have this issue.
`deactivateOnClose` currently doesn't do anything at all if the Redlining Element is in a sidebar (tab or accordion style makes no difference here). It only works for dialogs (aka popups).  
Repeated sketching is fixed.

**Comment by werrolf** [comment]
Auto-closed by Github merge. Fix will be in upcoming release.
