### ISSUE TITLE
Search Router: Enter key does not trigger submit in search forms with more than one field

### ISSUE THREAD

**Issue by ilikemaps** [mapbender/mapbender#993]
Currently, the Search Router form can be submitted by pressing the enter key when there is a single search field. Alternatively, users can press the search button below the form. When there is more than one field, pressing the enter key does not work. Instead, users have to scroll down/navigate to and click the search button. Often, they are confused that nothing happens after having pressed the enter key.

I suppose/hope this is indeed a bug and not working as inteded as this inconsistency is slightly annoying and contrary to users' expectations.

**To Reproduce**

The behavior can be reproduced in [this application](http://www.stadtplan.troisdorf.de/application/troisdorf-vorlage-v01) (as well as in many applications in the [Mapbender Gallery](https://mapbender.org/?q=en/gallery)). Click the button titled "Suchen" on the left side. The default search "Adresssuche" consists of a single search field. Enter "Gerhardstr" or any other text into the search field and press enter while you are still in the search field. You either get a list of results or a notification that nothing was found.

After this, choose Flurstücksuche from the drop-down list. This is a search form with three search fields plus one drop-down list. Choose any entry from the drop-down-list "Gemarkung". Enter 1 or any other number into the first field "Flur" and press the enter key. Nothing happens. Click on the button "Suchen" below the search fields and you do get results.

**Suggestion**

- Change the search form so that the enter key submits the form on any field, i. e. make it equal to pressing the search button.

**Versions**

    Mapbender: 3.0.5.3, 3.0.6.3

**Comment by AxxL** [comment]
Thanks @ilikemaps. We're looking into this issue to check when we are going to include that into Mapbender.

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
