### ISSUE TITLE
Button allows selecting itself as a target

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#997]
- Create a button.
- Call it "1"
- Save it.
- Reopen the button
- Set the target.

Important step in this recipe: Save the button and open it again. If you choose the target directly on creation, the effect doesn't occur.

Observation:

- You can set the button itself as a target. The target lists shows "1".

Expectation:

- You should not set the button itself as a target. It should not be listed in the target list.

Background / PITA effect:

- Normally you set the title of the button like the tile of your element. For example: Element title is "Redlining", button title is also "Redlining". If you want to choose a new target from the list, you see two entries "Redlining" and don't know which to choose.

**Comment by werrolf** [comment]
Cannot be reproduced, no released version has this bug. [Last modification was end of June](https://github.com/mapbender/mapbender/commit/cbfa3c6e3484732b355ab8541e4a744f5234092a).
