### ISSUE TITLE
[documentation] provide information about Git-based installation - information got lost

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#998]
In our documentation we refer to the Git-based installation at
* https://doc.mapbender.org/en/installation/installation_git.html

Problem: in this versoin the " Git-based installation" Chapter does not exist anymore. 

**To Reproduce**

* open actual Documentation https://github.com/mapbender/mapbender-starter/blob/release/3.0.6/CONTRIBUTING.md#installation
* open Documentation from 2017-07-14 https://github.com/mapbender/mapbender-starter/blob/3dfc72d947b7551a822decbc7024c63c73fc821c/CONTRIBUTING.md

For your information: till version 3.0.5.3 we proveide the information about  **Git-based installation** directly in the documentation:
* https://docs.mapbender.org/3053/en/book/installation/installation_git.html

**Comment by AxxL** [comment]
It's directly at the README for all to see when you open [the repository](https://github.com/mapbender/mapbender-starter):


https://github.com/mapbender/mapbender-starter/blob/master/README.md

**Comment by AxxL** [comment]
https://github.com/mapbender/mapbender-documentation/commit/b28430ceeffec78fe71b8af79f470ac922f84c2b
