### ISSUE TITLE
[documentation] reduce the size of the documentation in the download package

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#999]
Documentation in download Mapbender 3.0.7.3  is 79,4 MB unzipped (release-package has 188,4 MB unzipped). Would be great to reduce the size of the documentation in the release package.

* https://mapbender.org/builds/3.0.7.3/

**possible Solution**
* reduce size of the images at https://github.com/mapbender/mapbender-documentation/tree/master/figures
* can we delete? https://github.com/mapbender/fom/tree/release/3.0.6/documentation/en

**Comment by AxxL** [comment]
No. Sorry. We've discussed that and won't do it.
